import type { Metadata } from 'next';
import { Atom, Ruler, Sigma } from 'lucide-react';
import { Badge } from '@/components/ui/Badge';
import { Card, CardBody, CardHeader, CardTitle } from '@/components/ui/Card';
import { PeriodicTable } from '@/components/content/PeriodicTable';
import { physicalConstants, prefixes, periodicElements } from '@/lib/constants';

export const metadata: Metadata = { title: 'Constants & tables', description: 'Physical constants, SI prefixes and a clickable periodic table.' };
export default function ConstantsPage() { return <section className="page-shell section-space"><div className="mb-10 max-w-3xl"><p className="eyebrow">PhysChem Lab · Reference</p><h1 className="display-title mt-3">ধ্রুবক <span className="text-chemistry-600 dark:text-chemistry-200">/ Reference</span></h1><p className="mt-4 text-base leading-7 muted">A compact reference for common physical constants, SI prefixes and the periodic table. Values are presented for learning and checked against modern SI definitions.</p></div><div className="grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><Card><CardHeader><div className="flex items-center gap-2 text-chemistry-600"><Sigma size={18} /><CardTitle>Physical constants</CardTitle></div></CardHeader><CardBody><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-[var(--line)] text-xs uppercase tracking-wider muted"><th className="px-2 py-3">Symbol</th><th className="px-2 py-3">Name</th><th className="px-2 py-3">Value</th><th className="px-2 py-3">Unit</th></tr></thead><tbody>{physicalConstants.map((constant) => <tr key={constant.symbol} className="border-b border-[var(--line)] last:border-0"><td className="px-2 py-3 font-mono font-black text-physics-600">{constant.symbol}</td><td className="px-2 py-3"><span className="font-bold">{constant.name}</span><span className="block text-xs muted">{constant.name_bn}</span></td><td className="px-2 py-3 font-mono">{constant.value}</td><td className="px-2 py-3 muted">{constant.unit}</td></tr>)}</tbody></table></div></CardBody></Card><Card><CardHeader><div className="flex items-center gap-2 text-physics-600"><Ruler size={18} /><CardTitle>SI prefixes</CardTitle></div></CardHeader><CardBody><div className="grid grid-cols-2 gap-2">{prefixes.map(([name, symbol, power]) => <div key={name} className="rounded-xl bg-[var(--surface-soft)] p-3"><p className="text-xs font-bold muted">{name}</p><p className="mt-1 font-mono font-black">{symbol}</p><p className="text-xs text-physics-600">{power}</p></div>)}</div></CardBody></Card></div><Card className="mt-5 overflow-hidden"><CardHeader className="bg-[var(--surface-soft)]"><div className="flex items-center gap-2 text-chemistry-600"><Atom size={18} /><CardTitle>Periodic table</CardTitle><Badge tone="chemistry">{periodicElements.length} reference elements</Badge></div></CardHeader><CardBody><PeriodicTable elements={periodicElements} /></CardBody></Card></section>; }
