/**
 * Subject-topic groups used to filter equations and practicals.
 * Groups are topics such as শব্দ, তরঙ্গ, আলো rather than school levels.
 */
export const topicGroups = [
  { id: 'motion', bn: 'গতি, বল ও মহাকর্ষ', en: 'Motion, force and gravitation' },
  { id: 'energy', bn: 'কাজ ও শক্তি', en: 'Work and energy' },
  { id: 'oscillation', bn: 'দোলন', en: 'Oscillations' },
  { id: 'wave', bn: 'তরঙ্গ', en: 'Waves' },
  { id: 'sound', bn: 'শব্দ', en: 'Sound' },
  { id: 'light', bn: 'আলো ও বর্ণালি', en: 'Light and spectra' },
  { id: 'matter', bn: 'পদার্থের ধর্ম ও প্রবাহ', en: 'Properties of matter and flow' },
  { id: 'heat', bn: 'তাপ ও গ্যাস', en: 'Heat and gases' },
  { id: 'electricity', bn: 'তড়িৎ', en: 'Electricity' },
  { id: 'magnetism', bn: 'চুম্বকত্ব ও আবেশ', en: 'Magnetism and induction' },
  { id: 'modern', bn: 'আধুনিক পদার্থবিজ্ঞান ও পরমাণু', en: 'Modern physics and atoms' },
  { id: 'stoichiometry', bn: 'মোল ও রাসায়নিক সংকেত', en: 'Mole and chemical formulae' },
  { id: 'chem-kinetics', bn: 'রাসায়নিক গতিবিদ্যা', en: 'Chemical kinetics' },
  { id: 'chem-thermo', bn: 'রাসায়নিক তাপগতিবিদ্যা', en: 'Chemical thermodynamics' },
  { id: 'equilibrium', bn: 'রাসায়নিক সাম্য ও অম্ল-ক্ষার', en: 'Equilibrium and acid–base' },
  { id: 'electrochem', bn: 'তড়িৎ রসায়ন', en: 'Electrochemistry' },
  { id: 'solution', bn: 'দ্রবণ ও পৃষ্ঠ রসায়ন', en: 'Solutions and surfaces' },
  { id: 'inorganic', bn: 'জৈব ও অজৈব রসায়ন', en: 'Organic and inorganic chemistry' }
] as const;

export type TopicId = (typeof topicGroups)[number]['id'];

const chapterTopic: Record<string, TopicId> = {
  // physics
  'আধুনিক পদার্থবিজ্ঞান': 'modern',
  'কোয়ান্টাম মেকানিক্স': 'modern',
  'বিশেষ আপেক্ষিকতা': 'modern',
  'পারমাণবিক পদার্থবিজ্ঞান': 'modern',
  'নিউক্লিয় পদার্থবিজ্ঞান': 'modern',
  'আলো ও আলোকবিজ্ঞান': 'light',
  'আলোকবিজ্ঞান': 'light',
  'আলোর প্রতিফলন': 'light',
  'আলোর প্রতিসরণ': 'light',
  'জ্যামিতিক আলোকবিজ্ঞান': 'light',
  'তরঙ্গ আলোকবিজ্ঞান': 'light',
  'কাজ, ক্ষমতা ও শক্তি': 'energy',
  'কাজ, শক্তি ও ক্ষমতা': 'energy',
  'সরল যন্ত্র': 'energy',
  'গতি': 'motion',
  'গতি ও পরিমাপ': 'motion',
  'ঘূর্ণন গতি': 'motion',
  'দ্বিমাত্রিক গতি': 'motion',
  'প্রক্ষেপণ গতি': 'motion',
  'বল': 'motion',
  'বল ও গতি': 'motion',
  'বল ও ভরবেগ': 'motion',
  'বল ও মহাকর্ষ': 'motion',
  'বৃত্তীয় গতি': 'motion',
  'বিশ্লেষণী বলবিদ্যা': 'motion',
  'ভেক্টর': 'motion',
  'মহাকর্ষ': 'motion',
  'দোলন': 'oscillation',
  'দোলন ও তরঙ্গ': 'oscillation',
  'তরঙ্গ': 'wave',
  'তড়িৎচুম্বকীয় তরঙ্গ': 'wave',
  'শব্দ': 'sound',
  'তরল ও বায়বীয় পদার্থের চাপ': 'matter',
  'তরল বলবিদ্যা': 'matter',
  'প্রবাহী গতিবিদ্যা': 'matter',
  'সান্দ্রতা ও প্রবাহ': 'matter',
  'পৃষ্ঠটান': 'matter',
  'স্থিতিস্থাপকতা': 'matter',
  'পদার্থের বৈশিষ্ট্য': 'matter',
  'কঠিন অবস্থার পদার্থবিজ্ঞান': 'matter',
  'বল ও চাপ': 'matter',
  'তাপ ও তাপগতিবিদ্যা': 'heat',
  'তাপ ও তাপমাত্রা': 'heat',
  'তাপগতিবিদ্যা': 'heat',
  'তাপীয় বিকিরণ': 'heat',
  'পদার্থের ওপর তাপের প্রভাব': 'heat',
  'পদার্থের অবস্থা ও চাপ': 'heat',
  'গ্যাসের গতীয় তত্ত্ব': 'heat',
  'পরিসংখ্যানিক তাপগতিবিদ্যা': 'heat',
  'স্থির তড়িৎ': 'electricity',
  'তড়িৎ': 'electricity',
  'চল তড়িৎ': 'electricity',
  'ধারকত্ব': 'electricity',
  'পরিবর্তী প্রবাহ': 'electricity',
  'ইলেকট্রনিক্স': 'electricity',
  'চুম্বকত্ব': 'magnetism',
  'চুম্বকত্ব ও তড়িৎচৌম্বক আবেশ': 'magnetism',
  'তড়িৎচুম্বকীয় আবেশ': 'magnetism',
  // chemistry
  'অম্ল, ক্ষার ও buffer': 'equilibrium',
  'অম্ল, ক্ষার ও লবণ': 'equilibrium',
  'আয়নিক সাম্যাবস্থা': 'equilibrium',
  'রাসায়নিক সাম্য': 'equilibrium',
  'রাসায়নিক সাম্যাবস্থা': 'equilibrium',
  'সাম্যাবস্থা': 'equilibrium',
  'সাম্যাবস্থা ও অম্ল-ক্ষার রসায়ন': 'equilibrium',
  'তড়িৎ রসায়ন': 'electrochem',
  'তড়িৎরসায়ন': 'electrochem',
  'গ্যাস': 'heat',
  'পদার্থের অবস্থা': 'heat',
  'তাপরসায়ন': 'chem-thermo',
  'রাসায়নিক তাপগতিবিদ্যা': 'chem-thermo',
  'দ্রবণ': 'solution',
  'সমষ্টিগত ধর্ম': 'solution',
  'পৃষ্ঠ রসায়ন': 'solution',
  'পরমাণুর গঠন': 'modern',
  'পরমাণুর গঠন ও পর্যায়বৃত্ততা': 'modern',
  'পরমাণু ও অণু': 'stoichiometry',
  'পরমাণু ও মোল': 'stoichiometry',
  'মোল ধারণা': 'stoichiometry',
  'রসায়নমিতি': 'stoichiometry',
  'রাসায়নিক সংকেত': 'stoichiometry',
  'রাসায়নিক সংযোজন': 'stoichiometry',
  'রাসায়নিক বিক্রিয়া': 'stoichiometry',
  'রাসায়নিক গতিবিদ্যা': 'chem-kinetics',
  'বর্ণালিবীক্ষণ': 'light',
  'জৈব রসায়ন': 'inorganic',
  'শিল্প ও অজৈব রসায়ন': 'inorganic'
};

/** Entries whose chapter is too generic (e.g. "স্নাতক রসায়ন") or English-only, keyed by slug. */
const slugTopic: Record<string, TopicId> = {
  'acid-dissociation-ratio': 'equilibrium',
  'weak-acid-ph-approx': 'equilibrium',
  'nernst-distribution-law': 'equilibrium',
  'beer-transmittance': 'light',
  'rotational-spectra-level': 'light',
  'rydberg-ionization-limit': 'light',
  'vibrational-zero-point': 'light',
  'cell-emf-from-reduction': 'electrochem',
  'conductance-cell-constant': 'electrochem',
  'debye-huckel-limiting-law': 'electrochem',
  'faradays-law': 'electrochem',
  'common-ion-solubility': 'solution',
  'freezing-depression-electrolyte': 'solution',
  'langmuir-half-coverage': 'solution',
  'osmotic-pressure-electrolyte': 'solution',
  'relative-vapor-pressure-lowering': 'solution',
  'solubility-ab-salt': 'solution',
  'freundlich-adsorption-isotherm': 'solution',
  'langmuir-adsorption-isotherm': 'solution',
  'dalton-partial-pressure-honours': 'heat',
  'graham-effusion-honours': 'heat',
  'kirchhoff-reaction-enthalpy': 'chem-thermo',
  'reaction-quotient-gibbs': 'chem-thermo',
  'gibbs-duhem-equation': 'chem-thermo',
  'gibbs-phase-rule': 'chem-thermo',
  'pseudo-first-order-rate': 'chem-kinetics',
  'second-order-half-life': 'chem-kinetics',
  'eyring-transition-state-equation': 'chem-kinetics',
  'michaelis-menten-equation': 'chem-kinetics',
  'equilibrium-constant': 'equilibrium',
  'vanthoff-equilibrium-temperature': 'equilibrium',
  'crystal-field-octahedral-cfse': 'inorganic',
  'spin-only-magnetic-moment': 'inorganic',
  'bond-order-molecular-orbitals': 'stoichiometry',
  'radial-node-count': 'modern',
  'cubic-interplanar-spacing': 'modern',
  'partition-function': 'heat',
  'boltzmann-distribution': 'heat',
  'fermi-dirac-occupation': 'heat',
  'fourier-heat-conduction': 'heat',
  'maxwell-thermodynamic-relation': 'heat',
  'adiabatic-work-ideal-gas': 'heat',
  'maxwell-rms-speed-honours': 'heat',
  'heat-engine-carnot-honours': 'heat',
  'angular-impulse': 'motion',
  'centripetal-force-honours': 'motion',
  'orbital-speed-circular': 'motion',
  'gravity-potential-energy-honours': 'motion',
  'coriolis-force': 'motion',
  'hamilton-equations': 'motion',
  'rotational-kinetic-energy': 'energy',
  'shm-energy': 'oscillation',
  'damped-amplitude': 'oscillation',
  'quality-factor-oscillator': 'oscillation',
  'bragg-equation': 'wave',
  'bragg-order-limit': 'wave',
  'wave-energy-string': 'wave',
  'wave-group-velocity': 'wave',
  'maxwell-em-wave-speed': 'wave',
  'brewster-angle-honours': 'light',
  'lensmaker-thin-honours': 'light',
  'single-slit-minimum-honours': 'light',
  'thin-film-phase-reversal': 'light',
  'young-fringe-width-honours': 'light',
  'cyclotron-radius-honours': 'magnetism',
  'inductor-energy-honours': 'magnetism',
  'magnetic-flux-induction': 'magnetism',
  'poynting-vector': 'magnetism',
  'rc-discharge-honours': 'electricity',
  'blackbody-photon-energy': 'modern',
  'compton-effect-wavelength-shift': 'modern',
  'heisenberg-uncertainty-principle': 'modern',
  'particle-in-box-energy': 'modern',
  'schrodinger-equation': 'modern',
  'relativistic-length-contraction': 'modern',
  'relativistic-time-dilation': 'modern',
  'relativistic-momentum-honours': 'modern',
  'radioactive-half-life-honours': 'modern',
  'bohr-quantization-angular-momentum': 'modern',
  'hydrogen-energy-levels-bohr': 'modern',
  'rydberg-equation-hydrogen': 'modern',
  'euler-lagrange-equation': 'motion'
};

/** Topic group for an equation. Slug overrides win over the chapter name. */
export function topicFor(entry: { slug: string; chapter: string; chapter_bn?: string }): TopicId | undefined {
  return slugTopic[entry.slug] ?? chapterTopic[entry.chapter_bn ?? ''] ?? chapterTopic[entry.chapter];
}

export function topicLabel(id: TopicId, locale: 'bn' | 'en'): string {
  const topic = topicGroups.find((item) => item.id === id);
  return topic ? (locale === 'bn' ? topic.bn : topic.en) : '';
}
