"""Add 50 conceptual questions to both Honours lab guides (viva) and quizzes.
Each new item probes experimental reasoning, errors, assumptions, or safety.
Run once; refuses to append a second time.
"""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]/'content'
# slug | question EN~BN | correct answer EN~BN | three distractors EN~BN separated by ; | explanation EN~BN
PHYSICS=r'''
katers-pendulum-gravity|Why time many oscillations instead of one?~একটির বদলে অনেক দোলনের সময় কেন মাপা হয়?|To reduce relative timing uncertainty~সময় মাপার আপেক্ষিক অনিশ্চয়তা কমাতে|To change gravitational acceleration~মহাকর্ষীয় ত্বরণ বদলাতে;To eliminate all amplitude effects~বিস্তারের সব প্রভাব দূর করতে;To increase pivot separation~দুই স্থিতিবিন্দুর দূরত্ব বাড়াতে|Period is total time divided by number of swings; a similar start-stop error is a smaller fraction of the longer interval. Small-angle and equal-period checks remain necessary.~পর্যায়কাল মোট সময়কে দোলনসংখ্যা দিয়ে ভাগ করে পাওয়া যায়; দীর্ঘ সময়ে একই শুরু-শেষের ত্রুটির আপেক্ষিক প্রভাব কমে। ক্ষুদ্র কোণ ও দুই পর্যায়কালের মিলও যাচাই করতে হবে।
searles-young-modulus|If a loading-unloading curve shows large permanent extension, should Y be obtained from those points?~ভার কমানোর পর তারে বড় স্থায়ী প্রসারণ থাকলে সেই পাঠ থেকে Y নেওয়া উচিত?|No, the elastic-region assumption has failed~না, স্থিতিস্থাপক অঞ্চলের অনুমান ভেঙেছে|Yes, plastic deformation is required~হ্যাঁ, স্থায়ী বিকৃতি জরুরি;Yes, all extensions are reversible~হ্যাঁ, সব প্রসারণ প্রত্যাবর্তী;Only if diameter is ignored~শুধু ব্যাস উপেক্ষা করলে|Y=FL/(AΔL) describes reversible elastic extension. Residual strain means the sample was overloaded or changed, so use elastic-range data only.~Y=FL/(AΔL) প্রত্যাবর্তী স্থিতিস্থাপক প্রসারণের জন্য। অবশিষ্ট বিকৃতিতে নমুনা বদলেছে; তাই শুধু স্থিতিস্থাপক সীমার পাঠ নিন।
beam-bending-modulus|Why record beam thickness d more carefully than width b?~বিমের প্রস্থ b-এর চেয়ে পুরুত্ব d বেশি যত্নে মাপবেন কেন?|The formula contains d cubed~সূত্রে d-এর ঘন আছে|Width does not enter the formula~সূত্রে প্রস্থ নেই;Thickness is always equal to span~পুরুত্ব সবসময় বিস্তারের সমান;Only thickness sets the load~শুধু পুরুত্বেই ভার নির্ধারিত|Y=FL³/(4bd³δ). A small relative thickness error approximately triples its contribution to relative Y uncertainty; width enters only to first power.~Y=FL³/(4bd³δ)। পুরুত্বের সামান্য আপেক্ষিক ত্রুটি Y-তে প্রায় তিন গুণ প্রভাব ফেলে; প্রস্থ প্রথম ঘাতে আসে।
rigidity-torsion-pendulum|If the disc swings sideways as well as twisting, what is the best response?~চাকতি পাক দোলনের সঙ্গে পাশেও দুললে কী করবেন?|Realign and repeat pure torsional oscillations~সারিবদ্ধ করে শুধু পাক দোলনে আবার মাপবেন|Include sideways swings as more periods~পার্শ্বদোলনকে বাড়তি পর্যায়কাল ধরবেন;Increase twist beyond elastic limit~স্থিতিস্থাপক সীমার বাইরে পাকাবেন;Ignore the motion without recording it~না লিখেই গতি উপেক্ষা করবেন|T=2π√(I/κ) models torsional motion, not coupled lateral movement. Mixed modes bias the timed period and inferred modulus.~T=২π√(I/κ) শুধু পাক দোলনের মডেল; মিশ্র পার্শ্বদোলনে মাপা পর্যায়কাল ও গুণাঙ্ক ভুল হয়।
capillary-rise-tension|If the liquid does not completely wet glass, what additional measurement or parameter is needed?~তরল কাচ পুরো না ভেজালে অতিরিক্ত কী জানা দরকার?|Contact angle θ~স্পর্শকোণ θ|Only tube length~শুধু নলের দৈর্ঘ্য;Only atmospheric pressure~শুধু বায়ুচাপ;Only liquid colour~শুধু তরলের রং|Vertical surface-tension force is 2πrγcosθ, so γ=ρgrh/(2cosθ); setting cosθ=1 without wetting evidence biases γ.~পৃষ্ঠটানের উল্লম্ব বল ২πrγcosθ; তাই γ=ρgrh/(২cosθ)। ভেজার প্রমাণ ছাড়া cosθ=১ নিলে γ ভুল হয়।
poiseuille-viscosity|Why is capillary-radius calibration especially critical?~কৈশিক ব্যাসার্ধের ক্রমাঙ্কন বিশেষ জরুরি কেন?|Inferred viscosity contains r to the fourth power~নির্ণীত সান্দ্রতায় r-এর চতুর্থ ঘাত আছে|Radius cancels from Poiseuille's law~পয়জুই সূত্রে ব্যাসার্ধ বাদ যায়;Only tube colour affects viscosity~শুধু নলের রং সান্দ্রতা বদলায়;Pressure head cannot be measured~চাপের উচ্চতা মাপা যায় না|η=πr⁴ΔP/(8LQ). A 1% radius bias contributes about 4% viscosity bias even before flow errors.~η=πr⁴ΔP/(৮LQ)। ব্যাসার্ধে ১% ভুলে প্রবাহের অন্য ত্রুটি ছাড়াই η-তে প্রায় ৪% ভুল হয়।
stokes-falling-sphere|Why may the simple Stokes formula fail for a sphere in a narrow cylinder?~সরু নলে গোলকের জন্য সরল Stokes সূত্র কেন ভুল হতে পারে?|Nearby walls alter fluid drag~পাশের দেয়াল তরলের বাধা বদলায়|Gravity vanishes inside glass~কাচের মধ্যে মহাকর্ষ থাকে না;Sphere density becomes zero~গোলকের ঘনত্ব শূন্য হয়;Terminal speed becomes infinite~প্রান্তিক বেগ অসীম হয়|Stokes drag 6πηrv assumes an unbounded slow-flow fluid. Vessel walls increase drag, requiring a wall correction or a wider cylinder.~Stokes বাধা ৬πηrv অসীম বিস্তৃত ধীর তরলের জন্য। পাত্রের দেয়ালে বাধা বাড়ে; দেয়াল সংশোধন বা চওড়া পাত্র দরকার।
atwood-machine-acceleration|Why can observed acceleration be smaller than the ideal mass-only prediction?~মাপা ত্বরণ আদর্শ ভরভিত্তিক মানের চেয়ে কম কেন হতে পারে?|Pulley inertia and friction consume driving torque~পুলির জড়তা ও ঘর্ষণ চালক টর্কের অংশ নেয়|Gravitational acceleration reverses~মহাকর্ষীয় ত্বরণ উল্টে যায়;Both masses become equal automatically~দুটি ভর আপনা থেকে সমান হয়;A longer string removes all force~লম্বা সুতোয় সব বল দূর হয়|Ideal a=(m₁−m₂)g/(m₁+m₂) assumes massless frictionless pulley. Real pulley rotation adds effective inertia and bearings dissipate energy.~আদর্শ a=(m₁−m₂)g/(m₁+m₂)-এ ভরহীন ঘর্ষণমুক্ত পুলি ধরা হয়। বাস্তব পুলির জড়তা ও ঘর্ষণে ত্বরণ কমে।
inclined-plane-friction|Why should the angle be recorded at first sustained motion, not after the block has sped up?~ব্লক দ্রুত চলার পরে নয়, প্রথম স্থায়ী পিছলানোর কোণ কেন মাপবেন?|The threshold corresponds to maximum static friction~সীমাটি সর্বোচ্চ স্থির ঘর্ষণ নির্দেশ করে|Fast motion measures the same static limit exactly~দ্রুত গতিতেও একই স্থির সীমা নির্ভুল মাপে;Motion removes the normal force~গতিতে লম্ব প্রতিক্রিয়া চলে যায়;The angle is irrelevant once moving~চলা শুরু হলে কোণ অপ্রাসঙ্গিক|At impending slip mg sinθ=μs mg cosθ. Once moving, kinetic friction may differ from maximum static friction.~পিছলানোর প্রাক্কালে mg sinθ=μs mg cosθ। চলতে শুরু করলে গতীয় ঘর্ষণ সর্বোচ্চ স্থির ঘর্ষণ থেকে ভিন্ন হতে পারে।
joules-heat-equivalent|If measured water-plus-calorimeter heat is less than VIt, which explanation is reasonable?~জল ও পাত্রে পাওয়া তাপ VIt-এর চেয়ে কম হলে যুক্তিসংগত কারণ কী?|Some energy escaped to surroundings and heater parts~কিছু শক্তি পরিবেশ ও হিটারের অংশে গেছে|Electrical energy must be negative~বৈদ্যুতিক শক্তি ঋণাত্মক;Energy conservation has failed~শক্তি সংরক্ষণ ভেঙেছে;Voltage times current has units of mass~বিভব গুণ প্রবাহের একক ভর|VIt counts electrical input, while calorimetry may miss heat lost to air, leads and heater thermal mass; include a loss estimate.~VIt মোট বৈদ্যুতিক ইনপুট, কিন্তু বায়ু, তার ও হিটারে যাওয়া তাপ ক্যালরিমিটিতে ধরা নাও পড়তে পারে; ক্ষতি বিবেচনা করুন।
specific-heat-calorimetry-honours|What sign should Ts−Tf have if a hot specimen cools into water?~গরম নমুনা পানিতে ঠান্ডা হলে Ts−Tf-এর চিহ্ন কী?|Positive~ধনাত্মক|Negative~ঋণাত্মক;Exactly zero~ঠিক শূন্য;Undefined even after measurement~মাপার পরেও অনির্ধারিত|A hot specimen starts above the equilibrium temperature (Ts>Tf), so its lost heat ms cs(Ts−Tf) has positive magnitude.~গরম নমুনার শুরুর তাপমাত্রা সাম্য তাপমাত্রার চেয়ে বেশি (Ts>Tf); তাই হারানো তাপের মান ms cs(Ts−Tf) ধনাত্মক।
lees-disc-conductivity|Why is the cooling slope determined as the disc crosses its steady-state temperature T₂?~শীতলনের ঢাল চাকতি T₂ পার হওয়ার সময় কেন নেওয়া হয়?|To match the heat-loss rate to the steady-state energy balance~স্থিত অবস্থার শক্তিসাম্যের সঙ্গে একই তাপমাত্রার তাপক্ষয় মেলাতে|To make sheet thickness vanish~পাতের পুরুত্ব শূন্য করতে;Because cooling stops at T₂~T₂-এ শীতলন বন্ধ হয়;To eliminate all contact resistance automatically~সব সংযোগ রোধ নিজে থেকে বাদ দিতে|The steady disc was losing heat at T₂. Cooling at another temperature has a different rate and cannot be inserted without correction.~স্থির অবস্থায় চাকতি T₂-এ তাপ হারাচ্ছিল। অন্য তাপমাত্রায় শীতলনের হার ভিন্ন; সংশোধন ছাড়া তা বসানো যায় না।
resonance-tube-speed|Why use the difference between first and second resonant lengths?~প্রথম ও দ্বিতীয় অনুনাদ দৈর্ঘ্যের পার্থক্য কেন নেন?|A nearly constant open-end correction cancels~খোলা প্রান্তের প্রায় স্থির সংশোধন বাদ যায়|Sound frequency becomes zero~শব্দের কম্পাঙ্ক শূন্য হয়;The tube becomes open at both ends~নল দুই দিকেই খোলা হয়;Air temperature no longer matters~বায়ুর তাপমাত্রা আর প্রভাব ফেলে না|L₁+e≈λ/4 and L₂+e≈3λ/4, so subtraction yields L₂−L₁≈λ/2 without needing the same end correction e explicitly.~L₁+e≈λ/৪ ও L₂+e≈৩λ/৪; বিয়োগে একই প্রান্ত-সংশোধন e বাদ গিয়ে L₂−L₁≈λ/২।
meldes-string-frequency|What must be stated before comparing drive frequency with f in v=fλ?~v=fλ-এ f-এর সঙ্গে চালক কম্পাঙ্ক তুলনার আগে কী বলতে হবে?|The vibrator's orientation and drive-to-string frequency relation~কম্পকের বিন্যাস ও চালক-তার কম্পাঙ্কের সম্পর্ক|Only the string colour~শুধু তারের রং;Only room pressure~শুধু কক্ষের চাপ;Only the number of clamps~শুধু আটকানোর সংখ্যা|Depending on transverse or longitudinal vibrator arrangement, the string can oscillate at the drive frequency or at a related frequency. Assuming equality without noting setup biases v.~কম্পকের আনুপ্রস্থ বা অনুদৈর্ঘ্য বিন্যাসে তারের কম্পাঙ্ক চালকের সমান বা সম্পর্কিত হতে পারে। বিন্যাস না লিখে সমান ধরলে v ভুল হয়।
newtons-rings-radius|Why fit several Dm² values against ring order rather than rely on the central dark spot alone?~শুধু কেন্দ্রের অন্ধকার দাগ না নিয়ে কয়েকটি Dm² বনাম ক্রম কেন আঁকবেন?|The slope reduces contact-offset and single-reading errors~ঢালে সংস্পর্শ ও একক পাঠের ত্রুটির প্রভাব কমে|Only the central spot has nonzero wavelength~শুধু কেন্দ্রেই তরঙ্গদৈর্ঘ্য থাকে;Ring order is always zero~বলয়ের ক্রম সবসময় শূন্য;Fitting replaces measuring the lens radius~ঢাল নিলে লেন্সের ব্যাসার্ধ মাপতে হয় না|D_m² is approximately linear in m; a nonzero central-contact intercept can be diagnosed and slope=4λR yields wavelength.~D_m² প্রায় m-এর সঙ্গে সরলরৈখিক; কেন্দ্রে ফাঁক থাকলে ছেদ থেকে বোঝা যায়, আর ঢাল=৪λR থেকে তরঙ্গদৈর্ঘ্য মেলে।
prism-minimum-deviation|How do you recognize minimum deviation while rotating a prism?~প্রিজম ঘোরানোর সময় সর্বনিম্ন বিচ্যুতি কীভাবে চিনবেন?|The spectral image reverses its motion at a turning point~বর্ণরেখার চলার দিক একটি turning point-এ বদলায়|The apex angle becomes 90 degrees~শীর্ষকোণ ৯০° হয়;The line disappears permanently~রেখা চিরতরে অদৃশ্য হয়;The refractive index becomes zero~প্রতিসরাঙ্ক শূন্য হয়|At minimum deviation the path is symmetric and the emergent ray briefly stops moving in one direction before reversing.~সর্বনিম্ন বিচ্যুতিতে পথ সমমিত; নির্গত রশ্মি একদিকে চলা থামিয়ে বিপরীতদিকে ঘুরতে শুরু করে।
grating-spectrometer-wavelength|Why should grating lines per millimetre be inverted before calculating wavelength?~তরঙ্গদৈর্ঘ্য বের করার আগে প্রতি mm-এ রেখাসংখ্যার ব্যস্ত কেন নিতে হয়?|The grating equation uses spacing d, not line density~গ্রেটিং সূত্রে রেখা-ঘনত্ব নয়, ব্যবধান d লাগে|The order m must be negative~ক্রম m ঋণাত্মক হতে হবে;The speed of light is in mm/s~আলোর বেগ mm/s-এ হয়;Angles must be doubled twice~কোণ দুবার দ্বিগুণ করতে হয়|If line density is N lines/mm, d=(1/N) mm, then convert d to metres before using d sinθ=mλ.~প্রতি mm-এ Nটি রেখা হলে d=(১/N) mm; পরে d মিটারে নিয়ে d sinθ=mλ বসান।
polarimetry-sugar|Can an unknown sugar concentration be inferred from a specific rotation measured at a different wavelength without correction?~অন্য তরঙ্গদৈর্ঘ্যে মাপা আপেক্ষিক ঘূর্ণন দিয়ে সংশোধন ছাড়া অজানা চিনির ঘনত্ব পাবেন?|No, specific rotation depends on wavelength and temperature~না, আপেক্ষিক ঘূর্ণন তরঙ্গদৈর্ঘ্য ও তাপমাত্রানির্ভর|Yes, it is universal for all colours~হ্যাঁ, সব রঙে সর্বজনীন;Only tube length matters~শুধু নলের দৈর্ঘ্য গুরুত্বপূর্ণ;Changing wavelength makes rotation zero~তরঙ্গদৈর্ঘ্য বদলালে ঘূর্ণন শূন্য|α=[α]λ,Tlc; match wavelength and temperature (and solvent convention) when comparing to a reference value.~α=[α]λ,Tlc; মানের সঙ্গে তুলনায় তরঙ্গদৈর্ঘ্য, তাপমাত্রা ও দ্রাবকের রীতি মিলতে হবে।
photoelectric-planck-honours|Does the intercept at Vs=0 directly give Planck's constant?~Vs=০-এ রেখার ছেদ কি সরাসরি প্ল্যাঙ্ক ধ্রুবক দেয়?|No, slope gives h/e, while frequency intercept is φ/h~না, ঢাল h/e, কম্পাঙ্ক অক্ষের ছেদ φ/h|Yes, the intercept always equals h~হ্যাঁ, ছেদই সবসময় h;No, both intercept and slope are always zero~না, ছেদ-ঢাল উভয়ই শূন্য;Yes, only intensity determines h~হ্যাঁ, শুধু তীব্রতা h নির্ধারণ করে|From eVs=hf−φ, Vs=(h/e)f−φ/e; the f-axis threshold is φ/h, and h is e times the slope.~eVs=hf−φ থেকে Vs=(h/e)f−φ/e; কম্পাঙ্ক অক্ষে প্রান্তিক φ/h, আর h=e×ঢাল।
franck-hertz-mercury|Why use spacing between successive extrema instead of the voltage of the first maximum alone?~প্রথম চরম মানের বিভবের বদলে পরপর চরম মানের ব্যবধান কেন নেন?|Spacing reduces an approximately fixed contact-potential offset~ব্যবধান নিলে প্রায় স্থির সংযোগ-বিভব বাদ যায়|The first maximum has no electrons~প্রথম চরম মানে ইলেকট্রন নেই;Atomic excitation energy changes for every collision~প্রতি সংঘর্ষে উত্তেজনা শক্তি বদলায়;It removes all effects of vapour temperature~বাষ্পের তাপের সব প্রভাব দূর করে|Absolute peak position includes contact potentials and apparatus effects; differences across several peaks better approximate the repeated excitation energy eΔV.~চরম মানের নিরপেক্ষ অবস্থানে সংযোগ-বিভব ও যন্ত্রের প্রভাব থাকে; কয়েকটি পার্থক্য থেকে পুনরাবৃত্ত উত্তেজনা শক্তি eΔV ভালো পাওয়া যায়।
thermocouple-seebeck|Why must the reference junction temperature be measured or stabilized?~তুলনা সংযোগের তাপমাত্রা কেন মাপতে বা স্থির রাখতে হয়?|Thermoelectric emf depends on the junction temperature difference~তাপবিভব দুই সংযোগের তাপমাত্রা-পার্থক্যের ওপর নির্ভর করে|Only wire length sets emf~শুধু তারের দৈর্ঘ্যে বিভব হয়;The cold junction has zero resistance by definition~ঠান্ডা সংযোগের রোধ সংজ্ঞাতেই শূন্য;Measuring it prevents heat transfer~এটি মাপলে তাপ পরিবহন বন্ধ হয়|E≈SAB(Th−Tc). Unknown drift in Tc changes ΔT and corrupts the fitted Seebeck slope.~E≈SAB(Th−Tc)। Tc অজানাভাবে বদলালে ΔT ও নির্ণীত সিবেক ঢাল ভুল হয়।
lcr-series-resonance-lab|Why must the generator amplitude remain fixed while sweeping frequency?~কম্পাঙ্ক বদলানোর সময় উৎসের বিস্তার স্থির রাখতে হয় কেন?|Otherwise current changes may reflect input voltage rather than circuit resonance~নইলে প্রবাহের পরিবর্তন বর্তনীর অনুনাদ নয়, ইনপুট বিভবের কারণে হতে পারে|Resonance is impossible at constant amplitude~স্থির বিস্তারে অনুনাদ হয় না;Capacitance vanishes at high frequency~বেশি কম্পাঙ্কে ধারকত্ব শূন্য;Resistance becomes negative~রোধ ঋণাত্মক হয়|I=Vsource/Z. To infer the frequency dependence of Z and find half-power points, Vsource must be kept approximately constant.~I=Vsource/Z। Z-এর কম্পাঙ্কনির্ভরতা ও অর্ধক্ষমতার বিন্দু পেতে Vsource প্রায় স্থির রাখতে হয়।
transformer-characteristics-lab|Why is VI not always equal to real input power in a transformer?~ট্রান্সফরমারে VI কি সবসময় প্রকৃত ইনপুট ক্ষমতা? কেন নয়?|AC current may be phase-shifted; real power needs power factor~AC প্রবাহের দশা সরে যেতে পারে; প্রকৃত ক্ষমতায় power factor লাগে|Voltage has no SI unit~বিভবের SI একক নেই;Transformers only use DC~ট্রান্সফরমার শুধু DC-তে চলে;Current is always zero at all loads~সব ভারে প্রবাহ শূন্য|For sinusoidal AC, real input power is Vrms Irms cosφ, not generally Vrms Irms; use a wattmeter or measured power factor.~সাইন-রূপ AC-তে প্রকৃত ক্ষমতা Vrms Irms cosφ, শুধু Vrms Irms নয়; wattmeter বা power factor নিন।
pn-diode-iv-lab|Why is reverse current normally measured before reaching breakdown in an ordinary P–N diode test?~সাধারণ P–N ডায়োডে breakdown-এর আগে বিপরীত প্রবাহ মাপা হয় কেন?|Beyond the rating large reverse current may damage the diode~অনুমোদিত সীমা পেরিয়ে বড় বিপরীত প্রবাহে ডায়োড নষ্ট হতে পারে|All reverse voltages are harmless~সব বিপরীত বিভব নিরাপদ;A series resistor prevents any voltage across the diode~সারি রোধে ডায়োডে বিভবই থাকে না;Breakdown is required to measure forward current~সম্মুখ প্রবাহ মাপতে breakdown লাগে|A normal diode is not designed as a voltage regulator. Respect rated reverse voltage and use current limiting; a Zener is a different rated device.~সাধারণ ডায়োড বিভব নিয়ন্ত্রণের জন্য তৈরি নয়। বিপরীত বিভবের সীমা ও প্রবাহ-সীমক মানুন; জেনার আলাদা অনুমোদিত উপাদান।
zener-regulator-lab|When load current rises but input and Rs are fixed, what happens first to Zener current in regulation?~ইনপুট ও Rs স্থির রেখে ভারের প্রবাহ বাড়লে নিয়ন্ত্রণ অবস্থায় জেনার প্রবাহ প্রথমে কী হয়?|It decreases~কমে|It increases without limit~সীমাহীন বাড়ে;It must equal the load current~ভার প্রবাহের সমান হয়;It becomes negative immediately~সঙ্গে সঙ্গে ঋণাত্মক হয়|At approximately fixed Vout, series current (Vin−Vout)/Rs is nearly fixed and splits as Is=IL+Iz. Increasing IL reduces Iz until regulation fails.~Vout প্রায় স্থির হলে সারি প্রবাহ (Vin−Vout)/Rs প্রায় স্থির; Is=IL+Iz। IL বাড়লে Iz কমে, পরে নিয়ন্ত্রণ ভেঙে যেতে পারে।
'''
CHEMISTRY=r'''
naoh-oxalic-standardization|Why should the exact oxalic-acid hydrate form be checked before weighing?~ওজনের আগে অক্সালিক অ্যাসিডের hydrate রূপ নিশ্চিত করতে হয় কেন?|Anhydrous acid and dihydrate have different molar masses~অনাজল অম্ল ও ডাইহাইড্রেটের মোলার ভর আলাদা|Hydration changes the NaOH reaction ratio from 2:1 to 1:1~hydrate থাকলে NaOH-এর অনুপাত ২:১ থেকে ১:১ হয়;The burette capacity depends on hydrate~বিউরেটের ধারণক্ষমতা hydrate-নির্ভর;Water of crystallization makes acid non-acidic~স্ফটিকজলে অম্লের অম্লত্ব থাকে না|Dihydrate has molar mass about 126.07 g/mol versus 90.03 g/mol for anhydrous acid. Using the wrong mass gives a wrong primary-standard concentration, though neutralization remains 2:1.~ডাইহাইড্রেটের মোলার ভর প্রায় ১২৬.০৭ g/mol, অনাজলের ৯০.০৩ g/mol। ভুল ভরে মান ঘনত্ব ভুল হয়, তবে নিরপেক্ষকরণ অনুপাত ২:১-ই থাকে।
hcl-sodium-carbonate-standardization|Why is the endpoint for complete carbonate neutralization different from the first phenolphthalein endpoint?~কার্বোনেটের সম্পূর্ণ নিরপেক্ষতার সীমা প্রথম phenolphthalein সীমা থেকে আলাদা কেন?|The first step makes bicarbonate, which still consumes acid~প্রথম ধাপে বাইকার্বোনেট হয়, যা আরও অম্ল গ্রহণ করে|The first step releases all chloride ions~প্রথম ধাপে সব ক্লোরাইড বের হয়;Carbonate has only one neutralizable charge~কার্বোনেটে একটিই নিরপেক্ষযোগ্য আধান;Hydrochloric acid stops reacting above pH 7~pH ৭-এর উপরে HCl আর বিক্রিয়া করে না|CO₃²− first accepts H+ to become HCO₃−; a second H+ converts HCO₃− to carbonic acid and CO₂. Complete neutralization therefore uses two acid equivalents.~CO₃²− প্রথমে H+ নিয়ে HCO₃− হয়; দ্বিতীয় H+-এ কার্বনিক অম্ল ও CO₂ হয়। তাই সম্পূর্ণ নিরপেক্ষতায় দুই অম্ল-সমতুল্য লাগে।
double-indicator-carbonate|For a sample containing only NaOH and Na₂CO₃, what does M greater than 2P suggest?~শুধু NaOH ও Na₂CO₃ থাকার কথা হলে M>২P কী নির্দেশ করে?|Another component or a measurement/endpoint error~অন্য উপাদান বা পাঠ/সমাপ্তির ত্রুটি|A required result for pure NaOH~বিশুদ্ধ NaOH-এর আবশ্যিক ফল;Always exactly zero carbonate~সবসময় কার্বোনেট শূন্য;A negative concentration is physically valid~ঋণাত্মক ঘনত্ব বাস্তবে গ্রহণযোগ্য|n(OH−)=C(2P−M) would become negative. Since physical moles cannot be negative, the assumed two-component model or readings must be revisited.~n(OH−)=C(২P−M) ঋণাত্মক হবে। বাস্তবে মোল ঋণাত্মক হয় না; তাই দুই-উপাদান অনুমান বা পাঠ পুনর্বিবেচনা করুন।
permanganate-ferrous-titration|Why is dilute H₂SO₄ preferred over HCl in the permanganate–Fe²⁺ titration?~পারম্যাঙ্গানেট–Fe²⁺ টাইট্রেশনে HCl-এর বদলে পাতলা H₂SO₄ কেন?|Chloride can be oxidized, consuming permanganate~ক্লোরাইড জারিত হয়ে পারম্যাঙ্গানেট খরচ করতে পারে|Sulfate is the indicator colour~সালফেটই নির্দেশকের রং;HCl prevents Fe²⁺ from dissolving~HCl-এ Fe²⁺ দ্রবীভূত হয় না;Sulfuric acid has no hydrogen ions~সালফিউরিক অম্লে H+ নেই|Permanganate is a strong oxidant in acid and can oxidize chloride under titration conditions, giving an excessive titre unrelated to Fe²⁺.~অম্লে পারম্যাঙ্গানেট শক্তিশালী জারক; ক্লোরাইড জারিত হলে Fe²⁺ ছাড়াও বিকারক খরচ হয়ে পাঠ বেশি হয়।
dichromate-ferrous-titration|What should happen to Cr(VI)-containing leftovers after the experiment?~পরীক্ষার পর Cr(VI)-যুক্ত অবশিষ্টাংশ কী করবেন?|Collect in designated hazardous waste for supervised disposal~তত্ত্বাবধানে নির্দিষ্ট বিপজ্জনক বর্জ্যে সংগ্রহ|Pour directly into the sink~সরাসরি বেসিনে ঢালবেন;Evaporate openly in the classroom~ক্লাসরুমে উন্মুক্তভাবে শুকাবেন;Mix into ordinary paper waste~সাধারণ কাগজের বর্জ্যে মেশাবেন|Hexavalent chromium is toxic and carcinogenic. Use the smallest instructed quantity, wear protection and follow the institution's hazardous-waste protocol.~ষড়যোজী ক্রোমিয়াম বিষাক্ত ও ক্যানসার-ঝুঁকিপূর্ণ। নির্দেশিত অল্প পরিমাণ, সুরক্ষা ও প্রতিষ্ঠানের বিপজ্জনক বর্জ্যবিধি মানুন।
copper-iodometry|Why is starch added near the end rather than at the start of iodine titration?~আয়োডিন টাইট্রেশনে শ্বেতসার শুরুতে না দিয়ে শেষে কেন দেন?|Strong iodine–starch binding at high iodine levels can blur the endpoint~বেশি আয়োডিনে শক্ত শ্বেতসার-আয়োডিন বন্ধনে সীমা অস্পষ্ট হয়|Starch is required to form CuI~CuI তৈরিতে শ্বেতসার লাগে;Starch neutralizes acid quantitatively~শ্বেতসার অম্ল নিরপেক্ষ করে;Iodine has no colour without starch~শ্বেতসার ছাড়া আয়োডিনের রং নেই|Add starch when free iodine has fallen to pale yellow, then titrate to the loss of the blue complex; early addition can prolong a stubborn colour.~মুক্ত আয়োডিন ফিকে হলুদ হলে শ্বেতসার দিন, তারপর নীল রং মিলানো পর্যন্ত যান; আগে দিলে রং দীর্ঘস্থায়ী হয়ে সীমা ভুল হতে পারে।
vitamin-c-iodimetry|Why might direct iodine titration overestimate vitamin C in a mixed juice?~মিশ্র ফলের রসে প্রত্যক্ষ আয়োডিন টাইট্রেশনে ভিটামিন C বেশি মনে হতে পারে কেন?|Other reducing compounds also consume iodine~অন্য বিজারকও আয়োডিন খরচ করে|Water itself always consumes all iodine~পানিই সব আয়োডিন খরচ করে;Starch forms vitamin C from sugar~শ্বেতসার চিনি থেকে ভিটামিন C বানায়;The mole ratio changes with bottle size~বোতলের আকারে মোল অনুপাত বদলায়|The 1:1 ascorbate–iodine calculation assumes no other reductants. Other antioxidants give additional iodine demand unless separately corrected.~১:১ অ্যাসকরবেট–আয়োডিন হিসাবে অন্য বিজারক নেই ধরা হয়। অন্য অ্যান্টিঅক্সিডেন্টও আয়োডিন গ্রহণ করলে সংশোধন ছাড়া ফল বেশি হবে।
mohr-chloride-titration|Why should Mohr titration not be carried out in strongly acidic solution?~প্রবল অম্লীয় দ্রবণে মোহরের টাইট্রেশন করবেন না কেন?|The chromate indicator equilibrium and endpoint precipitation are disturbed~ক্রোমেট নির্দেশকের সাম্য ও সমাপ্তির অধঃক্ষেপ ব্যাহত হয়|AgCl becomes a gas~AgCl গ্যাস হয়;Chloride loses all electrons instantly~ক্লোরাইড সঙ্গে সঙ্গে সব ইলেকট্রন হারায়;Burette volume becomes negative~বিউরেটের আয়তন ঋণাত্মক হয়|Acid shifts chromate toward hydrogen chromate/dichromate, delaying the Ag₂CrO₄ brick-red endpoint. Use the method in its prescribed near-neutral pH range.~অম্লে ক্রোমেট hydrogen chromate/dichromate-এর দিকে সরে ইট-লাল Ag₂CrO₄ সমাপ্তি দেরি করে। নির্ধারিত প্রায় নিরপেক্ষ pH রাখুন।
volhard-chloride-back-titration|Why might AgCl be separated before back-titrating residual silver with SCN−?~বাকি সিলভারকে SCN− দিয়ে মাপার আগে AgCl কেন আলাদা করতে হয়?|SCN− can react with AgCl and bias the back-titre~SCN−, AgCl-এর সঙ্গে বিক্রিয়া করে বিপরীত পাঠ বদলাতে পারে|AgCl produces additional chloride from water~AgCl পানি থেকে ক্লোরাইড বানায়;Filtering changes the added silver moles~ছাঁকায় দেওয়া সিলভারের মোল বাড়ে;SCN− cannot precipitate silver~SCN− সিলভার অধঃক্ষেপ করতে পারে না|AgSCN is less soluble than AgCl; contact with AgCl can consume thiocyanate beyond that needed for free Ag+, affecting calculated chloride.~AgSCN, AgCl-এর চেয়ে কম দ্রবণীয়; AgCl থাকলে মুক্ত Ag+ ছাড়াও SCN− খরচ হয়ে ক্লোরাইডের হিসাব বদলায়।
sulfate-gravimetry-baso4|Why is BaSO₄ digested before filtering?~ছাঁকার আগে BaSO₄ অধঃক্ষেপ কিছুক্ষণ রেখে দেওয়া হয় কেন?|To grow larger, more filterable crystals and reduce adsorbed impurities~বড় সহজে-ছাঁকা স্ফটিক পেতে ও উপরিভাগের অশুদ্ধি কমাতে|To turn sulfate into chloride~সালফেটকে ক্লোরাইড করতে;To dissolve all BaSO₄~সব BaSO₄ গলাতে;To make barium harmless automatically~বেরিয়ামকে নিজে থেকে নিরাপদ করতে|Careful precipitation and digestion improve crystal size and purity. Drying to constant mass then limits water-related mass error.~ধীরে অধঃক্ষেপ ও digestion-এ স্ফটিক বড় ও তুলনামূলক বিশুদ্ধ হয়। স্থির ভর পর্যন্ত শুকালে পানির কারণে ভর-ত্রুটি কমে।
nickel-dmg-gravimetry|If Ni(DMG)₂ is weighed while still damp, what happens to the inferred nickel mass?~Ni(DMG)₂ ভেজা অবস্থায় ওজন করলে নির্ণীত নিকেলের ভর কী হবে?|It is overestimated~বেশি দেখাবে|It is exactly unchanged~একদম বদলাবে না;It is always zero~সবসময় শূন্য হবে;It becomes negative~ঋণাত্মক হবে|Residual liquid adds to the apparent precipitate mass, and m(Ni)=m(precipitate)×58.693/288.91 then scales upward. Dry to constant mass.~অবশিষ্ট তরল অধঃক্ষেপের আপাত ভর বাড়ায়; m(Ni)=m(অধঃক্ষেপ)×৫৮.৬৯৩/২৮৮.৯১-এ নিকেলের ফলও বাড়ে। স্থির ভর পর্যন্ত শুকান।
flame-test-cations|Can a flame test alone prove that an unknown salt contains only sodium?~শুধু শিখা পরীক্ষায় অজানা লবণে কেবল সোডিয়াম আছে বলে নিশ্চিত হওয়া যায়?|No, intense sodium yellow can mask other ions~না, সোডিয়ামের তীব্র হলুদ অন্য আয়ন ঢাকতে পারে|Yes, all other ions must be absent~হ্যাঁ, অন্য সব আয়ন অনুপস্থিত;Yes, yellow proves a pure element sample~হ্যাঁ, হলুদ মানেই বিশুদ্ধ মৌল;Only when the burner is unlit~শুধু বার্নার বন্ধ থাকলে|Flame emission is a preliminary qualitative observation. Clean the loop and confirm suspected ions with independent chemical tests or appropriate spectroscopy.~শিখার আলো প্রাথমিক গুণগত ধারণা। তার পরিষ্কার করে অন্য রাসায়নিক পরীক্ষা বা বর্ণালিবিজ্ঞানে আয়ন নিশ্চিত করুন।
dissolved-oxygen-winkler|Why must oxygen be fixed immediately after collecting water?~পানির নমুনা নেওয়ার সঙ্গে সঙ্গে অক্সিজেন fix করতে হয় কেন?|Dissolved oxygen can change through air exchange and biological activity~বায়ু বিনিময় ও জীবক্রিয়ায় দ্রবীভূত অক্সিজেন বদলায়|The water otherwise becomes pure oxygen~নইলে পানি বিশুদ্ধ অক্সিজেন হয়;Delayed fixation makes the bottle larger~দেরিতে বোতল বড় হয়;Thiosulfate concentration becomes zero in the bottle~বোতলে থায়োসালফেট শূন্য হয়|Bubbles, air exchange and microbial respiration/photosynthesis can change O₂ before titration. Immediate fixation preserves the sampling-time condition.~বুদ্‌বুদ, বায়ু বিনিময় ও অণুজীবের শ্বাস/আলোকসংশ্লেষে O₂ বদলাতে পারে। দ্রুত fix করলে নমুনা নেওয়ার সময়ের অবস্থা ধরে রাখা যায়।
neutralization-calorimetry|Why is the heat absorbed by the calorimeter included along with solution heat?~দ্রবণের তাপের সঙ্গে ক্যালরিমিটারের শোষিত তাপ কেন ধরবেন?|The container warms and absorbs part of the reaction heat~পাত্র গরম হয়ে বিক্রিয়ার তাপের অংশ শোষণ করে|The container produces extra acid~পাত্র অতিরিক্ত অম্ল তৈরি করে;A warmed container has negative mass~গরম পাত্রের ভর ঋণাত্মক;Water cannot absorb heat~পানি তাপ শোষণ করতে পারে না|At approximately constant pressure, qreleased≈(msol c+Cc)ΔT plus environmental losses; ignoring Cc generally underestimates the reaction heat magnitude.~প্রায় স্থির চাপে qনিঃসৃত≈(msol c+Cc)ΔT এবং পরিবেশের ক্ষতি; Cc বাদ দিলে সাধারণত বিক্রিয়া তাপের মান কম আসে।
ester-hydrolysis-kinetics|Why determine V∞ using a fully reacted aliquot rather than assume it?~V∞ অনুমান না করে সম্পূর্ণ বিক্রিয়ার নমুনা থেকে কেন মাপবেন?|V∞ sets the remaining-ester estimate V∞−Vt~V∞−Vt অবশিষ্ট এস্টারের পরিমাণ নির্দেশ করে|V∞ is always equal to V₀~V∞ সবসময় V₀-এর সমান;V∞ removes the need to record time~V∞ পেলে সময় মাপতে হয় না;Catalyst acid concentration is always zero~অনুঘটক অম্ল সবসময় শূন্য|The kinetic plot uses ln[(V∞−V₀)/(V∞−Vt)]. A wrong V∞ distorts every transformed value and can create a false linear trend.~গতির লেখচিত্র ln[(V∞−V₀)/(V∞−Vt)] ব্যবহার করে। ভুল V∞ সব রূপান্তরিত পাঠ ও রেখার ঢাল বিকৃত করে।
iodine-clock-rate-law|Why keep thiosulfate amount fixed when comparing clock times?~ঘড়ি পরীক্ষায় সময় তুলনায় থায়োসালফেটের পরিমাণ একই রাখেন কেন?|It fixes the iodine amount needed for blue colour~নীল রং দেখা দেওয়ার জন্য প্রয়োজনীয় আয়োডিনের পরিমাণ স্থির রাখে|It makes temperature irrelevant~তাপমাত্রার প্রভাব দূর করে;It removes all reaction induction delays~সব সূচনাবিলম্ব বাদ দেয়;It turns all reactions into zero order~সব বিক্রিয়াকে শূন্য-ক্রম করে|The colour appears after thiosulfate is consumed. Only a fixed threshold permits 1/t to act as a comparable rate proxy across mixtures.~থায়োসালফেট ফুরানোর পরে রং আসে। একই সীমা থাকলেই মিশ্রণভেদে ১/t-কে তুলনাযোগ্য হার ধরা যায়।
hydrogen-peroxide-decomposition|If the gas syringe leaks, how will measured O₂ volume compare with actual production?~গ্যাস সিরিঞ্জে ফুটো থাকলে মাপা O₂ আয়তন প্রকৃত উৎপাদের তুলনায় কেমন?|Too low~কম হবে|Too high by exactly twofold~ঠিক দ্বিগুণ বেশি হবে;Always unchanged~সবসময় একই থাকবে;Negative~ঋণাত্মক হবে|Escaping O₂ is not collected, so the observed volume underestimates product formation and corrupts rates derived from volume versus time.~বেরিয়ে যাওয়া O₂ ধরা পড়ে না; মাপা আয়তন প্রকৃত উৎপাদের কম হয় এবং সময়-আয়তন থেকে বের করা হারও ভুল হয়।
conductometric-acid-base|Why measure conductance beyond the equivalence point?~সাম্যবিন্দু পার হয়েও পরিবাহন কেন মাপেন?|Both descending and rising branches are needed for their intersection~নিম্নমুখী ও ঊর্ধ্বমুখী দুই রেখার ছেদ দরকার|After equivalence all conductance is zero~সমাপ্তির পরে পরিবাহন শূন্য;Only post-equivalence readings give original acid volume~শুধু পরের পাঠে প্রথম অম্লের আয়তন পাওয়া যায়;It makes dilution correction unnecessary~এতে পাতলা হওয়ার সংশোধন লাগে না|Before equivalence H+ replacement lowers conductance; excess OH− raises it afterwards. Their fitted intersection estimates the equivalence volume.~আগে H+ বদলায় বলে পরিবাহন কমে; পরে অতিরিক্ত OH−-এ বাড়ে। দুই রেখার ছেদ থেকে সাম্য আয়তন।
potentiometric-ferrous-ceric|Why use smaller Ce⁴⁺ additions near the steep potential jump?~বিভব দ্রুত বদলানোর কাছে Ce⁴⁺ অল্প অল্প কেন যোগ করেন?|To locate the equivalence inflection more accurately~সাম্যবিন্দুর মোড় আরও নির্ভুল পেতে|To stop Ce⁴⁺ from oxidizing Fe²⁺~Ce⁴⁺ যেন Fe²⁺ জারিত না করে;To make the electrode an insulator~ইলেকট্রোডকে অন্তরক করতে;To make the mole ratio 2:1~মোল অনুপাত ২:১ করতে|Large steps can leap over the maximum ΔE/ΔV and shift the estimated equivalence; allow the electrode reading to stabilize after each addition.~বড় ধাপে ΔE/ΔV-এর সর্বোচ্চ অঞ্চল বাদ পড়ে সাম্যবিন্দু ভুল হয়; প্রতিটি সংযোজনে বিভব স্থির হতে দিন।
nernst-cell-concentration|Why may measured concentration-cell emf differ from a calculation using concentration alone?~শুধু ঘনত্ব দিয়ে গণনা করা মান থেকে ঘনত্ব কোষের মাপা বিভব কেন ভিন্ন হতে পারে?|Activity coefficients and liquid-junction potential~সক্রিয়তা সহগ ও তরল-সংযোগ বিভব|Both electrodes necessarily have different standard potentials~দুই ইলেকট্রোডের মান বিভব অবশ্যই আলাদা;The Faraday constant is zero~ফ্যারাডে ধ্রুবক শূন্য;Identical electrodes eliminate all real-world corrections~একই ইলেকট্রোডে সব বাস্তব সংশোধন দূর হয়|Nernst law uses activities, not raw concentrations. A salt bridge can introduce junction potential, so record medium, temperature and these limitations.~নার্নস্ট সূত্রে ঘনত্ব নয়, সক্রিয়তা লাগে। লবণ সেতুতে সংযোগ বিভব থাকতে পারে; মাধ্যম, তাপ ও সীমা লিখুন।
ostwald-viscometer-relative|Why must bubbles be removed from an Ostwald viscometer?~অস্টওয়াল্ড সান্দ্রতামাপকে বুদ্‌বুদ কেন দূর করতে হয়?|They disrupt steady capillary flow and timing~বুদ্‌বুদ স্থির কৈশিক প্রবাহ ও সময় মাপা নষ্ট করে|They make all liquids identical~সব তরলকে একই করে;They make density exactly zero~ঘনত্ব শূন্য করে;They guarantee laminar motion~স্তরী প্রবাহ নিশ্চিত করে|The ratio η₁/η₂≈ρ₁t₁/(ρ₂t₂) assumes comparable uninterrupted flow through the same tube; trapped air changes the effective head and flow path.~η₁/η₂≈ρ₁t₁/(ρ₂t₂)-এ একই নলে বাধাহীন তুলনাযোগ্য প্রবাহ ধরা হয়; আটকে থাকা বায়ু চাপ ও পথ বদলায়।
stalagmometer-surface-tension|What happens if drops are produced rapidly instead of slowly?~ফোঁটা ধীরে না পড়িয়ে দ্রুত ফেললে কী সমস্যা?|Dynamic detachment biases the drop-count approximation~গতিশীল বিচ্ছেদে ফোঁটা-গণনার অনুমান ভুল হয়|Surface tension becomes identically zero~পৃষ্ঠটান শূন্য হয়;Density becomes infinite~ঘনত্ব অসীম হয়;The same volume contains no liquid~একই আয়তনে তরল থাকে না|The approximate mass-at-detachment model presumes similar, near-quasistatic drop formation for both liquids. Fast flow changes detachment and drop size.~দুটি তরলে প্রায় স্থিরভাবে অনুরূপ ফোঁটা বিচ্ছেদ ধরা হয়। দ্রুত প্রবাহে বিচ্ছেদ ও ফোঁটার আকার বদলায়।
liquid-partition-coefficient|Why might apparent Kd vary with concentration for an ionizable solute?~আয়নীভবনযোগ্য দ্রবের আপাত Kd ঘনত্বভেদে বদলাতে পারে কেন?|Neutral and ionic forms partition differently~নিরপেক্ষ ও আয়নিক রূপ ভিন্নভাবে বণ্টিত হয়|Both solvents must be identical~দুটি দ্রাবক অবশ্যই এক;Chemical potential stops existing~রাসায়নিক বিভব থাকে না;The separating funnel has no volume~পৃথকীকরণ ফানেলের আয়তন নেই|Kd=Corganic/Caqueous is constant for the same molecular form under defined conditions. Ionization or association changes the fraction of that form in each phase.~নির্দিষ্ট অবস্থায় একই আণবিক রূপে Kd=Corganic/Caqueous স্থির। আয়নীভবন বা সংযুক্তিতে দুই স্তরে সেই রূপের অংশ বদলায়।
charcoal-acetic-adsorption|Why should filtration occur only after sufficient adsorption-equilibration time?~যথেষ্ট শোষণ-সাম্যের পরেই ছাঁকা উচিত কেন?|Ce measured too early does not represent equilibrium~আগে মাপা Ce সাম্য ঘনত্ব নয়|The charcoal otherwise becomes soluble~নইলে কয়লা দ্রবীভূত হয়;All acid spontaneously disappears at equilibrium~সাম্যে সব অম্ল আপনা থেকে হারায়;Filtration creates acid molecules~ছাঁকায় অম্ল অণু তৈরি হয়|The fitted x/m versus Ce relation describes equilibrium uptake. A prematurely measured Ce varies with contact time and biases the Freundlich slope.~x/m বনাম Ce সম্পর্ক সাম্য শোষণের। আগে মাপা Ce সংস্পর্শ সময়ে বদলায় এবং Freundlich ঢাল ভুল করে।
thin-layer-chromatography-honours|Why mark the solvent front immediately after removing a TLC plate?~TLC প্লেট তোলার পরই দ্রাবকসীমা চিহ্নিত করবেন কেন?|The solvent evaporates and the front becomes hard to locate~দ্রাবক উবে গেলে সীমা চেনা কঠিন হয়|The front moves backward under gravity after drying~শুকালে সীমা মহাকর্ষে পিছিয়ে যায়;Rf becomes independent of front distance~Rf-এ দ্রাবকসীমার দূরত্ব লাগে না;Pencil marks always dissolve the plate~পেনসিলের দাগ সবসময় প্লেট গলায়|Rf uses the distance from origin to the solvent front. Delay obscures that position and produces an incorrect denominator.~Rf-এ মূল থেকে দ্রাবকসীমার দূরত্ব লাগে। দেরিতে সেই স্থান অস্পষ্ট হয়ে হর ভুল হয়।
'''

def pair(text):
    a,b=text.split('~',1)
    return a.strip(),b.strip()

if __name__=='__main__':
    records=[line.split('|') for block in (PHYSICS,CHEMISTRY) for line in block.splitlines() if line.strip()]
    assert len(records)==50 and all(len(record)==5 for record in records)
    slugs=set()
    for index,(slug,q,correct,wrong,explanation) in enumerate(records):
        assert slug not in slugs;slugs.add(slug)
        files=list(ROOT.glob(f'*/honours/{slug}.mdx'))
        assert len(files)==1,(slug,files)
        lab=files[0]
        quiz_file=ROOT/'quizzes'/f'honours-{slug}.json'
        data=json.loads(quiz_file.read_text(encoding='utf8'))
        assert len(data['questions'])==2, f'Already added to quiz: {slug}'
        source=lab.read_text(encoding='utf8')
        assert source.count('  - q:')==1, f'Already added to guide: {slug}'
        q_en,q_bn=pair(q);answer_en,answer_bn=pair(correct)
        why_en,why_bn=pair(explanation)
        distractors=[pair(value) for value in wrong.split(';')]
        assert len(distractors)==3,(slug,distractors)
        choices=[(answer_en,answer_bn)]+distractors
        assert len({c[0] for c in choices})==4
        shift=index%4
        ordered=choices[-shift:]+choices[:-shift] if shift else choices
        data['questions'].append(dict(q=q_en,q_bn=q_bn,options=[c[0] for c in ordered],options_bn=[c[1] for c in ordered],answer=shift,explanation=why_en,explanation_bn=why_bn))
        quiz_file.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
        # YAML quoted JSON strings are valid and safe for punctuation/newlines.
        viva='  - q: '+json.dumps(q_en,ensure_ascii=False)+'\n    a: '+json.dumps(why_en,ensure_ascii=False)+'\n    q_bn: '+json.dumps(q_bn,ensure_ascii=False)+'\n    a_bn: '+json.dumps(why_bn,ensure_ascii=False)+'\n'
        assert '\ntags:\n' in source
        lab.write_text(source.replace('\ntags:\n','\n'+viva+'tags:\n',1),encoding='utf8')
    print('Added 50 bilingual conceptual MCQs with detailed explanations and 50 corresponding lab viva items.')
