"""Generate a reviewed, bilingual Honours equation collection and its concept checks.
Run: python3 scripts/add-honours-50.py
No third-party Python packages are needed. Existing entries are never overwritten.
"""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]/'content'
# slug | subject | Bangla title | English title | relation (LaTex) | symbol:name:SI-unit list
# | starting law / reasoning (EN~BN) | intermediate relation | application (EN~BN) | assumption (EN~BN)
# | MCQ question (EN~BN) | correct;wrong;wrong;wrong | explanation (EN~BN)
DATA=r'''
rotational-kinetic-energy|physics|ঘূর্ণন গতিশক্তি|Rotational kinetic energy|K=\frac12 I\omega^2|K:energy:J,I:moment of inertia:kg m²,ω:angular speed:rad/s|Add kinetic energies of particles rigidly rotating about the same fixed axis.~একই স্থির অক্ষ ঘিরে দৃঢ়ভাবে ঘোরা কণাগুলোর গতিশক্তি যোগ করুন।|K=\sum_i\tfrac12m_i(\omega r_i)^2|I=2 kg m² and ω=3 rad/s give K=9 J.~I=২ kg m² এবং ω=৩ rad/s হলে K=৯ J।|Rigid body and fixed rotation axis; translating bodies also carry translational energy.~দৃঢ় বস্তু ও স্থির ঘূর্ণন অক্ষ; সরণ থাকলে অতিরিক্ত সরণগত শক্তিও থাকবে।|If angular speed doubles at fixed I, what happens to K?~I স্থির রেখে কৌণিক বেগ দ্বিগুণ হলে K কী হয়?|Four times;Twice;Half;Unchanged|K scales as ω².~K, ω²-এর সমানুপাতিক।
angular-impulse|physics|কৌণিক ঘাত|Angular impulse and torque|\boldsymbol\tau=\frac{d\mathbf L}{dt}|τ:torque:N m,L:angular momentum:kg m²/s,t:time:s|Take r×F for a particle about a fixed inertial origin.~স্থির জড় মূলবিন্দুতে কণার r×F নিন।|\frac{d}{dt}(\mathbf r\times\mathbf p)=\mathbf v\times\mathbf p+\mathbf r\times\mathbf F=\mathbf r\times\mathbf F|A constant 2 N m torque acting 3 s changes angular momentum by 6 kg m²/s.~২ N m ধ্রুব টর্ক ৩ s কাজ করলে কৌণিক ভরবেগ ৬ kg m²/s বদলায়।|Sum external torques for a many-particle system; choose one inertial origin throughout.~বহুকণার ক্ষেত্রে বহিঃস্থ টর্ক যোগ করুন; একই জড় মূলবিন্দু রাখুন।|Zero net external torque implies what?~মোট বহিঃস্থ টর্ক শূন্য হলে কী সংরক্ষিত?|Angular momentum;Angular speed always;Kinetic energy always;Torque|Integrate dL/dt=0.~dL/dt=০ সমাকলন করুন।
centripetal-force-honours|physics|অভিকেন্দ্র বল|Centripetal force on circular motion|F_c=\frac{mv^2}{r}|F_c:radial net force:N,m:mass:kg,v:speed:m/s,r:radius:m|For uniform circular motion the velocity vector rotates while its magnitude stays fixed.~সুষম বৃত্তীয় গতিতে বেগ ভেক্টর ঘোরে কিন্তু মান স্থির থাকে।|a_c=v^2/r|A 2 kg mass at 3 m/s on a 1 m circle needs radial resultant 18 N.~১ m ব্যাসার্ধে ৩ m/s বেগে ২ kg বস্তুর কেন্দ্রাভিমুখী লব্ধি ১৮ N।|F_c is the resultant radial component, not an additional force; circular path assumed.~F_c লব্ধি বলের অরীয় অংশ; এটি আলাদা কোনো নতুন বল নয়; বৃত্তীয় পথ ধরা হয়েছে।|Doubling speed at fixed radius changes F_c by?~ব্যাসার্ধ স্থির রেখে বেগ দ্বিগুণ করলে F_c কত গুণ?|Four;Two;Eight;One|Force is proportional to v².~বল v²-এর সমানুপাতিক।
gravity-potential-energy-honours|physics|মহাকর্ষীয় বিভব শক্তি|Gravitational potential energy outside a sphere|U=-\frac{GMm}{r}|U:potential energy:J,G:gravitational constant:N m²/kg²,M:source mass:kg,m:test mass:kg,r:center distance:m|Choose zero potential at infinity and integrate attractive inverse-square force.~অসীমে বিভব শূন্য ধরে আকর্ষী বিপরীত-বর্গ বল সমাকলন করুন।|U(r)-U(\infty)=-\int_\infty^r(-GMm/r'^2)\,dr'|Moving from r=R to 2R requires positive work GMm/(2R).~R থেকে ২R-এ নিতে ধনাত্মক কাজ GMm/(২R) লাগে।|Valid outside a spherically symmetric source or point mass; ignore other gravitating bodies.~গোলীয় প্রতিসম উৎসের বাইরে বা বিন্দুভরে প্রযোজ্য; অন্য উৎস উপেক্ষিত।|Why is U negative with zero at infinity?~অসীমে শূন্য ধরলে U ঋণাত্মক কেন?|Attractive binding;Repulsive binding;Negative mass;Zero gravity|Work is needed to remove a bound test mass to infinity.~আবদ্ধ ভরকে অসীমে সরাতে কাজ লাগে।
orbital-speed-circular|physics|বৃত্তীয় কক্ষপথের বেগ|Circular orbital speed|v=\sqrt{GM/r}|v:orbital speed:m/s,G:gravitational constant:N m²/kg²,M:central mass:kg,r:orbital radius:m|Balance gravitational force with centripetal force.~মহাকর্ষীয় বলকে অভিকেন্দ্র বলের সমান ধরুন।|GMm/r^2=mv^2/r|At 4 times the orbital radius speed becomes half for the same central mass.~একই কেন্দ্রভরে কক্ষপথের ব্যাসার্ধ ৪ গুণ হলে বেগ অর্ধেক হয়।|Circular orbit about a dominant spherical mass; elliptical orbits have variable speed.~প্রধান গোলীয় ভরের চারপাশে বৃত্তীয় কক্ষপথ; উপবৃত্তে বেগ বদলায়।|At four times the radius, speed is?~চার গুণ ব্যাসার্ধে বেগ কত?|Half;Double;Four times;Unchanged|v scales as 1/√r.~v, ১/√r-এর সমানুপাতিক।
shm-energy|physics|সরল ছন্দিত গতির শক্তি|Energy of ideal simple harmonic motion|E=\frac12 kA^2|E:total energy:J,k:spring stiffness:N/m,A:amplitude:m|Combine spring potential with kinetic energy under conservation.~শক্তি সংরক্ষণে স্প্রিংয়ের বিভব ও গতিশক্তি যোগ করুন।|E=\tfrac12kx^2+\tfrac12mv^2;\quad v=0\text{ at }x=A|k=100 N/m and A=0.10 m give E=0.50 J.~k=১০০ N/m এবং A=০.১০ m হলে E=০.৫০ J।|Ideal linear spring without damping or external drive; energy is not constant if friction acts.~ঘর্ষণ বা বাহ্যিক চালনা ছাড়া আদর্শ রৈখিক স্প্রিং; ঘর্ষণে শক্তি স্থির নয়।|Doubling amplitude changes energy by?~বিস্তার দ্বিগুণ হলে শক্তি কত গুণ?|Four;Two;One half;Unchanged|Energy depends on A².~শক্তি A²-এর সমানুপাতিক।
damped-amplitude|physics|ক্ষয়মান দোলনের বিস্তার|Envelope of a damped oscillator|A(t)=A_0e^{-bt/(2m)}|A:amplitude:m,A_0:initial amplitude:m,b:viscous damping coefficient:kg/s,m:mass:kg,t:time:s|Solve m ẍ+b ẋ+kx=0 using an exponential trial solution.~m ẍ+b ẋ+kx=০-এ সূচকীয় সমাধান বসান।|r_{\pm}=-b/(2m)\pm i\sqrt{k/m-b^2/(4m^2)}|After t=2m/b, envelope is A₀/e.~t=২m/b পরে বিস্তার A₀/e হয়।|Underdamped regime b²<4mk with constant linear damping; overdamping has no oscillatory amplitude envelope.~b²<৪mk এবং ধ্রুব রৈখিক damping; অতিক্ষয়ে দোলনের বিস্তার-আবরণ নেই।|At t=2m/b the amplitude is?~t=২m/b-এ বিস্তার কত?|A₀/e;A₀;2A₀;A₀/e²|Substitute into the exponential envelope.~সূচকীয় আবরণে মান বসান।
quality-factor-oscillator|physics|দোলকের গুণাঙ্ক|Quality factor of weakly damped oscillator|Q=\frac{m\omega_0}{b}|Q:quality factor:1,m:mass:kg,ω₀:natural angular frequency:rad/s,b:viscous damping coefficient:kg/s|Use the amplitude envelope e^(−bt/2m); energy scales as amplitude squared.~বিস্তার e^(−bt/2m); শক্তি বিস্তারের বর্গের সমানুপাতিক।|E(t)=E_0e^{-bt/m};\quad Q=2\pi\frac{E}{\Delta E_{\rm cycle}}|m=1 kg, ω₀=10 rad/s and b=0.5 kg/s give Q≈20.~m=১ kg, ω₀=১০ rad/s ও b=০.৫ kg/s হলে Q≈২০।|Weak linear damping b≪mω₀; different textbooks define damping rate γ differently.~দুর্বল রৈখিক ক্ষয় b≪mω₀; γ-এর সংজ্ঞা বইভেদে আলাদা হতে পারে।|Reducing b to half makes Q?~b অর্ধেক হলে Q কত?|Double;Half;Four times;Unchanged|Q inversely depends on b.~Q, b-এর ব্যস্তানুপাতিক।
wave-energy-string|physics|টানটান তারে তরঙ্গের বেগ|Wave speed on a stretched string|v=\sqrt{\mathcal T/\mu}|v:wave speed:m/s,𝒯:string tension:N,μ:linear mass density:kg/m|Apply transverse Newton's law to a short string element at small slope.~অল্প ঢালের ক্ষুদ্র তারখণ্ডে আনুপ্রস্থ নিউটনের সূত্র প্রয়োগ করুন।|\mu\partial_t^2y=\mathcal T\partial_x^2y;\quad\partial_t^2y=v^2\partial_x^2y|Four times the tension yields twice the speed at fixed μ.~μ স্থির রেখে টান ৪ গুণ করলে বেগ ২ গুণ হয়।|Small-amplitude transverse waves, uniform flexible string and nearly constant tension.~ক্ষুদ্র বিস্তারের আনুপ্রস্থ তরঙ্গ; সুষম নমনীয় তার ও প্রায় স্থির টান।|If tension quadruples, speed becomes?~টান চার গুণ করলে বেগ কত?|Twice;Four times;Half;Unchanged|Square-root dependence on tension.~টানের বর্গমূলের সমানুপাতিক।
wave-group-velocity|physics|তরঙ্গগুচ্ছের বেগ|Group velocity|v_g=\frac{d\omega}{dk}|v_g:group velocity:m/s,ω:angular frequency:rad/s,k:wave number:1/m|Superpose neighbouring wave numbers and frequencies.~কাছাকাছি তরঙ্গসংখ্যা ও কম্পাঙ্কের তরঙ্গ যোগ করুন।|\cos(k_1x-\omega_1t)+\cos(k_2x-\omega_2t)=2\cos(\Delta kx/2-\Delta\omega t/2)\cos(\bar kx-\bar\omega t)|For ω=ck in a nondispersive medium v_g=c.~অবিচ্ছুরণশীল মাধ্যমে ω=ck হলে v_g=c।|A narrow wave packet in a smooth dispersion relation; group velocity is not automatically signal speed in absorbing media.~মসৃণ বিচ্ছুরণ সম্পর্কে সংকীর্ণ তরঙ্গগুচ্ছ; শোষণকারী মাধ্যমে গুচ্ছবেগ সবসময় সংকেতবেগ নয়।|For ω=ck, group speed is?~ω=ck হলে গুচ্ছবেগ কত?|c;k/c;0;c²|Differentiate ω with respect to k.~k অনুযায়ী ω অন্তরক করুন।
young-fringe-width-honours|physics|ইয়ং পরীক্ষায় ঝালর প্রস্থ|Young interference fringe spacing|\beta=\frac{\lambda D}{d}|β:fringe spacing:m,λ:wavelength:m,D:screen distance:m,d:slit separation:m|Use path difference d sinθ≈dy/D for small angles.~ক্ষুদ্র কোণে পথ পার্থক্য d sinθ≈dy/D নিন।|dy_n/D=n\lambda;\quad y_{n+1}-y_n=\lambda D/d|λ=500 nm, D=2 m, d=0.5 mm give β=2 mm.~λ=৫০০ nm, D=২ m, d=০.৫ mm হলে β=২ mm।|Coherent monochromatic light, small angle and D≫d; finite slit width changes visibility.~সুসঙ্গত একরঙা আলো, ক্ষুদ্র কোণ ও D≫d; চিরের প্রস্থে দৃশ্যমানতা বদলায়।|If slit separation doubles, fringe width becomes?~চিরের ব্যবধান দ্বিগুণ হলে ঝালর-প্রস্থ কত?|Half;Double;Four times;Unchanged|β is inversely proportional to d.~β, d-এর ব্যস্তানুপাতিক।
single-slit-minimum-honours|physics|একক চিরের অন্ধকার ঝালর|Single-slit diffraction minima|a\sin\theta=m\lambda|a:slit width:m,θ:diffraction angle:rad,m:minimum order:1,λ:wavelength:m|Sum coherent contributions across a uniformly illuminated aperture of width a.~a প্রস্থের সমানভাবে আলোকিত চিরের অংশগুলোর বিস্তার যোগ করুন।|E(\theta)\propto\int_{-a/2}^{a/2}e^{ikx\sin\theta}dx\propto\frac{\sin(\pi a\sin\theta/\lambda)}{\pi a\sin\theta/\lambda}|For λ=500 nm and a=0.10 mm, the first minimum is near θ=0.005 rad.~λ=৫০০ nm ও a=০.১০ mm-এ প্রথম অন্ধকার প্রায় θ=০.০০৫ rad।|Fraunhofer far field, uniform illumination, m nonzero integer; m=0 is the central maximum.~দূরক্ষেত্র ও সুষম আলোকন; m অশূন্য পূর্ণসংখ্যা, m=০ কেন্দ্রীয় উজ্জ্বল অংশ।|Is m=0 a dark fringe?~m=০ কি অন্ধকার ঝালর?|No, central maximum;Yes;Only at large angle;Only for red light|At zero path difference fields add in phase.~শূন্য পথ পার্থক্যে তরঙ্গ একই দশায় যোগ হয়।
bragg-order-limit|physics|ব্র্যাগ প্রতিফলনের সর্বোচ্চ ক্রম|Maximum Bragg reflection order|n_{\max}=\left\lfloor\frac{2d}{\lambda}\right\rfloor|n_max:maximum order:1,d:interplanar spacing:m,λ:wavelength:m|Start with constructive interference from successive planes.~পরপর তল থেকে গঠনমূলক ব্যতিচারের শর্ত নিন।|n\lambda=2d\sin\theta;\quad\sin\theta\leq1|For 2d/λ=2.4, highest possible integer order is 2.~২d/λ=২.৪ হলে সর্বোচ্চ পূর্ণসংখ্যা ক্রম ২।|Geometric upper bound only; structure-factor extinction and intensity can hide allowed orders.~এটি শুধু জ্যামিতিক সীমা; গঠনগত বিলুপ্তি ও তীব্রতায় অনুমোদিত ক্রম অদৃশ্য হতে পারে।|If 2d/λ=2.4, largest possible order is?~২d/λ=২.৪ হলে সর্বোচ্চ ক্রম কত?|2;3;1;2.4|Reflection order is integer and sinθ≤1.~ক্রম পূর্ণসংখ্যা এবং sinθ≤১।
lensmaker-thin-honours|physics|পাতলা লেন্স নির্মাতার সূত্র|Thin lensmaker equation|\frac1f=(n-1)\left(\frac1{R_1}-\frac1{R_2}\right)|f:focal length:m,n:relative refractive index:1,R₁:first signed radius:m,R₂:second signed radius:m|Apply paraxial refraction at both spherical surfaces.~দুটি গোলীয় পৃষ্ঠে অক্ষসংলগ্ন প্রতিসরণ প্রয়োগ করুন।|P_1=(n-1)/R_1;\quad P_2=(1-n)/R_2;\quad P=1/f=P_1+P_2|For symmetric biconvex radii R₁=R and R₂=−R, 1/f=2(n−1)/R.~সমমিত দ্বি-উত্তল লেন্সে R₁=R, R₂=−R হলে ১/f=২(n−১)/R।|Thin lens in air with signed radii, paraxial rays and uniform n; thick lenses need separation correction.~বাতাসে পাতলা লেন্স, চিহ্নযুক্ত ব্যাসার্ধ ও অক্ষসংলগ্ন রশ্মি; মোটা লেন্সে সংশোধন লাগে।|If n approaches 1, focal power tends to?~n→১ হলে ফোকাস ক্ষমতা কতের দিকে যায়?|Zero;Infinity;One;Negative infinity|No relative index contrast means no refraction power.~আপেক্ষিক প্রতিসরাঙ্কের পার্থক্য না থাকলে ফোকাস ক্ষমতা থাকে না।
brewster-angle-honours|physics|ব্রুস্টার কোণ|Brewster angle for dielectric interface|\tan\theta_B=\frac{n_2}{n_1}|θ_B:Brewster incidence angle:rad,n₁:incident medium index:1,n₂:transmitted medium index:1|At zero p-polarized reflection, refracted and reflected rays are perpendicular.~p-মেরুকৃত প্রতিফলন শূন্য হলে প্রতিসৃত ও প্রতিফলিত রশ্মি লম্ব হয়।|\theta_t=\pi/2-\theta_B;\quad n_1\sin\theta_B=n_2\sin\theta_t|From air to glass n₂=1.5, θB≈56.3°.~বাতাস থেকে n₂=১.৫ কাচে θB≈৫৬.৩°।|Nonabsorbing isotropic dielectrics and flat interface; metals need complex refractive index.~শোষণহীন সমদিকী ডাইইলেকট্রিক ও সমতল সীমা; ধাতুতে জটিল প্রতিসরাঙ্ক লাগে।|At Brewster incidence, which component has zero reflected intensity ideally?~ব্রুস্টার কোণে আদর্শভাবে কোন মেরুকরণ প্রতিফলিত হয় না?|p polarization;s polarization;both;unpolarized component|Parallel (p) reflection coefficient vanishes.~সমান্তরাল (p) প্রতিফলন সহগ শূন্য।
thin-film-phase-reversal|physics|পাতলা স্তরে প্রতিফলিত ব্যতিচার|Thin-film reflected interference|2nt\cos\theta_t=\left(m+\tfrac12\right)\lambda_0|n:film refractive index:1,t:film thickness:m,θ_t:angle inside film:rad,m:fringe order:1,λ₀:vacuum wavelength:m|Find the round-trip optical path in the layer.~স্তরে যাতায়াতের আলোকপথ বের করুন।|\Delta_{opt}=2nt\cos\theta_t|At normal incidence and m=0, t=λ₀/(4n); for 600 nm and n=1.5, t=100 nm.~লম্ব আপতনে m=০ হলে t=λ₀/(৪n); ৬০০ nm ও n=১.৫-এ t=১০০ nm।|Constructive reflected light here assumes exactly one π phase reversal between the two rays; with zero or two reversals the bright condition is 2nt cosθ=mλ₀ instead.~এখানে প্রতিফলনে উজ্জ্বল শর্তটি দুই রশ্মির মধ্যে ঠিক একটি π দশা-বিপর্যয় ধরে; শূন্য বা দুটি বিপর্যয় হলে উজ্জ্বল শর্ত ২nt cosθ=mλ₀।|Does the reflection phase shift matter?~প্রতিফলনে দশা-বিপর্যয় কি গুরুত্বপূর্ণ?|Yes;No;Only for sound;Only at normal incidence|A π reversal switches bright and dark conditions.~π বিপর্যয়ে উজ্জ্বল ও অন্ধকার শর্ত পাল্টায়।
adiabatic-work-ideal-gas|physics|অ্যাডিয়াবেটিক গ্যাসের কাজ|Reversible adiabatic work by ideal gas|W=\frac{P_iV_i-P_fV_f}{\gamma-1}|W:work done by gas:J,P_i:initial pressure:Pa,V_i:initial volume:m³,P_f:final pressure:Pa,V_f:final volume:m³,γ:heat capacity ratio:1|Use Q=0 in the first law with W defined as work by the gas.~গ্যাসের করা কাজ W ধরে প্রথম সূত্রে Q=০ বসান।|W=-\Delta U=nC_V(T_i-T_f)=\frac{nR(T_i-T_f)}{\gamma-1}|During expansion PiVi=400 J and PfVf=300 J at γ=1.4, work is 250 J.~প্রসারণে PiVi=৪০০ J ও PfVf=৩০০ J, γ=১.৪ হলে কাজ ২৫০ J।|Reversible adiabatic ideal gas with constant heat capacities; not an irreversible free expansion.~ধ্রুব তাপধারণ ক্ষমতার আদর্শ গ্যাসে প্রত্যাবর্তী অ্যাডিয়াবেটিক প্রক্রিয়া; মুক্ত প্রসারণে নয়।|For expansion, is work by the gas positive?~প্রসারণে গ্যাসের করা কাজের চিহ্ন কী?|Positive;Negative;Always zero;Undefined|With the stated sign convention W=∫P dV>0 for expansion.~নির্ধারিত চিহ্নরীতিতে প্রসারণে W=∫P dV>০।
maxwell-rms-speed-honours|physics|গ্যাস অণুর rms বেগ|RMS molecular speed|v_{rms}=\sqrt{3RT/M}|v_rms:root mean square speed:m/s,R:gas constant:J/(mol K),T:absolute temperature:K,M:molar mass:kg/mol|Equipartition gives three translational degrees of freedom per molecule.~সমবণ্টনে প্রতি অণুর তিনটি সরণগত স্বাধীনতা নিন।|\tfrac12m\langle v^2\rangle=\tfrac32 k_BT;\quad m=M/N_A|At equal temperature, a gas with fourfold molar mass has half the rms speed.~একই তাপমাত্রায় ৪ গুণ মোলার ভরে rms বেগ অর্ধেক।|Classical equilibrium dilute gas; quantum degeneracy invalidates Maxwell distribution.~ধ্রুপদি সাম্যাবস্থার বিরল গ্যাস; কোয়ান্টাম অধঃপতনে ম্যাক্সওয়েল বণ্টন চলে না।|Four times the molar mass yields what speed ratio?~মোলার ভর চার গুণ হলে বেগের অনুপাত কত?|One half;Double;One fourth;Four|v_rms scales as 1/√M.~v_rms, ১/√M-এর সমানুপাতিক।
heat-engine-carnot-honours|physics|কার্নো ইঞ্জিনের সর্বোচ্চ দক্ষতা|Carnot heat-engine efficiency|\eta=1-\frac{T_c}{T_h}|η:thermal efficiency:1,T_c:cold reservoir temperature:K,T_h:hot reservoir temperature:K|For a reversible cycle, total entropy change of the reservoirs vanishes.~প্রত্যাবর্তী চক্রে তাপাধারগুলোর মোট এনট্রপি পরিবর্তন শূন্য।|Q_c/T_c=Q_h/T_h;\quad\eta=(Q_h-Q_c)/Q_h|Th=600 K and Tc=300 K yield η=0.50, not 100%.~Th=৬০০ K ও Tc=৩০০ K হলে দক্ষতা ০.৫০, ১০০% নয়।|Reversible upper bound between two reservoirs; temperatures in kelvin and actual engines are less efficient.~দুটি তাপাধারে প্রত্যাবর্তী ঊর্ধ্বসীমা; কেলভিন ব্যবহার করুন, বাস্তবে দক্ষতা কম।|For Th=600 K and Tc=300 K maximum η is?~Th=৬০০ K ও Tc=৩০০ K হলে সর্বোচ্চ η কত?|50%;25%;100%;0%|1−300/600=0.5.~১−৩০০/৬০০=০.৫।
blackbody-photon-energy|physics|কৃষ্ণবস্তুর ফোটন শক্তি|Photon energy and wavelength|E=\frac{hc}{\lambda}|E:photon energy:J,h:Planck constant:J s,c:speed of light:m/s,λ:vacuum wavelength:m|Combine quantum energy E=hν with vacuum dispersion c=λν.~ফোটনের E=hν এবং শূন্যস্থানের c=λν যোগ করুন।|\nu=c/\lambda|A photon of twice the wavelength has half the energy.~দ্বিগুণ তরঙ্গদৈর্ঘ্যের ফোটনের শক্তি অর্ধেক।|Vacuum wavelength is required; in a medium frequency and photon energy stay fixed while wavelength changes.~শূন্যস্থানের তরঙ্গদৈর্ঘ্য লাগবে; মাধ্যমে কম্পাঙ্ক ও ফোটনশক্তি অপরিবর্তিত থেকেও তরঙ্গদৈর্ঘ্য বদলায়।|If vacuum wavelength doubles, energy becomes?~শূন্যস্থানে তরঙ্গদৈর্ঘ্য দ্বিগুণ হলে শক্তি কত?|Half;Double;Four times;Unchanged|Energy varies inversely with vacuum wavelength.~শক্তি শূন্যস্থানের তরঙ্গদৈর্ঘ্যের ব্যস্তানুপাতিক।
relativistic-momentum-honours|physics|আপেক্ষিকতামূলক ভরবেগ|Relativistic momentum|p=\gamma mv|p:momentum:kg m/s,γ:Lorentz factor:1,m:rest mass:kg,v:speed:m/s|Define four-momentum as rest mass times four-velocity.~চার-বেগকে স্থির ভর দিয়ে গুণ করে চার-ভরবেগ সংজ্ঞায়িত করুন।|P^\mu=m\gamma(c,\mathbf v);\quad\gamma=(1-v^2/c^2)^{-1/2}|For v≪c, γ≈1 and p≈mv.~v≪c হলে γ≈১, তাই p≈mv।|Massive particle in an inertial frame; photons have m=0 and p=E/c instead.~জড় কাঠামোয় স্থির ভরযুক্ত কণা; ফোটনের m=০, তার p=E/c।|For v≪c, what does p approach?~v≪c হলে p কোন মানের দিকে যায়?|mv;mc²;0 always;m/v|γ approaches 1 in the low-speed limit.~কম বেগে γ→১।
radioactive-half-life-honours|physics|তেজস্ক্রিয় ক্ষয়ের অর্ধায়ু|Radioactive half-life|t_{1/2}=\frac{\ln2}{\lambda_d}|t_half:half-life:s,λ_d:decay constant:1/s|Begin with first-order radioactive decay dN/dt=−λd N.~প্রথম-ক্রম তেজস্ক্রিয় ক্ষয় dN/dt=−λd N থেকে শুরু করুন।|N(t)=N_0e^{-\lambda_dt};\quad N(t_{1/2})=N_0/2|After three half-lives N=N₀/8.~তিন অর্ধায়ু পরে N=N₀/৮।|Independent nuclei with constant decay probability; not a deterministic lifetime for one nucleus.~ধ্রুব ক্ষয়সম্ভাবনাযুক্ত স্বাধীন নিউক্লিয়াস; এক নিউক্লিয়াসের নিশ্চিত আয়ু নয়।|After three half-lives what fraction remains?~তিন অর্ধায়ু পরে কত অংশ অবশিষ্ট?|1/8;1/3;1/6;1/9|Repeatedly divide by two three times.~তিনবার ২ দিয়ে ভাগ করুন।
cyclotron-radius-honours|physics|চৌম্বক ক্ষেত্রে কণার কক্ষব্যাসার্ধ|Cyclotron orbit radius|r=\frac{p_\perp}{\lvert q\rvert B}|r:orbit radius:m,p_perp:transverse momentum:kg m/s,q:particle charge:C,B:magnetic field:T|Perpendicular magnetic Lorentz force provides radial centripetal change in momentum.~লম্ব চৌম্বক লরেঞ্জ বল ভরবেগের অভিকেন্দ্র পরিবর্তন ঘটায়।|\lvert q\rvert v_\perp B=p_\perp v_\perp/r|At fixed momentum, doubling B halves r.~স্থির ভরবেগে B দ্বিগুণ করলে r অর্ধেক।|Uniform field and motion with a nonzero perpendicular component; parallel velocity produces a helix.~সুষম ক্ষেত্র ও লম্ব বেগ-উপাংশ; সমান্তরাল বেগ থাকলে সর্পিল পথ।|At fixed p and q, doubling B makes r?~p ও q স্থির রেখে B দ্বিগুণ করলে r কত?|Half;Double;Four times;Unchanged|r is inversely proportional to B.~r, B-এর ব্যস্তানুপাতিক।
magnetic-flux-induction|physics|চৌম্বক ফ্লাক্সে আবিষ্ট বিভব|Induced emf in N-turn coil|\mathcal E=-N\frac{d\Phi_B}{dt}|ℰ:induced electromotive force:V,N:turn count:1,Φ_B:flux per turn:Wb,t:time:s|Faraday law relates the emf around a loop to changing flux linkage.~ফ্যারাডের সূত্রে বদ্ধ পথে বিভবকে ফ্লাক্স-সংযোগ পরিবর্তনের সঙ্গে তুলনা করুন।|\Lambda=N\Phi_B;\quad\mathcal E=-d\Lambda/dt|A 10-turn coil with flux per turn falling by 0.02 Wb in 1 s has emf magnitude 0.2 V.~১০ পাক কুণ্ডলীতে প্রতি পাকে ফ্লাক্স ১ s-এ ০.০২ Wb কমলে বিভবের মান ০.২ V।|Same flux through each tightly coupled turn; minus sign expresses Lenz's law and orientation convention.~সব পাকে একই ফ্লাক্স; ঋণ চিহ্ন লেঞ্জের সূত্র ও অভিমুখ রীতি নির্দেশ করে।|If N doubles with the same flux change rate, emf magnitude?~একই ফ্লাক্স পরিবর্তনে N দ্বিগুণ হলে বিভবের মান?|Doubles;Halves;Zero;Unchanged|Flux linkage is NΦB.~ফ্লাক্স-সংযোগ NΦB।
inductor-energy-honours|physics|আবেশকে সঞ্চিত শক্তি|Energy stored in an inductor|U=\frac12 LI^2|U:stored energy:J,L:inductance:H,I:current:A|The source must work against induced emf while current rises.~প্রবাহ বাড়ার সময় উৎসকে আবিষ্ট বিভবের বিপরীতে কাজ করতে হয়।|dU=I L\,dI|L=2 H and I=3 A give U=9 J.~L=২ H ও I=৩ A হলে U=৯ J।|Linear inductor with constant L; saturation makes L current dependent.~ধ্রুব L-সহ রৈখিক আবেশক; চৌম্বক saturation-এ L বদলায়।|If I doubles at fixed L, stored energy?~L স্থির রেখে I দ্বিগুণ হলে সঞ্চিত শক্তি কত?|Four times;Twice;Half;Unchanged|Energy scales as I².~শক্তি I²-এর সমানুপাতিক।
rc-discharge-honours|physics|RC বর্তনীর নিঃসরণ|RC capacitor discharge|V_C(t)=V_0e^{-t/(RC)}|V_C:capacitor voltage:V,V₀:initial voltage:V,R:resistance:Ω,C:capacitance:F,t:time:s|Use Kirchhoff loop law for a discharging capacitor with I=−dq/dt.~নিঃসরণে I=−dq/dt রেখে কির্শহফের বর্তনী সূত্র ব্যবহার করুন।|R\,dq/dt+q/C=0;\quad q(0)=CV_0|At t=RC, voltage is V₀/e≈0.368 V₀.~t=RC-এ বিভব V₀/e≈০.৩৬৮V₀।|Ideal constant R and C without leakage or inductance; measure voltage with a high-impedance meter.~আদর্শ ধ্রুব R ও C, leakage বা আবেশ নেই; উচ্চ প্রতিবন্ধক ভোল্টমিটার লাগবে।|At t=RC, voltage is closest to?~t=RC-এ বিভব প্রায় কত?|0.37V₀;0.50V₀;0;V₀|e^(−1)≈0.368.~e^(−১)≈০.৩৬৮।
'''
DATA+=r'''
dalton-partial-pressure-honours|chemistry|ডাল্টনের আংশিক চাপ|Dalton partial-pressure law|P=\sum_i P_i|P:total pressure:Pa,P_i:partial pressure of component i:Pa|For ideal noninteracting gases, pressure is the sum of wall momentum transfers from each species.~আদর্শ আন্তঃক্রিয়াহীন গ্যাসে প্রতিটি প্রজাতির দেয়ালে ভরবেগ হস্তান্তর যোগ হয়।|P_i=n_iRT/V;\quad P=(\sum_i n_i)RT/V|Two ideal gases at 20 and 30 kPa contribute 50 kPa total.~দুটি আদর্শ গ্যাসের ২০ ও ৩০ kPa মিলে মোট ৫০ kPa।|Ideal-gas approximation at shared T and V; strong interactions cause nonideal departures.~একই T ও V-তে আদর্শ গ্যাসের অনুমান; প্রবল আন্তঃক্রিয়ায় বিচ্যুতি হয়।|20 kPa plus 30 kPa partial pressures make total?~২০ ও ৩০ kPa আংশিক চাপ মিলে মোট?|50 kPa;10 kPa;600 kPa;1.5 kPa|Add the partial pressures.~আংশিক চাপ যোগ করুন।
graham-effusion-honours|chemistry|গ্রাহামের ব্যাপন সূত্র|Graham effusion rate ratio|\frac{r_1}{r_2}=\sqrt{\frac{M_2}{M_1}}|r₁:effusion rate of gas 1:mol/s,r₂:effusion rate of gas 2:mol/s,M₁:molar mass of gas 1:kg/mol,M₂:molar mass of gas 2:kg/mol|At equal temperature molecular speed is inversely proportional to square root of molar mass.~একই তাপমাত্রায় অণুর বেগ মোলার ভরের বর্গমূলের ব্যস্তানুপাতিক।|r\propto\bar v\propto\sqrt{RT/M}|A gas four times heavier effuses approximately half as fast.~৪ গুণ ভারী গ্যাস প্রায় অর্ধেক হারে বের হয়।|Small-hole molecular effusion, equal T and comparable pressures; not bulk diffusion through a tube.~ক্ষুদ্র ছিদ্র দিয়ে আণবিক নির্গমন, সমান T ও কাছাকাছি চাপ; নলের ভেতর স্থূল ব্যাপন নয়।|Fourfold higher molar mass gives rate?~মোলার ভর চার গুণ হলে নির্গমন হার?|Half;Double;Four times;Unchanged|r scales with M^(−1/2).~r, M^(−১/২)-এর সমানুপাতিক।
relative-vapor-pressure-lowering|chemistry|বাষ্পচাপের আপেক্ষিক হ্রাস|Relative vapour-pressure lowering|\frac{P^\circ-P}{P^\circ}=x_B|P:pure-solvent solution vapour pressure:Pa,P°:pure solvent vapour pressure:Pa,x_B:nonvolatile solute mole fraction:1|Apply Raoult's law to solvent A with nonvolatile solute B.~অনুদ্বায়ী B দ্রবসহ দ্রাবক A-তে রাউল্টের সূত্র প্রয়োগ করুন।|P=x_A P^\circ;\quad x_A=1-x_B|A 0.10 solute mole fraction ideally reduces vapour pressure by 10%.~দ্রবের মোলভাগ ০.১০ হলে আদর্শভাবে বাষ্পচাপ ১০% কমে।|Ideal solution and nonvolatile solute; deviations arise from different intermolecular interactions.~আদর্শ দ্রবণ ও অনুদ্বায়ী দ্রব; ভিন্ন আন্তঃআণবিক আকর্ষণে বিচ্যুতি হয়।|For xB=0.10, relative lowering is?~xB=০.১০ হলে আপেক্ষিক হ্রাস?|0.10;0.90;10;0|Directly equals solute mole fraction.~এটি দ্রবের মোলভাগের সমান।
freezing-depression-electrolyte|chemistry|তড়িৎবিশ্লেষ্যের হিমাঙ্ক হ্রাস|Electrolyte freezing-point depression|\Delta T_f=iK_f m|ΔT_f:freezing point decrease:K,i:van't Hoff factor:1,K_f:cryoscopic constant:K kg/mol,m:molality:mol/kg|At low concentration the solvent chemical-potential decrease depends on dissolved particle concentration.~কম ঘনত্বে দ্রাবকের রাসায়নিক বিভবের হ্রাস দ্রবীভূত কণার ঘনত্বের ওপর নির্ভর করে।|\Delta T_f=K_fm_{particles};\quad m_{particles}=im|For ideal NaCl with i≈2 and Kf=1.86 K kg/mol at m=0.10 mol/kg, ΔTf≈0.372 K.~আদর্শ NaCl-এ i≈২, Kf=১.৮৬ ও m=০.১০ হলে ΔTf≈০.৩৭২ K।|Dilute solution and approximately constant i; association or incomplete dissociation alters i.~বিরল দ্রবণ ও প্রায় স্থির i; সংযুক্তি বা অসম্পূর্ণ বিয়োজনে i বদলায়।|If ideal i doubles, ΔTf does what?~আদর্শ i দ্বিগুণ হলে ΔTf কত?|Doubles;Halves;Unchanged;Zero|ΔTf is proportional to i at fixed m.~m স্থির থাকলে ΔTf, i-এর সমানুপাতিক।
osmotic-pressure-electrolyte|chemistry|তড়িৎবিশ্লেষ্যের অভিস্রবণ চাপ|Osmotic pressure of dilute electrolyte|\pi=iCRT|π:osmotic pressure:Pa,i:van't Hoff factor:1,C:solute molarity:mol/m³,R:gas constant:J/(mol K),T:absolute temperature:K|Balance solvent chemical potentials across a semipermeable membrane in the dilute limit.~বিরল সীমায় অর্ধভেদ্য ঝিল্লির দুপাশে দ্রাবকের রাসায়নিক বিভব সমান করুন।|\pi=RTC_{particles};\quad C_{particles}=iC|At same concentration and temperature, ideal CaCl₂ (i≈3) exerts thrice the pressure of a nondissociating solute.~একই T ও ঘনত্বে আদর্শ CaCl₂ (i≈৩) অবিয়োজিত দ্রবের তিন গুণ চাপ দেয়।|Dilute ideal solution, membrane passes solvent but rejects all solute; C in SI mol/m³ for pascals.~বিরল আদর্শ দ্রবণ; ঝিল্লি দ্রাবক পার করে কিন্তু দ্রব নয়; Pa পেতে C-এর একক mol/m³।|At fixed C and T, doubling i makes π?~C ও T স্থির রেখে i দ্বিগুণ হলে π?|Double;Half;Zero;Same|π scales with effective particle concentration.~π কার্যকর কণাঘনত্বের সমানুপাতিক।
second-order-half-life|chemistry|দ্বিতীয়-ক্রম বিক্রিয়ার অর্ধায়ু|Second-order half-life|t_{1/2}=\frac{1}{k[A]_0}|t_half:half-life:s,k:second-order rate constant:m³/(mol s),A₀:initial reactant concentration:mol/m³|Use the integrated law for a single-reactant second-order rate −d[A]/dt=k[A]².~একক বিকারকের দ্বিতীয়-ক্রম হার −d[A]/dt=k[A]² সমাকলন করুন।|1/[A]-1/[A]_0=kt;\quad[A](t_{1/2})=[A]_0/2|If k=0.1 L/(mol s) and [A]₀=1 mol/L, t½=10 s (consistent units).~k=০.১ L/(mol s) ও [A]₀=১ mol/L হলে t½=১০ s (সঙ্গত এককে)।|Specifically rate law k[A]², not every overall second-order reaction.~বিশেষভাবে হার k[A]²; সব মোট দ্বিতীয়-ক্রম বিক্রিয়ায় একই নয়।|If initial concentration doubles, half-life becomes?~প্রাথমিক ঘনত্ব দ্বিগুণ হলে অর্ধায়ু?|Half;Double;Four times;Same|Inverse dependence on initial concentration.~প্রাথমিক ঘনত্বের ব্যস্তানুপাতিক।
pseudo-first-order-rate|chemistry|ছদ্ম প্রথম-ক্রম হার|Pseudo-first-order rate law|r=k'[A],\quad k'=k[B]_0|r:reaction rate:mol/(m³ s),k_prime:observed first-order constant:1/s,A:limiting reactant concentration:mol/m³,B₀:approximately fixed excess reactant:mol/m³|Start from an elementary or measured bimolecular rate k[A][B].~k[A][B] ধরনের মৌলিক বা পরীক্ষালব্ধ দ্বি-অণু হার দিয়ে শুরু করুন।|[B]\approx[B]_0\gg[A]_0|If [B]₀ doubles while k stays fixed, the apparent first-order constant doubles.~k স্থির রেখে [B]₀ দ্বিগুণ হলে আপাত প্রথম-ক্রম ধ্রুবক দ্বিগুণ।|B remains effectively constant due to large excess; a first-order-looking plot does not prove a unimolecular mechanism.~অতিরিক্ত B প্রায় অপরিবর্তিত; প্রথম-ক্রম রেখা মানেই এক-অণু প্রক্রিয়া নয়।|If excess [B]₀ doubles, k′?~অতিরিক্ত [B]₀ দ্বিগুণ হলে k′?|Doubles;Halves;Unchanged;Squares|k′=k[B]₀.~k′=k[B]₀।
reaction-quotient-gibbs|chemistry|বিক্রিয়া ভাগফল ও গিবস শক্তি|Reaction Gibbs energy and quotient|\Delta_rG=\Delta_rG^\circ+RT\ln Q|ΔrG:reaction Gibbs energy:J/mol,ΔrG°:standard reaction Gibbs energy:J/mol,R:gas constant:J/(mol K),T:absolute temperature:K,Q:dimensionless activity quotient:1|Write each chemical potential as μi=μi°+RT ln ai and sum with stoichiometric coefficients.~প্রতিটি রাসায়নিক বিভব μi=μi°+RT ln ai লিখে বিক্রিয়ার সহগসহ যোগ করুন।|\Delta_rG=\sum_i\nu_i\mu_i;\quad Q=\prod_i a_i^{\nu_i}|At equilibrium ΔrG=0, giving ΔrG°=−RT ln K.~সাম্যে ΔrG=০; ফলে ΔrG°=−RT ln K।|Activities are dimensionless relative to standards; Q must not be a logarithm of dimensional concentrations.~সক্রিয়তা মান অবস্থার তুলনায় মাত্রাহীন; মাত্রাযুক্ত ঘনত্বের লগারিদম নেবেন না।|At equilibrium ΔrG equals?~সাম্যে ΔrG কত?|Zero;RT;Infinity;Always positive|No thermodynamic driving force at equilibrium.~সাম্যে তাপগতীয় চালিকা শক্তি শূন্য।
vanthoff-equilibrium-temperature|chemistry|সাম্যে ভান্ট হফ তাপমাত্রা সূত্র|van't Hoff temperature dependence of equilibrium|\frac{d\ln K}{dT}=\frac{\Delta_rH^\circ}{RT^2}|K:dimensionless equilibrium constant:1,T:absolute temperature:K,ΔrH°:standard reaction enthalpy:J/mol,R:gas constant:J/(mol K)|Use ΔrG°=−RT ln K and the Gibbs–Helmholtz identity.~ΔrG°=−RT ln K ও গিবস–হেলমহোল্টজ পরিচয় ব্যবহার করুন।|d(\Delta_rG^\circ/T)/dT=-\Delta_rH^\circ/T^2|For ΔrH°>0, K rises with increasing T locally.~ΔrH°>০ হলে T বাড়ালে স্থানীয়ভাবে K বাড়ে।|Standard-state K; integrated forms require ΔH° approximately constant over the range.~মান অবস্থার K; সমাকলিত সূত্রে পরিসরে ΔH° প্রায় স্থির ধরতে হয়।|For endothermic reaction, increasing T tends to?~তাপশোষী বিক্রিয়ায় T বাড়ালে K সাধারণত?|Increase;Decrease;Always 1;Undefined|Derivative is positive if ΔrH°>0.~ΔrH°>০ হলে অন্তরক ধনাত্মক।
kirchhoff-reaction-enthalpy|chemistry|কির্শহফের বিক্রিয়া এনথ্যালপি সূত্র|Kirchhoff relation for reaction enthalpy|\Delta_rH^\circ(T_2)=\Delta_rH^\circ(T_1)+\int_{T_1}^{T_2}\Delta_rC_p^\circ(T)\,dT|ΔrH°:standard reaction enthalpy:J/mol,T₁:initial temperature:K,T₂:final temperature:K,ΔrCp°:reaction heat capacity:J/(mol K)|At constant pressure, temperature derivative of reaction enthalpy equals the stoichiometric heat-capacity difference.~স্থির চাপে বিক্রিয়া এনথ্যালপির তাপমাত্রা-অন্তরক হলো স্টইকিওমেট্রিক তাপধারণ ক্ষমতার পার্থক্য।|d\Delta_rH^\circ/dT=\Delta_rC_p^\circ|If ΔCp°=10 J/(mol K) from 300 to 400 K, ΔH° rises by 1.0 kJ/mol.~৩০০ থেকে ৪০০ K-তে ΔCp°=১০ J/(mol K) হলে ΔH° ১.০ kJ/mol বাড়ে।|Same specified reaction and consistent standard states; phase transitions require additional latent-heat terms.~একই বিক্রিয়া ও সঙ্গত মান অবস্থা; দশা পরিবর্তনে সুপ্ততাপ যোগ করতে হয়।|For positive ΔCp°, heating raises ΔH° by?~ΔCp° ধনাত্মক হলে তাপ বাড়ালে ΔH°?|Positive amount;Negative amount;Always zero;Infinite amount|Integral of positive ΔCp° over rising T is positive.~বাড়ন্ত T-তে ধনাত্মক ΔCp°-এর সমাকলন ধনাত্মক।
acid-dissociation-ratio|chemistry|অম্লের বিয়োজন অনুপাত|Acid dissociation and conjugate-base ratio|\frac{[A^-]}{[HA]}=10^{pH-pK_a}|A_minus:conjugate-base concentration:mol/L,HA:weak acid concentration:mol/L,pH:hydrogen ion pH:1,pKa:acid strength exponent:1|Start from Ka=aH aA/aHA and approximate activities by concentrations under fixed ionic conditions.~Ka=aH aA/aHA থেকে স্থির আয়নিক অবস্থায় সক্রিয়তার স্থলে ঘনত্বের অনুমান নিন।|pH=pK_a+\log_{10}([A^-]/[HA])|When pH exceeds pKa by one, base-to-acid ratio is 10:1.~pH, pKa-এর চেয়ে ১ বেশি হলে ক্ষার:অম্ল অনুপাত ১০:১।|Dilute buffer approximation; at high ionic strength use activities, not raw concentrations.~বিরল বাফারে অনুমান; উচ্চ আয়নিক শক্তিতে ঘনত্ব নয়, সক্রিয়তা নিন।|At pH=pKa, ratio base/acid?~pH=pKa হলে ক্ষার/অম্ল অনুপাত?|1;10;0.1;0|10⁰=1.~১০⁰=১।
weak-acid-ph-approx|chemistry|দুর্বল অম্লের pH অনুমান|Weak monoprotic acid pH approximation|[H^+]\approx\sqrt{K_a C}|H_plus:hydrogen ion concentration:mol/L,Ka:acid dissociation constant:mol/L,C:analytical acid concentration:mol/L|Let dissociation x from HA⇌H+ + A− so Ka=x²/(C−x).~HA⇌H+ + A−-তে x বিয়োজন ধরে Ka=x²/(C−x) লিখুন।|x\ll C\Rightarrow C-x\approx C|For Ka=10⁻⁵ mol/L and C=0.10 mol/L, [H+]≈10⁻³ mol/L, pH≈3.~Ka=১০⁻⁵ mol/L ও C=০.১০ mol/L হলে [H+]≈১০⁻³ mol/L, pH≈৩।|Assumes x≪C and water autoionization negligible; validate x/C, and use activities for accurate pH.~x≪C ও পানির স্ববিয়োজন উপেক্ষণীয়; x/C যাচাই ও নির্ভুল pH-তে সক্রিয়তা ব্যবহার করুন।|If C quadruples at fixed Ka, approximate [H+] becomes?~Ka স্থির রেখে C চার গুণ হলে আনুমানিক [H+]?|Double;Four times;Half;Unchanged|Square-root dependence on C.~C-এর বর্গমূলের সমানুপাতিক।
solubility-ab-salt|chemistry|AB লবণের দ্রাব্যতা গুণফল|Solubility product for an AB salt|K_{sp}=s^2|Ksp:concentration-based solubility product:mol²/L²,s:molar solubility in pure water:mol/L|For AB(s)⇌A+ + B−, each mole dissolved gives one mole of each ion.~AB(s)⇌A+ + B−-এ প্রতি মোল দ্রবণে উভয় আয়ন এক মোল করে আসে।|[A^+]=[B^-]=s;\quad K_{sp}=[A^+][B^-]|If Ksp=10⁻⁸ (mol/L)² then s=10⁻⁴ mol/L in pure water.~Ksp=১০⁻⁸ (mol/L)² হলে বিশুদ্ধ পানিতে s=১০⁻⁴ mol/L।|No common ions, complexes or hydrolysis; thermodynamic Ksp uses activities and is dimensionless.~সাধারণ আয়ন, জটিল আয়ন বা hydrolysis নেই; প্রকৃত Ksp সক্রিয়তাভিত্তিক মাত্রাহীন।|If Ksp grows 100-fold, s grows?~Ksp ১০০ গুণ হলে s কত গুণ?|Ten;Hundred;Two;Unchanged|s=√Ksp.~s=√Ksp।
common-ion-solubility|chemistry|সাধারণ আয়নে দ্রাব্যতা|Common-ion suppression of AB solubility|s\approx\frac{K_{sp}}{c}|s:molar solubility:mol/L,Ksp:concentration product:mol²/L²,c:initial common-ion concentration:mol/L|Dissolve AB in a solution already containing A+ at concentration c.~আগে থেকে c ঘনত্বে A+ থাকা দ্রবণে AB দ্রবীভূত করুন।|K_{sp}=(c+s)s;\quad s\ll c|If Ksp=10⁻⁸ (mol/L)² and c=0.01 mol/L, s≈10⁻⁶ mol/L.~Ksp=১০⁻⁸ (mol/L)² ও c=০.০১ mol/L হলে s≈১০⁻⁶ mol/L।|c≫s; no side reactions and constant activity coefficients; otherwise solve quadratic and use activities.~c≫s; পার্শ্ববিক্রিয়া ও সক্রিয়তা-সহগ পরিবর্তন নেই; নইলে দ্বিঘাত সমাধান ও সক্রিয়তা দরকার।|If c doubles under the approximation, s becomes?~অনুমানে c দ্বিগুণ হলে s?|Half;Double;Four times;Same|s≈Ksp/c.~s≈Ksp/c।
cell-emf-from-reduction|chemistry|বিজারণ বিভব থেকে কোষ বিভব|Cell emf from electrode reduction potentials|E^\circ_{cell}=E^\circ_{cathode}-E^\circ_{anode}|Ecell:standard cell emf:V,Ecathode:cathode reduction potential:V,Eanode:anode reduction potential:V|Use reduction potentials for BOTH half cells; oxidation at the anode reverses its reduction potential.~উভয় অর্ধকোষের বিজারণ বিভব নিন; অ্যানোডে জারণ হওয়ায় তার বিজারণ বিভবের চিহ্ন উল্টান।|E_{oxidation,anode}=-E_{reduction,anode}|With cathode +0.34 V and anode −0.76 V, Ecell=1.10 V.~ক্যাথোড +০.৩৪ V ও অ্যানোড −০.৭৬ V হলে Ecell=১.১০ V।|Standard activities and consistently tabulated reduction potentials; do not multiply electrode potentials by stoichiometric coefficients.~মান সক্রিয়তা ও একই রীতির বিজারণ বিভব; স্টইকিওমেট্রিক সহগ দিয়ে বিভব গুণ করবেন না।|With +0.34 V cathode and −0.76 V anode, emf?~ক্যাথোড +০.৩৪ V ও অ্যানোড −০.৭৬ V হলে emf?|1.10 V;−0.42 V;0.42 V;−1.10 V|0.34−(−0.76)=1.10 V.~০.৩৪−(−০.৭৬)=১.১০ V।
conductance-cell-constant|chemistry|কোষ ধ্রুবক ও পরিবাহিতা|Conductivity from cell constant|\kappa=G\frac{l}{A}|κ:conductivity:S/m,G:conductance:S,l:electrode separation:m,A:electrode area:m²|For a uniform conductor resistance R=l/(κA) and conductance G=1/R.~সুষম পরিবাহীতে রোধ R=l/(κA) এবং পরিবাহিতা G=১/R।|G=\kappa A/l|For G=0.01 S and calibrated l/A=100 m⁻¹, κ=1 S/m.~G=০.০১ S ও ক্রমাঙ্কিত l/A=১০০ m⁻¹ হলে κ=১ S/m।|Uniform field approximation; actual conductivity cells use an experimentally calibrated effective cell constant.~সুষম ক্ষেত্র অনুমান; বাস্তব কোষে পরীক্ষালব্ধ কার্যকর কোষধ্রুবক লাগে।|G doubles at unchanged geometry; κ?~জ্যামিতি অপরিবর্তিত রেখে G দ্বিগুণ হলে κ?|Doubles;Halves;Zero;Same|κ=G(l/A).~κ=G(l/A)।
langmuir-half-coverage|chemistry|ল্যাংমুইর অর্ধ-পৃষ্ঠঢাকা|Langmuir half-coverage pressure|P_{1/2}=\frac1K|P_half:half-coverage pressure:Pa,K:adsorption equilibrium constant:1/Pa|Balance adsorption k_aP(1−θ) against desorption k_dθ for a monolayer.~একস্তরীয় শোষণে k_aP(১−θ) ও k_dθ সমান করুন।|\theta=KP/(1+KP);\quad K=k_a/k_d|At P=1/K, occupied surface fraction θ=0.5.~P=১/K হলে দখলকৃত পৃষ্ঠের অংশ θ=০.৫।|Independent identical sites, monolayer, no lateral interactions; K has inverse-pressure units here.~স্বাধীন সমান আসন, একস্তর ও পার্শ্বিক মিথস্ক্রিয়া নেই; এখানে K-এর একক চাপের ব্যস্ত।|At P=1/K, θ equals?~P=১/K হলে θ?|0.5;0;1;2|KP=1 gives θ=1/(1+1).~KP=১ হলে θ=১/(১+১)।
beer-transmittance|chemistry|শোষণ ও সঞ্চারণ সম্পর্ক|Absorbance and transmittance|A=-\log_{10}T|A:absorbance:1,T:transmittance ratio:1|Transmittance is transmitted intensity divided by incident intensity.~সঞ্চারণ হলো প্রেরিত তীব্রতা ভাগ আপতিত তীব্রতা।|T=I/I_0;\quad A=\log_{10}(I_0/I)|For T=0.10, absorbance A=1.~T=০.১০ হলে শোষণ A=১।|Blank-corrected intensities, negligible scattering and stray light; T is fraction, not percent.~blank-সংশোধিত তীব্রতা; বিচ্ছুরণ ও stray light উপেক্ষণীয়; T ভগ্নাংশ, শতাংশ নয়।|If 10% of light transmits, A=?~১০% আলো পার হলে A কত?|1;0.1;10;2|T=0.10 and −log10(0.10)=1.~T=০.১০, −log10(০.১০)=১।
rydberg-ionization-limit|chemistry|বালমার শ্রেণির সীমা|Balmer-series wavelength limit|\lambda_{limit}=\frac4{R_H}|λ_limit:series-limit wavelength:m,R_H:hydrogen Rydberg constant:1/m|Use Rydberg's relation for transitions to n₁=2.~n₁=২-এ আগত পরিবর্তনে রিডবার্গ সম্পর্ক নিন।|1/\lambda=R_H(1/2^2-1/n_2^2);\quad n_2\to\infty|With RH≈1.097×10⁷ m⁻¹, λlimit≈365 nm.~RH≈১.০৯৭×১০⁷ m⁻¹ হলে λlimit≈৩৬৫ nm।|Hydrogen spectrum ignoring fine structure and isotope corrections; use reduced-mass Rydberg constant for accuracy.~সূক্ষ্ম গঠন ও আইসোটোপ সংশোধন উপেক্ষিত হাইড্রোজেন; নির্ভুলতায় reduced-mass ধ্রুবক নিন।|For Balmer series the lower level is?~বালমার শ্রেণিতে নিম্ন শক্তিস্তর কোনটি?|n=2;n=1;n=3;n=∞|Balmer transitions end at n=2.~বালমার পরিবর্তন n=২-এ শেষ হয়।
spin-only-magnetic-moment|chemistry|স্পিনমাত্র চৌম্বক মুহূর্ত|Spin-only magnetic moment|\mu_{eff}=\sqrt{n(n+2)}\,\mu_B|μ_eff:effective magnetic moment:J/T,n:number of unpaired electrons:1,μ_B:Bohr magneton:J/T|Combine spin angular momentum S=n/2 with spin g-factor approximately 2.~স্পিন কৌণিক ভরবেগ S=n/২ ও স্পিন g-গুণক প্রায় ২ ব্যবহার করুন।|\mu_{eff}=g\sqrt{S(S+1)}\,\mu_B;\quad g\approx2|For three unpaired electrons μeff=√15≈3.87 μB.~তিনটি অযুগ্ম ইলেকট্রনে μeff=√১৫≈৩.৮৭ μB।|Orbital angular momentum quenched and negligible spin–orbit effects; not universal for heavy-metal complexes.~কক্ষীয় কৌণিক ভরবেগ দমিত ও স্পিন–কক্ষীয় প্রভাব নগণ্য; ভারী ধাতব জটিলে সর্বজনীন নয়।|For zero unpaired electrons, spin-only moment?~অযুগ্ম ইলেকট্রন শূন্য হলে স্পিনমাত্র মুহূর্ত?|Zero;1 μB;2 μB;√3 μB|Put n=0 in the expression.~সূত্রে n=০ বসান।
radial-node-count|chemistry|রেডিয়াল নোডের সংখ্যা|Radial nodes of hydrogenic orbital|N_r=n-l-1|N_r:radial node count:1,n:principal quantum number:1,l:orbital quantum number:1|The hydrogenic radial wavefunction includes an associated Laguerre polynomial.~হাইড্রোজেন সদৃশ রেডিয়াল তরঙ্গফাংশনে associated Laguerre বহুপদী থাকে।|R_{nl}(r)\propto e^{-\rho/2}\rho^l L_{n-l-1}^{2l+1}(\rho)|A 3p orbital (n=3,l=1) has one radial node.~3p অরবিটালে (n=৩,l=১) একটি রেডিয়াল নোড।|Hydrogen-like orbitals; n≥1 and 0≤l≤n−1. Multielectron orbitals only approximately retain this pattern.~হাইড্রোজেন সদৃশ অরবিটাল; n≥১ ও ০≤l≤n−১; বহু-ইলেকট্রন অরবিটালে আনুমানিক।|How many radial nodes has 3p?~3p-তে রেডিয়াল নোড কত?|1;0;2;3|3−1−1=1.~৩−১−১=১।
rotational-spectra-level|chemistry|দৃঢ় ঘূর্ণকের শক্তি|Rigid-rotor rotational levels|E_J=hcB\,J(J+1)|E_J:rotational level energy:J,h:Planck constant:J s,c:speed of light:cm/s,B:rotational constant:1/cm,J:rotational quantum number:1|Solve the angular part of the rigid-rotor Schrödinger equation.~দৃঢ় ঘূর্ণকের শ্রোডিঙ্গার সমীকরণের কৌণিক অংশ সমাধান করুন।|E_J=\hbar^2J(J+1)/(2I);\quad B=h/(8\pi^2Ic)|J=0 has zero rotational energy; J=1 has 2hcB.~J=০-এ ঘূর্ণনশক্তি শূন্য; J=১-এ ২hcB।|B in cm⁻¹ requires c in cm/s; rigid rotor ignores centrifugal distortion and vibration–rotation coupling.~B cm⁻¹ হলে c cm/s; দৃঢ় ঘূর্ণকে বিকৃতি ও কম্পন–ঘূর্ণন সংযোগ উপেক্ষিত।|For J=1, E/(hcB) equals?~J=১ হলে E/(hcB) কত?|2;1;0;3|J(J+1)=1×2=2.~J(J+১)=১×২=২।
vibrational-zero-point|chemistry|কম্পকের শূন্য-বিন্দু শক্তি|Harmonic vibrational zero-point energy|E_0=\frac12h\nu|E₀:ground vibrational energy:J,h:Planck constant:J s,ν:harmonic frequency:1/s|Solve the one-dimensional quantum harmonic oscillator.~একমাত্রিক কোয়ান্টাম হারমোনিক কম্পকের সমাধান করুন।|E_v=(v+\tfrac12)h\nu;\quad v=0,1,2,\ldots|If hν=0.20 eV, ground-state energy is 0.10 eV.~hν=০.২০ eV হলে ভূমিস্তরের শক্তি ০.১০ eV।|Harmonic approximation about equilibrium bond length; real molecular potentials are anharmonic.~সাম্য বন্ধনদৈর্ঘ্যের কাছে হারমোনিক অনুমান; বাস্তবে বিভব anharmonic।|Can the ideal quantum oscillator have zero energy?~আদর্শ কোয়ান্টাম কম্পকের শক্তি কি শূন্য হতে পারে?|No;Yes always;Only at high T;Only with large mass|Its lowest level is hν/2.~নিম্নতম স্তর hν/২।
crystal-field-octahedral-cfse|chemistry|অষ্টতলক জটিলে CFSE|Octahedral crystal-field stabilization|CFSE=(-0.4n_{t_{2g}}+0.6n_{e_g})\Delta_o|CFSE:crystal-field energy relative to barycentre:J,n_t2g:electrons in t2g orbitals:1,n_eg:electrons in eg orbitals:1,Δo:octahedral splitting:J|An octahedral field raises eg by 0.6Δo and lowers t2g by 0.4Δo relative to the barycentre.~অষ্টতলক ক্ষেত্রে ভারকেন্দ্রের তুলনায় eg ০.৬Δo উপরে ও t2g ০.৪Δo নিচে।|3(-0.4\Delta_o)+2(0.6\Delta_o)=0\quad\text{(barycentre)}|For t2g³ eg⁰, CFSE=−1.2Δo before any pairing correction.~t2g³ eg⁰-তে জোড়া শক্তির সংশোধনের আগে CFSE=−১.২Δo।|Simple octahedral crystal-field model; account separately for pairing and covalency when comparing spin states.~সরল অষ্টতলক crystal-field মডেল; স্পিন তুলনায় pairing ও সমযোজিতা আলাদা নিন।|For t2g³ eg⁰, CFSE is?~t2g³ eg⁰-এ CFSE কত?|−1.2Δo;+1.2Δo;0;−0.4Δo|Three electrons each contribute −0.4Δo.~তিন ইলেকট্রন প্রতি −০.৪Δo দেয়।
'''

def yaml_lines(value,indent=0):
    out=[]; prefix=' '*indent
    if isinstance(value,dict):
        for k,v in value.items():
            if isinstance(v,(dict,list)):
                out.append(prefix+k+':');out+=yaml_lines(v,indent+2)
            else:out.append(prefix+k+': '+json.dumps(v,ensure_ascii=False))
    else:
        for v in value:
            if isinstance(v,dict):
                first=next(iter(v));out.append(prefix+'- '+first+': '+json.dumps(v[first],ensure_ascii=False))
                out+=yaml_lines({k:x for k,x in v.items() if k!=first},indent+2)
            else:out.append(prefix+'- '+json.dumps(v,ensure_ascii=False))
    return out

def bilingual(text):
    a,b=text.split('~',1)
    return a.strip(),b.strip()

lines=[s for s in DATA.splitlines() if s.strip()]
assert len(lines)==50, f'Expected 50, got {len(lines)}'
added=0
for line in lines:
    parts=line.split('|')
    assert len(parts)==13,(parts[0],len(parts))
    slug,subject,title_bn,title_en,latex,variables,first,middle,example,scope,question,options,explanation=parts
    path=ROOT/subject/'honours'/f'{slug}.mdx'
    assert not path.exists(),f'Would overwrite {path}'
    e,b=bilingual(first); worked,worked_bn=bilingual(example); assumption,assumption_bn=bilingual(scope)
    end_en='Substitute the preceding result and identify the requested relation.'
    end_bn='আগের ফল বসিয়ে নির্ণেয় সম্পর্কটি শনাক্ত করুন।'
    # Provide the algebra line with the physical starting point and a separate intermediate line.
    steps=[dict(step_en=e,step_bn=b,latex=middle),
           dict(step_en=end_en,step_bn=end_bn,latex=latex)]
    var=[]
    for v in variables.split(','):
        symbol,name,unit=v.split(':')
        var.append(dict(symbol=symbol,name=name,name_bn=name,unit=unit,si_unit=unit))
    data=dict(type='equation',slug=slug,title_bn=title_bn,title_en=title_en,subject=subject,level='honours',chapter='Honours Physics' if subject=='physics' else 'Honours Chemistry',chapter_bn='স্নাতক পদার্থবিজ্ঞান' if subject=='physics' else 'স্নাতক রসায়ন',latex=latex,calculator=False,variables=var,derivation=e+' '+middle+' '+end_en,derivation_bn=b+' '+middle+' '+end_bn,derivation_steps=steps,summary_en=worked,summary_bn=worked_bn,tags=['honours',subject,'derivation'])
    body='---\n'+'\n'.join(yaml_lines(data))+'\n---\n\n### প্রতিপাদনের ব্যাখ্যা / Derivation\n\n'+e+' `'+middle+'` '+end_en+'\n\n'+b+' `'+middle+'` '+end_bn+'\n\n### সমাধানসহ উদাহরণ / Worked application\n\n'+worked+'\n\n'+worked_bn+'\n\n### সীমা ও সতর্কতা / Assumptions\n\n'+assumption.replace('<','&lt;').replace('>','&gt;')+'\n\n'+assumption_bn.replace('<','&lt;').replace('>','&gt;')+'\n'
    path.write_text(body,encoding='utf8')
    q,qbn=bilingual(question);ex,exbn=bilingual(explanation)
    opts=options.split(';');assert len(opts)==4
    quiz=dict(slug='honours-'+slug,title_en=title_en+' — concept check',title_bn=title_bn+' — বহুনির্বাচনী',subject=subject,level='honours',chapter=data['chapter'],chapter_bn=data['chapter_bn'],description_en='One explained multiple-choice check for this derivation.',description_bn='এই প্রতিপাদনের ওপর ব্যাখ্যাসহ একটি বহুনির্বাচনী প্রশ্ন।',questions=[dict(q=q,q_bn=qbn,options=opts,options_bn=opts,answer=0,explanation=ex,explanation_bn=exbn)])
    quiz_path=ROOT/'quizzes'/f'honours-{slug}.json';assert not quiz_path.exists(),f'Would overwrite {quiz_path}'
    quiz_path.write_text(json.dumps(quiz,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
    added+=1
print(f'Added {added} bilingual equations and {added} MCQs.')
