"""Eight supervised, bilingual practicals paired with Honours equation pages.
Run once; refuses to overwrite existing laboratory guides.
"""
from pathlib import Path
import json
import re
ROOT=Path(__file__).resolve().parents[1]
# equation slug | lab title EN~BN | aim EN~BN | apparatus EN~BN (comma-separated)
# theory EN~BN | steps EN~BN (semicolon-separated, each step ~ bilingual)
# observed quantities separated by ; | calculation EN~BN | safety EN~BN
# errors EN~BN | viva Q EN~BN | viva A EN~BN
DATA=r'''
rotational-kinetic-energy|Flywheel moment of inertia and rotational energy~ফ্লাইহুইলের জড়তার ভ্রামক ও ঘূর্ণনশক্তি|Measure I by falling-mass acceleration and estimate the flywheel's rotational energy.~পতনশীল ভরের ত্বরণ থেকে I এবং ফ্লাইহুইলের ঘূর্ণনশক্তি নির্ণয়।|Flywheel with axle:অক্ষসহ ফ্লাইহুইল,calibrated hanging mass:জানা ঝুলন্ত ভর,thread and pulley:সুতো ও পুলি,photogate or stopwatch:আলোক-গেট বা স্টপওয়াচ,vernier caliper:ভার্নিয়ার ক্যালিপার|For no slip v=rω and a=rα. For ideal apparatus mg−T=ma and Tr=Iα; eliminating T gives I=mr²(g/a−1). Then Krot=Iω²/2. Correct for friction rather than claiming this ideal expression is exact.~সুতো পিছলায় না ধরে v=rω ও a=rα। আদর্শ যন্ত্রে mg−T=ma এবং Tr=Iα; T বাদ দিলে I=mr²(g/a−1)। পরে Krot=Iω²/২। ঘর্ষণ সংশোধন ছাড়া আদর্শ মানকে নির্ভুল বলবেন না।|Measure axle radius r and mass m; allow the mass to descend a known distance from rest.~অক্ষের ব্যাসার্ধ r ও ভর m মেপে স্থিরাবস্থা থেকে জানা দূরত্বে ভর নামান।;Measure descent time with repeated photogate trials and obtain a=2h/t².~বারবার photogate পাঠ নিয়ে পতনের সময় থেকে a=২h/t² বের করুন।;Calculate I and measure angular speed at the end of descent to obtain Krot.~I হিসাব করে পতনের শেষে কৌণিক বেগ মেপে Krot বের করুন।;Compare the observed result with friction-corrected energy accounting.~ঘর্ষণ-সংশোধিত শক্তি হিসাবের সঙ্গে পর্যবেক্ষণ তুলনা করুন।|m (kg);r (m);h (m);t (s);a (m/s²);ω (rad/s);I (kg m²)|For m=0.10 kg, r=0.020 m and a=1.96 m/s², I≈1.60×10⁻⁴ kg m² using g=9.81 m/s². Report spread across repeated runs.~m=০.১০ kg, r=০.০২০ m ও a=১.৯৬ m/s² হলে g=৯.৮১ m/s² নিয়ে I≈১.৬০×১০⁻⁴ kg m²। পুনরাবৃত্তির বিচ্যুতি লিখুন।|Use a guard and keep hands clear of rotating parts; secure the hanging mass and never let it strike feet.~রক্ষাকবচ লাগিয়ে ঘূর্ণমান অংশ থেকে হাত দূরে রাখুন; ঝুলন্ত ভর আটকে রাখুন যাতে পায়ে না পড়ে।|Axle friction, thread slip and inaccurate axle radius bias I; reaction time affects t.~অক্ষের ঘর্ষণ, সুতোর পিছলানো ও ব্যাসার্ধের ভুলে I বদলায়; সময় মাপায় প্রতিক্রিয়া-ত্রুটি থাকে।|Why does an axle-friction torque invalidate the ideal I formula?~অক্ষের ঘর্ষণ টর্ক থাকলে আদর্শ I সূত্র কেন ঠিক থাকে না?|Part of the gravitational torque is spent against friction, so Tr is not the only torque accelerating the flywheel.~মহাকর্ষীয় টর্কের কিছু অংশ ঘর্ষণের বিরুদ্ধে যায়, ফলে Tr একমাত্র ত্বরণকারী টর্ক নয়।
wave-energy-string|Sonometer test of transverse-wave speed~সনোমিটারে আনুপ্রস্থ তরঙ্গবেগ যাচাই|Test v²=𝒯/μ from the fundamental resonance of a tensioned string.~টানটান তারের মৌলিক অনুনাদে v²=𝒯/μ যাচাই।|Sonometer and string:সনোমিটার ও তার,pulley and masses:পুলি ও ভার,frequency generator or tuning fork:কম্পাঙ্ক উৎস বা সুরশলাকা,metre rule:মিটার স্কেল,balance:তুলা|For a string fixed at both ends the fundamental has λ=2L; v=fλ=2Lf and hence (2Lf)²=𝒯/μ. Use 𝒯≈Mg only if pulley friction is negligible.~দুই প্রান্তে আটকানো তারের মৌলিক কম্পনে λ=২L; তাই v=২Lf এবং (২Lf)²=𝒯/μ। পুলির ঘর্ষণ উপেক্ষণীয় হলেই 𝒯≈Mg।|Measure mass per known length to estimate μ; stretch string over the pulley with a safe hanging load.~জানা দৈর্ঘ্যের তার ওজন করে μ নির্ণয় ও নিরাপদ ভার ঝুলিয়ে টান দিন।;Adjust the bridge length for fundamental resonance at a measured frequency f.~জানা f-এ মৌলিক অনুনাদ পেতে সেতুর অবস্থান বদলান।;Measure vibrating length L; repeat with at least three different loads without changing the string.~কম্পমান দৈর্ঘ্য L লিখে একই তারে অন্তত তিনটি ভারে পুনরাবৃত্তি করুন।;Plot (2Lf)² versus load Mg and compare slope with 1/μ.~(২Lf)² বনাম Mg লেখচিত্রের ঢাল ১/μ-এর সঙ্গে তুলনা করুন।|load M (kg);f (Hz);L (m);μ (kg/m);v=2Lf (m/s);Mg (N)|With L=0.50 m and f=100 Hz, v=100 m/s; if μ=0.001 kg/m, predicted 𝒯=10 N.~L=০.৫০ m ও f=১০০ Hz-এ v=১০০ m/s; μ=০.০০১ kg/m হলে প্রত্যাশিত 𝒯=১০ N।|Clamp masses, stay clear of falling loads and do not overtighten the string.~ভার নিরাপদে আটকান, পড়ন্ত ভরের পথ থেকে দূরে থাকুন ও তার অতিরিক্ত টানবেন না।|Pulley friction, nonuniform μ, harmonic mistaken for the fundamental and length-reading error.~পুলির ঘর্ষণ, μ অসম হওয়া, মৌলিকের বদলে উচ্চতর সুর নেওয়া ও দৈর্ঘ্য-পাঠের ত্রুটি।|Why is the fundamental wavelength 2L?~মৌলিক সুরে তরঙ্গদৈর্ঘ্য ২L কেন?|A string fixed at both ends contains half a wavelength between the nodes.~দুই আটকানো প্রান্তের মধ্যে অর্ধেক তরঙ্গদৈর্ঘ্য থাকে।
brewster-angle-honours|Polarization at Brewster angle~ব্রুস্টার কোণে মেরুকরণ|Measure Brewster angle and infer refractive-index ratio from reflected p-polarized light.~p-মেরুকৃত প্রতিফলিত আলো থেকে ব্রুস্টার কোণ মেপে প্রতিসরাঙ্ক অনুপাত নির্ণয়।|Low-power polarized laser:কম-ক্ষমতার মেরুকৃত লেজার,glass block:কাচের খণ্ড,rotating stage:ঘূর্ণায়মান মঞ্চ,polarizer:মেরুকারক,light sensor:আলোক সেন্সর|At θB=arctan(n₂/n₁), the ideal p-reflected component has a minimum; the s-reflected component generally does not vanish. Use the incidence angle relative to the surface normal.~θB=arctan(n₂/n₁) হলে আদর্শ p-মেরুকৃত প্রতিফলন সর্বনিম্ন; s-প্রতিফলন সাধারণত শূন্য নয়। কোণটি পৃষ্ঠের লম্ব থেকে মাপুন।|Mount the block, label its surface normal and align the laser below eye level.~কাচ বসিয়ে পৃষ্ঠের লম্ব চিহ্নিত করে চোখের নিচে লেজার সাজান।;Select p-polarization and measure reflected intensity as incidence angle changes.~p-মেরুকরণ বেছে আপতন কোণ বদলে প্রতিফলিত তীব্রতা মাপুন।;Locate the minimum by readings on both sides; repeat for s-polarization as a control.~সর্বনিম্নের দুই পাশে পাঠ নিয়ে অবস্থান নির্ধারণ করুন; তুলনার জন্য s-মেরুকরণেও মাপুন।;Calculate n₂/n₁=tan θB and compare with an independent refractive-index measurement.~n₂/n₁=tan θB বের করে পৃথক প্রতিসরাঙ্ক পাঠের সঙ্গে তুলনা করুন।|angle θ (°);p reflected intensity (a.u.);s reflected intensity (a.u.);θB (°);tan θB|For θB≈56.3° from air, n₂≈1.50 when n₁≈1.~বাতাসে θB≈৫৬.৩° হলে n₁≈১ ধরে n₂≈১.৫০।|Never look into laser or specular reflection; use a low-power source and beam stop.~লেজার বা ঝকঝকে প্রতিফলনের দিকে তাকাবেন না; কম-ক্ষমতার উৎস ও রশ্মি-নিবারক ব্যবহার করুন।|Misidentified polarization, nonflat surface, stray light and poorly marked normal broaden the minimum.~ভুল মেরুকরণ, অমসৃণ পৃষ্ঠ, বাইরের আলো ও ভুল লম্বে সর্বনিম্ন অস্পষ্ট হয়।|Does s-polarized reflection also vanish at Brewster angle?~ব্রুস্টার কোণে s-মেরুকৃত প্রতিফলনও কি শূন্য হয়?|No; the zero refers to ideal p-polarized reflection only.~না; আদর্শভাবে শুধু p-মেরুকৃত প্রতিফলন শূন্য হয়।
rc-discharge-honours|RC discharge time-constant practical~RC নিঃসরণের সময় ধ্রুবক ব্যবহারিক|Measure τ=RC from capacitor voltage as a function of discharge time.~সময়ের সঙ্গে ধারকের বিভব মেপে τ=RC নির্ণয়।|Resistor and capacitor:রোধ ও ধারক,low-voltage DC source:কম বিভবের DC উৎস,switch:সুইচ,high-impedance voltmeter or logger:উচ্চ প্রতিবন্ধক ভোল্টমিটার বা তথ্যলেখক,stopwatch:স্টপওয়াচ|From I=−dq/dt and q=CV, loop law gives dV/dt=−V/(RC). Consequently ln(V/V₀)=−t/(RC), so a semilog slope is −1/τ.~I=−dq/dt ও q=CV থেকে বর্তনী সূত্রে dV/dt=−V/(RC)। তাই ln(V/V₀)=−t/(RC), অর্থাৎ অর্ধলগ লেখচিত্রের ঢাল −১/τ।|Measure R and C, wire a safe low-voltage circuit and charge the capacitor.~R ও C মেপে নিরাপদ কম-বিভব বর্তনী সাজিয়ে ধারক চার্জ করুন।;Disconnect the supply before discharging through R; record V at short regular intervals.~R দিয়ে নিঃসরণের আগে উৎস বিচ্ছিন্ন করে নিয়মিত অল্প বিরতিতে V লিখুন।;Plot ln(V/V₀) against t and determine τ from the negative reciprocal slope.~ln(V/V₀) বনাম t লেখচিত্রে ঋণাত্মক ঢালের ব্যস্ত থেকে τ বের করুন।;Repeat and compare measured τ with the independently measured RC product.~পুনরাবৃত্তি করে মাপা τ-কে স্বাধীনভাবে মাপা RC-এর সঙ্গে তুলনা করুন।|R (Ω);C (F);time t (s);V (V);ln(V/V₀);τ (s)|For R=100 kΩ and C=100 μF, RC=10 s and V(10 s)≈0.368V₀.~R=১০০ kΩ ও C=১০০ μF হলে RC=১০ s; V(১০ s)≈০.৩৬৮V₀।|Check capacitor polarity and voltage rating; discharge safely before rewiring.~ধারকের মেরু ও অনুমোদিত বিভব পরীক্ষা করুন; তার বদলের আগে নিরাপদে চার্জমুক্ত করুন।|Meter loading, capacitor leakage, switch delay and resistance tolerance alter the fitted slope.~ভোল্টমিটারের লোড, ধারকের leakage, সুইচে বিলম্ব ও রোধের সহনশীলতায় ঢাল বদলায়।|Why use ln(V/V₀) rather than ln V with a unit?~এককযুক্ত V-এর ln না নিয়ে ln(V/V₀) কেন?|The logarithm must have a dimensionless argument.~লগারিদমের আর্গুমেন্ট মাত্রাহীন হতে হয়।
freezing-depression-electrolyte|Cryoscopic molar-mass and van't Hoff-factor measurement~হিমাঙ্ক হ্রাসে মোলার ভর ও ভান্ট হফ গুণক|Measure a solvent freezing point and its dilute solution to estimate ΔTf and effective i.~দ্রাবক ও বিরল দ্রবণের হিমাঙ্ক মেপে ΔTf ও কার্যকর i নির্ণয়।|Cryoscopic tube:হিমাঙ্ক পরিমাপক নল,temperature probe:তাপমাত্রা সেন্সর,stirrer:নাড়নী,known solvent:জানা দ্রাবক,analytical balance:বিশ্লেষণী তুলা,cooling bath:শীতল জলস্নান|At low molality, ΔTf=iKf m. With known Kf and correctly computed molality, i=ΔTf/(Kf m). Identify the freezing plateau rather than the lowest supercooled temperature.~কম মোলালিটিতে ΔTf=iKf m। জানা Kf ও সঠিক মোলালিটিতে i=ΔTf/(Kf m)। অতিশীতল অবস্থার সর্বনিম্ন তাপমাত্রা নয়, জমাটের স্থিতিশীল পর্যায় শনাক্ত করুন।|Measure pure-solvent cooling curve and identify its freezing plateau.~বিশুদ্ধ দ্রাবকের শীতলন রেখা মেপে জমাট বাঁধার স্থির তাপমাত্রা নিন।;Weigh solute and solvent separately and prepare a dilute mixture.~দ্রব ও দ্রাবক আলাদা ওজন করে বিরল মিশ্রণ বানান।;Repeat cooling with gentle stirring, noting the corrected solution plateau.~আলতো নেড়ে আবার শীতলন করে দ্রবণের সংশোধিত স্থির তাপমাত্রা নিন।;Calculate m from solvent mass in kilograms and compute i; discuss ion association.~দ্রাবকের ভর kg-এ নিয়ে m ও i হিসাব করুন; আয়নের সংযুক্তির প্রভাব আলোচনা করুন।|solute mass (g);solvent mass (kg);pure Tf (°C);solution Tf (°C);ΔTf (K);molality (mol/kg);i|For Kf=1.86 K kg/mol, m=0.10 mol/kg and ΔTf=0.30 K, i≈1.61, not necessarily the integer dissociation count.~Kf=১.৮৬ K kg/mol, m=০.১০ mol/kg ও ΔTf=০.৩০ K হলে i≈১.৬১; এটি অবশ্যই পূর্ণসংখ্যক বিয়োজন গণনা নয়।|Use eye protection; avoid direct skin contact with freezing bath chemicals and handle glass gently.~চোখরক্ষী পরুন; শীতলন-মাধ্যম ত্বকে লাগাবেন না এবং কাচ সাবধানে ধরুন।|Supercooling, thermal lag, impure solvent and inaccurate solvent mass distort ΔTf.~অতিশীতলন, তাপীয় বিলম্ব, অশুদ্ধ দ্রাবক ও ভুল দ্রাবক-ভরে ΔTf বদলায়।|Why use solvent mass rather than total solution mass for molality?~মোলালিটিতে মোট দ্রবণের বদলে দ্রাবকের ভর কেন?|Molality is moles of solute per kilogram of solvent by definition.~মোলালিটির সংজ্ঞা প্রতি kg দ্রাবকে দ্রবের মোল সংখ্যা।
weak-acid-ph-approx|Weak-acid dissociation and pH measurement~দুর্বল অম্লের বিয়োজন ও pH পরিমাপ|Estimate Ka from the pH of a known analytical concentration of monoprotic weak acid.~জানা প্রাথমিক ঘনত্বের এক-প্রোটনীয় দুর্বল অম্লের pH থেকে Ka নির্ণয়।|Standardized weak-acid solution:জানা ঘনত্বের দুর্বল অম্ল,calibrated pH meter:ক্রমাঙ্কিত pH মিটার,buffer standards:মান বাফার,volumetric glassware:আয়তনমাত্রিক কাচপাত্র,thermometer:তাপমাপক|For HA⇌H+ + A−, x≈[H+] and Ka≈x²/(C−x) when activity corrections and water autoionization are negligible. If x≪C, [H+]≈√(KaC). pH gives hydrogen-ion activity rather than exact concentration.~HA⇌H+ + A−-এ সক্রিয়তার সংশোধন ও পানির স্ববিয়োজন নগণ্য হলে x≈[H+] এবং Ka≈x²/(C−x)। x≪C হলে [H+]≈√(KaC)। pH ঠিক ঘনত্ব নয়, H+ সক্রিয়তা দেয়।|Calibrate the electrode with standards at the same temperature and rinse between samples.~একই তাপমাত্রায় মান বাফার দিয়ে ইলেকট্রোড ক্রমাঙ্কিত করে নমুনার মাঝে ধুয়ে নিন।;Prepare several known concentrations and read stable pH after equilibration.~কয়েকটি জানা ঘনত্ব তৈরি করে সাম্যাবস্থায় স্থির pH লিখুন।;Estimate x from pH under a dilute-solution approximation; calculate Ka=x²/(C−x).~বিরল দ্রবণের অনুমানে pH থেকে x বের করে Ka=x²/(C−x) হিসাব করুন।;Check x/C and compare Ka across concentrations; flag activity and CO₂ effects.~x/C যাচাই করে ঘনত্বভেদে Ka তুলনা করুন; সক্রিয়তা ও CO₂-এর প্রভাব লিখুন।|acid concentration C (mol/L);temperature (°C);measured pH;x estimate (mol/L);x/C;Ka estimate|If C=0.10 M and pH≈3 under the concentration approximation, x≈0.001 M and Ka≈(0.001)²/(0.099)=1.01×10⁻⁵ M.~C=০.১০ M ও ঘনত্ব অনুমানে pH≈৩ হলে x≈০.০০১ M এবং Ka≈(০.০০১)²/(০.০৯৯)=১.০১×১০⁻⁵ M।|Wear eye protection; do not immerse a pH electrode beyond its marked limit or wipe its sensing bulb abrasively.~চোখরক্ষী পরুন; pH ইলেকট্রোড চিহ্নের বেশি ডোবাবেন না ও সেন্সর ঘষে মুছবেন না।|Electrode calibration drift, CO₂ uptake, activity coefficients and temperature variation affect pH.~ইলেকট্রোড ক্রমাঙ্কনের বিচ্যুতি, CO₂ শোষণ, সক্রিয়তা সহগ ও তাপমাত্রা pH বদলায়।|Is pH exactly −log₁₀ of a molar concentration in every solution?~সব দ্রবণে pH কি হুবহু মোলার ঘনত্বের −log₁₀?|No; rigorous pH refers to hydrogen-ion activity relative to a standard state.~না; যথাযথ pH মান অবস্থা সাপেক্ষে হাইড্রোজেন আয়নের সক্রিয়তা দিয়ে লেখা হয়।
conductance-cell-constant|Calibration of conductivity-cell constant~পরিবাহিতা কোষধ্রুবকের ক্রমাঙ্কন|Calibrate the effective cell constant with a standard solution then measure unknown conductivity.~মান দ্রবণে কার্যকর কোষধ্রুবক ক্রমাঙ্কিত করে অজানা দ্রবণের পরিবাহিতা মাপা।|Conductivity cell and meter:পরিবাহিতা কোষ ও মিটার,standard conductivity solution:মান পরিবাহিতা দ্রবণ,thermostatic bath:তাপ-নিয়ন্ত্রিত জলস্নান,unknown solution:অজানা দ্রবণ,thermometer:তাপমাপক|For a cell with effective constant Kcell=l/A, κ=GKcell. A known standard κstd yields Kcell=κstd/Gstd. Use AC meters to reduce polarization and maintain matched temperature.~কার্যকর কোষধ্রুবক Kcell=l/A হলে κ=GKcell। জানা κstd দিয়ে Kcell=κstd/Gstd। মেরুকরণ কমাতে AC মিটার ব্যবহার এবং একই তাপমাত্রা রাখুন।|Rinse the cell with standard solution and equilibrate it at the reference temperature.~মান দ্রবণ দিয়ে কোষ ধুয়ে নির্দেশিত তাপমাত্রায় সাম্য আনুন।;Read conductance for the standard at least three times; compute Kcell from its certified κstd.~মান দ্রবণের পরিবাহন অন্তত তিনবার মেপে তার প্রমাণিত κstd থেকে Kcell হিসাব করুন।;Rinse with unknown, read conductance at the same temperature and compute κunknown.~অজানা দ্রবণে ধুয়ে একই তাপমাত্রায় পরিবাহন মেপে κunknown বের করুন।;Repeat with a second standard to check linear range and report uncertainty.~দ্বিতীয় মান দ্রবণে রৈখিকতা যাচাই করে অনিশ্চয়তা লিখুন।|T (°C);κstd (S/m);Gstd (S);Kcell (m⁻¹);Gunknown (S);κunknown (S/m)|If κstd=1.0 S/m and Gstd=0.010 S, Kcell=100 m⁻¹; unknown G=0.005 S gives κ=0.50 S/m.~κstd=১.০ S/m ও Gstd=০.০১০ S হলে Kcell=১০০ m⁻¹; অজানায় G=০.০০৫ S হলে κ=০.৫০ S/m।|Use only properly insulated low-voltage instrument leads; avoid spills around electrical contacts.~যথাযথ অন্তরিত কম-বিভব তার ব্যবহার করুন; বৈদ্যুতিক সংযোগে দ্রবণ ফেলবেন না।|Temperature drift, bubbles, cell polarization, contamination and calibration-solution aging bias readings.~তাপমাত্রা পরিবর্তন, বুদ্‌বুদ, মেরুকরণ, দূষণ ও মান দ্রবণের পুরোনো হওয়ায় পাঠ বদলায়।|Why not trust geometric l/A without calibration?~ক্রমাঙ্কন ছাড়া শুধু জ্যামিতিক l/A কেন যথেষ্ট নয়?|Fringing fields and electrode geometry make the effective cell constant differ from the simple estimate.~প্রান্তীয় ক্ষেত্র ও ইলেকট্রোডের গঠনে কার্যকর ধ্রুবক সরল হিসাব থেকে ভিন্ন হয়।
beer-transmittance|Beer–Lambert absorbance and transmittance calibration~বিয়ার–ল্যাম্বার্ট শোষণ ও সঞ্চারণ ক্রমাঙ্কন|Verify A=−log₁₀T and A=εlc over a dilute standard concentration series.~বিরল মান দ্রবণে A=−log₁₀T ও A=εlc যাচাই।|Spectrophotometer:স্পেকট্রোফটোমিটার,matched cuvettes:সমমান কুভেট,solvent blank:দ্রাবক blank,standard coloured solutions:রঙিন মান দ্রবণ,pipettes:পিপেট|After blank correction T=I/I₀ and A=−log₁₀T. In the linear concentration range A=εlc. The slope of A versus c is εl; deviation can signal stray light, chemistry or excessive concentration.~blank সংশোধনের পর T=I/I₀ ও A=−log₁₀T। রৈখিক ঘনত্ব পরিসরে A=εlc। A বনাম c-এর ঢাল εl; বিচ্যুতিতে stray light, বিক্রিয়া বা অতিরিক্ত ঘনত্ব থাকতে পারে।|Select an absorption wavelength and zero the spectrophotometer with matching solvent blank.~শোষণের তরঙ্গদৈর্ঘ্য বেছে অনুরূপ দ্রাবক blank দিয়ে যন্ত্র শূন্য করুন।;Prepare at least five known dilutions with the same solvent and record T and A.~একই দ্রাবকে অন্তত পাঁচটি জানা পাতলা দ্রবণ তৈরি করে T ও A লিখুন।;Check measured A against −log₁₀T and fit A versus concentration.~মাপা A-কে −log₁₀T-এর সঙ্গে যাচাই করে A বনাম ঘনত্বে রেখা বসান।;Test an unknown only within the calibrated range and report uncertainty.~ক্রমাঙ্কিত পরিসরের মধ্যেই অজানা দ্রবণ মেপে অনিশ্চয়তা লিখুন।|c (mol/L);path length l (cm);T (fraction);A measured;−log₁₀T;A predicted|If T=0.10, A=1.00; with l=1 cm and ε=100 L/(mol cm), c=0.010 mol/L.~T=০.১০ হলে A=১.০০; l=১ cm ও ε=১০০ L/(mol cm) হলে c=০.০১০ mol/L।|Use eye protection for chemical solutions; handle glass cuvettes by their frosted sides and dispose of reagents as instructed.~রাসায়নিক দ্রবণে চোখরক্ষী পরুন; কুভেটের অস্বচ্ছ পাশ ধরে ব্যবহার করে নির্দেশমতো বর্জ্য ফেলুন।|Fingerprints, bubbles, wrong blank, stray light and concentration-dependent chemical equilibria.~আঙুলের দাগ, বুদ্‌বুদ, ভুল blank, stray light ও ঘনত্বনির্ভর রাসায়নিক সাম্য।|Why is a 10% transmittance recorded as T=0.10 in the logarithm?~১০% সঞ্চারণকে লগারিদমে T=০.১০ কেন লিখি?|Transmittance is a dimensionless fraction; using 10 would give the wrong absorbance.~সঞ্চারণ মাত্রাহীন ভগ্নাংশ; ১০ বসালে শোষণ ভুল হবে।
'''

def pair(s):
    a,b=s.split('~',1)
    return a.strip(),b.strip()

def yaml_lines(obj,indent=0):
    out=[];pad=' '*indent
    if isinstance(obj,dict):
        for key,value in obj.items():
            if isinstance(value,(dict,list)):
                out.append(pad+key+':');out+=yaml_lines(value,indent+2)
            else:out.append(pad+key+': '+json.dumps(value,ensure_ascii=False))
    else:
        for value in obj:
            if isinstance(value,dict):
                key=next(iter(value));out.append(pad+'- '+key+': '+json.dumps(value[key],ensure_ascii=False))
                out+=yaml_lines({k:v for k,v in value.items() if k!=key},indent+2)
            else:out.append(pad+'- '+json.dumps(value,ensure_ascii=False))
    return out

if __name__=='__main__':
    rows=[line.split('|') for line in DATA.splitlines() if line.strip()]
    assert len(rows)==8 and all(len(row)==12 for row in rows)
    for equation_slug,title,aim,apparatus,theory,steps,columns,calculation,precautions,errors,viva_q,viva_a in rows:
        eq_path=next((ROOT/'content'/subject/'honours'/f'{equation_slug}.mdx' for subject in ('physics','chemistry') if (ROOT/'content'/subject/'honours'/f'{equation_slug}.mdx').exists()))
        subject=eq_path.parts[-3]
        slug=equation_slug+'-lab'
        target=eq_path.with_name(slug+'.mdx')
        assert not target.exists(),f'Would overwrite {target}'
        en,bn=pair(title)
        apparatus_items=[item.split(':',1) for item in apparatus.split(',')]
        step_pairs=[pair(s) for s in re.split(r';(?=[A-Z])',steps)]
        header=columns.split(';')
        assert len(step_pairs)>=3
        a_en,a_bn=pair(aim);t_en,t_bn=pair(theory);c_en,c_bn=pair(calculation)
        p_en,p_bn=pair(precautions);e_en,e_bn=pair(errors)
        q_en,q_bn=pair(viva_q);answer_en,answer_bn=pair(viva_a)
        data=dict(type='experiment',slug=slug,title_bn=bn,title_en=en,subject=subject,level='honours',aim=a_en,aim_bn=a_bn,apparatus=[i[0] for i in apparatus_items],apparatus_bn=[i[1] for i in apparatus_items],theory=t_en,theory_bn=t_bn,procedure=[p[0] for p in step_pairs],procedure_bn=[p[1] for p in step_pairs],observation_table=dict(headers=header,rows=[['record']*len(header) for _ in range(3)]),calculation=c_en,calculation_bn=c_bn,precautions=[p_en],precautions_bn=[p_bn],sources_of_error=[e_en],sources_of_error_bn=[e_bn],viva=[dict(q=q_en,a=answer_en,q_bn=q_bn,a_bn=answer_bn)],tags=['honours',subject,'lab'])
        target.write_text('---\n'+'\n'.join(yaml_lines(data))+'\n---\n\nMeasurements must be recorded before calculations; do not fabricate observations.\n\nহিসাবের আগে প্রকৃত পর্যবেক্ষণ লিখুন; কোনো মাপ বানিয়ে লিখবেন না।\n')
        raw=eq_path.read_text()
        assert '\nexperiment:' not in raw.split('---',2)[1]
        raw=raw.replace('\ncalculator: false\n','\ncalculator: false\nexperiment: "'+slug+'"\n',1)
        eq_path.write_text(raw)
    print('Added 8 full practical guides and linked their equations.')
