"""Bengali names for equation variables.

Many generated entries copied the English `name` into `name_bn`, so the Bangla
variable table showed English phrases. `scripts/repair-equation-formatting.py`
uses this map to fill in real Bangla names. Keys are the exact English strings
found in `content/**/*.mdx`; values are the Bangla term a subject teacher would
write on the board.
"""

BN_VARIABLE_NAMES = {
    "Bohr magneton": "বোর ম্যাগনেটন",
    "Boltzmann constant": "বোলৎসমান ধ্রুবক",
    "Brewster incidence angle": "ব্রুস্টার আপতন কোণ",
    "Coriolis pseudo-force": "কোরিওলিস ছদ্মবল",
    "Hamiltonian": "হ্যামিলটনিয়ান",
    "Lorentz factor": "লরেঞ্জ গুণক",
    "Michaelis constant": "মাইকেলিস ধ্রুবক",
    "Miller index h": "মিলার সূচক h",
    "Miller index k": "মিলার সূচক k",
    "Miller index l": "মিলার সূচক l",
    "Planck constant": "প্লাঙ্ক ধ্রুবক",
    "absolute temperature": "পরম তাপমাত্রা",
    "absorbance": "শোষণ মাত্রা",
    "acid dissociation constant": "অম্ল বিয়োজন ধ্রুবক",
    "acid dissociation index": "অম্ল বিয়োজন সূচক",
    "acid strength exponent": "অম্লের শক্তি সূচক",
    "adsorption equilibrium constant": "শোষণ সাম্য ধ্রুবক",
    "amplitude": "বিস্তার",
    "analytical acid concentration": "অম্লের বিশ্লেষণী ঘনত্ব",
    "angle inside film": "পর্দার ভেতরের কোণ",
    "angular frequency": "কৌণিক কম্পাঙ্ক",
    "angular momentum": "কৌণিক ভরবেগ",
    "angular speed": "কৌণিক বেগ",
    "anode reduction potential": "অ্যানোডের বিজারণ বিভব",
    "approximately fixed excess reactant": "প্রায় স্থির অতিরিক্ত বিকারক",
    "bond order": "বন্ধন ক্রম",
    "capacitance": "ধারকত্ব",
    "capacitor voltage": "ধারকের বিভব",
    "cathode reduction potential": "ক্যাথোডের বিজারণ বিভব",
    "center distance": "কেন্দ্র থেকে দূরত্ব",
    "central mass": "কেন্দ্রীয় ভর",
    "chemical potential": "রাসায়নিক বিভব",
    "cold reservoir temperature": "শীতল আধারের তাপমাত্রা",
    "concentration product": "ঘনত্বের গুণফল",
    "concentration-based solubility product": "ঘনত্ব-ভিত্তিক দ্রাব্যতা গুণফল",
    "conductance": "পরিবাহিতা",
    "conductivity": "তড়িৎ পরিবাহিতা",
    "conjugate momentum": "অনুবন্ধী ভরবেগ",
    "conjugate-base concentration": "অনুবন্ধী ক্ষারকের ঘনত্ব",
    "cryoscopic constant": "ক্রায়োস্কোপিক ধ্রুবক",
    "crystal-field energy relative to barycentre": "ভারকেন্দ্রের সাপেক্ষে স্ফটিক-ক্ষেত্র শক্তি",
    "cubic lattice parameter": "ঘনক ল্যাটিস ধ্রুবক",
    "current": "তড়িৎ প্রবাহ",
    "decay constant": "ক্ষয় ধ্রুবক",
    "degeneracy of level i": "i-তম স্তরের সমশক্তি অবস্থার সংখ্যা",
    "diffraction angle": "অপবর্তন কোণ",
    "dimensionless activity quotient": "এককহীন সক্রিয়তা অনুপাত",
    "dimensionless equilibrium constant": "এককহীন সাম্য ধ্রুবক",
    "effective magnetic moment": "কার্যকর চৌম্বক ভ্রামক",
    "effusion rate of gas 1": "গ্যাস ১-এর নিঃসরণ হার",
    "effusion rate of gas 2": "গ্যাস ২-এর নিঃসরণ হার",
    "electric field": "তড়িৎ ক্ষেত্র",
    "electrode area": "তড়িৎদ্বারের ক্ষেত্রফল",
    "electrode separation": "তড়িৎদ্বারের ব্যবধান",
    "electrons in antibonding orbitals": "বন্ধন-বিরোধী অরবিটালের ইলেকট্রন",
    "electrons in bonding orbitals": "বন্ধন অরবিটালের ইলেকট্রন",
    "electrons in eg orbitals": "eg অরবিটালের ইলেকট্রন",
    "electrons in t2g orbitals": "t2g অরবিটালের ইলেকট্রন",
    "energy": "শক্তি",
    "energy flux density": "শক্তি ফ্লাক্স ঘনত্ব",
    "entropy": "এনট্রপি",
    "film refractive index": "পর্দার প্রতিসরাঙ্ক",
    "film thickness": "পর্দার পুরুত্ব",
    "final pressure": "চূড়ান্ত চাপ",
    "final temperature": "চূড়ান্ত তাপমাত্রা",
    "final volume": "চূড়ান্ত আয়তন",
    "first signed radius": "প্রথম চিহ্নযুক্ত ব্যাসার্ধ",
    "flux per turn": "প্রতি পাকে ফ্লাক্স",
    "focal length": "ফোকাস দূরত্ব",
    "frame angular speed": "কাঠামোর কৌণিক বেগ",
    "freezing point decrease": "হিমাঙ্ক অবনমন",
    "frequency factor": "কম্পাঙ্ক গুণক",
    "fringe order": "ঝালরের ক্রম",
    "fringe spacing": "ঝালরের ব্যবধান",
    "gas constant": "গ্যাস ধ্রুবক",
    "generalized coordinate": "সাধারণীকৃত স্থানাঙ্ক",
    "gravitational constant": "মহাকর্ষ ধ্রুবক",
    "ground vibrational energy": "ভূমিস্তরের কম্পন শক্তি",
    "group velocity": "গুচ্ছ বেগ",
    "half-coverage pressure": "অর্ধ-পৃষ্ঠঢাকা চাপ",
    "half-life": "অর্ধায়ু",
    "harmonic frequency": "হারমোনিক কম্পাঙ্ক",
    "heat capacity ratio": "তাপ ধারকতার অনুপাত",
    "heat flux": "তাপ ফ্লাক্স",
    "hot reservoir temperature": "উষ্ণ আধারের তাপমাত্রা",
    "hydrogen Rydberg constant": "হাইড্রোজেনের রিডবার্গ ধ্রুবক",
    "hydrogen ion concentration": "হাইড্রোজেন আয়নের ঘনত্ব",
    "hydrogen ion pH": "হাইড্রোজেন আয়নের pH",
    "incident medium index": "আপতন মাধ্যমের প্রতিসরাঙ্ক",
    "independent components": "স্বাধীন উপাদানের সংখ্যা",
    "induced electromotive force": "আবিষ্ট তড়িৎচালক বল",
    "inductance": "আবেশকত্ব",
    "initial amplitude": "প্রারম্ভিক বিস্তার",
    "initial common-ion concentration": "সাধারণ আয়নের প্রারম্ভিক ঘনত্ব",
    "initial pressure": "প্রারম্ভিক চাপ",
    "initial rate": "প্রারম্ভিক হার",
    "initial reactant concentration": "বিকারকের প্রারম্ভিক ঘনত্ব",
    "initial temperature": "প্রারম্ভিক তাপমাত্রা",
    "initial voltage": "প্রারম্ভিক বিভব",
    "initial volume": "প্রারম্ভিক আয়তন",
    "intensive degrees of freedom": "স্বাধীনতার মাত্রা",
    "internal energy": "অভ্যন্তরীণ শক্তি",
    "interplanar spacing": "তলীয় ব্যবধান",
    "level energy": "শক্তিস্তরের শক্তি",
    "limiting reactant concentration": "সীমাকারী বিকারকের ঘনত্ব",
    "linear mass density": "রৈখিক ভর ঘনত্ব",
    "magnetic field": "চৌম্বক ক্ষেত্র",
    "magnetic flux density": "চৌম্বক ফ্লাক্স ঘনত্ব",
    "mass": "ভর",
    "maximum order": "সর্বোচ্চ ক্রম",
    "minimum order": "সর্বনিম্ন ক্রম",
    "molality": "মোলালিটি",
    "molar mass": "মোলার ভর",
    "molar mass of gas 1": "গ্যাস ১-এর মোলার ভর",
    "molar mass of gas 2": "গ্যাস ২-এর মোলার ভর",
    "molar solubility": "মোলার দ্রাব্যতা",
    "molar solubility in pure water": "বিশুদ্ধ পানিতে মোলার দ্রাব্যতা",
    "moment of inertia": "জড়তার ভ্রামক",
    "momentum": "ভরবেগ",
    "natural angular frequency": "স্বাভাবিক কৌণিক কম্পাঙ্ক",
    "nonvolatile solute mole fraction": "অউদ্বায়ী দ্রাবের মোল ভগ্নাংশ",
    "number of phases": "দশার সংখ্যা",
    "number of unpaired electrons": "অযুগ্ম ইলেকট্রনের সংখ্যা",
    "observed first-order constant": "পর্যবেক্ষিত প্রথম-ক্রম ধ্রুবক",
    "occupation probability": "দখলের সম্ভাবনা",
    "octahedral splitting": "অষ্টতলক বিভাজন",
    "orbit radius": "কক্ষপথের ব্যাসার্ধ",
    "orbital quantum number": "কক্ষীয় কোয়ান্টাম সংখ্যা",
    "orbital radius": "কক্ষপথের ব্যাসার্ধ",
    "orbital speed": "কক্ষপথের বেগ",
    "osmotic pressure": "অভিস্রবণ চাপ",
    "partial pressure of component i": "উপাদান i-এর আংশিক চাপ",
    "particle charge": "কণার আধান",
    "photon energy": "ফোটনের শক্তি",
    "potential energy": "বিভব শক্তি",
    "pressure": "চাপ",
    "principal quantum number": "প্রধান কোয়ান্টাম সংখ্যা",
    "pure solvent vapour pressure": "বিশুদ্ধ দ্রাবকের বাষ্প চাপ",
    "pure-solvent solution vapour pressure": "দ্রবণের বাষ্প চাপ",
    "quality factor": "গুণাঙ্ক (Q)",
    "radial net force": "অরীয় লব্ধি বল",
    "radial node count": "রেডিয়াল নোডের সংখ্যা",
    "radius": "ব্যাসার্ধ",
    "reaction Gibbs energy": "বিক্রিয়ার গিবস শক্তি",
    "reaction heat capacity": "বিক্রিয়ার তাপ ধারকতা",
    "reaction rate": "বিক্রিয়ার হার",
    "relative refractive index": "আপেক্ষিক প্রতিসরাঙ্ক",
    "resistance": "রোধ",
    "rest mass": "স্থির ভর",
    "root mean square speed": "গড়-বর্গমূল বেগ",
    "rotational constant": "ঘূর্ণন ধ্রুবক",
    "rotational level energy": "ঘূর্ণন স্তরের শক্তি",
    "rotational quantum number": "ঘূর্ণন কোয়ান্টাম সংখ্যা",
    "saturating initial rate": "সম্পৃক্ত প্রারম্ভিক হার",
    "screen distance": "পর্দার দূরত্ব",
    "second signed radius": "দ্বিতীয় চিহ্নযুক্ত ব্যাসার্ধ",
    "second-order rate constant": "দ্বিতীয়-ক্রম হার ধ্রুবক",
    "series-limit wavelength": "শ্রেণির সীমা তরঙ্গদৈর্ঘ্য",
    "single-particle energy": "একক-কণার শক্তি",
    "single-particle partition function": "একক-কণার বণ্টন ফাংশন",
    "slit separation": "চিরের ব্যবধান",
    "slit width": "চিরের প্রস্থ",
    "solute molarity": "দ্রবের মোলারিটি",
    "source mass": "উৎসের ভর",
    "speed": "বেগ",
    "speed of light": "আলোর বেগ",
    "spring stiffness": "স্প্রিংয়ের দৃঢ়তা",
    "standard cell emf": "প্রমাণ কোষের তড়িৎচালক বল",
    "standard reaction Gibbs energy": "প্রমাণ বিক্রিয়া গিবস শক্তি",
    "standard reaction enthalpy": "প্রমাণ বিক্রিয়া এনথালপি",
    "stored energy": "সঞ্চিত শক্তি",
    "string tension": "তারের টান",
    "substrate concentration": "সাবস্ট্রেটের ঘনত্ব",
    "temperature": "তাপমাত্রা",
    "test mass": "পরীক্ষ্য ভর",
    "thermal conductivity": "তাপ পরিবাহিতা",
    "thermal efficiency": "তাপীয় দক্ষতা",
    "time": "সময়",
    "torque": "টর্ক",
    "total energy": "মোট শক্তি",
    "total pressure": "মোট চাপ",
    "transmittance ratio": "সঞ্চারণ অনুপাত",
    "transmitted medium index": "প্রতিসৃত মাধ্যমের প্রতিসরাঙ্ক",
    "transverse momentum": "অনুপ্রস্থ ভরবেগ",
    "turn count": "পাকসংখ্যা",
    "vacuum permeability": "শূন্যস্থানের প্রবেশ্যতা",
    "vacuum wavelength": "শূন্যস্থানে তরঙ্গদৈর্ঘ্য",
    "van't Hoff factor": "ভ্যান্ট হফ গুণক",
    "velocity relative to rotating frame": "ঘূর্ণায়মান কাঠামোর সাপেক্ষে বেগ",
    "viscous damping coefficient": "সান্দ্র ক্ষয় গুণাঙ্ক",
    "volume": "আয়তন",
    "wave number": "তরঙ্গসংখ্যা",
    "wave speed": "তরঙ্গের বেগ",
    "wavefunction": "তরঙ্গফাংশন",
    "wavelength": "তরঙ্গদৈর্ঘ্য",
    "weak acid concentration": "দুর্বল অম্লের ঘনত্ব",
    "work done by gas": "গ্যাস দ্বারা কৃত কাজ",
}
