"""Fill coverage gaps in legacy and early Honours entries with bilingual concept checks.
One question per previously uncovered equation or practical; no files are overwritten.
"""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]/'content'
# slug | EN~BN question | EN~BN correct | 3 wrong EN~BN separated by ; | EN~BN explanation
EQUATIONS=r'''
bohr-quantization-angular-momentum|What is Bohr's allowed orbital angular momentum for principal number n?~বোরের n প্রধান সংখ্যায় অনুমোদিত কৌণিক ভরবেগ কত?|nħ~nħ;ħ/n~ħ/n;n²ħ~n²ħ;Zero for every n~সব n-এ শূন্য|Bohr postulated mvr=nħ for permitted circular orbits; this is a historical model, superseded by quantum orbital theory.~বোর অনুমোদিত বৃত্তীয় কক্ষপথে mvr=nħ ধরেন; এটি ঐতিহাসিক মডেল, আধুনিক কোয়ান্টাম তত্ত্বে সংশোধিত।
bragg-equation|A reflection of order n=1 occurs at θ=30° with d=0.20 nm. Wavelength?~d=০.২০ nm ও θ=৩০°-এ প্রথম ক্রমের প্রতিফলনে তরঙ্গদৈর্ঘ্য কত?|0.20 nm~০.২০ nm;0.10 nm~০.১০ nm;0.40 nm~০.৪০ nm;0.80 nm~০.৮০ nm|nλ=2d sinθ; λ=2×0.20×0.5=0.20 nm. The angle is measured to the crystal planes.~nλ=২d sinθ; λ=২×০.২০×০.৫=০.২০ nm। কোণটি স্ফটিকতলের সঙ্গে মাপা।
compton-effect-wavelength-shift|At scattering angle θ=0°, the Compton wavelength shift is?~বিচ্ছুরণ কোণ θ=০° হলে কম্পটন তরঙ্গদৈর্ঘ্যের পরিবর্তন কত?|Zero~শূন্য;h/(mc)~h/(mc);2h/(mc)~2h/(mc);Infinite~অসীম|Δλ=h(1−cosθ)/(mc); cos0°=1, so Δλ=0.~Δλ=h(১−cosθ)/(mc); cos০°=১, তাই Δλ=০।
euler-lagrange-equation|For L=½m q̇²−½kq², what equation follows?~L=½m q̇²−½kq² হলে কোন গতিসমীকরণ মেলে?|mq̈+kq=0~mq̈+kq=০;mq̈−kq=0~mq̈−kq=০;q̈=0~q̈=০;mq̇+kq=0~mq̇+kq=০|∂L/∂q=−kq and d(∂L/∂q̇)/dt=mq̈. Euler–Lagrange gives mq̈=−kq.~∂L/∂q=−kq ও d(∂L/∂q̇)/dt=mq̈; তাই mq̈=−kq।
heisenberg-uncertainty-principle|What is the lower bound on ΔxΔp for a quantum state?~কোয়ান্টাম অবস্থায় ΔxΔp-এর নিম্নসীমা কত?|ħ/2~ħ/২;0 always~সবসময় ০;2ħ~২ħ;ħ²~ħ²|The standard-deviation form is ΔxΔp≥ħ/2; it does not merely describe poor measuring equipment.~প্রমিত বিচ্যুতির রূপে ΔxΔp≥ħ/২; এটি শুধু যন্ত্রের দুর্বলতা নয়।
hydrogen-energy-levels-bohr|If hydrogen's ground-state energy is −13.6 eV, what is E₂ in the Bohr model?~হাইড্রোজেনের ভূমিস্তর −১৩.৬ eV হলে বোর মডেলে E₂ কত?|−3.4 eV~−৩.৪ eV;−27.2 eV~−২৭.২ eV;−6.8 eV~−৬.৮ eV;+3.4 eV~+৩.৪ eV|Eₙ=−13.6/n² eV, giving −13.6/4=−3.4 eV for n=2.~Eₙ=−১৩.৬/n² eV; n=২-এ −১৩.৬/৪=−৩.৪ eV।
maxwell-em-wave-speed|What determines electromagnetic-wave speed in vacuum?~শূন্যস্থানে তড়িৎচুম্বকীয় তরঙ্গের বেগ কী নির্ধারণ করে?|1/√(μ₀ε₀)~১/√(μ₀ε₀);√(μ₀ε₀)~√(μ₀ε₀);μ₀/ε₀~μ₀/ε₀;Zero~শূন্য|Combining vacuum Maxwell equations yields a wave equation with c²=1/(μ₀ε₀).~শূন্যস্থানে ম্যাক্সওয়েলের সমীকরণে তরঙ্গ সমীকরণ থেকে c²=১/(μ₀ε₀)।
particle-in-box-energy|If one-dimensional box length doubles, ground-state energy becomes?~একমাত্রিক বাক্সের দৈর্ঘ্য দ্বিগুণ হলে ভূমিস্তরের শক্তি কত হয়?|One quarter~এক চতুর্থাংশ;One half~অর্ধেক;Double~দ্বিগুণ;Fourfold~চার গুণ|E₁=h²/(8mL²); the inverse-square dependence gives E₁/4 for length 2L.~E₁=h²/(৮mL²); দৈর্ঘ্য ২L হলে বিপরীত-বর্গ নিয়মে E₁/৪।
relativistic-length-contraction|Which length is the proper length in Lorentz contraction?~লরেঞ্জ সংকোচনে প্রকৃত দৈর্ঘ্য কোনটি?|Length measured in the object's rest frame~বস্তুর স্থির কাঠামোয় মাপা দৈর্ঘ্য;Length measured only by a moving observer~শুধু চলমান পর্যবেক্ষকের দৈর্ঘ্য;Length measured at zero temperature~শূন্য তাপে মাপা দৈর্ঘ্য;Every object's diameter in any frame~সব কাঠামোয় যেকোনো ব্যাস|Proper length L₀ is measured when the object is at rest; its length parallel to relative motion is L=L₀/γ.~বস্তু যে কাঠামোতে স্থির সেখানে L₀; আপেক্ষিক গতির সমান্তরাল দৈর্ঘ্য L=L₀/γ।
relativistic-time-dilation|A moving clock has proper interval 1 s and γ=2. What interval does an inertial observer measure?~ঘড়ির নিজস্ব সময় ১ s ও γ=২ হলে স্থির জড় পর্যবেক্ষক কত সময় মাপেন?|2 s~২ s;0.5 s~০.৫ s;1 s~১ s;4 s~৪ s|Δt=γΔτ=2×1 s=2 s; the proper interval is measured with the clock at rest.~Δt=γΔτ=২×১ s=২ s; নিজস্ব সময় ঘড়ির স্থির কাঠামোতে মাপা।
schrodinger-equation|When can Ψ(r,t)=ψ(r)e^(−iEt/ħ) describe a stationary state?~Ψ(r,t)=ψ(r)e^(−iEt/ħ) কখন স্থির অবস্থা বর্ণনা করে?|For a time-independent Hamiltonian energy eigenstate~সময়-স্বাধীন হ্যামিল্টনীয়ের শক্তি-স্বকীয় অবস্থায়;For arbitrary time-changing potential~যেকোনো সময়-বদলানো বিভবে;Only when E=0~শুধু E=০ হলে;Only for a classical trajectory~শুধু ধ্রুপদি গতিপথে|Separation gives Ĥψ=Eψ when the potential has no explicit time dependence; boundary conditions select allowed energies.~বিভব সময়ে স্পষ্টভাবে না বদলালে পৃথকীকরণে Ĥψ=Eψ; সীমানা-শর্ত অনুমোদিত শক্তি নির্ধারণ করে।
boltzmann-distribution|For two nondegenerate levels separated by ΔE>0, which population ratio is expected at equilibrium?~ΔE>০ ব্যবধানের দুটি অধঃপতনহীন স্তরে সাম্যে জনসংখ্যার অনুপাত?|Nhigh/Nlow=e^(−ΔE/kBT)~Nউচ্চ/Nনিম্ন=e^(−ΔE/kBT);e^(+ΔE/kBT)~e^(+ΔE/kBT);Always 1~সবসময় ১;−ΔE/kBT~−ΔE/kBT|Boltzmann weights decrease exponentially with energy; degeneracy factors must be included if levels have different degeneracies.~উচ্চ শক্তিতে বোল্টজমান ওজন সূচকীয়ভাবে কমে; অধঃপতন ভিন্ন হলে তার গুণক লাগবে।
debye-huckel-limiting-law|What regime supports the Debye–Hückel limiting law?~ডিবাই–হুকেল সীমা সূত্র কোন অবস্থায় প্রযোজ্য?|Very dilute electrolyte solutions~অতি বিরল ইলেকট্রোলাইট দ্রবণ;Any concentrated salt melt~যেকোনো ঘন গলিত লবণ;Pure ideal gas only~শুধু বিশুদ্ধ আদর্শ গ্যাস;Only solid crystals~শুধু কঠিন স্ফটিক|The limiting expression for log activity coefficient scales with √I only as ionic strength I tends toward zero.~আয়নিক শক্তি I শূন্যের কাছে গেলে log সক্রিয়তা সহগের সীমা সূত্র √I-র সঙ্গে সম্পর্কিত।
equilibrium-constant|At equilibrium, what is ΔᵣG for the reaction as written?~বর্ণিত বিক্রিয়া সাম্যে থাকলে ΔᵣG কত?|Zero~শূন্য;Always positive~সবসময় ধনাত্মক;Always negative~সবসময় ঋণাত্মক;Equal to RT~RT-এর সমান|Equilibrium means Q=K and ΔᵣG=ΔᵣG°+RT lnK=0. Thermodynamic K uses dimensionless activities.~সাম্যে Q=K, ফলে ΔᵣG=ΔᵣG°+RT lnK=০। প্রকৃত K মাত্রাহীন সক্রিয়তায় লেখা।
eyring-transition-state-equation|In transition-state theory, which factor has units of inverse time in k≈(kBT/h)exp(−ΔG‡/RT)?~পরিবর্তন-অবস্থা তত্ত্বে k≈(kBT/h)exp(−ΔG‡/RT)-এ কোন গুণকের একক সময়ের ব্যস্ত?|kBT/h~kBT/h;exp(−ΔG‡/RT)~exp(−ΔG‡/RT);ΔG‡/RT~ΔG‡/RT;Equilibrium activity~সাম্য সক্রিয়তা|kBT/h has dimensions s⁻¹; the exponent and its exponential are dimensionless. The expression needs transition-state assumptions.~kBT/h-এর একক s⁻¹; সূচক ও সূচকীয় রাশি মাত্রাহীন। পরিবর্তন-অবস্থার অনুমান দরকার।
faradays-law|If current efficiency is 50%, how does actual deposit mass compare with ideal m=QM/(nF)?~প্রবাহ দক্ষতা ৫০% হলে প্রকৃত জমা ভর আদর্শ m=QM/(nF)-এর তুলনায় কত?|Half~অর্ধেক;Double~দ্বিগুণ;Equal~সমান;Fourfold~চার গুণ|Only half the passed charge contributes to the desired deposit, so mactual≈0.5QM/(nF).~চলতি চার্জের অর্ধেক কাঙ্ক্ষিত সঞ্চয়ে লাগে; তাই mপ্রকৃত≈০.৫QM/(nF)।
freundlich-adsorption-isotherm|In log(x/m)=logK+(1/n)logCe, what is the slope against logCe?~log(x/m)=logK+(১/n)logCe রেখায় logCe-এর বিপরীতে ঢাল কত?|1/n~১/n;n~n;K~K;Zero always~সবসময় শূন্য|The linearized empirical Freundlich relation has slope 1/n over its fitted concentration range; it is not a universal monolayer law.~রৈখিক Freundlich সম্পর্কে সীমিত ঘনত্ব পরিসরে ঢাল ১/n; এটি সর্বজনীন একস্তর সূত্র নয়।
gibbs-duhem-equation|At fixed T and P in a binary homogeneous mixture, which differential identity holds?~স্থির T ও P-তে দ্বি-উপাদান সমসত্ত্ব মিশ্রণে কোন অন্তরক সম্পর্ক?|x₁dμ₁+x₂dμ₂=0~x₁dμ₁+x₂dμ₂=০;dμ₁=dμ₂=0 always~dμ₁=dμ₂ সবসময় ০;μ₁+μ₂=0~μ₁+μ₂=০;dT=dP=1~dT=dP=১|At fixed T and P, Gibbs–Duhem gives Σnᵢdμᵢ=0; dividing by total moles yields Σxᵢdμᵢ=0.~স্থির T ও P-তে Σnᵢdμᵢ=০; মোট মোল দিয়ে ভাগে Σxᵢdμᵢ=০।
langmuir-adsorption-isotherm|At KP=1 in Langmuir's monolayer model, surface coverage is?~ল্যাংমুইরের একস্তর মডেলে KP=১ হলে পৃষ্ঠঢাকা কত?|One half~অর্ধেক;One~এক;Zero~শূন্য;Two~দুই|θ=KP/(1+KP)=1/2. Independent equivalent sites and negligible lateral interactions are assumed.~θ=KP/(১+KP)=১/২; সমতুল্য স্বাধীন আসন ও পার্শ্বিক মিথস্ক্রিয়া নগণ্য ধরা হয়।
nernst-distribution-law|Why can a partition coefficient appear concentration dependent for an acid distributed between solvents?~দুটি দ্রাবকে অম্ল বণ্টনে আপাত সহগ ঘনত্বনির্ভর কেন হতে পারে?|Ionization or association changes the fraction of the same molecular form~আয়নীভবন বা সংযুক্তিতে একই আণবিক রূপের অংশ বদলায়;Both solvents become identical~দুটি দ্রাবক একই হয়ে যায়;All concentrations vanish at equilibrium~সাম্যে সব ঘনত্ব শূন্য;Temperature has no effect on equilibrium~তাপমাত্রায় সাম্য বদলায় না|Nernst distribution compares the same chemical species in both phases at constant T; additional equilibria require a modified mass balance.~স্থির তাপে একই রাসায়নিক রূপের দুই স্তরের বণ্টন তুলনা করতে হয়; অন্য সাম্য থাকলে ভর-সাম্য সংশোধন লাগে।
rydberg-equation-hydrogen|For a Balmer line, what is the lower principal quantum number n₁?~বালমার রেখায় নিম্ন প্রধান কোয়ান্টাম সংখ্যা n₁ কত?|2~২;1~১;3~৩;0~০|Balmer emissions terminate on n₁=2; higher levels n₂>2 produce different visible/near-UV lines.~বালমার নির্গমন n₁=২ স্তরে শেষ হয়; n₂>২ থেকে দৃশ্যমান/নিকট UV রেখা মেলে।
'''
LABS=r'''
brewster-angle-honours-lab|Which reflected polarization ideally vanishes at Brewster incidence?~ব্রুস্টার কোণে কোন প্রতিফলিত মেরুকরণ আদর্শভাবে শূন্য?|p-polarized component~p-মেরুকৃত উপাংশ;s-polarized component~s-মেরুকৃত উপাংশ;Both at all angles~সব কোণে উভয়ই;Unpolarized beam regardless of medium~মাধ্যম নির্বিশেষে অমেরুকৃত রশ্মি|For transparent dielectric interfaces, the p-reflection coefficient goes to zero at θB while s-reflection generally remains.~স্বচ্ছ ডাইইলেকট্রিকে θB-তে p-প্রতিফলন শূন্য হলেও s-প্রতিফলন সাধারণত থাকে।
hall-effect-lab|Why reverse the field when measuring Hall voltage?~হল বিভব মাপায় ক্ষেত্রের দিক উল্টানো হয় কেন?|To reject a fixed contact-voltage offset~স্থির সংযোগজনিত বিভব বাদ দিতে;To double sample thickness~নমুনার পুরুত্ব দ্বিগুণ করতে;To remove the carrier charge~বাহকের আধান দূর করতে;To make field zero in both trials~দুই পাঠে ক্ষেত্র শূন্য করতে|The Hall signal changes sign with B while a fixed geometric offset is approximately even, so half the difference isolates the Hall contribution.~B উল্টালে হল বিভবের চিহ্ন বদলায়, স্থির সংযোগ-offset মোটামুটি বদলায় না; পার্থক্যের অর্ধেক হল উপাংশ দেয়।
michelson-interferometer-lab|If a mirror moves 0.10 mm while 400 fringes cross, wavelength is?~দর্পণ ০.১০ mm সরলে ৪০০ ঝালর গেলে তরঙ্গদৈর্ঘ্য কত?|500 nm~৫০০ nm;250 nm~২৫০ nm;1000 nm~১০০০ nm;400 nm~৪০০ nm|The optical path changes by 2Δx, so λ=2×0.10 mm/400=0.0005 mm=500 nm.~আলোকপথ ২Δx বদলায়; তাই λ=২×০.১০ mm/৪০০=০.০০০৫ mm=৫০০ nm।
rc-discharge-honours-lab|What fraction of initial capacitor voltage remains at t=RC?~t=RC-এ ধারকের প্রাথমিক বিভবের কত অংশ থাকে?|1/e~১/e;1/2~১/২;1~১;0~০|V(t)=V₀ exp(−t/RC); at t=RC this is V₀/e≈0.368V₀.~V(t)=V₀ exp(−t/RC); t=RC-এ V₀/e≈০.৩৬৮V₀।
rotational-kinetic-energy-lab|If string slip occurs on the flywheel axle, is v=rω still valid?~ফ্লাইহুইলের অক্ষে সুতো পিছলালে v=rω কি প্রযোজ্য?|No, the no-slip link between linear and angular motion fails~না, সরল ও কৌণিক গতির পিছলনহীন সম্পর্ক ভাঙে;Yes, slip improves the equality~হ্যাঁ, পিছলন সম্পর্ক ভালো করে;Only when mass is zero~শুধু ভর শূন্য হলে;Always, by definition of radius~সবসময়, ব্যাসার্ধের সংজ্ঞায়|The ideal inertia derivation assumes falling mass displacement follows axle rotation. Slip invalidates v=rω and a=rα, biasing I.~আদর্শ জড়তার প্রতিপাদনে পতনশীল ভরের সরণ অক্ষের ঘূর্ণনের সঙ্গে বাঁধা। পিছলনে v=rω ও a=rα চলে না; I ভুল হয়।
wave-energy-string-lab|Why measure string mass per unit length independently?~তারের একক দৈর্ঘ্যের ভর স্বাধীনভাবে কেন মাপি?|To compare observed (2Lf)² with tension divided by μ~মাপা (২Lf)²-কে টান/μ-এর সঙ্গে তুলতে;To remove gravitational acceleration~মহাকর্ষীয় ত্বরণ বাদ দিতে;To change the frequency generator~কম্পাঙ্ক উৎস বদলাতে;To force the string to have no nodes~তারে কোনো নিস্পন্দ বিন্দু না রাখতে|From v=2Lf and v²=𝒯/μ, testing the relation requires an independent μ rather than fitting it from the same speed data.~v=২Lf ও v²=𝒯/μ যাচাইয়ে বেগের একই পাঠ থেকে μ না বের করে স্বাধীনভাবে মাপা দরকার।
aspirin-synthesis-lab|Why must aspirin crystals be dry before reporting percentage yield?~শতকরা উৎপাদ লেখার আগে অ্যাসপিরিন স্ফটিক শুকাতে হয় কেন?|Residual liquid inflates measured product mass~অবশিষ্ট তরল উৎপাদের মাপা ভর বাড়ায়;Water doubles the stoichiometric ratio~পানি স্টইকিওমেট্রিক অনুপাত দ্বিগুণ করে;Aspirin has no mass when wet~ভেজা অ্যাসপিরিনের ভর থাকে না;Drying creates salicylic acid~শুকালে স্যালিসিলিক অ্যাসিড তৈরি হয়|Percentage yield uses actual dry product mass divided by theoretical mass. Wet crystals can show an impossible apparent yield over 100%.~শতকরা উৎপাদে প্রকৃত শুকনো ভরকে তাত্ত্বিক ভরে ভাগ করা হয়; ভেজা স্ফটিকে আপাত উৎপাদ ১০০%-এর বেশি হতে পারে।
beer-transmittance-lab|For transmittance T=0.01, absorbance A is?~সঞ্চারণ T=০.০১ হলে শোষণ A কত?|2~২;1~১;0.01~০.০১;100~১০০|A=−log₁₀T=−log₁₀(0.01)=2; use fractional rather than percentage transmittance.~A=−log₁₀T=−log₁₀(০.০১)=২; শতাংশ নয়, ভগ্নাংশ বসান।
conductance-cell-constant-lab|With calibrated Kcell=100 m⁻¹ and unknown G=0.005 S, conductivity is?~Kcell=১০০ m⁻¹ ও অজানার G=০.০০৫ S হলে পরিবাহিতা কত?|0.5 S/m~০.৫ S/m;5 S/m~৫ S/m;20 S/m~২০ S/m;0.00005 S/m~০.০০০০৫ S/m|κ=G Kcell=0.005×100=0.5 S/m at the calibration temperature.~ক্রমাঙ্কন তাপমাত্রায় κ=G Kcell=০.০০৫×১০০=০.৫ S/m।
freezing-depression-electrolyte-lab|Why not use the lowest supercooled temperature as the freezing point?~অতিশীতল অবস্থার সর্বনিম্ন তাপমাত্রা হিমাঙ্ক ধরা উচিত নয় কেন?|It is a transient non-equilibrium dip~এটি সাম্যবিহীন ক্ষণস্থায়ী তাপমাত্রা-পতন;It is always above the true plateau~এটি সবসময় প্রকৃত plateau-এর উপরে;It equals boiling point~এটি স্ফুটনাঙ্কের সমান;It is independent of solvent~এটি দ্রাবকনিরপেক্ষ|After nucleation, latent heat raises temperature toward the freezing plateau; ΔTf should compare reproducible equilibrium plateaus.~স্ফটিক শুরু হলে সুপ্ততাপে তাপমাত্রা স্থিতিশীল হিমাঙ্কের দিকে ফেরে; ΔTf-এ পুনরাবৃত্ত স্থির অংশ তুলনা করতে হয়।
iron-thiocyanate-equilibrium-lab|Why use excess Fe³⁺ for the calibration standards?~ক্রমাঙ্কন মান দ্রবণে Fe³⁺ অতিরিক্ত কেন রাখা হয়?|To make added SCN− approximately equal to formed FeSCN²⁺~যোগ করা SCN−-কে উৎপন্ন FeSCN²⁺-এর আনুমানিক সমান করতে;To prevent all visible absorbance~সব দৃশ্যমান শোষণ ঠেকাতে;To make the cuvette longer~কুভেট লম্বা করতে;To remove the need for a blank~blank-এর প্রয়োজন দূর করতে|A large Fe³⁺ excess shifts complexation toward product, enabling an approximate known-complex calibration; the approximation still needs scrutiny.~বেশি Fe³⁺ জটিল আয়ন গঠনের দিকে সাম্য সরায়, ফলে আনুমানিক জানা ঘনত্বের ক্রমাঙ্কন মেলে; অনুমান যাচাইও জরুরি।
weak-acid-ph-approx-lab|If pH meter calibration drifts, which reported quantity is most directly affected?~pH মিটারের ক্রমাঙ্কন বদলালে কোন নির্ণীত মান সরাসরি প্রভাবিত?|Estimated hydrogen-ion activity and inferred Ka~হাইড্রোজেন সক্রিয়তা ও তা থেকে নির্ণীত Ka;Weighed mass only~শুধু ওজন করা ভর;Glassware volume only~শুধু কাচপাত্রের আয়তন;Molar mass of the acid~অম্লের মোলার ভর|The measured pH determines the estimated H+ activity. An offset propagates exponentially into inferred [H+] and then into Ka.~মাপা pH থেকে H+ সক্রিয়তা অনুমান হয়; বিভব-পাঠে offset থাকলে [H+] এবং সেখান থেকে Ka-তে সূচকীয় ত্রুটি হয়।
'''

def pair(text):
    a,b=text.split('~',1)
    return a.strip(),b.strip()

if __name__=='__main__':
    records=[line.split('|') for block in (EQUATIONS,LABS) for line in block.splitlines() if line.strip()]
    assert len(records)==33 and len({record[0] for record in records})==33
    for index,(slug,stem,choices,why) in enumerate(records):
        matches=list(ROOT.glob(f'*/honours/{slug}.mdx'))
        assert len(matches)==1,(slug,matches)
        path=ROOT/'quizzes'/f'honours-{slug}.json'
        assert not path.exists(),f'Existing quiz {path}'
        from pathlib import Path
        raw=matches[0].read_text()
        import re
        bn=re.search(r'^title_bn: ["\']?(.*?)["\']?$',raw,re.M)
        en=re.search(r'^title_en: ["\']?(.*?)["\']?$',raw,re.M)
        # Support both quoted and unquoted frontmatter titles using an anchored lookup.
        assert bn and en,(slug,'missing titles')
        title_bn=bn.group(1).strip().strip('"\'')
        title_en=en.group(1).strip().strip('"\'')
        subject=matches[0].parts[-3]
        q_en,q_bn=pair(stem); ex_en,ex_bn=pair(why)
        options=[pair(c) for c in choices.split(';')]
        assert len(options)==4 and len({c[0] for c in options})==4,(slug,options)
        shift=index%4
        options=options[-shift:]+options[:-shift] if shift else options
        entry=dict(slug='honours-'+slug,title_bn=title_bn+' — ধারণা যাচাই',title_en=title_en+' — concept check',subject=subject,level='honours',chapter='Honours '+subject,chapter_bn='স্নাতক '+('পদার্থবিজ্ঞান' if subject=='physics' else 'রসায়ন'),description_en='Equation or lab concept with explained answer.',description_bn='ব্যাখ্যাসহ সমীকরণ বা ব্যবহারিক ধারণা।',questions=[dict(q=q_en,q_bn=q_bn,options=[c[0] for c in options],options_bn=[c[1] for c in options],answer=shift,explanation=ex_en,explanation_bn=ex_bn)])
        path.write_text(json.dumps(entry,ensure_ascii=False,indent=2)+'\n')
    print('Completed',len(records),'previously uncovered topic quizzes.')
