"""Points for the second half of the HSC chemistry practicals: preparations,
kinetics, thermochemistry, solubility, instrumental titration, chromatography,
buffers, purity and electrochemistry. `scripts/add-practical-topic-points.py`
imports this module alongside `practical_points_chemistry_hsc`.
"""

POINTS = {
    'chemistry-soap-preparation-hsc': {
        'en': [
            'Aim: prepare soap from a fat or oil by saponification.',
            'Apparatus: beaker, tripod, gauze, burner, glass rod, oil, NaOH solution, ethanol, NaCl, mould or filter paper.',
            'Saponification: $\\text{fat} + 3\\mathrm{NaOH} \\rightarrow \\text{glycerol} + 3\\mathrm{RCOONa}$.',
            'Weigh the oil, then add the calculated amount of NaOH solution.',
            'A little ethanol helps the oil and the aqueous alkali mix into one phase.',
            'Heat gently for 20–30 minutes, stirring so the mixture does not bump.',
            'Test completeness by taking a drop into water — it should dissolve without oily droplets.',
            'Add saturated NaCl to salt out the soap, which rises as a solid layer.',
            'Cool, then filter and press the curd between filter papers to remove the liquor.',
            'Weigh the dry soap, calculate the percentage yield and note the pH of a solution of it; a strongly alkaline soap means excess NaOH.',
            'Precautions: goggles and gloves for NaOH, no vigorous boiling, keep the beaker covered.',
            'Error sources: incomplete saponification, soap lost in the filtrate, excess alkali, damp product.',
        ],
        'bn': [
            'উদ্দেশ্য: স্যাপোনিফিকেশন প্রক্রিয়ায় চর্বি বা তেল থেকে সাবান তৈরি।',
            'যন্ত্রপাতি: বিকার, ট্রাইপড, গজ, বার্নার, কাচদণ্ড, তেল, NaOH দ্রবণ, ইথানল, NaCl, ছাঁচ বা ফিল্টার কাগজ।',
            'স্যাপোনিফিকেশন: $\\text{fat} + 3\\mathrm{NaOH} \\rightarrow \\text{glycerol} + 3\\mathrm{RCOONa}$।',
            'তেলের ভর নিয়ে হিসাবমতো NaOH দ্রবণ যোগ করুন।',
            'সামান্য ইথানল তেল ও জলীয় ক্ষারকে এক দশায় মিশতে সাহায্য করে।',
            '২০–৩০ মিনিট মৃদু তাপ দিন এবং নাড়তে থাকুন যাতে মিশ্রণ লাফিয়ে না ওঠে।',
            'সম্পূর্ণতা যাচাইতে এক ফোঁটা পানিতে দিন — তৈলাক্ত ফোঁটা ছাড়াই গলে যাওয়ার কথা।',
            'পরিপৃক্ত NaCl দিয়ে সাবান আলাদা করুন, যা কঠিন স্তর হিসেবে ওপরে ওঠে।',
            'ঠান্ডা করে ছেঁকে নিন এবং ফিল্টার কাগজের মাঝে চেপে মাদার লিকার সরান।',
            'শুকনো সাবানের ভর নিয়ে শতকরা উৎপাদন হিসাব করুন এবং সাবানের দ্রবণের pH লিখুন; অতিরিক্ত ক্ষারীয় মানে বেশি NaOH থেকে গেছে।',
            'সতর্কতা: NaOH-এর জন্য চশমা ও গ্লাভস, জোরে ফোটানো নয়, বিকার ঢেকে রাখুন।',
            'ভুলের উৎস: অসম্পূর্ণ স্যাপোনিফিকেশন, পরিশ্রুতে সাবান হারানো, অতিরিক্ত ক্ষার, ভেজা উৎপাদ।',
        ],
    },
    'chemistry-aspirin-preparation-hsc': {
        'en': [
            'Aim: prepare aspirin (acetylsalicylic acid) by acetylating salicylic acid.',
            'Apparatus: conical flask, water bath, thermometer, Büchner funnel or filter paper, salicylic acid, acetic anhydride, concentrated H₃PO₄ or H₂SO₄, ice.',
            'Reaction: salicylic acid + acetic anhydride $\\rightarrow$ aspirin + acetic acid, an esterification of the phenolic OH.',
            'Weigh the salicylic acid and calculate the theoretical yield from its moles.',
            'Add acetic anhydride, then two or three drops of the acid catalyst.',
            'Warm in a water bath at about $60^\\circ\\mathrm{C}$ for 15 minutes, swirling occasionally.',
            'Add cold water to destroy the excess anhydride — this releases heat and fumes — then cool the flask in ice so the aspirin crystallises.',
            'Filter under suction, wash with a little cold water and dry between filter papers.',
            'Weigh the product, compute the percentage yield and check purity by the melting point, about $135^\\circ\\mathrm{C}$; a wide or low range means impurity.',
            'Test with FeCl₃: unreacted salicylic acid gives a violet colour, pure aspirin does not.',
            'Precautions: acetic anhydride is corrosive and lachrymatory — use a fume hood, gloves and goggles.',
            'Error sources: water in the flask hydrolysing the anhydride, overheating, product left in the mother liquor.',
        ],
        'bn': [
            'উদ্দেশ্য: স্যালিসাইলিক অ্যাসিডের অ্যাসিটাইলেশনে অ্যাসপিরিন প্রস্তুত করা।',
            'যন্ত্রপাতি: কোনিক্যাল ফ্লাস্ক, পানি-স্নান, তাপমাপক, বুকনার ফানেল বা ফিল্টার কাগজ, স্যালিসাইলিক অ্যাসিড, অ্যাসিটিক অ্যানহাইড্রাইড, গাঢ় H₃PO₄ বা H₂SO₄, বরফ।',
            'বিক্রিয়া: স্যালিসাইলিক অ্যাসিড + অ্যাসিটিক অ্যানহাইড্রাইড $\\rightarrow$ অ্যাসপিরিন + অ্যাসিটিক অ্যাসিড; এটি ফেনলীয় OH-এর এস্টারীকরণ।',
            'স্যালিসাইলিক অ্যাসিডের ভর নিয়ে মোল থেকে তাত্ত্বিক উৎপাদন হিসাব করুন।',
            'অ্যাসিটিক অ্যানহাইড্রাইড দিয়ে দুই-তিন ফোঁটা অ্যাসিড প্রভাবক যোগ করুন।',
            'প্রায় $60^\\circ\\mathrm{C}$ পানি-স্নানে ১৫ মিনিট গরম করুন এবং মাঝে মাঝে নাড়ুন।',
            'ঠান্ডা পানি দিয়ে অতিরিক্ত অ্যানহাইড্রাইড নষ্ট করুন — এতে তাপ ও ধোঁয়া বের হয় — তারপর ফ্লাস্ক বরফে ঠান্ডা করুন যাতে অ্যাসপিরিন স্ফটিক হয়।',
            'সাকশনে ছেঁকে সামান্য ঠান্ডা পানি দিয়ে ধুয়ে ফিল্টার কাগজের মাঝে শুকান।',
            'উৎপাদের ভর নিয়ে শতকরা উৎপাদন বের করুন এবং গলনাঙ্ক দিয়ে বিশুদ্ধতা দেখুন, প্রায় $135^\\circ\\mathrm{C}$; বিস্তৃত বা কম পরিসর মানে অপদ্রব্য।',
            'FeCl₃ পরীক্ষা করুন: অবিক্রিয়াশীল স্যালিসাইলিক অ্যাসিড বেগুনি রং দেয়, বিশুদ্ধ অ্যাসপিরিন দেয় না।',
            'সতর্কতা: অ্যাসিটিক অ্যানহাইড্রাইড ক্ষয়কারী ও চোখে জ্বালা ধরায় — ফিউম হুড, গ্লাভস ও চশমা ব্যবহার করুন।',
            'ভুলের উৎস: ফ্লাস্কের পানিতে অ্যানহাইড্রাইডের আর্দ্রবিশ্লেষণ, অতিরিক্ত তাপ, মাদার লিকারে উৎপাদ থেকে যাওয়া।',
        ],
    },
    'chemistry-ester-preparation-hsc': {
        'en': [
            'Aim: prepare an ester by reacting a carboxylic acid with an alcohol.',
            'Apparatus: round-bottom flask, reflux condenser, water bath, measuring cylinder, acid, alcohol, concentrated H₂SO₄, sodium carbonate solution.',
            'Esterification: $\\mathrm{RCOOH} + \\mathrm{R\\prime OH} \\rightleftharpoons \\mathrm{RCOOR\\prime} + \\mathrm{H_2O}$, an equilibrium.',
            'Concentrated sulfuric acid catalyses the reaction and removes water, pushing it right.',
            'Measure the acid and alcohol in the molar ratio the equation requires.',
            'Add the acid catalyst slowly while swirling and cooling the flask.',
            'Reflux gently for 20–30 minutes in a water bath so nothing is lost.',
            'Pour the mixture into sodium carbonate solution to neutralise the leftover acid.',
            'The ester separates as an upper layer with a fruity smell; decant it or collect it with a separating funnel.',
            'Record the volume or mass obtained and compare with the theoretical yield.',
            'Precautions: never heat a sealed flask, add acid to the mixture rather than the reverse, keep flames away from alcohols.',
            'Error sources: incomplete reflux, ester lost in the aqueous layer, water left in the flask, too little catalyst.',
        ],
        'bn': [
            'উদ্দেশ্য: কার্বক্সিলিক অ্যাসিড ও অ্যালকোহলের বিক্রিয়ায় এস্টার তৈরি।',
            'যন্ত্রপাতি: গোলতল ফ্লাস্ক, রিফ্লাক্স কনডেনসার, পানি-স্নান, আয়তন মাপক চোঙ, অ্যাসিড, অ্যালকোহল, গাঢ় H₂SO₄, সোডিয়াম কার্বোনেট দ্রবণ।',
            'এস্টারীকরণ: $\\mathrm{RCOOH} + \\mathrm{R\\prime OH} \\rightleftharpoons \\mathrm{RCOOR\\prime} + \\mathrm{H_2O}$, যা একটি সাম্যাবস্থা।',
            'গাঢ় সালফিউরিক অ্যাসিড বিক্রিয়ায় প্রভাবক এবং পানি সরিয়ে সাম্যাবস্থাকে ডানে ঠেলে দেয়।',
            'সমীকরণের অনুপাত ধরে অ্যাসিড ও অ্যালকোহল মেপে নিন।',
            'ফ্লাস্ক নাড়তে নাড়তে ও ঠান্ডা রেখে আস্তে প্রভাবক অ্যাসিড যোগ করুন।',
            'পানি-স্নানে ২০–৩০ মিনিট মৃদু রিফ্লাক্স করুন যাতে কিছুই হারিয়ে না যায়।',
            'মিশ্রণটি সোডিয়াম কার্বোনেট দ্রবণে ঢেলে অবশিষ্ট অ্যাসিড প্রশমিত করুন।',
            'এস্টার ওপরের স্তর হিসেবে আলাদা হয় এবং ফলের মতো গন্ধ দেয়; ঢেলে নিন বা পৃথকীকরণ চুঙ্গি দিয়ে সংগ্রহ করুন।',
            'প্রাপ্ত আয়তন বা ভর লিখে তাত্ত্বিক উৎপাদনের সঙ্গে তুলনা করুন।',
            'সতর্কতা: বন্ধ ফ্লাস্ক গরম নয়, মিশ্রণে অ্যাসিড দিন (উল্টো নয়), অ্যালকোহলের কাছে শিখা রাখবেন না।',
            'ভুলের উৎস: অসম্পূর্ণ রিফ্লাক্স, জলীয় স্তরে এস্টার হারানো, ফ্লাস্ক থেকে না যাওয়া পানি, কম প্রভাবক।',
        ],
    },
    'chemistry-thiosulfate-hcl-rate-hsc': {
        'en': [
            'Aim: study how concentration and temperature affect the rate of the thiosulfate–HCl reaction.',
            'Apparatus: conical flask, paper with a black cross, stopwatch, measuring cylinders, Na₂S₂O₃, dilute HCl, water bath, thermometer.',
            'Reaction: $\\mathrm{S_2O_3^{2-}} + 2\\mathrm{H^+} \\rightarrow \\mathrm{S} + \\mathrm{SO_2} + \\mathrm{H_2O}$; the sulfur makes the solution cloudy.',
            'Rate is taken as proportional to $1/t$, where $t$ is the time for the cross to disappear.',
            'Draw a bold cross on white paper and place the flask directly on it.',
            'Add a fixed volume of acid to the thiosulfate, start the stopwatch at once, stir once, look down through the solution and stop the watch when the cross vanishes.',
            'Repeat with different thiosulfate concentrations, keeping the total volume constant with water.',
            'Plot $1/t$ against concentration; a straight line through the origin shows first-order behaviour.',
            'Repeat at several temperatures and note that the rate roughly doubles for every $10^\\circ\\mathrm{C}$ rise.',
            'Keep the light, the observer and the cross the same in every trial.',
            'Precautions: constant total volume, same flask, start the watch as the acid goes in, ventilate the SO₂.',
            'Error sources: inconsistent judgement of the vanishing point, temperature drift, dirty flask, delayed timing.',
        ],
        'bn': [
            'উদ্দেশ্য: থায়োসালফেট–HCl বিক্রিয়ার হারে ঘনমাত্রা ও তাপমাত্রার প্রভাব দেখা।',
            'যন্ত্রপাতি: কোনিক্যাল ফ্লাস্ক, কালো ক্রস আঁকা কাগজ, স্টপওয়াচ, আয়তন মাপক চোঙ, Na₂S₂O₃, লঘু HCl, পানি-স্নান, তাপমাপক।',
            'বিক্রিয়া: $\\mathrm{S_2O_3^{2-}} + 2\\mathrm{H^+} \\rightarrow \\mathrm{S} + \\mathrm{SO_2} + \\mathrm{H_2O}$; সালফারে দ্রবণ ঘোলা হয়।',
            'হার ধরা হয় $1/t$-এর সমানুপাতিক, যেখানে $t$ হলো ক্রস মিলিয়ে যাওয়ার সময়।',
            'সাদা কাগজে মোটা ক্রস এঁকে ফ্লাস্ক ঠিক তার ওপর বসান।',
            'থায়োসালফেটে নির্দিষ্ট আয়তনের অ্যাসিড দিয়ে সঙ্গে সঙ্গে ঘড়ি চালু করুন, একবার নাড়ুন, দ্রবণের ভেতর দিয়ে নিচে তাকান এবং ক্রস মিলিয়ে গেলে ঘড়ি থামান।',
            'পানি দিয়ে মোট আয়তন স্থির রেখে বিভিন্ন ঘনমাত্রায় পুনরাবৃত্তি করুন।',
            '$1/t$ বনাম ঘনমাত্রা আঁকুন; মূলবিন্দুগামী সরলরেখা প্রথম ক্রমের আচরণ দেখায়।',
            'কয়েকটি তাপমাত্রায় পুনরাবৃত্তি করে লিখুন যে প্রতি $10^\\circ\\mathrm{C}$ বাড়ায় হার প্রায় দ্বিগুণ হয়।',
            'প্রতিটি পরীক্ষায় আলো, পর্যবেক্ষক ও ক্রস একই রাখুন।',
            'সতর্কতা: মোট আয়তন স্থির, একই ফ্লাস্ক, অ্যাসিড দেওয়ার সঙ্গে সঙ্গে ঘড়ি, SO₂-এর জন্য বায়ুচলাচল।',
            'ভুলের উৎস: ক্রস মেলানোর অসংগত বিচার, তাপমাত্রার পরিবর্তন, নোংরা ফ্লাস্ক, ঘড়ি চালাতে দেরি।',
        ],
    },
    'chemistry-neutralisation-enthalpy-hsc': {
        'en': [
            'Aim: determine the enthalpy of neutralisation of a strong acid with a strong base.',
            'Apparatus: two polystyrene cups with a lid, thermometer, measuring cylinders, 1 M HCl, 1 M NaOH, stirrer.',
            'Definition: $\\Delta H = -\\dfrac{mc\\Delta T}{n}$, where $n$ is the moles of water formed.',
            'The polystyrene cup acts as a calorimeter with very little heat capacity of its own.',
            'Measure equal volumes, say $50\\ \\mathrm{cm^3}$, of acid and base and record both initial temperatures.',
            'Add the base to the acid quickly, put the lid on and stir continuously.',
            'Record the highest temperature reached, reading the thermometer at eye level.',
            'Take $m$ as the total mass of the solution, $c$ as $4.18\\ \\mathrm{J\\,g^{-1}K^{-1}}$ and $n$ as the moles of the limiting reactant.',
            'The accepted value is about $-57\\ \\mathrm{kJ/mol}$; compare and give the percentage error.',
            'Repeat with a weak acid such as ethanoic acid and explain why the value is smaller.',
            'Precautions: dry cups, lid on, no splashing, both solutions at room temperature to start.',
            'Error sources: heat lost to the air and the cup, slow mixing, thermometer precision, evaporation.',
        ],
        'bn': [
            'উদ্দেশ্য: তীব্র অ্যাসিড ও তীব্র ক্ষারকের প্রশমন এনথালপি নির্ণয়।',
            'যন্ত্রপাতি: ঢাকনাসহ দুটি পলিস্টাইরিন কাপ, তাপমাপক, আয়তন মাপক চোঙ, ১ M HCl, ১ M NaOH, নাড়ুনি।',
            'সংজ্ঞা: $\\Delta H = -\\dfrac{mc\\Delta T}{n}$, যেখানে $n$ হলো উৎপন্ন পানির মোল সংখ্যা।',
            'পলিস্টাইরিন কাপ ক্যালোরিমিটার হিসেবে কাজ করে এবং এর নিজস্ব তাপধারণ ক্ষমতা খুব কম।',
            'অ্যাসিড ও ক্ষারকের সমান আয়তন, ধরুন $50\\ \\mathrm{cm^3}$, মেপে দুটির শুরুর তাপমাত্রা লিখুন।',
            'দ্রুত ক্ষারক অ্যাসিডে মিশিয়ে ঢাকনা দিন এবং ক্রমাগত নাড়ুন।',
            'চোখের সমান উচ্চতায় পাঠ নিয়ে সর্বোচ্চ তাপমাত্রা লিখুন।',
            '$m$ ধরুন দ্রবণের মোট ভর, $c$ ধরুন $4.18\\ \\mathrm{J\\,g^{-1}K^{-1}}$ এবং $n$ ধরুন সীমাকারী বিকারকের মোল সংখ্যা।',
            'স্বীকৃত মান প্রায় $-57\\ \\mathrm{kJ/mol}$; তুলনা করে শতকরা ত্রুটি লিখুন।',
            'ইথানয়িক অ্যাসিডের মতো দুর্বল অ্যাসিডে পুনরাবৃত্তি করে ব্যাখ্যা করুন কেন মান কম আসে।',
            'সতর্কতা: শুকনো কাপ, ঢাকনা দেওয়া, ছিটকে ফেলা নয়, দুই দ্রবণই শুরুতে কক্ষ তাপমাত্রায়।',
            'ভুলের উৎস: বাতাস ও কাপে তাপ ক্ষয়, ধীর মিশ্রণ, তাপমাপকের সূক্ষ্মতা, বাষ্পীভবন।',
        ],
    },
    'chemistry-solubility-hsc': {
        'en': [
            'Aim: determine the solubility of a solid in water and draw its solubility curve.',
            'Apparatus: beakers, thermometer, burner or hot plate, glass rod, evaporating dish, balance, filter paper, solid sample.',
            'Solubility $S$ is the mass of solute that saturates $100\\ \\mathrm{g}$ of solvent at a fixed temperature.',
            'Prepare a saturated solution at a chosen temperature, stir for 10 minutes and let the excess solid settle while the temperature stays steady.',
            'Weigh a clean, dry evaporating dish, then weigh it again with a known volume of clear solution.',
            'Evaporate to dryness on a water bath, then heat gently until the mass is constant.',
            'Mass of solute $=$ dish with dry solid $-$ empty dish; mass of solvent $=$ solution mass $-$ solute mass.',
            'Convert to $S = \\dfrac{\\text{mass of solute}}{\\text{mass of solvent}} \\times 100$ in grams per 100 g of water.',
            'Repeat at about five temperatures, for example $30$, $40$, $50$, $60$ and $70^\\circ\\mathrm{C}$.',
            'Plot $S$ against temperature; the curve shows whether solubility rises or falls.',
            'Precautions: no solid in the sampled solution, dry the dish fully, cool in a desiccator before weighing.',
            'Error sources: undissolved solid carried over, incomplete drying, temperature drop during sampling, splattering.',
        ],
        'bn': [
            'উদ্দেশ্য: পানিতে কঠিনের দ্রাব্যতা নির্ণয় ও দ্রাব্যতা রেখা অঙ্কন।',
            'যন্ত্রপাতি: বিকার, তাপমাপক, বার্নার বা হট প্লেট, কাচদণ্ড, বাষ্পীভবন পাত্র, তুলা, ফিল্টার কাগজ, কঠিন নমুনা।',
            'দ্রাব্যতা $S$ হলো নির্দিষ্ট তাপমাত্রায় $100\\ \\mathrm{g}$ দ্রাবককে সম্পৃক্ত করতে প্রয়োজনীয় দ্রবের ভর।',
            'বাছাই করা তাপমাত্রায় সম্পৃক্ত দ্রবণ তৈরি করে ১০ মিনিট নাড়ুন এবং তাপমাত্রা স্থির রেখে অতিরিক্ত কঠিন জমতে দিন।',
            'পরিষ্কার শুকনো বাষ্পীভবন পাত্রের ভর নিয়ে, তারপর জানা আয়তনের স্বচ্ছ দ্রবণসহ ভর নিন।',
            'পানি-স্নানে শুকিয়ে নিন, তারপর ভর স্থির না হওয়া পর্যন্ত মৃদু তাপ দিন।',
            'দ্রবের ভর $=$ শুকনো কঠিনসহ পাত্র $-$ খালি পাত্র; দ্রাবকের ভর $=$ দ্রবণের ভর $-$ দ্রবের ভর।',
            'রূপান্তর করুন: $S =$ (দ্রবের ভর $\\div$ দ্রাবকের ভর) $\\times 100$, অর্থাৎ প্রতি ১০০ গ্রাম পানিতে কত গ্রাম।',
            'প্রায় পাঁচটি তাপমাত্রায় পুনরাবৃত্তি করুন, যেমন $30$, $40$, $50$, $60$ ও $70^\\circ\\mathrm{C}$।',
            '$S$ বনাম তাপমাত্রা আঁকুন; রেখা থেকে বোঝা যাবে দ্রাব্যতা বাড়ে না কমে।',
            'সতর্কতা: নমুনায় কঠিন যেন না থাকে, পাত্র পুরোপুরি শুকান, ওজনের আগে ডেসিকেটরে ঠান্ডা করুন।',
            'ভুলের উৎস: অগলিত কঠিন চলে আসা, অসম্পূর্ণ শুকানো, নমুনা নেওয়ার সময় তাপমাত্রা কমে যাওয়া, ছিটকে পড়া।',
        ],
    },
    'chemistry-conductometric-titration-hsc': {
        'en': [
            'Aim: locate the end point of an acid–base titration by measuring conductivity.',
            'Apparatus: conductivity meter or meter with a cell, burette, beaker, magnetic stirrer, HCl, NaOH, distilled water.',
            'Conductivity depends on the concentration and mobility of the ions in solution.',
            'H⁺ and OH⁻ are the most mobile ions, so replacing them changes conductivity sharply.',
            'In HCl versus NaOH the conductivity falls as H⁺ becomes Na⁺, then rises with excess OH⁻.',
            'Place a measured volume of the acid in the beaker with the conductivity cell immersed.',
            'Add the base in equal increments, such as $1.0\\ \\mathrm{cm^3}$, stirring after each addition.',
            'Record the conductance after every addition once the reading is steady.',
            'Plot conductance against volume added; the two straight portions meet at the end point, which is more reliable than any single reading.',
            'Use the end-point volume with $c_aV_a = c_bV_b$ to find the unknown concentration.',
            'Precautions: keep the cell fully immersed, constant total volume, rinse the cell between runs, calibrate the meter.',
            'Error sources: temperature change, air bubbles on the cell, uneven stirring, large increments near the end point.',
        ],
        'bn': [
            'উদ্দেশ্য: পরিবাহিতা মেপে অ্যাসিড-ক্ষারক টাইট্রেশনের সমাপ্তি বিন্দু নির্ণয়।',
            'যন্ত্রপাতি: কনডাক্টিভিটি মিটার ও সেল, বুরেট, বিকার, ম্যাগনেটিক স্টিরার, HCl, NaOH, পাতিত পানি।',
            'পরিবাহিতা নির্ভর করে দ্রবণে আয়নের ঘনমাত্রা ও সচলতার ওপর।',
            'H⁺ ও OH⁻ সবচেয়ে সচল আয়ন, তাই এদের প্রতিস্থাপনে পরিবাহিতা দ্রুত বদলায়।',
            'HCl বনাম NaOH-এ H⁺ থেকে Na⁺ হওয়ার সময় পরিবাহিতা কমে, তারপর অতিরিক্ত OH⁻-এ বাড়ে।',
            'বিকারে অ্যাসিডের মাপা আয়তন নিয়ে কনডাক্টিভিটি সেল নিমজ্জিত করুন।',
            'সমান ধাপে, যেমন $1.0\\ \\mathrm{cm^3}$, ক্ষারক যোগ করে প্রতিবার নাড়ুন।',
            'পাঠ স্থির হলে প্রতি যোগের পর পরিবাহিতা লিখুন।',
            'পরিবাহিতা বনাম যোগ করা আয়তন আঁকুন; দুই সরল অংশের মিলনবিন্দুই সমাপ্তি বিন্দু, যা যেকোনো একক পাঠের চেয়ে নির্ভরযোগ্য।',
            'সমাপ্তি বিন্দুর আয়তনকে $c_aV_a = c_bV_b$-তে বসিয়ে অজানা ঘনমাত্রা বের করুন।',
            'সতর্কতা: সেল পুরোপুরি নিমজ্জিত রাখুন, মোট আয়তন স্থির রাখুন, প্রতি রানে সেল ধুয়ে নিন, মিটার ক্যালিব্রেট করুন।',
            'ভুলের উৎস: তাপমাত্রার পরিবর্তন, সেলে বাতাসের বুদবুদ, অসম নাড়া, সমাপ্তি বিন্দুর কাছে বড় ধাপ।',
        ],
    },
    'chemistry-ph-metric-titration-hsc': {
        'en': [
            'Aim: follow an acid–base titration with a pH meter and locate the equivalence point.',
            'Apparatus: pH meter with glass electrode, burette, beaker, magnetic stirrer, standard acid, base, buffer solutions.',
            'The pH changes slowly at first, jumps sharply at the equivalence point, then levels off again.',
            'Calibrate the meter with pH 4 and pH 9 buffers, rinse the electrode with distilled water and blot it — never rub it with paper.',
            'Immerse the electrode in the analyte, keeping the bulb well below the liquid surface.',
            'Add the titrant in $1.0\\ \\mathrm{cm^3}$ steps and record the pH after each steady reading.',
            'Near the steep region reduce the steps to $0.2\\ \\mathrm{cm^3}$ so the jump is captured.',
            'Plot pH against volume; the steepest point, or the peak of $\\Delta\\mathrm{pH}/\\Delta V$, is the equivalence point.',
            'For a strong acid–strong base the equivalence pH is about 7; for a weak acid it is above 7.',
            'Choose an indicator whose colour-change range covers that pH, and compare with the meter result.',
            'Precautions: stir gently, do not let the stir bar hit the electrode, keep the temperature stable.',
            'Error sources: uncalibrated meter, a dried or aged electrode, CO₂ absorption, large increments near the jump.',
        ],
        'bn': [
            'উদ্দেশ্য: pH মিটার দিয়ে অ্যাসিড-ক্ষারক টাইট্রেশন পর্যবেক্ষণ ও তুল্যতা বিন্দু নির্ণয়।',
            'যন্ত্রপাতি: কাচ তড়িৎদ্বারসহ pH মিটার, বুরেট, বিকার, ম্যাগনেটিক স্টিরার, আদর্শ অ্যাসিড, ক্ষারক, বাফার দ্রবণ।',
            'শুরুতে pH ধীরে বদলায়, তুল্যতা বিন্দুতে তীব্র লাফ দেয়, তারপর আবার সমান্তরাল হয়।',
            'pH ৪ ও pH ৯ বাফার দিয়ে মিটার ক্যালিব্রেট করুন, তড়িৎদ্বার পাতিত পানিতে ধুয়ে মুছে নিন — কাগজে ঘষবেন না।',
            'পরীক্ষণীয় দ্রবণে তড়িৎদ্বার ডুবান, বাল্ব যেন তলের বেশ নিচে থাকে।',
            '$1.0\\ \\mathrm{cm^3}$ ধাপে টাইট্র্যান্ট যোগ করে প্রতিটি স্থির পাঠের পর pH লিখুন।',
            'খাড়া অংশের কাছে ধাপ $0.2\\ \\mathrm{cm^3}$-এ নামিয়ে আনুন, যাতে লাফটি ধরা পড়ে।',
            'pH বনাম আয়তন আঁকুন; সবচেয়ে খাড়া বিন্দু বা $\\Delta\\mathrm{pH}/\\Delta V$-এর শীর্ষই তুল্যতা বিন্দু।',
            'তীব্র অ্যাসিড–তীব্র ক্ষারকে তুল্যতা pH প্রায় ৭; দুর্বল অ্যাসিডে তা ৭-এর ওপরে।',
            'যে নির্দেশকের রং পরিবর্তনের পরিসর সেই pH ঢাকে তাকে বেছে নিন এবং মিটারের ফলের সঙ্গে তুলনা করুন।',
            'সতর্কতা: আস্তে নাড়ুন, স্টিরার যেন তড়িৎদ্বারে না ঠোকে, তাপমাত্রা স্থির রাখুন।',
            'ভুলের উৎস: ক্যালিব্রেট না করা মিটার, শুকনো বা পুরনো তড়িৎদ্বার, CO₂ শোষণ, লাফের কাছে বড় ধাপ।',
        ],
    },
    'chemistry-rf-chromatography-hsc': {
        'en': [
            'Aim: separate a mixture and calculate the $R_f$ values of its components.',
            'Apparatus: chromatography chamber with lid, TLC plate or chromatography paper, capillary tube, pencil, ruler, solvent system, UV lamp or spraying reagent.',
            'Definition: $R_f = \\dfrac{\\text{distance travelled by the spot}}{\\text{distance travelled by the solvent front}}$.',
            '$R_f$ depends on polarity: a component that likes the mobile phase travels farther.',
            'Draw the baseline in pencil about $1\\ \\mathrm{cm}$ above the bottom edge and apply the sample as a small concentrated spot, letting it dry between applications.',
            'Choose the solvent so the components give $R_f$ values between 0.2 and 0.8.',
            'Place the plate in the closed chamber without letting the solvent cover the baseline.',
            'Remove the plate when the front is near the top, mark that line at once, dry it and make the spots visible with a UV lamp or a locating reagent.',
            'Measure both distances from the baseline and compute $R_f$ for every spot.',
            'Compare with authentic standards run on the same plate to identify each component.',
            'Precautions: closed chamber, do not touch the plate surface, no shaking, record the solvent and temperature.',
            'Error sources: overloaded spots, solvent above the baseline, an evaporating front, measuring to a smeared edge.',
        ],
        'bn': [
            'উদ্দেশ্য: মিশ্রণ পৃথক করা এবং প্রতিটি উপাদানের $R_f$ মান নির্ণয়।',
            'যন্ত্রপাতি: ঢাকনাসহ ক্রোম্যাটোগ্রাফি চেম্বার, TLC প্লেট বা ক্রোম্যাটোগ্রাফি কাগজ, কৈশিক নল, পেন্সিল, স্কেল, দ্রাবক ব্যবস্থা, UV বাতি বা স্প্রে বিকারক।',
            'সংজ্ঞা: $R_f =$ দাগের অতিক্রান্ত দূরত্ব $\\div$ দ্রাবক সম্মুখের অতিক্রান্ত দূরত্ব।',
            '$R_f$ নির্ভর করে পোলারিটির ওপর: যে উপাদান সচল দশাকে বেশি পছন্দ করে সেটি বেশি দূর যায়।',
            'নিচের কিনারা থেকে প্রায় $1\\ \\mathrm{cm}$ ওপরে পেন্সিলে বেসলাইন আঁকুন এবং নমুনা ছোট ঘন দাগ হিসেবে দিন, প্রতিবার শুকিয়ে নিতে নিতে।',
            'এমন দ্রাবক বাছুন যাতে উপাদানগুলোর $R_f$ ০.২ থেকে ০.৮-এর মধ্যে আসে।',
            'বন্ধ চেম্বারে প্লেট রাখুন, যেন দ্রাবক বেসলাইন ঢেকে না ফেলে।',
            'সম্মুখ ওপরের কাছে এলে প্লেট তুলে সেই রেখা সঙ্গে সঙ্গে চিহ্নিত করুন, শুকান এবং UV বাতি বা লোকেটিং বিকারক দিয়ে দাগগুলো দৃশ্যমান করুন।',
            'বেসলাইন থেকে দুই দূরত্ব মেপে প্রতিটি দাগের $R_f$ বের করুন।',
            'একই প্লেটে চালানো আদর্শ নমুনার সঙ্গে মিলিয়ে প্রতিটি উপাদান শনাক্ত করুন।',
            'সতর্কতা: চেম্বার বন্ধ রাখুন, প্লেটের তলে হাত নয়, ঝাঁকানো নয়, দ্রাবক ও তাপমাত্রা লিখুন।',
            'ভুলের উৎস: অতিরিক্ত নমুনা, বেসলাইনের ওপরে দ্রাবক, সম্মুখ বাষ্পীভূত হওয়া, ছড়িয়ে যাওয়া কিনারা মাপা।',
        ],
    },
    'chemistry-buffer-preparation-hsc': {
        'en': [
            'Aim: prepare a buffer of a given pH and test its resistance to added acid and base.',
            'Apparatus: volumetric flask, beakers, pH meter, burette or droppers, ethanoic acid, sodium ethanoate, dilute HCl and NaOH.',
            'Henderson–Hasselbalch: $\\mathrm{pH} = \\mathrm{p}K_a + \\log\\dfrac{[\\mathrm{A^-}]}{[\\mathrm{HA}]}$.',
            'For an ethanoic acid buffer $\\mathrm{p}K_a = 4.76$, so equal concentrations give pH 4.76; calculate the salt-to-acid ratio for your target pH first.',
            'Dissolve the calculated amounts and make the volume up in a volumetric flask.',
            'Measure the pH of the buffer and compare it with the calculated value.',
            'Split the buffer into three portions, keep one as a control, and add a few drops of dilute HCl to one portion and dilute NaOH to another.',
            'Measure the pH again; a good buffer shifts by only a few tenths of a pH unit.',
            'Repeat the same additions to pure water to show how large the change is without a buffer.',
            'Note the buffer capacity: how much acid or base it can absorb before the pH moves sharply.',
            'Precautions: calibrate the pH meter, rinse the electrode, add acid and base dropwise.',
            'Error sources: impure salt, wrong volume, an uncalibrated meter, CO₂ absorbed by a basic buffer.',
        ],
        'bn': [
            'উদ্দেশ্য: নির্দিষ্ট pH-এর বাফার তৈরি করে অ্যাসিড ও ক্ষারক যোগে তার সহনশীলতা পরীক্ষা।',
            'যন্ত্রপাতি: আয়তনিক ফ্লাস্ক, বিকার, pH মিটার, বুরেট বা ড্রপার, ইথানয়িক অ্যাসিড, সোডিয়াম ইথানয়েট, লঘু HCl ও NaOH।',
            'হেন্ডারসন-হাসেলবাল্ক: $\\mathrm{pH} = \\mathrm{p}K_a + \\log\\dfrac{[\\mathrm{A^-}]}{[\\mathrm{HA}]}$।',
            'ইথানয়িক অ্যাসিডের বাফারে $\\mathrm{p}K_a = 4.76$, তাই সমান ঘনমাত্রায় pH হয় ৪.৭৬; আগেই কাঙ্ক্ষিত pH-এর জন্য লবণ ও অ্যাসিডের অনুপাত হিসাব করুন।',
            'হিসাবমতো পরিমাণ গুলে আয়তনিক ফ্লাস্কে আয়তন পূর্ণ করুন।',
            'বাফারের pH মেপে হিসাব করা মানের সঙ্গে তুলনা করুন।',
            'বাফারকে তিন ভাগ করে একটি অংশ নিয়ন্ত্রণ হিসেবে রাখুন, এক ভাগে কয়েক ফোঁটা লঘু HCl এবং আরেক ভাগে লঘু NaOH দিন।',
            'আবার pH মাপুন; ভালো বাফার মাত্র কয়েক দশমাংশ একক বদলায়।',
            'বিশুদ্ধ পানিতেও একই পরিমাণ যোগ করে দেখুন বাফার ছাড়া পরিবর্তন কত বড় হয়।',
            'বাফার ক্ষমতা লিখুন: pH তীব্রভাবে বদলানোর আগে এটি কত অ্যাসিড বা ক্ষারক নিতে পারে।',
            'সতর্কতা: pH মিটার ক্যালিব্রেট করুন, তড়িৎদ্বার ধুয়ে নিন, অ্যাসিড ও ক্ষারক ফোঁটায় ফোঁটায় দিন।',
            'ভুলের উৎস: অশুদ্ধ লবণ, ভুল আয়তন, ক্যালিব্রেট না করা মিটার, ক্ষারীয় বাফারে CO₂ শোষণ।',
        ],
    },
    'chemistry-melting-boiling-point-hsc': {
        'en': [
            'Aim: determine the melting point and boiling point of an organic compound to judge its purity.',
            'Apparatus: melting point apparatus or Thiele tube, capillary tubes, thermometer, oil bath, distillation flask, condenser, sample.',
            'A pure substance melts sharply over a $1$–$2^\\circ\\mathrm{C}$ range at a fixed temperature.',
            'Impurities lower the melting point and widen the range — that is the key diagnostic.',
            'Seal one end of a capillary tube, pack in the dry finely powdered sample $2$–$3\\ \\mathrm{mm}$ high and tap the tube so it settles at the closed end.',
            'Attach the capillary to the thermometer with the sample beside the bulb.',
            'Heat slowly, about $1$–$2^\\circ\\mathrm{C}$ per minute near the expected melting point.',
            'Record the temperature when the first liquid appears and when the last solid disappears.',
            'For the boiling point use simple distillation and read the thermometer at the side arm.',
            'A constant distillation temperature is the boiling point; compare with the literature value.',
            'Precautions: dry sample, slow heating, calibrated thermometer, do not overfill the distillation flask.',
            'Error sources: heating too fast, a wet or coarse sample, thermometer not beside the sample, superheating.',
        ],
        'bn': [
            'উদ্দেশ্য: জৈব যৌগের গলনাঙ্ক ও স্ফুটনাঙ্ক নির্ণয় করে বিশুদ্ধতা বিচার।',
            'যন্ত্রপাতি: গলনাঙ্ক যন্ত্র বা থিয়েল টিউব, কৈশিক নল, তাপমাপক, তেল-স্নান, পাতন ফ্লাস্ক, কনডেনসার, নমুনা।',
            'বিশুদ্ধ পদার্থ নির্দিষ্ট তাপমাত্রায় মাত্র $1$–$2^\\circ\\mathrm{C}$ পরিসরে দ্রুত গলে।',
            'অপদ্রব্য গলনাঙ্ক কমিয়ে দেয় এবং পরিসর বাড়িয়ে দেয় — এটিই প্রধান নির্দেশক।',
            'কৈশিক নলের এক প্রান্ত বন্ধ করে শুকনো সূক্ষ্ম গুঁড়ো নমুনা $2$–$3\\ \\mathrm{mm}$ উচ্চতা পর্যন্ত ভরুন এবং নলে ঠোকা দিয়ে বন্ধ প্রান্তে বসিয়ে নিন।',
            'কৈশিক নলটি তাপমাপকের সঙ্গে এমনভাবে বাঁধুন যেন নমুনা বাল্বের পাশে থাকে।',
            'আস্তে গরম করুন, প্রত্যাশিত গলনাঙ্কের কাছে প্রতি মিনিটে প্রায় $1$–$2^\\circ\\mathrm{C}$।',
            'প্রথম তরল দেখা দেওয়া এবং শেষ কঠিন মিলিয়ে যাওয়ার তাপমাত্রা লিখুন।',
            'স্ফুটনাঙ্কের জন্য সরল পাতন ব্যবহার করে পার্শ্বনলের তাপমাপকের পাঠ নিন।',
            'স্থির পাতন তাপমাত্রাই স্ফুটনাঙ্ক; সাহিত্যিক মানের সঙ্গে তুলনা করুন।',
            'সতর্কতা: শুকনো নমুনা, ধীর তাপ, ক্যালিব্রেটেড তাপমাপক, পাতন ফ্লাস্ক বেশি ভরা নয়।',
            'ভুলের উৎস: দ্রুত তাপ, ভেজা বা মোটা নমুনা, নমুনার পাশে তাপমাপক না থাকা, অতিতাপন।',
        ],
    },
    'chemistry-galvanic-cell-hsc': {
        'en': [
            'Aim: build a simple galvanic cell and measure its emf.',
            'Apparatus: two beakers, zinc and copper strips, ZnSO₄ and CuSO₄ solutions, salt bridge, voltmeter, wires, sandpaper.',
            'Cell emf: $E_{\\text{cell}} = E_{\\text{cathode}} - E_{\\text{anode}}$; for a Daniell cell the standard value is about $1.10\\ \\mathrm{V}$.',
            'Clean both metal strips with sandpaper so the contacts are bright.',
            'Place each strip in its own salt solution, at a known concentration.',
            'Connect the two beakers with the salt bridge, which completes the circuit and keeps charge balance.',
            'Connect the voltmeter with copper as the positive terminal and zinc as the negative.',
            'Record the emf immediately, before concentration changes at the electrodes.',
            'Change one concentration and note how the emf shifts, as the Nernst equation predicts.',
            'Identify the anode as the electrode that loses mass and the cathode as the one that gains it.',
            'Precautions: keep the salt bridge full of solution, no direct mixing of the two beakers, high-resistance voltmeter.',
            'Error sources: oxidised electrodes, a dried salt bridge, dirty contacts, a voltmeter drawing current.',
        ],
        'bn': [
            'উদ্দেশ্য: সরল গ্যালভানিক কোষ তৈরি করে তার তড়িচ্চালক বল মাপা।',
            'যন্ত্রপাতি: দুই বিকার, দস্তা ও তামার ফালি, ZnSO₄ ও CuSO₄ দ্রবণ, লবণ সেতু, ভোল্টমিটার, তার, স্যান্ডপেপার।',
            'কোষ emf: $E_{\\text{cell}} = E_{\\text{cathode}} - E_{\\text{anode}}$; ড্যানিয়েল কোষের আদর্শ মান প্রায় $1.10\\ \\mathrm{V}$।',
            'দুই ধাতুর ফালি স্যান্ডপেপারে পরিষ্কার করুন যাতে সংযোগ উজ্জ্বল হয়।',
            'প্রতিটি ফালি জানা ঘনমাত্রার নিজ নিজ লবণ দ্রবণে রাখুন।',
            'দুই বিকারকে লবণ সেতু দিয়ে যুক্ত করুন, যা বর্তনী পূর্ণ করে এবং আধান ভারসাম্য রাখে।',
            'তামাকে ধনাত্মক ও দস্তাকে ঋণাত্মক প্রান্ত ধরে ভোল্টমিটার যুক্ত করুন।',
            'তড়িৎদ্বারে ঘনমাত্রা বদলানোর আগেই সঙ্গে সঙ্গে emf লিখুন।',
            'একটি ঘনমাত্রা বদলে দেখুন emf কীভাবে সরে যায়, যেমন নার্নস্ট সমীকরণ বলে।',
            'যে তড়িৎদ্বারের ভর কমে সেটি অ্যানোড এবং যেটির বাড়ে সেটি ক্যাথোড।',
            'সতর্কতা: লবণ সেতু দ্রবণে পূর্ণ রাখুন, দুই বিকারের দ্রবণ সরাসরি মেশাবেন না, উচ্চ রোধের ভোল্টমিটার নিন।',
            'ভুলের উৎস: জারিত তড়িৎদ্বার, শুকনো লবণ সেতু, নোংরা সংযোগ, প্রবাহ টানা ভোল্টমিটার।',
        ],
    },
    'chemistry-boyle-law-hsc': {
        'en': [
            'Aim: verify Boyle’s law with a gas syringe at constant temperature.',
            'Apparatus: gas syringe with a sealed tip, pressure gauge or a trapped-air column, clamp stand, weights or a pump, thermometer.',
            'Boyle’s law: at constant temperature and mass, $P_1V_1 = P_2V_2$, so $P \\propto 1/V$.',
            'Seal the syringe so no gas escapes, and record the initial volume.',
            'Increase the pressure in known steps and allow the volume to settle each time.',
            'Record the pressure and the corresponding volume in a table with units.',
            'Keep the temperature constant — do not hold the syringe in your hand, and wait between readings.',
            'Check that the product $PV$ stays roughly the same for every reading.',
            'Plot $P$ against $1/V$ for a straight line through the origin, or $V$ against $P$ for a hyperbola; both confirm the law.',
            'State the conditions — fixed mass, constant temperature, ideal behaviour — and note that real gases deviate at high pressure and low temperature.',
            'Precautions: no leaks, lubricate the plunger, read the volume at eye level, do not exceed the syringe rating.',
            'Error sources: friction of the plunger, gas leaking, temperature rise from compression, parallax on the scale.',
        ],
        'bn': [
            'উদ্দেশ্য: স্থির তাপমাত্রায় গ্যাস সিরিঞ্জ দিয়ে বয়েলের সূত্র যাচাই।',
            'যন্ত্রপাতি: বন্ধ মুখের গ্যাস সিরিঞ্জ, চাপ মাপক বা আবদ্ধ বায়ুস্তম্ভ, ক্ল্যাম্প স্ট্যান্ড, ভার বা পাম্প, তাপমাপক।',
            'বয়েলের সূত্র: স্থির তাপমাত্রা ও ভরে $P_1V_1 = P_2V_2$, অর্থাৎ $P \\propto 1/V$।',
            'সিরিঞ্জ বন্ধ করুন যাতে গ্যাস বেরোতে না পারে, এবং শুরুর আয়তন লিখুন।',
            'জানা ধাপে চাপ বাড়ান এবং প্রতিবার আয়তন স্থির হতে দিন।',
            'এককসহ চাপ ও সংশ্লিষ্ট আয়তন সারণিতে লিখুন।',
            'তাপমাত্রা স্থির রাখুন — সিরিঞ্জ হাতে ধরে রাখবেন না এবং পাঠের মাঝে অপেক্ষা করুন।',
            'প্রতিটি পাঠে গুণফল $PV$ প্রায় একই থাকে কি না যাচাই করুন।',
            '$P$ বনাম $1/V$ আঁকলে মূলবিন্দুগামী সরলরেখা, আর $V$ বনাম $P$ আঁকলে অধিবৃত্ত পাওয়া যায়; দুটোই সূত্রটি নিশ্চিত করে।',
            'শর্তগুলো লিখুন — নির্দিষ্ট ভর, স্থির তাপমাত্রা, আদর্শ আচরণ — এবং উল্লেখ করুন যে উচ্চ চাপ ও নিম্ন তাপমাত্রায় বাস্তব গ্যাস বিচ্যুত হয়।',
            'সতর্কতা: ফুটো নয়, প্লাঞ্জারে পিচ্ছকারক, চোখের সমান উচ্চতায় আয়তন পাঠ, সিরিঞ্জের সীমা অতিক্রম নয়।',
            'ভুলের উৎস: প্লাঞ্জারের ঘর্ষণ, গ্যাস নির্গত হওয়া, সংকোচনে তাপমাত্রা বৃদ্ধি, স্কেলে দৃষ্টিভ্রম।',
        ],
    },
}
