"""Ten to twelve revision points for each school (Classes 6–10) chemistry
practical. See `practical_points_physics_school.py` for the conventions every
entry follows.
"""

POINTS = {
    'chemistry-lab-safety-apparatus-school': {
        'en': [
            'Aim: learn the names, uses and safe handling of common laboratory apparatus.',
            'Apparatus: beaker, conical flask, test tube, measuring cylinder, funnel, pipette, burette, tripod, gauze, Bunsen burner.',
            'Know what each item measures and its accuracy: a measuring cylinder is rough, a pipette is exact.',
            'Read the volume at the bottom of the meniscus, with your eye level with the liquid.',
            'Personal safety: lab coat, closed shoes, tied hair and safety goggles for heating work.',
            'Never taste, smell directly or pipette by mouth; waft vapour towards you instead.',
            'Heat a test tube at an angle, pointing its mouth away from yourself and others.',
            'Add acid to water slowly while stirring — never water to concentrated acid.',
            'Know the symbols: flammable, corrosive, toxic, oxidising and irritant.',
            'Report every spill, breakage or burn to the teacher immediately.',
            'Locate the eyewash, fire blanket, extinguisher and first-aid box before starting.',
            'Dispose of chemicals in the labelled waste containers, not down the sink.',
        ],
        'bn': [
            'উদ্দেশ্য: সাধারণ পরীক্ষাগার যন্ত্রপাতির নাম, ব্যবহার ও নিরাপদ হাতলানো শেখা।',
            'যন্ত্রপাতি: বিকার, কোনিক্যাল ফ্লাস্ক, টেস্টটিউব, আয়তন মাপক চোঙ, ফানেল, পিপেট, বুরেট, ট্রাইপড, গজ, বুনসেন বার্নার।',
            'কোনটি কী মাপে ও কতটা নির্ভুল জানুন: চোঙ মোটামুটি, পিপেট নিখুঁত।',
            'মেনিস্কাসের নিচের তল বরাবর, চোখ তরলের সমান উচ্চতায় রেখে আয়তন পড়ুন।',
            'ব্যক্তিগত নিরাপত্তা: ল্যাব কোট, বন্ধ জুতা, বাঁধা চুল এবং তাপের কাজে নিরাপত্তা চশমা।',
            'কখনো স্বাদ নেবেন না, সরাসরি ঘ্রাণ নয়, মুখে পিপেট নয়; বাষ্প হাত দিয়ে নিজের দিকে টেনে নিন।',
            'টেস্টটিউব হেলিয়ে গরম করুন এবং মুখ নিজের ও অন্যদের থেকে দূরে রাখুন।',
            'গাঢ় অ্যাসিড পানিতে আস্তে মেশান — পানি গাঢ় অ্যাসিডে কখনো নয়।',
            'চিহ্নগুলো চিনুন: দাহ্য, ক্ষয়কারী, বিষাক্ত, জারক ও বিরক্তিকারী।',
            'যেকোনো ছড়াছড়ি, ভাঙা কাচ বা দগ্ধ তৎক্ষণাৎ শিক্ষককে জানান।',
            'শুরু করার আগেই চোখ ধোয়ার ব্যবস্থা, ফায়ার ব্ল্যাঙ্কেট, নেভানো যন্ত্র ও প্রাথমিক চিকিৎসা বাক্সের অবস্থান জেনে নিন।',
            'রাসায়নিক চিহ্নিত বর্জ্য পাত্রে ফেলুন, সিংকে নয়।',
        ],
    },
    'chemistry-flame-test-school': {
        'en': [
            'Aim: identify metal ions in a salt by the colour they give to a flame.',
            'Apparatus: Bunsen burner, nichrome or platinum wire loop, concentrated HCl, watch glass, salt samples.',
            'Principle: heat excites the electrons, and each metal emits its own colour when they fall back.',
            'Clean the wire by dipping it in concentrated HCl and heating until the flame is colourless.',
            'Moisten a little of the solid sample with HCl on the watch glass.',
            'Dip the clean loop in the paste and hold it in the non-luminous blue flame.',
            'Note the colour: sodium yellow, potassium lilac, calcium brick red, copper blue-green.',
            'Look at potassium through blue cobalt glass, which hides the yellow sodium glare.',
            'Clean the loop again between every sample, or the colours mix.',
            'Precautions: use a very small amount, keep away from flammable solvents, tie back hair.',
            'Error sources: a dirty loop, too much sample, sodium contamination from fingers or glassware.',
            'Viva: the flame test identifies the metal cation, not the anion.',
        ],
        'bn': [
            'উদ্দেশ্য: লবণের ধাতব আয়ন শিখার রং থেকে শনাক্তকরণ।',
            'যন্ত্রপাতি: বুনসেন বার্নার, নাইক্রোম বা প্লাটিনাম তারের ফাঁস, গাঢ় HCl, ওয়াচ গ্লাস, লবণের নমুনা।',
            'নীতি: তাপে ইলেকট্রন উত্তেজিত হয় এবং ফিরে আসার সময় প্রতিটি ধাতু নিজস্ব রং দেয়।',
            'তারটি গাঢ় HCl-এ ডুবিয়ে শিখা বর্ণহীন হওয়া পর্যন্ত গরম করে পরিষ্কার করুন।',
            'ওয়াচ গ্লাসে সামান্য কঠিন নমুনা HCl দিয়ে ভিজিয়ে নিন।',
            'পরিষ্কার ফাঁসটি পেস্টে ডুবিয়ে অদীপ্ত নীল শিখায় ধরুন।',
            'রং লিখুন: সোডিয়াম হলুদ, পটাশিয়াম বেগুনি, ক্যালসিয়াম ইটের মতো লাল, কপার নীল-সবুজ।',
            'পটাশিয়ামের বেগুনি দেখতে নীল কোবাল্ট কাচ ব্যবহার করুন, যা সোডিয়ামের হলুদ ঝলক ঢাকে।',
            'প্রতিটি নমুনার পরে ফাঁস আবার পরিষ্কার করুন, নইলে রং মিশে যাবে।',
            'সতর্কতা: খুব সামান্য নমুনা নিন, দাহ্য দ্রাবক থেকে দূরে রাখুন, চুল বাঁধুন।',
            'ভুলের উৎস: নোংরা ফাঁস, বেশি নমুনা, হাত বা কাচ থেকে সোডিয়ামের দূষণ।',
            'ভাইভা: শিখা পরীক্ষা ধাতব ক্যাটায়ন শনাক্ত করে, অ্যানায়ন নয়।',
        ],
    },
    'chemistry-filtration-school': {
        'en': [
            'Aim: separate an insoluble solid from a liquid by filtration.',
            'Apparatus: filter paper, funnel, funnel stand, beaker, glass rod, the mixture.',
            'Principle: the paper’s pores let liquid through but hold back solid particles.',
            'Fold the filter paper in half, then in quarters, and open it into a cone.',
            'Fit the cone into the funnel so it has three layers on one side and one on the other.',
            'Moisten the paper with a little water so it sticks to the funnel wall.',
            'Place the funnel stem against the receiving beaker to stop splashing.',
            'Pour the mixture slowly down the glass rod, never above the paper edge.',
            'The solid left on the paper is the residue; the liquid collected is the filtrate.',
            'Wash the residue with a little clean solvent if the filtrate matters.',
            'Precautions: fill only two-thirds, keep the level below the paper rim, no stirring on the paper.',
            'Error sources: a torn paper, overfilling, pouring too fast and losing solid over the edge.',
        ],
        'bn': [
            'উদ্দেশ্য: ছাঁকন প্রক্রিয়ায় অদ্রবণীয় কঠিনকে তরল থেকে আলাদা করা।',
            'যন্ত্রপাতি: ফিল্টার কাগজ, ফানেল, ফানেল স্ট্যান্ড, বিকার, কাচদণ্ড, মিশ্রণ।',
            'নীতি: কাগজের ছিদ্র দিয়ে তরল চলে যায়, কঠিন কণা আটকে থাকে।',
            'ফিল্টার কাগজ অর্ধেক, তারপর চার ভাঁজ করে শঙ্কুর মতো খুলুন।',
            'ফানেলে বসান যেন এক পাশে তিন স্তর ও অন্য পাশে এক স্তর থাকে।',
            'সামান্য পানি দিয়ে কাগজ ভিজিয়ে নিন যাতে ফানেলের গায়ে লেগে থাকে।',
            'ফানেলের নল গ্রাহক বিকারের গায়ে ঠেকিয়ে রাখুন, ছিটকে পড়বে না।',
            'কাচদণ্ড বেয়ে আস্তে মিশ্রণ ঢালুন, কাগজের কিনারার ওপরে নয়।',
            'কাগজে থেকে যাওয়া কঠিনই অবশেষ এবং জমা তরলই পরিশ্রুত।',
            'পরিশ্রুত গুরুত্বপূর্ণ হলে অবশেষ সামান্য পরিষ্কার দ্রাবক দিয়ে ধুয়ে নিন।',
            'সতর্কতা: দুই-তৃতীয়াংশের বেশি নয়, তলের উচ্চতা কাগজের কিনারার নিচে, কাগজে নাড়বেন না।',
            'ভুলের উৎস: ছেঁড়া কাগজ, বেশি ভরা, দ্রুত ঢেলে কিনারা দিয়ে কঠিন হারানো।',
        ],
    },
    'chemistry-evaporation-school': {
        'en': [
            'Aim: recover a dissolved solid from its solution by evaporation.',
            'Apparatus: evaporating dish, tripod, wire gauze, Bunsen burner, glass rod, beaker.',
            'Principle: heating drives off the solvent and leaves the non-volatile solute behind.',
            'Pour the solution into the evaporating dish, filling it no more than half.',
            'Heat gently on the gauze and stir with the glass rod to prevent bumping.',
            'Stop when crystals first appear on the rod — that is the saturation point.',
            'Let the remaining liquid evaporate slowly, or cool it to get bigger crystals.',
            'Weigh the empty dish first, then the dish with the dry solid, and subtract.',
            'Mass of solid $=$ mass of dish with solid $-$ mass of empty dish.',
            'Use the original volume of solution to report the concentration in $\\mathrm{g/L}$.',
            'Precautions: no naked flame directly on the dish, wear goggles, never evaporate to dryness over a strong flame.',
            'Error sources: spattering, solid left on the rod, an incompletely dry dish, soot on the outside.',
        ],
        'bn': [
            'উদ্দেশ্য: বাষ্পীভবন করে দ্রবণ থেকে দ্রবীভূত কঠিন ফিরে পাওয়া।',
            'যন্ত্রপাতি: বাষ্পীভবন পাত্র, ট্রাইপড, তারের গজ, বুনসেন বার্নার, কাচদণ্ড, বিকার।',
            'নীতি: তাপ দিলে দ্রাবক উড়ে যায় এবং অস্থির নয় এমন দ্রব অবশিষ্ট থাকে।',
            'দ্রবণ বাষ্পীভবন পাত্রে ঢালুন, অর্ধেকের বেশি নয়।',
            'গজের ওপর মৃদু তাপ দিয়ে কাচদণ্ডে নাড়ুন, যাতে লাফিয়ে ছিটকে না পড়ে।',
            'দণ্ডে প্রথম স্ফটিক দেখা দিলে থামুন — এটিই সম্পৃক্ত অবস্থা।',
            'বাকি তরল আস্তে বাষ্পীভূত হতে দিন, অথবা ঠান্ডা করে বড় স্ফটিক নিন।',
            'আগে খালি পাত্রের ভর নিন, তারপর কঠিনসহ পাত্রের ভর নিয়ে বিয়োগ করুন।',
            'কঠিনের ভর $=$ কঠিনসহ পাত্রের ভর $-$ খালি পাত্রের ভর।',
            'মূল দ্রবণের আয়তন ব্যবহার করে ঘনমাত্রা $\\mathrm{g/L}$-এ লিখুন।',
            'সতর্কতা: পাত্রে সরাসরি শিখা নয়, চশমা পরুন, তীব্র শিখায় শুকিয়ে ফেলবেন না।',
            'ভুলের উৎস: ছিটকে পড়া, দণ্ডে লেগে থাকা কঠিন, না শুকানো পাত্র, বাইরে ছাই জমা।',
        ],
    },
    'chemistry-distillation-school': {
        'en': [
            'Aim: separate a pure liquid from a solution by simple distillation.',
            'Apparatus: round-bottom flask, thermometer, Liebig condenser, adapter, receiver, heat source, anti-bumping granules.',
            'Principle: the liquid vaporises, the vapour is cooled in the condenser and collected as distillate.',
            'Fill the flask between one third and two thirds — never more than two thirds.',
            'Add anti-bumping granules so the liquid boils smoothly.',
            'Put the thermometer bulb level with the side arm, where the vapour leaves.',
            'Run condenser water in at the bottom and out at the top for full cooling.',
            'Heat gently and note the constant boiling temperature of the distillate.',
            'Stop before the flask runs dry; the residue stays behind.',
            'Compare the distillate’s boiling point with the accepted value to judge purity.',
            'Precautions: never seal the apparatus, no open flame with flammable liquids, use a water bath instead.',
            'Error sources: a wrongly placed thermometer, fast heating, leaking joints, no cooling water flow.',
        ],
        'bn': [
            'উদ্দেশ্য: সরল পাতন প্রক্রিয়ায় দ্রবণ থেকে বিশুদ্ধ তরল আলাদা করা।',
            'যন্ত্রপাতি: গোলতল ফ্লাস্ক, তাপমাপক, লিবিগ কনডেনসার, অ্যাডাপ্টার, গ্রাহক পাত্র, তাপ উৎস, অ্যান্টি-বাম্পিং দানা।',
            'নীতি: তরল বাষ্প হয়, বাষ্প কনডেনসারে ঠান্ডা হয়ে পাতিত রূপে জমা হয়।',
            'ফ্লাস্ক এক-তৃতীয়াংশ থেকে দুই-তৃতীয়াংশ পর্যন্ত ভরুন, এর বেশি নয়।',
            'অ্যান্টি-বাম্পিং দানা দিন যাতে তরল মসৃণভাবে ফোটে।',
            'তাপমাপকের বাল্ব পার্শ্বনলের সমান উচ্চতায় রাখুন, যেখানে বাষ্প বের হয়।',
            'কনডেনসারে পানি নিচ দিয়ে ঢুকিয়ে ওপর দিয়ে বের করুন, যাতে পুরোপুরি ঠান্ডা হয়।',
            'মৃদু তাপ দিয়ে পাতিত অংশের স্থির স্ফুটনাঙ্ক লিখুন।',
            'ফ্লাস্ক শুকিয়ে যাওয়ার আগেই থামুন; অবশেষ থেকে যাবে।',
            'বিশুদ্ধতা বিচারে পাতিতের স্ফুটনাঙ্ককে স্বীকৃত মানের সঙ্গে তুলনা করুন।',
            'সতর্কতা: যন্ত্র কখনো সম্পূর্ণ বন্ধ করবেন না, দাহ্য তরলে খোলা শিখা নয়, পানি-স্নান ব্যবহার করুন।',
            'ভুলের উৎস: ভুল জায়গায় তাপমাপক, দ্রুত তাপ, ফাঁকা জোড়া, কনডেনসারে পানি না চলা।',
        ],
    },
    'chemistry-chromatography-school': {
        'en': [
            'Aim: separate the components of a mixture by paper chromatography.',
            'Apparatus: chromatography paper, beaker with lid, pencil, capillary tube, ruler, solvent, ink or dye samples.',
            'Principle: components travel at different speeds because they differ in solubility and in how strongly they stick to the paper.',
            'Draw the start line in pencil, not pen, since pencil graphite does not move.',
            'Mark small spots with a capillary tube and let each one dry before the next.',
            'Pour solvent into the beaker so its level is below the start line.',
            'Hang the paper straight and cover the beaker to keep the solvent saturated.',
            'Stop when the solvent front is about $1\\ \\mathrm{cm}$ from the top and mark that line.',
            'Calculate $R_f = \\dfrac{\\text{distance moved by the spot}}{\\text{distance moved by the solvent front}}$.',
            'Each $R_f$ is between 0 and 1 and is fixed for a given solvent and temperature.',
            'Precautions: do not let the spot dip into the solvent, do not shake the beaker, dry the paper before measuring.',
            'Error sources: spots too large, solvent touching the spot, measuring to a fuzzy edge, a tilted paper.',
        ],
        'bn': [
            'উদ্দেশ্য: কাগজ ক্রোম্যাটোগ্রাফিতে মিশ্রণের উপাদান আলাদা করা।',
            'যন্ত্রপাতি: ক্রোম্যাটোগ্রাফি কাগজ, ঢাকনাসহ বিকার, পেন্সিল, কৈশিক নল, স্কেল, দ্রাবক, কালি বা রঙের নমুনা।',
            'নীতি: দ্রাব্যতা ও কাগজে আটকে থাকার তারতম্যে উপাদানগুলো ভিন্ন বেগে চলে।',
            'শুরুর রেখা পেন্সিলে আঁকুন, কলমে নয়, কারণ পেন্সিলের গ্রাফাইট সরে না।',
            'কৈশিক নল দিয়ে ছোট দাগ দিন এবং প্রতিটি শুকিয়ে পরেরটি দিন।',
            'বিকারে দ্রাবক ঢালুন যেন তল শুরুর রেখার নিচে থাকে।',
            'কাগজ সোজা ঝুলিয়ে বিকার ঢেকে রাখুন, যাতে দ্রাবক বাষ্পে পরিপূর্ণ থাকে।',
            'দ্রাবক সম্মুখ ওপর থেকে প্রায় $1\\ \\mathrm{cm}$ দূরে এলে থামুন এবং রেখাটি চিহ্নিত করুন।',
            '$R_f$ বের করুন: দাগের অতিক্রান্ত দূরত্বকে দ্রাবক সম্মুখের অতিক্রান্ত দূরত্ব দিয়ে ভাগ করুন।',
            'প্রতিটি $R_f$ ০ থেকে ১-এর মধ্যে এবং নির্দিষ্ট দ্রাবক ও তাপমাত্রায় ধ্রুব।',
            'সতর্কতা: দাগ যেন দ্রাবকে না ডোবে, বিকার নাড়বেন না, মাপার আগে কাগজ শুকান।',
            'ভুলের উৎস: বড় দাগ, দ্রাবকের স্পর্শে দাগ, ঝাপসা কিনারা মাপা, হেলে থাকা কাগজ।',
        ],
    },
    'chemistry-acid-base-indicators-school': {
        'en': [
            'Aim: test unknown solutions with natural and synthetic acid–base indicators.',
            'Apparatus: test tubes and rack, droppers, litmus paper, methyl orange, phenolphthalein, plant extracts, sample solutions.',
            'Principle: an indicator is a weak acid or base whose two forms have different colours.',
            'Litmus turns red in acid and blue in base; it only says which, not how strong.',
            'Methyl orange is red in acid, yellow in base and orange in between.',
            'Phenolphthalein is colourless in acid and pink in base.',
            'Make a natural indicator by crushing red cabbage or hibiscus in warm water.',
            'Add one or two drops of indicator only — too much shifts the colour.',
            'Use a fresh dropper or rinse it between samples so nothing is carried over.',
            'Record every colour in a table and group the samples as acid, base or neutral.',
            'Precautions: never taste the samples, wash hands after handling, keep droppers in their own bottle.',
            'Error sources: contaminated droppers, too much indicator, judging colour against a bright background.',
        ],
        'bn': [
            'উদ্দেশ্য: প্রাকৃতিক ও কৃত্রিম অ্যাসিড-ক্ষারক নির্দেশক দিয়ে অজানা দ্রবণ পরীক্ষা।',
            'যন্ত্রপাতি: টেস্টটিউব ও র‍্যাক, ড্রপার, লিটমাস কাগজ, মিথাইল অরেঞ্জ, ফিনফথ্যালিন, উদ্ভিদ নির্যাস, নমুনা দ্রবণ।',
            'নীতি: নির্দেশক এক ধরনের দুর্বল অ্যাসিড বা ক্ষারক, যার দুই রূপের রং আলাদা।',
            'লিটমাস অ্যাসিডে লাল ও ক্ষারকে নীল হয়; এটি শুধু কোনটি তা বলে, কতটা তীব্র তা নয়।',
            'মিথাইল অরেঞ্জ অ্যাসিডে লাল, ক্ষারকে হলুদ এবং মাঝখানে কমলা।',
            'ফিনফথ্যালিন অ্যাসিডে বর্ণহীন ও ক্ষারকে গোলাপি।',
            'লাল বাঁধাকপি বা জবা ফুল কুচি উষ্ণ পানিতে পিষে প্রাকৃতিক নির্দেশক বানান।',
            'মাত্র এক-দুই ফোঁটা নির্দেশক দিন — বেশি দিলে রং বদলে যায়।',
            'নতুন ড্রপার ব্যবহার করুন বা প্রতিবার ধুয়ে নিন, যাতে নমুনা মিশে না যায়।',
            'প্রতিটি রং সারণিতে লিখে নমুনাগুলোকে অ্যাসিড, ক্ষারক বা নিরপেক্ষ ধরে ভাগ করুন।',
            'সতর্কতা: নমুনার স্বাদ নেবেন না, হাত ধুয়ে নিন, ড্রপার নিজের বোতলেই রাখুন।',
            'ভুলের উৎস: দূষিত ড্রপার, বেশি নির্দেশক, উজ্জ্বল পটভূমিতে রং বিচার।',
        ],
    },
    'chemistry-ph-universal-indicator-school': {
        'en': [
            'Aim: estimate the pH of common solutions with universal indicator and a pH scale.',
            'Apparatus: test tubes, dropper, universal indicator solution or paper, colour chart, sample solutions.',
            'Definition: $\\mathrm{pH}=-\\log_{10}[\\mathrm{H^+}]$, so pH 7 is neutral, below 7 acidic and above 7 basic.',
            'Each pH unit means a tenfold change in hydrogen ion concentration.',
            'Place a small volume of the sample in a clean test tube or on a spot plate.',
            'Add two or three drops of universal indicator and swirl gently.',
            'Match the colour against the chart in daylight, not under coloured light.',
            'With indicator paper, dip it briefly and compare while it is still damp.',
            'Test household samples: lemon juice, vinegar, soap solution, salt water, baking soda solution.',
            'Record pH and label each sample as strongly acidic, weakly acidic, neutral, weakly basic or strongly basic.',
            'Precautions: clean glassware, no contamination between samples, do not reuse paper strips.',
            'Error sources: colour-matching by eye, dirty tubes, a faded chart, concentrated samples giving odd colours.',
        ],
        'bn': [
            'উদ্দেশ্য: ইউনিভার্সাল নির্দেশক ও pH স্কেল দিয়ে সাধারণ দ্রবণের pH অনুমান।',
            'যন্ত্রপাতি: টেস্টটিউব, ড্রপার, ইউনিভার্সাল নির্দেশক দ্রবণ বা কাগজ, রঙের চার্ট, নমুনা দ্রবণ।',
            'সংজ্ঞা: $\\mathrm{pH}=-\\log_{10}[\\mathrm{H^+}]$, তাই pH ৭ নিরপেক্ষ, ৭-এর নিচে অম্লীয় ও ৭-এর ওপরে ক্ষারীয়।',
            'pH-এর এক একক বদলালে হাইড্রোজেন আয়নের ঘনমাত্রা দশ গুণ বদলায়।',
            'পরিষ্কার টেস্টটিউব বা স্পট প্লেটে নমুনার সামান্য অংশ নিন।',
            'দুই-তিন ফোঁটা ইউনিভার্সাল নির্দেশক দিয়ে আস্তে নাড়ুন।',
            'রঙিন আলোর বদলে দিনের আলোয় চার্টের সঙ্গে রং মেলান।',
            'নির্দেশক কাগজ হলে সামান্য ডুবিয়ে ভেজা অবস্থায়ই তুলনা করুন।',
            'ঘরোয়া নমুনা পরীক্ষা করুন: লেবুর রস, ভিনেগার, সাবান দ্রবণ, লবণ পানি, বেকিং সোডা দ্রবণ।',
            'pH লিখে প্রতিটিকে তীব্র অম্লীয়, মৃদু অম্লীয়, নিরপেক্ষ, মৃদু ক্ষারীয় বা তীব্র ক্ষারীয় হিসেবে চিহ্নিত করুন।',
            'সতর্কতা: পরিষ্কার কাচের যন্ত্র, নমুনায় নমুনায় দূষণ নয়, কাগজের ফালি দুইবার নয়।',
            'ভুলের উৎস: চোখে রং মেলানো, নোংরা টিউব, বিবর্ণ চার্ট, ঘন নমুনার অস্বাভাবিক রং।',
        ],
    },
    'chemistry-prepare-test-common-gases-school': {
        'en': [
            'Aim: prepare oxygen, carbon dioxide and hydrogen in the lab and confirm each with its test.',
            'Apparatus: conical flask with thistle funnel and delivery tube, trough, test tubes, splints, reagents.',
            'Oxygen: hydrogen peroxide decomposes with manganese(IV) oxide as a catalyst, $2\\mathrm{H_2O_2} \\rightarrow 2\\mathrm{H_2O} + \\mathrm{O_2}$.',
            'Oxygen test: a glowing splint rekindles and bursts into flame.',
            'Carbon dioxide: dilute HCl on marble chips, $\\mathrm{CaCO_3} + 2\\mathrm{HCl} \\rightarrow \\mathrm{CaCl_2} + \\mathrm{H_2O} + \\mathrm{CO_2}$.',
            'Carbon dioxide test: it turns limewater milky, and the milkiness disappears with excess gas.',
            'Hydrogen: dilute HCl on zinc granules, $\\mathrm{Zn} + 2\\mathrm{HCl} \\rightarrow \\mathrm{ZnCl_2} + \\mathrm{H_2}$.',
            'Hydrogen test: a lit splint at the tube mouth gives a sharp squeaky pop.',
            'Collect oxygen and hydrogen over water; carbon dioxide dissolves, so collect it by upward delivery.',
            'Hydrogen is lighter than air, so keep its tube inverted; carbon dioxide is heavier, so keep it upright.',
            'Precautions: work in a ventilated area, no flames near hydrogen, wear goggles, add acid slowly.',
            'Error sources: leaks in the apparatus, contaminated reagents, testing before the air is displaced.',
        ],
        'bn': [
            'উদ্দেশ্য: পরীক্ষাগারে অক্সিজেন, কার্বন ডাই-অক্সাইড ও হাইড্রোজেন তৈরি করে নিজ নিজ পরীক্ষায় শনাক্তকরণ।',
            'যন্ত্রপাতি: থিসল ফানেল ও নির্গমন নলসহ কোনিক্যাল ফ্লাস্ক, ট্রাফ, টেস্টটিউব, কাঠি, বিকারক।',
            'অক্সিজেন: ম্যাঙ্গানিজ(IV) অক্সাইড প্রভাবক রেখে হাইড্রোজেন পারক্সাইড ভাঙে, $2\\mathrm{H_2O_2} \\rightarrow 2\\mathrm{H_2O} + \\mathrm{O_2}$।',
            'অক্সিজেন পরীক্ষা: দগ্ধ কাঠি আবার জ্বলে ওঠে এবং শিখা ধরে।',
            'কার্বন ডাই-অক্সাইড: মার্বেল চিপসে লঘু HCl, $\\mathrm{CaCO_3} + 2\\mathrm{HCl} \\rightarrow \\mathrm{CaCl_2} + \\mathrm{H_2O} + \\mathrm{CO_2}$।',
            'কার্বন ডাই-অক্সাইড পরীক্ষা: চুনের পানি ঘোলা হয় এবং অতিরিক্ত গ্যাসে ঘোলা ভাব মিলিয়ে যায়।',
            'হাইড্রোজেন: দস্তা কুচিতে লঘু HCl, $\\mathrm{Zn} + 2\\mathrm{HCl} \\rightarrow \\mathrm{ZnCl_2} + \\mathrm{H_2}$।',
            'হাইড্রোজেন পরীক্ষা: নলের মুখে জ্বলন্ত কাঠি ধরলে তীক্ষ্ণ ‘পপ’ শব্দ হয়।',
            'অক্সিজেন ও হাইড্রোজেন পানির ওপর দিয়ে সংগ্রহ করুন; কার্বন ডাই-অক্সাইড দ্রবণীয় বলে তা ঊর্ধ্বমুখী নির্গমনে নিন।',
            'হাইড্রোজেন বাতাসের চেয়ে হালকা বলে নল উল্টো রাখুন; কার্বন ডাই-অক্সাইড ভারী বলে সোজা রাখুন।',
            'সতর্কতা: বায়ুচলাচল আছে এমন জায়গায় কাজ করুন, হাইড্রোজেনের কাছে শিখা নয়, চশমা পরুন, অ্যাসিড আস্তে ঢালুন।',
            'ভুলের উৎস: যন্ত্রে ফুটো, দূষিত বিকারক, বাতাস সরানোর আগেই পরীক্ষা করা।',
        ],
    },
    'chemistry-rusting-school': {
        'en': [
            'Aim: find out what conditions iron needs to rust.',
            'Apparatus: three test tubes, iron nails, water, boiled water, oil, calcium chloride, cotton wool, rubber stoppers.',
            'Rusting is oxidation of iron in the presence of both oxygen and water, giving hydrated iron(III) oxide.',
            'Tube A: nail in ordinary water, open to air — both air and water present.',
            'Tube B: nail in boiled water covered with a layer of oil — water but no dissolved air.',
            'Tube C: nail with anhydrous calcium chloride and a cotton plug — dry air but no water.',
            'Leave all three tubes in the same place, watch them daily for several days and record where the reddish-brown coating appears.',
            'Only tube A rusts well, which shows that both oxygen and water are needed.',
            'Compare with a fourth tube holding salt water to see how salt speeds up rusting.',
            'Prevention: paint, grease, galvanising with zinc, or making stainless steel with chromium.',
            'Precautions: use clean uncoated nails, keep the tubes labelled, do not shake them.',
            'Error sources: oil layer too thin, damp calcium chloride, nails already coated, short observation time.',
        ],
        'bn': [
            'উদ্দেশ্য: লোহা মরিচা ধরতে কোন কোন শর্ত লাগে তা বের করা।',
            'যন্ত্রপাতি: তিনটি টেস্টটিউব, লোহার পেরেক, পানি, ফুটানো পানি, তেল, ক্যালসিয়াম ক্লোরাইড, তুলা, রাবার ছিপি।',
            'মরিচা ধরা হলো অক্সিজেন ও পানি দুটোর উপস্থিতিতে লোহার জারণ, যা থেকে জলযুক্ত আয়রন(III) অক্সাইড হয়।',
            'টিউব ক: সাধারণ পানিতে পেরেক, মুখ খোলা — বাতাস ও পানি দুটোই আছে।',
            'টিউব খ: ফুটানো পানিতে পেরেক এবং ওপরে তেলের স্তর — পানি আছে, দ্রবীভূত বাতাস নেই।',
            'টিউব গ: অনার্দ্র ক্যালসিয়াম ক্লোরাইড ও তুলার ছিপিসহ পেরেক — শুকনো বাতাস, পানি নেই।',
            'তিনটি টিউব একই জায়গায় না নাড়াচাড়া করে রাখুন, কয়েকদিন প্রতিদিন দেখুন এবং কোথায় লালচে-বাদামি আস্তরণ পড়ছে তা লিখুন।',
            'শুধু টিউব ক ভালোভাবে মরিচা ধরে, যা প্রমাণ করে অক্সিজেন ও পানি দুটোই দরকার।',
            'চতুর্থ টিউবে লবণ পানি রেখে দেখুন লবণ কীভাবে মরিচা দ্রুত করায়।',
            'প্রতিরোধ: রং, গ্রিজ, দস্তা দিয়ে গ্যালভানাইজিং, অথবা ক্রোমিয়াম যোগে স্টেইনলেস স্টিল তৈরি।',
            'সতর্কতা: পরিষ্কার অনাবৃত পেরেক নিন, টিউব চিহ্নিত রাখুন, ঝাঁকাবেন না।',
            'ভুলের উৎস: পাতলা তেলের স্তর, ভেজা ক্যালসিয়াম ক্লোরাইড, আগেই আবৃত পেরেক, কম পর্যবেক্ষণ সময়।',
        ],
    },
    'chemistry-electrolysis-water-cuso4-school': {
        'en': [
            'Aim: observe the electrolysis of acidified water and of copper(II) sulfate solution.',
            'Apparatus: Hoffman voltameter or beaker with carbon electrodes, battery, wires, dilute sulfuric acid, CuSO₄ solution, copper strips.',
            'Principle: direct current forces a non-spontaneous chemical change; oxidation at the anode, reduction at the cathode.',
            'Water: $2\\mathrm{H_2O} \\rightarrow 2\\mathrm{H_2} + \\mathrm{O_2}$, so hydrogen volume is twice the oxygen volume.',
            'Collect the gases in the two limbs and test them with a burning and a glowing splint.',
            'Copper sulfate with carbon electrodes: copper deposits on the cathode and the blue colour fades.',
            'Copper sulfate with copper electrodes: the cathode gains mass and the anode loses the same mass.',
            'Weigh the copper electrodes before and after to show the transfer of copper.',
            'Note the current and the time; a larger charge deposits more copper.',
            'Record observations in a table: electrode, product, colour change, volume or mass.',
            'Precautions: do not short the battery, keep electrodes apart, no touching bare wires, ventilate hydrogen away from flames.',
            'Error sources: electrode corrosion, gas dissolving, wet electrodes when weighing, unequal electrode areas.',
        ],
        'bn': [
            'উদ্দেশ্য: অম্লীয় পানি ও কপার(II) সালফেট দ্রবণের তড়িৎ বিশ্লেষণ পর্যবেক্ষণ।',
            'যন্ত্রপাতি: হফম্যান ভল্টামিটার বা কার্বন তড়িৎদ্বারসহ বিকার, ব্যাটারি, তার, লঘু সালফিউরিক অ্যাসিড, CuSO₄ দ্রবণ, তামার ফালি।',
            'নীতি: একমুখী প্রবাহ অস্বতঃস্ফূর্ত নয় এমন রাসায়নিক পরিবর্তন ঘটায়; অ্যানোডে জারণ, ক্যাথোডে বিজারণ।',
            'পানি: $2\\mathrm{H_2O} \\rightarrow 2\\mathrm{H_2} + \\mathrm{O_2}$, তাই হাইড্রোজেনের আয়তন অক্সিজেনের দ্বিগুণ।',
            'দুই বাহুতে গ্যাস জমিয়ে জ্বলন্ত ও দগ্ধ কাঠি দিয়ে পরীক্ষা করুন।',
            'কার্বন তড়িৎদ্বারে কপার সালফেট: ক্যাথোডে তামা জমে এবং নীল রং ফ্যাকাসে হয়।',
            'তামার তড়িৎদ্বারে: ক্যাথোডের ভর বাড়ে এবং অ্যানোডের ঠিক ততটুকু ভর কমে।',
            'তামার স্থানান্তর দেখাতে তড়িৎদ্বার দুটির আগে ও পরের ভর নিন।',
            'প্রবাহ ও সময় লিখে রাখুন; বেশি আধান বেশি তামা জমায়।',
            'পর্যবেক্ষণ সারণিতে লিখুন: তড়িৎদ্বার, উৎপাদ, রঙের পরিবর্তন, আয়তন বা ভর।',
            'সতর্কতা: ব্যাটারি শর্ট নয়, তড়িৎদ্বার আলাদা রাখুন, খালি তারে হাত নয়, হাইড্রোজেন শিখা থেকে দূরে রাখুন।',
            'ভুলের উৎস: তড়িৎদ্বারের ক্ষয়, গ্যাস দ্রবীভূত হওয়া, ভেজা তড়িৎদ্বার ওজন, অসমান তড়িৎদ্বার ক্ষেত্রফল।',
        ],
    },
    'chemistry-electroplating-school': {
        'en': [
            'Aim: electroplate a metal object with copper.',
            'Apparatus: beaker, copper(II) sulfate solution with a little dilute sulfuric acid, copper plate, iron key or spoon, battery, wires, sandpaper.',
            'Principle: the object to be plated is made the cathode, so copper ions are reduced onto it.',
            'Clean the object with sandpaper, then rinse it so the coating sticks evenly.',
            'Make up the plating bath and note its concentration and temperature.',
            'Connect the object to the negative terminal and the copper plate to the positive terminal.',
            'Both electrodes must be well immersed and must not touch each other.',
            'Pass a small steady current for a few minutes; a large current gives a loose, powdery layer.',
            'Watch the pink-brown layer grow, then rinse, dry and weigh the object to estimate the copper deposited.',
            'Record the current and time, since deposited mass grows with the total charge.',
            'Precautions: gloves and goggles, no bare-hand contact with the bath, wash the object afterwards.',
            'Error sources: greasy or oxidised surface, touching electrodes, current too high, plating time too short.',
        ],
        'bn': [
            'উদ্দেশ্য: একটি ধাতব বস্তুতে তামার প্রলেপ দেওয়া।',
            'যন্ত্রপাতি: বিকার, সামান্য লঘু সালফিউরিক অ্যাসিডসহ কপার(II) সালফেট দ্রবণ, তামার পাত, লোহার চাবি বা চামচ, ব্যাটারি, তার, স্যান্ডপেপার।',
            'নীতি: যে বস্তুতে প্রলেপ দেওয়া হবে তাকে ক্যাথোড বানানো হয়, ফলে কপার আয়ন তার ওপর বিজারিত হয়।',
            'বস্তুটি স্যান্ডপেপারে পরিষ্কার করে ধুয়ে নিন, যাতে প্রলেপ সমানভাবে লাগে।',
            'প্রলেপ দ্রবণ তৈরি করে তার ঘনমাত্রা ও তাপমাত্রা লিখুন।',
            'বস্তুকে ঋণাত্মক প্রান্তে এবং তামার পাতকে ধনাত্মক প্রান্তে যুক্ত করুন।',
            'দুই তড়িৎদ্বারই ভালোভাবে নিমজ্জিত থাকবে এবং একে অপরকে ছোঁবে না।',
            'কয়েক মিনিট সামান্য স্থির প্রবাহ চালান; বেশি প্রবাহে আলগা গুঁড়ো স্তর জমে।',
            'গোলাপি-বাদামি স্তর বাড়তে দেখুন, তারপর ধুয়ে শুকিয়ে ওজন নিয়ে জমা তামার ভর অনুমান করুন।',
            'প্রবাহ ও সময় লিখুন, কারণ মোট আধানের সঙ্গে জমা ভর বাড়ে।',
            'সতর্কতা: গ্লাভস ও চশমা পরুন, খালি হাতে দ্রবণে ছোঁবেন না, কাজ শেষে বস্তু ধুয়ে নিন।',
            'ভুলের উৎস: চর্বিযুক্ত বা জারিত তল, তড়িৎদ্বারে স্পর্শ, অতিরিক্ত প্রবাহ, কম সময় ধরে প্রলেপ।',
        ],
    },
    'chemistry-reactivity-series-school': {
        'en': [
            'Aim: arrange metals in order of reactivity using displacement reactions.',
            'Apparatus: test tubes, metal strips of magnesium, zinc, iron, copper, solutions of their sulfates, sandpaper, droppers.',
            'Principle: a more reactive metal displaces a less reactive metal from its salt solution.',
            'Clean every metal strip with sandpaper so the oxide layer does not block the reaction.',
            'Place a strip of one metal into the salt solution of another, one tube at a time.',
            'Note any colour change, coating on the strip, or temperature change.',
            'Zinc in copper sulfate turns the blue solution paler and coats the strip brown; copper in zinc sulfate shows no change.',
            'Complete the whole grid of metal against solution and build a table of yes/no results.',
            'Order the metals from the results; magnesium is most reactive and copper least.',
            'Predict what will happen for a new pair before testing it, then check.',
            'Precautions: label every tube, keep metals dry between tests, do not taste or touch solutions.',
            'Error sources: unclean metal surfaces, dilute solutions, too short a waiting time, cross-contaminated droppers.',
        ],
        'bn': [
            'উদ্দেশ্য: প্রতিস্থাপন বিক্রিয়া ব্যবহার করে ধাতুগুলোকে সক্রিয়তা অনুসারে সাজানো।',
            'যন্ত্রপাতি: টেস্টটিউব, ম্যাগনেসিয়াম, দস্তা, লোহা ও তামার ফালি, তাদের সালফেট দ্রবণ, স্যান্ডপেপার, ড্রপার।',
            'নীতি: অধিক সক্রিয় ধাতু কম সক্রিয় ধাতুকে তার লবণ দ্রবণ থেকে প্রতিস্থাপন করে।',
            'প্রতিটি ধাতুর ফালি স্যান্ডপেপারে পরিষ্কার করুন, যাতে অক্সাইড স্তর বিক্রিয়া আটকে না দেয়।',
            'একটি ধাতুর ফালি অন্য ধাতুর লবণ দ্রবণে দিন, একবারে একটি টিউবে।',
            'রঙের পরিবর্তন, ফালিতে আস্তরণ বা তাপমাত্রার পরিবর্তন লিখুন।',
            'কপার সালফেটে দস্তা দিলে নীল দ্রবণ ফ্যাকাসে হয় ও ফালিতে বাদামি আস্তরণ পড়ে, কিন্তু দস্তা সালফেটে তামায় কিছুই হয় না।',
            'পুরো গ্রিড (ধাতু বনাম দ্রবণ) সম্পন্ন করে হ্যাঁ/না ফলের একটি সারণি বানান।',
            'ফল থেকে ধাতুগুলোকে সাজান; ম্যাগনেসিয়াম সর্বোচ্চ ও তামা সর্বনিম্ন সক্রিয়।',
            'নতুন জোড়ার জন্য পরীক্ষার আগেই ফলাফল অনুমান করুন, তারপর মিলিয়ে দেখুন।',
            'সতর্কতা: প্রতিটি টিউব চিহ্নিত করুন, পরীক্ষার মাঝে ধাতু শুকনো রাখুন, দ্রবণে স্বাদ বা স্পর্শ নয়।',
            'ভুলের উৎস: নোংরা ধাতুতল, লঘু দ্রবণ, কম অপেক্ষার সময়, ড্রপারে এক নমুনা থেকে অন্যটি যাওয়া।',
        ],
    },
    'chemistry-neutralisation-school': {
        'en': [
            'Aim: study the neutralisation of an acid by a base and find the end point.',
            'Apparatus: burette, pipette, conical flask, stand, dilute HCl, dilute NaOH, phenolphthalein or methyl orange, white tile.',
            'General reaction: $\\text{acid} + \\text{base} \\rightarrow \\text{salt} + \\text{water}$, for example $\\mathrm{HCl} + \\mathrm{NaOH} \\rightarrow \\mathrm{NaCl} + \\mathrm{H_2O}$.',
            'A neutralisation is also an exothermic reaction, so the mixture warms slightly.',
            'Rinse the burette with the acid it will hold, then fill it and remove the air bubble.',
            'Pipette a fixed volume of the base into the flask and add two drops of indicator.',
            'Add acid slowly while swirling, with the flask on a white tile, and stop at the first permanent colour change.',
            'Record the burette reading and repeat until two readings agree within $0.1\\ \\mathrm{cm^3}$.',
            'Use $c_aV_a = c_bV_b$ with the stoichiometric ratio to find the unknown concentration.',
            'Plot temperature against volume added to locate the end point from the peak.',
            'Precautions: no air bubbles in the jet, read at the meniscus, rinse between trials, wear goggles.',
            'Error sources: overshooting the end point, parallax on the burette, an unwashed flask, indicator added in excess.',
        ],
        'bn': [
            'উদ্দেশ্য: ক্ষারক দ্বারা অ্যাসিডের প্রশমন এবং সমাপ্তি বিন্দু নির্ণয়।',
            'যন্ত্রপাতি: বুরেট, পিপেট, কোনিক্যাল ফ্লাস্ক, স্ট্যান্ড, লঘু HCl, লঘু NaOH, ফিনফথ্যালিন বা মিথাইল অরেঞ্জ, সাদা টালি।',
            'সাধারণ বিক্রিয়া: $\\text{acid} + \\text{base} \\rightarrow \\text{salt} + \\text{water}$, যেমন $\\mathrm{HCl} + \\mathrm{NaOH} \\rightarrow \\mathrm{NaCl} + \\mathrm{H_2O}$।',
            'প্রশমন একটি তাপোৎপাদী বিক্রিয়াও, তাই মিশ্রণ সামান্য গরম হয়।',
            'বুরেটটি যে অ্যাসিড নেবে তা দিয়ে ধুয়ে নিন, তারপর ভরে নলের বাতাস বের করুন।',
            'পিপেট দিয়ে নির্দিষ্ট আয়তনের ক্ষারক ফ্লাস্কে নিয়ে দুই ফোঁটা নির্দেশক দিন।',
            'ফ্লাস্ক সাদা টালির ওপর রেখে নাড়তে নাড়তে আস্তে অ্যাসিড যোগ করুন এবং প্রথম স্থায়ী রং পরিবর্তনে থামুন।',
            'বুরেটের পাঠ লিখে পুনরাবৃত্তি করুন যতক্ষণ না দুই পাঠ $0.1\\ \\mathrm{cm^3}$-এর মধ্যে মেলে।',
            'স্টয়কিওমিতিক অনুপাতসহ $c_aV_a = c_bV_b$ ব্যবহার করে অজানা ঘনমাত্রা বের করুন।',
            'যোগ করা আয়তন বনাম তাপমাত্রা এঁকে শীর্ষবিন্দু থেকে সমাপ্তি বিন্দু নির্ণয় করুন।',
            'সতর্কতা: নলে বাতাসের বুদবুদ নয়, মেনিস্কাস বরাবর পাঠ, পরীক্ষার মাঝে ধুয়ে নেওয়া, চশমা পরা।',
            'ভুলের উৎস: সমাপ্তি বিন্দু পার হয়ে যাওয়া, বুরেটে দৃষ্টিভ্রম, না ধোয়া ফ্লাস্ক, অতিরিক্ত নির্দেশক।',
        ],
    },
    'chemistry-crystallisation-school': {
        'en': [
            'Aim: prepare pure crystals of a soluble salt by crystallisation.',
            'Apparatus: beaker, evaporating dish, glass rod, tripod, gauze, filter funnel, watch glass, balance.',
            'Principle: a hot saturated solution holds more solute; cooling it makes the excess come out as crystals.',
            'Dissolve the solid in the minimum amount of hot water, stirring continuously.',
            'Filter the hot solution to remove any insoluble impurity.',
            'Test saturation by dipping a cold glass rod — crystals should form on it.',
            'Cool slowly for large crystals, or quickly in ice water for many small ones.',
            'Cover the beaker with a watch glass so dust cannot fall in while it cools.',
            'Decant the mother liquor and dry the crystals between filter papers.',
            'Weigh the dry crystals and calculate the percentage yield, $\\text{mass obtained} \\div \\text{mass expected} \\times 100$.',
            'Precautions: do not boil to dryness, handle hot glassware with tongs, label the sample.',
            'Error sources: losing crystals on the rod and paper, incomplete drying, impurities trapped in the crystal.',
        ],
        'bn': [
            'উদ্দেশ্য: স্ফটিকায়ন প্রক্রিয়ায় দ্রবণীয় লবণের বিশুদ্ধ স্ফটিক তৈরি।',
            'যন্ত্রপাতি: বিকার, বাষ্পীভবন পাত্র, কাচদণ্ড, ট্রাইপড, গজ, ফিল্টার ফানেল, ওয়াচ গ্লাস, তুলা।',
            'নীতি: গরম সম্পৃক্ত দ্রবণ বেশি দ্রব ধরে রাখে; ঠান্ডা করলে অতিরিক্ত অংশ স্ফটিক হয়ে বেরিয়ে আসে।',
            'কমপক্ষে গরম পানিতে কঠিনটি দ্রবীভূত করুন এবং ক্রমাগত নাড়ুন।',
            'অদ্রবণীয় অপদ্রব্য সরাতে গরম দ্রবণটি ছেঁকে নিন।',
            'ঠান্ডা কাচদণ্ড ডুবিয়ে সম্পৃক্ততা যাচাই করুন — তাতে স্ফটিক জমার কথা।',
            'বড় স্ফটিকের জন্য ধীরে ঠান্ডা করুন, আর অনেক ছোট স্ফটিকের জন্য বরফ পানিতে দ্রুত।',
            'ঠান্ডা হওয়ার সময় ধুলা না পড়তে বিকারের ওপর ওয়াচ গ্লাস ঢেকে দিন।',
            'মাদার লিকার ঢেলে ফেলে স্ফটিকগুলো ফিল্টার কাগজের মাঝে শুকান।',
            'শুকনো স্ফটিকের ভর নিয়ে শুরুর কঠিনের ভরের সঙ্গে তুলনা করুন এবং শতকরা উৎপাদন $=$ (প্রাপ্ত ভর $\\div$ প্রত্যাশিত ভর) $\\times 100$ বের করুন।',
            'সতর্কতা: শুকিয়ে ফেলবেন না, গরম কাচ সামলাতে চিমটি ব্যবহার করুন, নমুনা চিহ্নিত করুন।',
            'ভুলের উৎস: দণ্ড ও কাগজে স্ফটিক হারানো, অসম্পূর্ণ শুকানো, স্ফটিকে আটকে থাকা অপদ্রব্য।',
        ],
    },
    'chemistry-water-hardness-school': {
        'en': [
            'Aim: compare the hardness of different water samples with a soap test.',
            'Apparatus: test tubes, measuring cylinder, standard soap solution, dropper, water samples, distilled water.',
            'Hardness comes from dissolved calcium and magnesium ions in the water.',
            'Hard water wastes soap because it forms an insoluble scum before it lathers.',
            'Measure an equal volume, such as $10\\ \\mathrm{cm^3}$, of each sample into separate tubes.',
            'Add soap solution drop by drop, shaking after each drop.',
            'Count the drops needed for a lather that lasts one minute, and run the same test on distilled water as the control.',
            'More drops means harder water; fewer drops means softer water.',
            'Boil one portion of a hard sample and repeat the test to show temporary hardness is removed.',
            'Permanent hardness stays after boiling and needs washing soda or an ion exchanger.',
            'Precautions: rinse the cylinder between samples, shake consistently, use the same soap solution throughout.',
            'Error sources: unequal volumes, inconsistent shaking, judging the lather by eye, a changed soap batch.',
        ],
        'bn': [
            'উদ্দেশ্য: সাবান পরীক্ষায় বিভিন্ন পানির নমুনার খরতা তুলনা।',
            'যন্ত্রপাতি: টেস্টটিউব, আয়তন মাপক চোঙ, আদর্শ সাবান দ্রবণ, ড্রপার, পানির নমুনা, পাতিত পানি।',
            'পানিতে দ্রবীভূত ক্যালসিয়াম ও ম্যাগনেসিয়াম আয়নের কারণেই খরতা।',
            'খর পানিতে সাবান নষ্ট হয়, কারণ ফেনা ওঠার আগেই অদ্রবণীয় ময়লা তৈরি হয়।',
            'প্রতিটি নমুনার সমান আয়তন, যেমন $10\\ \\mathrm{cm^3}$, আলাদা টিউবে নিন।',
            'ফোঁটায় ফোঁটায় সাবান দ্রবণ দিন এবং প্রতি ফোঁটার পর ঝাঁকান।',
            'এক মিনিট টিকে থাকে এমন ফেনা তৈরিতে কত ফোঁটা লাগল তা গুনুন এবং তুলনার জন্য পাতিত পানিতেও একই পরীক্ষা করুন।',
            'বেশি ফোঁটা মানে কঠিন পানি; কম ফোঁটা মানে নরম পানি।',
            'কঠিন নমুনার একটি অংশ ফুটিয়ে আবার পরীক্ষা করুন, যাতে দেখা যায় সাময়িক খরতা দূর হয়।',
            'স্থায়ী খরতা ফুটানোর পরেও থেকে যায় এবং ওয়াশিং সোডা বা আয়ন বিনিময়ক দরকার হয়।',
            'সতর্কতা: নমুনার মাঝে চোঙ ধুয়ে নিন, একইভাবে ঝাঁকান, সব সময় একই সাবান দ্রবণ ব্যবহার করুন।',
            'ভুলের উৎস: অসমান আয়তন, অসংগত ঝাঁকানো, চোখে ফেনা বিচার, সাবানের নতুন ব্যাচ।',
        ],
    },
}
