"""Ten to twelve revision points for the HSC chemistry practicals: titrimetry,
qualitative analysis and functional-group tests. See
`practical_points_physics_school.py` for the conventions every entry follows.
"""

POINTS = {
    'chemistry-hcl-naoh-titration-hsc': {
        'en': [
            'Aim: standardise a NaOH solution against a standard HCl solution by titration.',
            'Apparatus: burette, pipette, conical flask, funnel, stand, white tile, indicator, both solutions.',
            'Reaction: $\\mathrm{HCl} + \\mathrm{NaOH} \\rightarrow \\mathrm{NaCl} + \\mathrm{H_2O}$, a $1:1$ mole ratio.',
            'At the end point $c_aV_a = c_bV_b$ because the stoichiometry is one to one.',
            'Rinse the burette with the acid and the pipette with the base, fill the burette, clear the air bubble and note the initial reading at eye level.',
            'Pipette $25.0\\ \\mathrm{cm^3}$ of NaOH into the flask and add two drops of indicator.',
            'Run in the acid while swirling, slowing near the end point until the colour just changes.',
            'Record the final reading, then repeat for concordant titres within $0.10\\ \\mathrm{cm^3}$.',
            'Discard the rough titre and average only the concordant ones.',
            'Indicator choice matters: phenolphthalein for strong acid–strong base, methyl orange if you prefer.',
            'Precautions: no leaks, no splashing, read the lower meniscus, keep the flask on the tile.',
            'Error sources: parallax, overshooting the end point, wet glassware diluting a solution, air bubbles.',
        ],
        'bn': [
            'উদ্দেশ্য: আদর্শ HCl দ্রবণের বিরুদ্ধে টাইট্রেশনে NaOH দ্রবণের মান নির্ধারণ।',
            'যন্ত্রপাতি: বুরেট, পিপেট, কোনিক্যাল ফ্লাস্ক, ফানেল, স্ট্যান্ড, সাদা টালি, নির্দেশক, দুই দ্রবণ।',
            'বিক্রিয়া: $\\mathrm{HCl} + \\mathrm{NaOH} \\rightarrow \\mathrm{NaCl} + \\mathrm{H_2O}$, অর্থাৎ মোল অনুপাত $1:1$।',
            'স্টয়কিওমিতি এক-এক হওয়ায় সমাপ্তি বিন্দুতে $c_aV_a = c_bV_b$।',
            'ভরার আগে বুরেট অ্যাসিড ও পিপেট ক্ষারক দিয়ে ধুয়ে নিন, বুরেট ভরে নলের বাতাস বের করুন এবং চোখের সমান উচ্চতায় শুরুর পাঠ লিখুন।',
            'পিপেটে $25.0\\ \\mathrm{cm^3}$ NaOH ফ্লাস্কে নিয়ে দুই ফোঁটা নির্দেশক দিন।',
            'নাড়তে নাড়তে অ্যাসিড যোগ করুন এবং সমাপ্তি বিন্দুর কাছে ধীর হয়ে প্রথম রং পরিবর্তনে থামুন।',
            'শেষ পাঠ লিখে $0.10\\ \\mathrm{cm^3}$-এর মধ্যে সমজাতীয় টাইটার না হওয়া পর্যন্ত পুনরাবৃত্তি করুন।',
            'আনুমানিক টাইটার বাদ দিয়ে শুধু সমজাতীয়গুলোর গড় নিন।',
            'নির্দেশক বাছাই গুরুত্বপূর্ণ: তীব্র অ্যাসিড–তীব্র ক্ষারকে ফিনফথ্যালিন, চাইলে মিথাইল অরেঞ্জ।',
            'সতর্কতা: ফুটো নয়, ছিটকে পড়া নয়, নিম্ন মেনিস্কাসের পাঠ, ফ্লাস্ক টালির ওপরে।',
            'ভুলের উৎস: দৃষ্টিভ্রম, সমাপ্তি বিন্দু পার হয়ে যাওয়া, ভেজা যন্ত্রে দ্রবণ লঘু হওয়া, বাতাসের বুদবুদ।',
        ],
    },
    'chemistry-sodium-carbonate-hcl-titration-hsc': {
        'en': [
            'Aim: determine the concentration or purity of sodium carbonate by titration with HCl.',
            'Apparatus: burette, pipette, conical flask, balance, standard HCl, methyl orange, anhydrous Na₂CO₃.',
            'Reaction: $\\mathrm{Na_2CO_3} + 2\\mathrm{HCl} \\rightarrow 2\\mathrm{NaCl} + \\mathrm{H_2O} + \\mathrm{CO_2}$, so the mole ratio is $1:2$.',
            'Two moles of acid react with one mole of carbonate — that factor of two is the usual slip.',
            'Prepare a standard solution by weighing pure, dry Na₂CO₃ into a volumetric flask.',
            'Dissolve it completely and make the volume up to the mark with distilled water.',
            'Pipette $25.0\\ \\mathrm{cm^3}$ of the carbonate solution and add two drops of methyl orange.',
            'Titrate with the acid until the yellow colour just turns permanent pink.',
            'Use $c_aV_a = 2\\,c_bV_b$ to relate the acid volume to the carbonate concentration.',
            'Boiling the solution near the end point removes CO₂ and sharpens the colour change.',
            'Precautions: dry the carbonate before weighing, no splashing, rinse the flask between titres.',
            'Error sources: damp or impure carbonate, CO₂ left in solution, overshooting the pink end point.',
        ],
        'bn': [
            'উদ্দেশ্য: HCl দিয়ে টাইট্রেশনে সোডিয়াম কার্বোনেটের ঘনমাত্রা বা বিশুদ্ধতা নির্ণয়।',
            'যন্ত্রপাতি: বুরেট, পিপেট, কোনিক্যাল ফ্লাস্ক, তুলা, আদর্শ HCl, মিথাইল অরেঞ্জ, অনার্দ্র Na₂CO₃।',
            'বিক্রিয়া: $\\mathrm{Na_2CO_3} + 2\\mathrm{HCl} \\rightarrow 2\\mathrm{NaCl} + \\mathrm{H_2O} + \\mathrm{CO_2}$, মোল অনুপাত $1:2$।',
            'এক মোল কার্বোনেটের সঙ্গে দুই মোল অ্যাসিড বিক্রিয়া করে — এই দুই গুণটিই সাধারণ ভুলের জায়গা।',
            'বিশুদ্ধ শুকনো Na₂CO₃ ওজন নিয়ে আয়তনিক ফ্লাস্কে আদর্শ দ্রবণ তৈরি করুন।',
            'সম্পূর্ণ দ্রবীভূত করে পাতিত পানি দিয়ে দাগ পর্যন্ত আয়তন পূর্ণ করুন।',
            'পিপেটে $25.0\\ \\mathrm{cm^3}$ কার্বোনেট দ্রবণ নিয়ে দুই ফোঁটা মিথাইল অরেঞ্জ দিন।',
            'হলুদ রং স্থায়ী গোলাপি হওয়া পর্যন্ত অ্যাসিড দিয়ে টাইট্রেট করুন।',
            'অ্যাসিডের আয়তনের সঙ্গে কার্বোনেটের ঘনমাত্রা মেলাতে $c_aV_a = 2\\,c_bV_b$ ব্যবহার করুন।',
            'সমাপ্তি বিন্দুর কাছে দ্রবণ ফুটিয়ে CO₂ সরালে রঙের পরিবর্তন স্পষ্ট হয়।',
            'সতর্কতা: ওজনের আগে কার্বোনেট শুকান, ছিটকে ফেলবেন না, টাইটারের মাঝে ফ্লাস্ক ধুয়ে নিন।',
            'ভুলের উৎস: ভেজা বা অশুদ্ধ কার্বোনেট, দ্রবণে থেকে যাওয়া CO₂, গোলাপি সমাপ্তি বিন্দু পার হয়ে যাওয়া।',
        ],
    },
    'chemistry-permanganate-redox-titration-hsc': {
        'en': [
            'Aim: standardise potassium permanganate against oxalic acid or Mohr’s salt.',
            'Apparatus: burette, pipette, conical flask, hot plate or burner, thermometer, dilute H₂SO₄, KMnO₄, oxalic acid or Mohr’s salt.',
            'With oxalic acid: $2\\mathrm{MnO_4^-} + 5\\mathrm{C_2O_4^{2-}} + 16\\mathrm{H^+} \\rightarrow 2\\mathrm{Mn^{2+}} + 10\\mathrm{CO_2} + 8\\mathrm{H_2O}$.',
            'With Mohr’s salt: $\\mathrm{MnO_4^-} + 5\\mathrm{Fe^{2+}} + 8\\mathrm{H^+} \\rightarrow \\mathrm{Mn^{2+}} + 5\\mathrm{Fe^{3+}} + 4\\mathrm{H_2O}$.',
            'KMnO₄ is self-indicating: the end point is the first faint permanent pink.',
            'Acidify with dilute H₂SO₄; HCl would be oxidised and HNO₃ is itself an oxidiser.',
            'Warm the oxalic acid solution to about $60$–$70^\\circ\\mathrm{C}$, since the reaction is slow when cold.',
            'Add the first few drops slowly and swirl — the Mn²⁺ formed then catalyses the rest.',
            'Read the upper meniscus, because the deep purple colour hides the lower one.',
            'Repeat for concordant titres and use the mole ratio above in the calculation.',
            'Precautions: no filter paper near KMnO₄, rinse the burette with the permanganate itself.',
            'Error sources: temperature too low or too high, using the wrong acid, overshooting to a dark pink.',
        ],
        'bn': [
            'উদ্দেশ্য: অক্সালিক অ্যাসিড বা মোহর লবণের বিরুদ্ধে পটাশিয়াম পারম্যাঙ্গানেটের মান নির্ধারণ।',
            'যন্ত্রপাতি: বুরেট, পিপেট, কোনিক্যাল ফ্লাস্ক, হট প্লেট বা বার্নার, তাপমাপক, লঘু H₂SO₄, KMnO₄, অক্সালিক অ্যাসিড বা মোহর লবণ।',
            'অক্সালিক অ্যাসিডে: $2\\mathrm{MnO_4^-} + 5\\mathrm{C_2O_4^{2-}} + 16\\mathrm{H^+} \\rightarrow 2\\mathrm{Mn^{2+}} + 10\\mathrm{CO_2} + 8\\mathrm{H_2O}$।',
            'মোহর লবণে: $\\mathrm{MnO_4^-} + 5\\mathrm{Fe^{2+}} + 8\\mathrm{H^+} \\rightarrow \\mathrm{Mn^{2+}} + 5\\mathrm{Fe^{3+}} + 4\\mathrm{H_2O}$।',
            'KMnO₄ নিজেই নির্দেশক: সমাপ্তি বিন্দু হলো প্রথম হালকা স্থায়ী গোলাপি রং।',
            'লঘু H₂SO₄ দিয়ে অম্লীয় করুন; HCl জারিত হবে আর HNO₃ নিজেই জারক।',
            'অক্সালিক অ্যাসিড দ্রবণ প্রায় $60$–$70^\\circ\\mathrm{C}$ পর্যন্ত গরম করুন, কারণ ঠান্ডায় বিক্রিয়া ধীর।',
            'প্রথম কয়েক ফোঁটা আস্তে দিয়ে নাড়ুন — তৈরি হওয়া Mn²⁺ পরের অংশ দ্রুত করে।',
            'উর্ধ্ব মেনিস্কাসের পাঠ নিন, কারণ গাঢ় বেগুনি রঙে নিম্ন মেনিস্কাস দেখা যায় না।',
            'সমজাতীয় টাইটার পর্যন্ত পুনরাবৃত্তি করে ওপরের মোল অনুপাত দিয়ে হিসাব করুন।',
            'সতর্কতা: KMnO₄-এর কাছে ফিল্টার কাগজ নয়, বুরেট পারম্যাঙ্গানেট দিয়েই ধুয়ে নিন।',
            'ভুলের উৎস: খুব কম বা বেশি তাপমাত্রা, ভুল অ্যাসিড ব্যবহার, গাঢ় গোলাপি পর্যন্ত পার হয়ে যাওয়া।',
        ],
    },
    'chemistry-edta-water-hardness-hsc': {
        'en': [
            'Aim: determine total water hardness by EDTA complexometric titration.',
            'Apparatus: burette, pipette, conical flask, standard EDTA solution, ammonia buffer pH 10, Eriochrome Black T indicator, water sample.',
            'Complex formation: $\\mathrm{M^{2+}} + \\mathrm{EDTA^{4-}} \\rightarrow [\\mathrm{M(EDTA)}]^{2-}$ in a $1:1$ ratio for Ca²⁺ and Mg²⁺.',
            'The buffer must hold pH 10, because the indicator and the complex both depend on it.',
            'Pipette a known volume of the water sample into the flask.',
            'Add the ammonia buffer, then a pinch of Eriochrome Black T.',
            'The wine-red colour shows metal ions are still bound to the indicator.',
            'Titrate with EDTA until the colour changes sharply to pure blue.',
            'Compute hardness from $n(\\mathrm{EDTA}) = n(\\mathrm{M^{2+}})$ and convert to $\\mathrm{mg/L}$ as CaCO₃.',
            'Hardness as CaCO₃ $= \\dfrac{V_{\\mathrm{EDTA}} \\times c_{\\mathrm{EDTA}} \\times 100.09 \\times 1000}{V_{\\mathrm{sample}}}$.',
            'Precautions: use freshly prepared buffer, do not let the sample stand for long, add only a pinch of indicator.',
            'Error sources: wrong pH, stale indicator, iron or copper interference, a fuzzy end point from over-titration.',
        ],
        'bn': [
            'উদ্দেশ্য: EDTA জটিল টাইট্রেশনে পানির মোট খরতা নির্ণয়।',
            'যন্ত্রপাতি: বুরেট, পিপেট, কোনিক্যাল ফ্লাস্ক, আদর্শ EDTA দ্রবণ, pH ১০-এর অ্যামোনিয়া বাফার, ইরিওক্রোম ব্ল্যাক T নির্দেশক, পানির নমুনা।',
            'জটিল গঠন: $\\mathrm{M^{2+}} + \\mathrm{EDTA^{4-}} \\rightarrow [\\mathrm{M(EDTA)}]^{2-}$ এবং Ca²⁺ ও Mg²⁺-এর জন্য অনুপাত $1:1$।',
            'বাফারকে অবশ্যই pH ১০ রাখতে হবে, কারণ নির্দেশক ও জটিল দুটোই তার ওপর নির্ভরশীল।',
            'পানির নমুনার জানা আয়তন পিপেট করে ফ্লাস্কে নিন।',
            'অ্যামোনিয়া বাফার দিয়ে সামান্য ইরিওক্রোম ব্ল্যাক T যোগ করুন।',
            'ওয়াইন-লাল রং বোঝায় ধাতব আয়ন তখনো নির্দেশকের সঙ্গে যুক্ত।',
            'রং স্পষ্টভাবে বিশুদ্ধ নীল হওয়া পর্যন্ত EDTA দিয়ে টাইট্রেট করুন।',
            '$n(\\mathrm{EDTA}) = n(\\mathrm{M^{2+}})$ থেকে খরতা হিসাব করে CaCO₃ হিসেবে $\\mathrm{mg/L}$-এ রূপান্তর করুন।',
            'CaCO₃ হিসেবে খরতা $= \\dfrac{V_{\\mathrm{EDTA}} \\times c_{\\mathrm{EDTA}} \\times 100.09 \\times 1000}{V_{\\mathrm{sample}}}$।',
            'সতর্কতা: তাজা বাফার ব্যবহার করুন, নমুনা বেশিক্ষণ রাখবেন না, নির্দেশক সামান্যই দিন।',
            'ভুলের উৎস: ভুল pH, পুরনো নির্দেশক, লোহা বা তামার বাধা, অতিরিক্ত টাইট্রেশনে ঝাপসা সমাপ্তি বিন্দু।',
        ],
    },
    'chemistry-iodometric-copper-titration-hsc': {
        'en': [
            'Aim: determine copper in a sample by iodometric titration with sodium thiosulfate.',
            'Apparatus: burette, pipette, conical flask with stopper, KI, dilute acetic acid, standard Na₂S₂O₃, starch indicator.',
            'Copper(II) oxidises iodide: $2\\mathrm{Cu^{2+}} + 4\\mathrm{I^-} \\rightarrow 2\\mathrm{CuI} + \\mathrm{I_2}$.',
            'The liberated iodine is then titrated: $\\mathrm{I_2} + 2\\mathrm{S_2O_3^{2-}} \\rightarrow 2\\mathrm{I^-} + \\mathrm{S_4O_6^{2-}}$.',
            'So $n(\\mathrm{Cu^{2+}}) = n(\\mathrm{S_2O_3^{2-}})$ — one mole of thiosulfate per mole of copper.',
            'Acidify with dilute acetic acid, not a strong acid, and keep the flask stoppered in the dark.',
            'Titrate until the brown iodine colour fades to pale straw.',
            'Add the starch only near the end point; adding it early traps iodine in the complex.',
            'Continue until the blue-black colour disappears and only the white CuI remains.',
            'Use the thiosulfate volume and concentration to find the mass of copper in the sample.',
            'Precautions: an excess of KI is needed, avoid air oxidation, keep the temperature moderate.',
            'Error sources: starch added too early, iodine lost by volatilisation, thiosulfate decomposed, light exposure.',
        ],
        'bn': [
            'উদ্দেশ্য: সোডিয়াম থায়োসালফেট দিয়ে আয়োডোমেট্রিক টাইট্রেশনে নমুনার তামা নির্ণয়।',
            'যন্ত্রপাতি: বুরেট, পিপেট, ছিপিসহ কোনিক্যাল ফ্লাস্ক, KI, লঘু অ্যাসিটিক অ্যাসিড, আদর্শ Na₂S₂O₃, স্টার্চ নির্দেশক।',
            'কপার(II) আয়োডাইডকে জারিত করে: $2\\mathrm{Cu^{2+}} + 4\\mathrm{I^-} \\rightarrow 2\\mathrm{CuI} + \\mathrm{I_2}$।',
            'মুক্ত আয়োডিন এরপর টাইট্রেট হয়: $\\mathrm{I_2} + 2\\mathrm{S_2O_3^{2-}} \\rightarrow 2\\mathrm{I^-} + \\mathrm{S_4O_6^{2-}}$।',
            'তাই $n(\\mathrm{Cu^{2+}}) = n(\\mathrm{S_2O_3^{2-}})$ — প্রতি মোল তামায় এক মোল থায়োসালফেট।',
            'তীব্র অ্যাসিডের বদলে লঘু অ্যাসিটিক অ্যাসিডে অম্লীয় করুন এবং ফ্লাস্ক ছিপি দিয়ে অন্ধকারে রাখুন।',
            'বাদামি আয়োডিনের রং ফ্যাকাসে হলুদ হওয়া পর্যন্ত টাইট্রেট করুন।',
            'স্টার্চ শুধু সমাপ্তি বিন্দুর কাছে দিন; আগে দিলে জটিলে আয়োডিন আটকে যায়।',
            'নীল-কালো রং মিলিয়ে সাদা CuI না থাকা পর্যন্ত চালিয়ে যান।',
            'থায়োসালফেটের আয়তন ও ঘনমাত্রা থেকে নমুনায় তামার ভর বের করুন।',
            'সতর্কতা: অতিরিক্ত KI দরকার, বাতাসের জারণ এড়ান, তাপমাত্রা মাঝারি রাখুন।',
            'ভুলের উৎস: আগেই স্টার্চ দেওয়া, বাষ্পীভবনে আয়োডিন হারানো, নষ্ট হওয়া থায়োসালফেট, আলোতে রাখা।',
        ],
    },
    'chemistry-cation-analysis-hsc': {
        'en': [
            'Aim: identify the cation present in an unknown salt by systematic group analysis.',
            'Apparatus: test tubes and rack, droppers, burner, dilute HCl, H₂S or thioacetamide, NH₄Cl, NH₄OH, NaOH, flame-test wire.',
            'Work through the groups in order — ammonium, lead, copper, iron, aluminium, zinc, calcium, barium — since each group reagent precipitates only its own cations.',
            'Ammonium: warm the salt with NaOH and test the gas with moist red litmus or Nessler’s reagent.',
            'Lead: dilute HCl gives a white precipitate that dissolves in hot water and reappears on cooling — needles.',
            'Copper: NH₄OH gives a pale blue precipitate that dissolves in excess to a deep blue solution.',
            'Iron(III): NH₄OH or NaOH gives a reddish-brown precipitate; potassium ferrocyanide gives Prussian blue.',
            'Aluminium: a white gelatinous precipitate soluble in excess NaOH, not in excess NH₄OH.',
            'Zinc: white precipitate soluble in excess NaOH and in excess NH₄OH — that separates it from aluminium.',
            'Calcium: ammonium oxalate gives a white precipitate; flame test gives brick red. Barium: yellow-green flame.',
            'Precautions: add NH₄Cl before NH₄OH, use small amounts, wash every precipitate, work in order.',
            'Error sources: skipping a group, reagents added in excess too early, dirty tubes, misreading a faint precipitate.',
        ],
        'bn': [
            'উদ্দেশ্য: ধারাবাহিক গ্রুপ বিশ্লেষণে অজানা লবণের ক্যাটায়ন শনাক্তকরণ।',
            'যন্ত্রপাতি: টেস্টটিউব ও র‍্যাক, ড্রপার, বার্নার, লঘু HCl, H₂S বা থায়োঅ্যাসিটামাইড, NH₄Cl, NH₄OH, NaOH, শিখা পরীক্ষার তার।',
            'গ্রুপ অনুসারে এগোন — অ্যামোনিয়াম, সীসা, তামা, লোহা, অ্যালুমিনিয়াম, দস্তা, ক্যালসিয়াম, বেরিয়াম — কারণ প্রতিটি গ্রুপ বিকারক শুধু নিজের ক্যাটায়নকে অধঃক্ষিপ্ত করে।',
            'অ্যামোনিয়াম: লবণকে NaOH দিয়ে গরম করে গ্যাসটি ভেজা লাল লিটমাস বা নেসলার বিকারকে পরীক্ষা করুন।',
            'সীসা: লঘু HCl-এ সাদা অধঃক্ষেপ, যা গরম পানিতে গলে এবং ঠান্ডা হলে সূচির মতো ফিরে আসে।',
            'তামা: NH₄OH-এ হালকা নীল অধঃক্ষেপ, যা অতিরিক্তে গলে গাঢ় নীল দ্রবণ দেয়।',
            'আয়রন(III): NH₄OH বা NaOH-এ লালচে-বাদামি অধঃক্ষেপ; পটাশিয়াম ফেরোসায়ানাইডে প্রুশিয়ান নীল।',
            'অ্যালুমিনিয়াম: সাদা জেলির মতো অধঃক্ষেপ, যা অতিরিক্ত NaOH-এ গলে কিন্তু অতিরিক্ত NH₄OH-এ নয়।',
            'দস্তা: সাদা অধঃক্ষেপ অতিরিক্ত NaOH ও অতিরিক্ত NH₄OH উভয়েই গলে — এভাবেই অ্যালুমিনিয়াম থেকে আলাদা হয়।',
            'ক্যালসিয়াম: অ্যামোনিয়াম অক্সালেটে সাদা অধঃক্ষেপ, শিখায় ইটের মতো লাল; বেরিয়ামে হলুদ-সবুজ শিখা।',
            'সতর্কতা: NH₄OH-এর আগে NH₄Cl দিন, সামান্য পরিমাণ নিন, প্রতিটি অধঃক্ষেপ ধুয়ে নিন, ক্রম ঠিক রাখুন।',
            'ভুলের উৎস: কোনো গ্রুপ বাদ দেওয়া, আগেভাগেই অতিরিক্ত বিকারক, নোংরা টিউব, হালকা অধঃক্ষেপ ভুল পড়া।',
        ],
    },
    'chemistry-anion-analysis-hsc': {
        'en': [
            'Aim: identify the anion present in an unknown salt by preliminary and confirmatory tests.',
            'Apparatus: test tubes, droppers, burner, delivery tube, dilute and concentrated H₂SO₄, AgNO₃, BaCl₂, limewater, filter paper.',
            'Dilute acid group first — carbonate, sulfite, sulfide, nitrite; carbonate fizzes with the acid and turns limewater milky.',
            'Concentrated acid group next: chloride, bromide, iodide, nitrate — these need concentrated H₂SO₄.',
            'Chloride: white fumes with concentrated H₂SO₄; AgNO₃ gives a white precipitate soluble in NH₄OH.',
            'Bromide: reddish-brown vapour; AgNO₃ gives a pale yellow precipitate partly soluble in NH₄OH.',
            'Iodide: violet vapour that turns starch paper blue-black.',
            'Nitrate: brown-ring test with fresh FeSO₄ and concentrated H₂SO₄ added carefully down the wall.',
            'Sulfate: BaCl₂ in dilute HCl gives a white precipitate insoluble in the acid.',
            'Phosphate: ammonium molybdate in nitric acid, warmed, gives a canary-yellow precipitate.',
            'Precautions: add concentrated acid slowly, never heat a stoppered tube, use fresh reagents, work in a fume area.',
            'Error sources: skipping the dilute-acid group, old FeSO₄, acidifying with the wrong acid, confusing Br⁻ and I⁻.',
        ],
        'bn': [
            'উদ্দেশ্য: প্রাথমিক ও নিশ্চায়ক পরীক্ষায় অজানা লবণের অ্যানায়ন শনাক্তকরণ।',
            'যন্ত্রপাতি: টেস্টটিউব, ড্রপার, বার্নার, নির্গমন নল, লঘু ও গাঢ় H₂SO₄, AgNO₃, BaCl₂, চুনের পানি, ফিল্টার কাগজ।',
            'আগে লঘু অ্যাসিড গ্রুপ — কার্বোনেট, সালফাইট, সালফাইড, নাইট্রাইট; কার্বোনেটে বুদবুদ ওঠে এবং গ্যাসটি চুনের পানি ঘোলা করে।',
            'এরপর গাঢ় অ্যাসিড গ্রুপ: ক্লোরাইড, ব্রোমাইড, আয়োডাইড, নাইট্রেট — এদের গাঢ় H₂SO₄ লাগে।',
            'ক্লোরাইড: গাঢ় H₂SO₄-এ সাদা ধোঁয়া; AgNO₃-এ সাদা অধঃক্ষেপ যা NH₄OH-এ গলে।',
            'ব্রোমাইড: লালচে-বাদামি বাষ্প; AgNO₃-এ হালকা হলুদ অধঃক্ষেপ যা NH₄OH-এ আংশিক গলে।',
            'আয়োডাইড: বেগুনি বাষ্প যা স্টার্চ কাগজকে নীল-কালো করে।',
            'নাইট্রেট: তাজা FeSO₄ এবং দেয়াল বেয়ে সাবধানে গাঢ় H₂SO₄ দিয়ে বাদামি বলয় পরীক্ষা।',
            'সালফেট: লঘু HCl-এ BaCl₂ দিলে সাদা অধঃক্ষেপ যা অ্যাসিডে অগলেয়।',
            'ফসফেট: নাইট্রিক অ্যাসিডে অ্যামোনিয়াম মলিবডেট গরম করলে ক্যানারি-হলুদ অধঃক্ষেপ।',
            'সতর্কতা: গাঢ় অ্যাসিড আস্তে দিন, ছিপি লাগানো টিউব গরম নয়, তাজা বিকারক, বায়ুচলাচলের জায়গায় কাজ।',
            'ভুলের উৎস: লঘু অ্যাসিড গ্রুপ বাদ দেওয়া, পুরনো FeSO₄, ভুল অ্যাসিডে অম্লীয়করণ, Br⁻ ও I⁻ গুলিয়ে ফেলা।',
        ],
    },
    'chemistry-alcohol-functional-group-test-hsc': {
        'en': [
            'Aim: confirm the presence of an alcohol group with chemical tests.',
            'Apparatus: test tubes, droppers, water bath, sample, sodium metal, Lucas reagent, acidified KMnO₄ or K₂Cr₂O₇, ceric ammonium nitrate.',
            'Sodium test: a small piece of dry sodium in the alcohol gives bubbles of hydrogen, which pop with a burning splint.',
            'The alcohol must be dry — water also reacts with sodium and gives a false positive.',
            'Ceric ammonium nitrate gives a red colour with alcohols; this is quick and specific.',
            'Lucas reagent distinguishes the three classes: tertiary turns cloudy at once.',
            'Secondary alcohols turn cloudy within about five minutes; primary show little change when cold.',
            'Oxidation: acidified dichromate turns from orange to green for primary and secondary alcohols.',
            'A tertiary alcohol does not oxidise, so the orange colour stays.',
            'Warm gently in a water bath; never heat alcohols over a naked flame.',
            'Precautions: small sodium pieces, dispose of sodium residues in ethanol, no flames nearby, ventilated area.',
            'Error sources: moisture in the sample, sodium oxide coating, over-heating, misjudging cloudiness.',
        ],
        'bn': [
            'উদ্দেশ্য: রাসায়নিক পরীক্ষায় অ্যালকোহল মূলকের উপস্থিতি নিশ্চিতকরণ।',
            'যন্ত্রপাতি: টেস্টটিউব, ড্রপার, পানি-স্নান, নমুনা, সোডিয়াম ধাতু, লুকাস বিকারক, অম্লীয় KMnO₄ বা K₂Cr₂O₇, সেরিক অ্যামোনিয়াম নাইট্রেট।',
            'সোডিয়াম পরীক্ষা: শুকনো অ্যালকোহলে সোডিয়ামের ছোট টুকরা দিলে হাইড্রোজেনের বুদবুদ ওঠে, যা জ্বলন্ত কাঠিতে তীক্ষ্ণ পপ শব্দ করে।',
            'অ্যালকোহল শুকনো হতে হবে — পানিও সোডিয়ামের সঙ্গে বিক্রিয়া করে ভুল ফল দেয়।',
            'সেরিক অ্যামোনিয়াম নাইট্রেট অ্যালকোহলে লাল রং দেয়; এ পরীক্ষা দ্রুত ও সুনির্দিষ্ট।',
            'লুকাস বিকারক তিন ধরনের অ্যালকোহল আলাদা করে: তৃতীয়ক সঙ্গে সঙ্গে ঘোলা হয়।',
            'দ্বিতীয়ক প্রায় পাঁচ মিনিটে ঘোলা হয়; প্রাথমিক ঠান্ডা অবস্থায় খুব একটা বদলায় না।',
            'জারণ: অম্লীয় ডাইক্রোমেট কমলা থেকে সবুজ হয় প্রাথমিক ও দ্বিতীয়ক অ্যালকোহলে।',
            'তৃতীয়ক অ্যালকোহল জারিত হয় না, তাই কমলা রং থেকে যায়।',
            'পানি-স্নানে মৃদু গরম করুন; খোলা শিখায় অ্যালকোহল গরম নয়।',
            'সতর্কতা: সোডিয়ামের ছোট টুকরা, অবশিষ্ট সোডিয়াম ইথানলে নষ্ট করুন, শিখা দূরে রাখুন, বায়ুচলাচলের জায়গা।',
            'ভুলের উৎস: নমুনায় আর্দ্রতা, সোডিয়ামের অক্সাইড আস্তরণ, অতিরিক্ত তাপ, ঘোলা ভাব ভুল বোঝা।',
        ],
    },
    'chemistry-aldehyde-tollens-fehling-hsc': {
        'en': [
            'Aim: distinguish an aldehyde from a ketone with Tollens’ and Fehling’s tests.',
            'Apparatus: test tubes, water bath, droppers, AgNO₃, dilute NaOH, NH₃ solution, Fehling A and B, sample.',
            'An aldehyde is easily oxidised; a ketone is not, which is the whole basis of both tests.',
            'Tollens’ reagent is prepared by adding NH₃ to the Ag₂O precipitate until it just dissolves.',
            'Warm the sample with Tollens’ reagent in a water bath at about $60^\\circ\\mathrm{C}$.',
            'A silver mirror on the tube wall, or a grey precipitate, confirms an aldehyde.',
            'Fehling’s test: mix equal volumes of A and B freshly, then add the sample and warm.',
            'A brick-red Cu₂O precipitate means an aldehyde; the blue colour stays for a ketone.',
            'Prepare only the Tollens’ reagent you need and destroy the leftovers with acid; stored ammoniacal silver nitrate can form explosive silver nitride.',
            'Run a known aldehyde and a known ketone side by side as controls.',
            'Precautions: use a very clean tube for a good mirror, gentle heating only, no naked flame.',
            'Error sources: overheating that decomposes the reagent, dirty glassware, stale Fehling mixture, too much sample.',
        ],
        'bn': [
            'উদ্দেশ্য: টোলেন ও ফেলিং পরীক্ষায় অ্যালডিহাইডকে কিটোন থেকে আলাদা করা।',
            'যন্ত্রপাতি: টেস্টটিউব, পানি-স্নান, ড্রপার, AgNO₃, লঘু NaOH, NH₃ দ্রবণ, ফেলিং A ও B, নমুনা।',
            'অ্যালডিহাইড সহজে জারিত হয়, কিটোন নয় — দুই পরীক্ষার ভিত্তিই এটি।',
            'Ag₂O অধঃক্ষেপে NH₃ মেশাতে থাকুন, ঠিক গলে যাওয়া পর্যন্ত; এটিই টোলেন বিকারক।',
            'নমুনাকে টোলেন বিকারকসহ প্রায় $60^\\circ\\mathrm{C}$ পানি-স্নানে গরম করুন।',
            'টিউবের গায়ে রুপার আয়না বা ধূসর অধঃক্ষেপ অ্যালডিহাইড নিশ্চিত করে।',
            'ফেলিং পরীক্ষা: A ও B সমান আয়তনে তাজা মিশিয়ে নমুনা দিয়ে গরম করুন।',
            'ইটের মতো লাল Cu₂O অধঃক্ষেপ মানে অ্যালডিহাইড; কিটোনে নীল রং থেকে যায়।',
            'টোলেন বিকারক শুধু প্রয়োজনমতো তৈরি করুন এবং অবশিষ্ট অংশ অ্যাসিড দিয়ে নষ্ট করুন; জমিয়ে রাখা অ্যামোনিয়াকাল সিলভার নাইট্রেট থেকে বিস্ফোরক সিলভার নাইট্রাইড হতে পারে।',
            'নিয়ন্ত্রণ হিসেবে জানা অ্যালডিহাইড ও জানা কিটোন পাশাপাশি পরীক্ষা করুন।',
            'সতর্কতা: ভালো আয়নার জন্য খুব পরিষ্কার টিউব, মৃদু তাপ, খোলা শিখা নয়।',
            'ভুলের উৎস: অতিরিক্ত তাপে বিকারক নষ্ট, নোংরা কাচ, পুরনো ফেলিং মিশ্রণ, বেশি নমুনা।',
        ],
    },
    'chemistry-ketone-functional-group-test-hsc': {
        'en': [
            'Aim: identify a ketone and show that it does not behave like an aldehyde.',
            'Apparatus: test tubes, water bath, droppers, sample, 2,4-DNP reagent, Tollens’ reagent, Fehling’s solution, iodoform reagents.',
            'Ketones do give a precipitate with 2,4-dinitrophenylhydrazine, just like aldehydes.',
            'An orange-yellow 2,4-DNP precipitate confirms a carbonyl group; filter, wash and dry it, because its melting point identifies the compound.',
            'Ketones give no silver mirror with Tollens’ reagent — that separates them from aldehydes.',
            'Ketones give no brick-red precipitate with Fehling’s solution either.',
            'Iodoform test: methyl ketones with warm iodine and NaOH give a pale yellow CHI₃ precipitate.',
            'The iodoform also has a characteristic antiseptic smell.',
            'Record both the positive carbonyl test and the two negative oxidation tests.',
            'Use a known aldehyde alongside the sample so the contrast is clear.',
            'Precautions: 2,4-DNP reagent is acidic and staining, warm gently, avoid skin contact.',
            'Error sources: impure sample, reagent kept too long, overheating, judging a faint yellow colour wrongly.',
        ],
        'bn': [
            'উদ্দেশ্য: কিটোন শনাক্ত করা এবং এটি অ্যালডিহাইডের মতো আচরণ করে না তা দেখানো।',
            'যন্ত্রপাতি: টেস্টটিউব, পানি-স্নান, ড্রপার, নমুনা, ২,৪-DNP বিকারক, টোলেন বিকারক, ফেলিং দ্রবণ, আয়োডোফর্ম বিকারক।',
            'অ্যালডিহাইডের মতো কিটোনও ২,৪-ডাইনাইট্রোফিনাইলহাইড্রাজিনের সঙ্গে অধঃক্ষেপ দেয়।',
            'কমলা-হলুদ ২,৪-DNP অধঃক্ষেপ কার্বোনিল মূলক নিশ্চিত করে; এটি ছেঁকে ধুয়ে শুকান, কারণ এর গলনাঙ্কই যৌগটি শনাক্ত করে।',
            'টোলেন বিকারকে কিটোন রুপার আয়না দেয় না — এভাবেই অ্যালডিহাইড থেকে আলাদা হয়।',
            'ফেলিং দ্রবণেও কিটোন ইটের মতো লাল অধঃক্ষেপ দেয় না।',
            'আয়োডোফর্ম পরীক্ষা: মিথাইল কিটোনে গরম আয়োডিন ও NaOH দিলে হালকা হলুদ CHI₃ অধঃক্ষেপ পড়ে।',
            'আয়োডোফর্মের নিজস্ব জীবাণুনাশক গন্ধও থাকে।',
            'ধনাত্মক কার্বোনিল পরীক্ষা এবং দুটি ঋণাত্মক জারণ পরীক্ষা দুটোই লিখে রাখুন।',
            'পার্থক্য স্পষ্ট করতে নমুনার পাশাপাশি একটি জানা অ্যালডিহাইডও পরীক্ষা করুন।',
            'সতর্কতা: ২,৪-DNP বিকারক অম্লীয় ও দাগ ফেলে, মৃদু গরম করুন, ত্বকের সংস্পর্শ এড়ান।',
            'ভুলের উৎস: অশুদ্ধ নমুনা, বিকারক বেশিদিন রাখা, অতিরিক্ত তাপ, হালকা হলুদ রং ভুল বোঝা।',
        ],
    },
    'chemistry-carboxylic-acid-test-hsc': {
        'en': [
            'Aim: confirm a carboxylic acid group in an organic sample.',
            'Apparatus: test tubes, droppers, spatula, sample, sodium hydrogen carbonate, litmus, esterification reagents.',
            'Carboxylic acids turn blue litmus red, but so do mineral acids — the litmus is only a first hint.',
            'The decisive test is effervescence with solid NaHCO₃, releasing CO₂.',
            'Reaction: $\\mathrm{RCOOH} + \\mathrm{NaHCO_3} \\rightarrow \\mathrm{RCOONa} + \\mathrm{CO_2} + \\mathrm{H_2O}$, and the CO₂ released turns limewater milky.',
            'Phenols do not give effervescence with NaHCO₃, so this test separates acids from phenols.',
            'Ester test: warm the sample with ethanol and a few drops of concentrated H₂SO₄.',
            'A fruity smell confirms the carboxylic acid through ester formation.',
            'Higher acids dissolve only slowly, so warm gently and stir to see the bubbles.',
            'Record the observation, the gas test and the smell test in a table.',
            'Precautions: add concentrated acid to the mixture slowly, use a water bath, no direct flame with organics.',
            'Error sources: damp sample, too little NaHCO₃, missing faint effervescence, confusing a phenol with an acid.',
        ],
        'bn': [
            'উদ্দেশ্য: জৈব নমুনায় কার্বক্সিলিক অ্যাসিড মূলক নিশ্চিতকরণ।',
            'যন্ত্রপাতি: টেস্টটিউব, ড্রপার, স্প্যাচুলা, নমুনা, সোডিয়াম হাইড্রোজেন কার্বোনেট, লিটমাস, এস্টারীকরণ বিকারক।',
            'কার্বক্সিলিক অ্যাসিড নীল লিটমাস লাল করে, তবে খনিজ অ্যাসিডও তাই করে — লিটমাস শুধু প্রাথমিক ইঙ্গিত।',
            'চূড়ান্ত পরীক্ষা হলো কঠিন NaHCO₃-এর সঙ্গে বুদবুদ ওঠা, যা থেকে CO₂ নির্গত হয়।',
            'বিক্রিয়া: $\\mathrm{RCOOH} + \\mathrm{NaHCO_3} \\rightarrow \\mathrm{RCOONa} + \\mathrm{CO_2} + \\mathrm{H_2O}$ এবং সেই CO\u2082 চুনের পানি ঘোলা করে।',
            'ফেনল NaHCO₃-এর সঙ্গে বুদবুদ দেয় না, তাই এই পরীক্ষায় অ্যাসিড ও ফেনল আলাদা হয়।',
            'এস্টার পরীক্ষা: নমুনাকে ইথানল ও কয়েক ফোঁটা গাঢ় H₂SO₄ দিয়ে গরম করুন।',
            'ফলের মতো গন্ধ এস্টার গঠনের মধ্য দিয়ে কার্বক্সিলিক অ্যাসিড নিশ্চিত করে।',
            'উচ্চতর অ্যাসিড ধীরে গলে, তাই মৃদু গরম করে নাড়লে বুদবুদ দেখা যায়।',
            'পর্যবেক্ষণ, গ্যাস পরীক্ষা ও গন্ধ পরীক্ষা একটি সারণিতে লিখুন।',
            'সতর্কতা: গাঢ় অ্যাসিড মিশ্রণে আস্তে দিন, পানি-স্নান ব্যবহার করুন, জৈব পদার্থে সরাসরি শিখা নয়।',
            'ভুলের উৎস: ভেজা নমুনা, অল্প NaHCO₃, হালকা বুদবুদ না দেখা, ফেনলকে অ্যাসিড ভাবা।',
        ],
    },
    'chemistry-phenol-test-hsc': {
        'en': [
            'Aim: identify a phenol with the neutral ferric chloride and bromine-water tests.',
            'Apparatus: test tubes, droppers, sample, neutral FeCl₃ solution, bromine water, sodium hydroxide, NaHCO₃.',
            'Neutral FeCl₃ gives a violet, blue or green colour with phenols — the classic test.',
            'Keep the FeCl₃ neutral, since acid destroys the coloured complex, and add only one or two drops — excess gives a yellow ferric colour that hides the result.',
            'Phenols are acidic but weaker than carbonic acid, so they do not fizz with NaHCO₃.',
            'That negative NaHCO₃ result is what separates a phenol from a carboxylic acid.',
            'Phenol dissolves in NaOH, giving a clear phenoxide solution.',
            'Bromine water is decolourised by phenol and a white precipitate of 2,4,6-tribromophenol forms.',
            'Phthalic anhydride with concentrated H₂SO₄ and heat gives a fluorescein-type colour for some phenols.',
            'Record each colour exactly, since different phenols give different shades.',
            'Precautions: bromine is corrosive and its vapour is toxic, work in a fume area, wear gloves and goggles.',
            'Error sources: acidic FeCl₃, excess reagent, impure sample, mistaking an enol for a phenol.',
        ],
        'bn': [
            'উদ্দেশ্য: নিরপেক্ষ ফেরিক ক্লোরাইড ও ব্রোমিন পানি পরীক্ষায় ফেনল শনাক্তকরণ।',
            'যন্ত্রপাতি: টেস্টটিউব, ড্রপার, নমুনা, নিরপেক্ষ FeCl₃ দ্রবণ, ব্রোমিন পানি, সোডিয়াম হাইড্রক্সাইড, NaHCO₃।',
            'নিরপেক্ষ FeCl₃ ফেনলের সঙ্গে বেগুনি, নীল বা সবুজ রং দেয় — এটিই প্রচলিত পরীক্ষা।',
            'FeCl₃ নিরপেক্ষ রাখুন, কারণ অ্যাসিড রঙিন জটিল নষ্ট করে দেয়, এবং মাত্র এক-দুই ফোঁটা দিন — অতিরিক্ত দিলে হলুদ ফেরিক রং ফল ঢেকে দেয়।',
            'ফেনল অম্লীয় হলেও কার্বনিক অ্যাসিডের চেয়ে দুর্বল, তাই NaHCO₃-এর সঙ্গে বুদবুদ দেয় না।',
            'NaHCO₃-এ এই ঋণাত্মক ফলই ফেনলকে কার্বক্সিলিক অ্যাসিড থেকে আলাদা করে।',
            'ফেনল NaOH-এ গলে স্বচ্ছ ফেনক্সাইড দ্রবণ দেয়।',
            'ব্রোমিন পানির রং ফেনলে উধাও হয় এবং সাদা ২,৪,৬-ট্রাইব্রোমোফেনল অধঃক্ষেপ পড়ে।',
            'কিছু ফেনলে ফথালিক অ্যানহাইড্রাইড, গাঢ় H₂SO₄ ও তাপ দিলে ফ্লুরোসিন ধরনের রং আসে।',
            'প্রতিটি রং হুবহু লিখুন, কারণ ভিন্ন ফেনলে ভিন্ন রঙের ছোঁয়া দেখা যায়।',
            'সতর্কতা: ব্রোমিন ক্ষয়কারী ও তার বাষ্প বিষাক্ত, বায়ুচলাচলের জায়গায় কাজ করুন, গ্লাভস ও চশমা পরুন।',
            'ভুলের উৎস: অম্লীয় FeCl₃, অতিরিক্ত বিকারক, অশুদ্ধ নমুনা, ইনলকে ফেনল ভাবা।',
        ],
    },
    'chemistry-amine-test-hsc': {
        'en': [
            'Aim: detect an amine and distinguish primary, secondary and tertiary amines.',
            'Apparatus: test tubes, droppers, ice bath, sample, dilute HCl, nitrous acid reagents, Hinsberg reagent, litmus.',
            'Amines are basic: they turn red litmus blue, dissolve in dilute HCl and often smell fishy or ammoniacal.',
            'Nitrous acid test: generate HNO₂ in situ from NaNO₂ and dilute HCl below $5^\\circ\\mathrm{C}$.',
            'A primary aliphatic amine gives brisk effervescence of nitrogen with nitrous acid.',
            'A primary aromatic amine forms a diazonium salt, which couples with β-naphthol to give an orange-red dye.',
            'A secondary amine gives a yellow oily nitrosoamine layer.',
            'A tertiary amine simply dissolves, with no visible product.',
            'Hinsberg test: benzenesulfonyl chloride with NaOH dissolves the primary product but not the secondary one.',
            'Keep the diazonium mixture cold and use it at once; it decomposes on warming.',
            'Precautions: work in an ice bath, add reagents dropwise, ventilate the area, never heat a diazonium solution strongly.',
            'Error sources: mixture too warm, stale nitrite, excess acid, mistaking ammonia contamination for an amine.',
        ],
        'bn': [
            'উদ্দেশ্য: অ্যামিন শনাক্তকরণ এবং প্রাথমিক, দ্বিতীয়ক ও তৃতীয়ক অ্যামিন আলাদা করা।',
            'যন্ত্রপাতি: টেস্টটিউব, ড্রপার, বরফ-স্নান, নমুনা, লঘু HCl, নাইট্রাস অ্যাসিড বিকারক, হিন্সবার্গ বিকারক, লিটমাস।',
            'অ্যামিন ক্ষারকীয়: লাল লিটমাস নীল করে, লঘু HCl-এ গলে যায় এবং প্রায়ই মাছের মতো বা অ্যামোনিয়ার গন্ধ দেয়।',
            'নাইট্রাস অ্যাসিড পরীক্ষা: NaNO₂ ও লঘু HCl থেকে $5^\\circ\\mathrm{C}$-এর নিচে HNO₂ তৈরি করুন।',
            'প্রাথমিক অ্যালিফ্যাটিক অ্যামিন নাইট্রাস অ্যাসিডে দ্রুত নাইট্রোজেনের বুদবুদ দেয়।',
            'প্রাথমিক অ্যারোম্যাটিক অ্যামিন ডায়াজোনিয়াম লবণ তৈরি করে, যা β-ন্যাপথলের সঙ্গে কমলা-লাল রঙ দেয়।',
            'দ্বিতীয়ক অ্যামিন হলুদ তৈলাক্ত নাইট্রোসোঅ্যামিন স্তর দেয়।',
            'তৃতীয়ক অ্যামিন কেবল গলে যায়, দৃশ্যমান উৎপাদ থাকে না।',
            'হিন্সবার্গ পরীক্ষা: NaOH-সহ বেনজিনসালফোনিল ক্লোরাইড প্রাথমিকের উৎপাদ গুলিয়ে দেয়, দ্বিতীয়কের নয়।',
            'ডায়াজোনিয়াম মিশ্রণ ঠান্ডা রেখে সঙ্গে সঙ্গে ব্যবহার করুন; গরম করলে তা ভেঙে যায়।',
            'সতর্কতা: বরফ-স্নানে কাজ করুন, বিকারক ফোঁটায় ফোঁটায় দিন, বায়ুচলাচল রাখুন, ডায়াজোনিয়াম দ্রবণ জোরে গরম নয়।',
            'ভুলের উৎস: মিশ্রণ বেশি গরম, পুরনো নাইট্রাইট, অতিরিক্ত অ্যাসিড, অ্যামোনিয়া দূষণকে অ্যামিন ভাবা।',
        ],
    },
    'chemistry-unsaturation-baeyer-test-hsc': {
        'en': [
            'Aim: test an organic compound for unsaturation by Baeyer’s test and the bromine test.',
            'Apparatus: test tubes, droppers, sample, dilute alkaline KMnO₄, bromine in CCl₄ or bromine water, acetone as solvent.',
            'Unsaturation means a carbon–carbon double or triple bond that can add across.',
            'Baeyer’s test: add dilute alkaline KMnO₄ dropwise and shake the tube.',
            'The purple colour disappears and a brown MnO₂ precipitate appears if a double bond is present.',
            'Bromine test: add bromine solution dropwise; the red-brown colour disappears on addition.',
            'Run both tests, because each has its own exceptions and interferences.',
            'A saturated compound such as hexane leaves both colours unchanged, while phenols, aldehydes and easily oxidised compounds also decolourise them.',
            'Note how many drops each sample takes before the colour persists.',
            'Dissolve the sample in acetone or CCl₄ first if it is not water-soluble.',
            'Precautions: bromine vapour is toxic and corrosive, work in a fume area, do not add excess KMnO₄.',
            'Error sources: oxidisable impurities, too much reagent, daylight decomposing bromine, an unshaken mixture.',
        ],
        'bn': [
            'উদ্দেশ্য: বায়ার পরীক্ষা ও ব্রোমিন পরীক্ষায় জৈব যৌগের অসম্পৃক্ততা যাচাই।',
            'যন্ত্রপাতি: টেস্টটিউব, ড্রপার, নমুনা, লঘু ক্ষারীয় KMnO₄, CCl₄-এ ব্রোমিন বা ব্রোমিন পানি, দ্রাবক হিসেবে অ্যাসিটোন।',
            'অসম্পৃক্ততা মানে কার্বন-কার্বন দ্বিবন্ধন বা ত্রিবন্ধন, যার ওপর সংযোজন সম্ভব।',
            'বায়ার পরীক্ষা: লঘু ক্ষারীয় KMnO₄ ফোঁটায় ফোঁটায় দিয়ে টিউব ঝাঁকান।',
            'দ্বিবন্ধন থাকলে বেগুনি রং মিলিয়ে যায় এবং বাদামি MnO₂ অধঃক্ষেপ দেখা দেয়।',
            'ব্রোমিন পরীক্ষা: ব্রোমিন দ্রবণ ফোঁটায় ফোঁটায় দিন; সংযোজনে লালচে-বাদামি রং উধাও হয়।',
            'দুটি পরীক্ষাই করুন, কারণ প্রত্যেকটির নিজস্ব ব্যতিক্রম ও বাধা আছে।',
            'হেক্সেনের মতো সম্পৃক্ত যৌগে দুই রংই অপরিবর্তিত থাকে, কিন্তু ফেনল, অ্যালডিহাইড ও সহজজার্য যৌগও এই বিকারকগুলোর রং নষ্ট করে।',
            'রং টিকে যাওয়ার আগে প্রতিটি নমুনা কত ফোঁটা নিল তা লিখুন।',
            'নমুনা পানিতে না গলে আগে অ্যাসিটোন বা CCl₄-এ দ্রবীভূত করুন।',
            'সতর্কতা: ব্রোমিন বাষ্প বিষাক্ত ও ক্ষয়কারী, বায়ুচলাচলের জায়গায় কাজ, অতিরিক্ত KMnO₄ নয়।',
            'ভুলের উৎস: জারণযোগ্য অপদ্রব্য, বেশি বিকারক, দিনের আলোয় ব্রোমিন ভাঙা, না ঝাঁকানো মিশ্রণ।',
        ],
    },
}
