"""Ten to twelve revision points for each HSC physics practical (measurement,
mechanics, heat and sound). See `practical_points_physics_school.py` for the
conventions every entry follows.
"""

POINTS = {
    'physics-vernier-callipers-hsc': {
        'en': [
            'Aim: measure internal diameter, external diameter and depth with vernier callipers.',
            'Apparatus: vernier callipers, a cylinder, a beaker and a thin wire.',
            'Least count $LC = $ main-scale division $-$ vernier division, usually $0.01\\ \\mathrm{cm}$.',
            'Find the zero error by closing the jaws; note it with its sign.',
            'Reading $= MSR + (VSR \\times LC)$, then subtract the zero error.',
            'Grip the object firmly but do not squeeze a soft or thin sample.',
            'For an inner diameter use the upper jaws and read along the same scale.',
            'For depth use the tail strip, keeping the callipers vertical.',
            'Take three readings at different orientations and use the mean.',
            'Precautions: clean jaws, eye perpendicular to the scale, no forced sliding.',
            'Error sources: uncorrected zero error, worn jaws, parallax, a tilted object.',
            'Viva: the vernier works because $n$ vernier divisions equal $(n-1)$ main divisions.',
        ],
        'bn': [
            'উদ্দেশ্য: ভার্নিয়ার ক্যালিপার্স দিয়ে ভেতরের ব্যাস, বাইরের ব্যাস ও গভীরতা মাপা।',
            'যন্ত্রপাতি: ভার্নিয়ার ক্যালিপার্স, সিলিন্ডার, বিকার ও সরু তার।',
            'লঘিষ্ঠ গণন $LC = $ প্রধান স্কেলের ঘর $-$ ভার্নিয়ারের ঘর, সাধারণত $0.01\\ \\mathrm{cm}$।',
            'চোয়াল মিলিয়ে শূন্য ত্রুটি বের করুন এবং চিহ্নসহ লিখে রাখুন।',
            'পাঠ $= MSR + (VSR \\times LC)$, এরপর শূন্য ত্রুটি বিয়োগ করুন।',
            'বস্তুকে শক্ত করে ধরুন, তবে নরম বা সরু নমুনা চাপবেন না।',
            'ভেতরের ব্যাসের জন্য ওপরের চোয়াল ব্যবহার করে একই স্কেলে পাঠ নিন।',
            'গভীরতার জন্য পেছনের দণ্ডটি ব্যবহার করুন, ক্যালিপার্স খাড়া রেখে।',
            'তিনটি ভিন্ন অবস্থানে পাঠ নিয়ে গড় মান নিন।',
            'সতর্কতা: পরিষ্কার চোয়াল, স্কেলের ওপর লম্বভাবে চোখ, জোর করে স্লাইড নয়।',
            'ভুলের উৎস: শূন্য ত্রুটি না কাটা, ক্ষয়প্রাপ্ত চোয়াল, দৃষ্টিভ্রম, হেলে থাকা বস্তু।',
            'ভাইভা: ভার্নিয়ারের $n$ ঘর প্রধান স্কেলের $(n-1)$ ঘরের সমান বলে এটি কাজ করে।',
        ],
    },
    'physics-screw-gauge-hsc': {
        'en': [
            'Aim: measure the diameter of a thin wire and the thickness of a sheet.',
            'Apparatus: screw gauge, wire, glass slide or thin sheet.',
            'Pitch is the distance the spindle moves in one complete rotation.',
            'Least count $LC = $ pitch $\\div$ number of circular-scale divisions.',
            'Close the spindle on the anvil and note the zero error with its sign.',
            'Reading $= MSR + (CSR \\times LC)$, then subtract the zero error.',
            'Turn the ratchet, not the thimble, so the pressure stays the same every time.',
            'Hold the wire between the anvils at five places and in two directions.',
            'Use the mean diameter, since a drawn wire is rarely perfectly circular.',
            'Precautions: no backlash, clean faces, no forcing, eye square to the scale.',
            'Error sources: backlash, an incorrect pitch reading, uncorrected zero error.',
            'Viva: the ratchet slips at a fixed pressure, which prevents over-tightening.',
        ],
        'bn': [
            'উদ্দেশ্য: সরু তারের ব্যাস ও পাতলা পাতের পুরুত্ব নির্ণয়।',
            'যন্ত্রপাতি: স্ক্রু গজ, তার, স্লাইড বা পাতলা পাত।',
            'পিচ হলো এক পূর্ণ ঘূরণে স্পিন্ডেল যত দূর সরে।',
            'লঘিষ্ঠ গণন $LC = $ পিচ $\\div$ বৃত্তাকার স্কেলের ঘরসংখ্যা।',
            'স্পিন্ডল অ্যানভিলের সঙ্গে মিলিয়ে শূন্য ত্রুটি চিহ্নসহ লিখুন।',
            'পাঠ $= MSR + (CSR \\times LC)$, এরপর শূন্য ত্রুটি বিয়োগ করুন।',
            'থিম্বলের বদলে র‍্যাকেট ঘোরান, যাতে প্রতিবার একই চাপ পড়ে।',
            'তারকে পাঁচ জায়গায় এবং দুই দিকে রেখে ব্যাস মাপুন।',
            'টানা তার পুরোপুরি বৃত্তাকার নাও হতে পারে, তাই গড় ব্যাস নিন।',
            'সতর্কতা: ব্যাকল্যাশ নয়, পরিষ্কার তল, জোর নয়, স্কেলে লম্বভাবে চোখ।',
            'ভুলের উৎস: ব্যাকল্যাশ, ভুল পিচ পাঠ, শূন্য ত্রুটি না কাটা।',
            'ভাইভা: র‍্যাকেট নির্দিষ্ট চাপে পিছলে যায়, তাই অতিরিক্ত জোর লাগে না।',
        ],
    },
    'physics-spherometer-hsc': {
        'en': [
            'Aim: measure the radius of curvature of a spherical surface with a spherometer.',
            'Apparatus: spherometer, plane glass plate, the spherical surface, magnifier.',
            'Pitch and least count are found exactly as for a screw gauge.',
            'Place the spherometer on the plane glass and note the zero reading.',
            'Shift it onto the curved surface until all four legs touch firmly.',
            'The sagitta $h$ is the difference between the two readings.',
            'Measure the mean distance $l$ between the three outer legs with dividers.',
            'Use $R = \\dfrac{l^2}{6h} + \\dfrac{h}{2}$ to calculate the radius of curvature.',
            'Take three readings on different parts of the surface and use the mean.',
            'Precautions: the central screw must turn smoothly, no dragging across the surface.',
            'Error sources: an uneven surface, loose legs, backlash, a wrong leg spacing.',
            'Viva: for a nearly flat surface $h$ is small, so the uncertainty in $R$ grows.',
        ],
        'bn': [
            'উদ্দেশ্য: স্ফেরোমিটার দিয়ে গোলীয় তলের বক্রতার ব্যাসার্ধ নির্ণয়।',
            'যন্ত্রপাতি: স্ফেরোমিটার, সমতল কাচের পাত, গোলীয় তল, বিবর্ধক।',
            'স্ক্রু গজের মতোই পিচ ও লঘিষ্ঠ গণন বের করে নিন।',
            'সমতল কাচের ওপর রেখে শূন্য পাঠ লিখুন।',
            'এরপর বক্র তলে রাখুন যতক্ষণ চারটি পায়া একসঙ্গে শক্তভাবে লাগে।',
            'দুই পাঠের পার্থক্যই স্যাজিটা $h$।',
            'কম্পাস দিয়ে বাইরের তিন পায়ার গড় ব্যবধান $l$ মাপুন।',
            '$R = \\dfrac{l^2}{6h} + \\dfrac{h}{2}$ সূত্রে বসিয়ে বক্রতার ব্যাসার্ধ বের করুন।',
            'তলের তিন জায়গায় পাঠ নিয়ে গড় মান নিন।',
            'সতর্কতা: কেন্দ্রীয় স্ক্রু মসৃণভাবে ঘুরবে, তলের ওপর টেনে নেওয়া যাবে না।',
            'ভুলের উৎস: অমসৃণ তল, আলগা পায়া, ব্যাকল্যাশ, ভুল পায়া-ব্যবধান।',
            'ভাইভা: প্রায় সমতল তলে $h$ খুব ছোট হয়, তাই $R$-এর অনিশ্চয়তা বেড়ে যায়।',
        ],
    },
    'physics-g-pendulum-hsc': {
        'en': [
            'Aim: determine the acceleration due to gravity with a simple pendulum.',
            'Apparatus: stand with clamp, string, metallic bob, metre scale, stopwatch.',
            'For small angles $T = 2\\pi\\sqrt{L/g}$, so $g = 4\\pi^2 L/T^2$.',
            'Effective length $L$ runs from the point of suspension to the centre of the bob.',
            'Add the radius of the bob to the string length; forgetting it biases $g$ high.',
            'Keep the amplitude below about $5^\\circ$ so the small-angle form holds.',
            'Time 20 or 30 oscillations and divide; do not time a single swing.',
            'Repeat for at least five lengths and plot $T^2$ against $L$.',
            'From the slope, $g = 4\\pi^2/\\text{slope}$; a graph beats one reading.',
            'Precautions: rigid support, no conical swinging, no draught, a heavy small bob.',
            'Error sources: reaction time, wrong effective length, large amplitude, a spinning bob.',
            'Viva: the period is independent of the bob’s mass for small oscillations.',
        ],
        'bn': [
            'উদ্দেশ্য: সরল দোলক দিয়ে অভিকর্ষজ ত্বরণ নির্ণয়।',
            'যন্ত্রপাতি: ক্ল্যাম্পসহ স্ট্যান্ড, সুতা, ধাতব বব, মিটার স্কেল, স্টপওয়াচ।',
            'ক্ষুদ্র কোণে $T = 2\\pi\\sqrt{L/g}$, অর্থাৎ $g = 4\\pi^2 L/T^2$।',
            'কার্যকর দৈর্ঘ্য $L$ ঝোলন বিন্দু থেকে ববের কেন্দ্র পর্যন্ত ধরতে হয়।',
            'সুতার দৈর্ঘ্যের সঙ্গে ববের ব্যাসার্ধ যোগ করুন; না করলে $g$ বেশি আসে।',
            'বিস্তার প্রায় $5^\\circ$-এর নিচে রাখুন, যাতে ক্ষুদ্র-কোণ সূত্র চলে।',
            '২০ বা ৩০টি দোলনের সময় নিয়ে ভাগ করুন; একটি দোলন মাপবেন না।',
            'অন্তত পাঁচটি দৈর্ঘ্যে মেপে $T^2$ বনাম $L$ লেখচিত্র আঁকুন।',
            'লেখচিত্রের ঢাল দিয়ে $4\\pi^2$ ভাগ করলেই $g$ মেলে; একটি পাঠের চেয়ে লেখচিত্র নির্ভরযোগ্য।',
            'সতর্কতা: শক্ত অবলম্বন, শঙ্কু দোলন নয়, বাতাসের ঝাপটা নয়, ছোট ও ভারী বব।',
            'ভুলের উৎস: প্রতিক্রিয়ার সময়, ভুল কার্যকর দৈর্ঘ্য, বড় বিস্তার, ঘুরতে থাকা বব।',
            'ভাইভা: ক্ষুদ্র দোলনে পর্যায়কাল ববের ভরের ওপর নির্ভর করে না।',
        ],
    },
    'physics-young-modulus-searle-hsc': {
        'en': [
            'Aim: determine Young’s modulus of a wire with Searle’s apparatus.',
            'Apparatus: Searle frame, two wires, hanger, slotted masses, micrometer, spirit level.',
            'Within the elastic limit $Y = FL/(A\\Delta L)$ with $A = \\pi d^2/4$.',
            'The second reference wire takes up the temperature and support movement.',
            'Measure the test-wire length from the fixed end to the micrometer.',
            'Measure the diameter at several points and directions with the micrometer.',
            'Load in equal steps and read the extension on the micrometer scale each time.',
            'Unload in the same steps and confirm the readings retrace — that proves elasticity.',
            'Use only the loading–unloading agreeing region; ignore the first small load.',
            'Plot extension against load and take the slope, not one noisy point.',
            'Precautions: never exceed the elastic limit, keep weights off the feet, no kinks.',
            'Error sources: backlash, creep of the wire, parallax, and $d^2$ magnifying error.',
        ],
        'bn': [
            'উদ্দেশ্য: সিয়ার্লের যন্ত্রে তারের ইয়ং গুণাঙ্ক নির্ণয়।',
            'যন্ত্রপাতি: সিয়ার্ল ফ্রেম, দুটি তার, ভারধারক, কাটা ভার, মাইক্রোমিটার, স্পিরিট লেভেল।',
            'স্থিতিস্থাপক সীমার ভেতরে $Y = FL/(A\\Delta L)$, যেখানে $A = \\pi d^2/4$।',
            'দ্বিতীয় রেফারেন্স তার তাপমাত্রা ও অবলম্বনের নড়াচড়া সামলে দেয়।',
            'পরীক্ষণ তারের দৈর্ঘ্য মাপুন স্থির প্রান্ত থেকে মাইক্রোমিটার পর্যন্ত।',
            'মাইক্রোমিটার দিয়ে কয়েক স্থানে ও কয়েক দিকে ব্যাস মাপুন।',
            'সমান ধাপে ভার বাড়ান এবং প্রতিবার প্রসারণ লিখুন।',
            'একই ধাপে ভার কমিয়ে দেখুন পাঠ ফিরে আসে কি না — এটিই স্থিতিস্থাপকতার প্রমাণ।',
            'শুধু ভার-যোগ ও ভার-কমানোর মিল থাকা অংশ নিন; প্রথম সামান্য ভার বাদ দিন।',
            'প্রসারণ বনাম ভার লেখচিত্র এঁকে ঢাল নিন, একটি অস্থির পাঠ নয়।',
            'সতর্কতা: স্থিতিস্থাপক সীমা ছাড়ানো যাবে না, ভার যেন পায়ে না লাগে, তারে ভাঁজ নয়।',
            'ভুলের উৎস: ব্যাকল্যাশ, তারের ক্রিপ, দৃষ্টিভ্রম এবং $d^2$-এর কারণে ত্রুটি বৃদ্ধি।',
        ],
    },
    'physics-spring-oscillation-hsc': {
        'en': [
            'Aim: find the spring constant and effective mass from vertical oscillations.',
            'Apparatus: spring, stand, mass hanger, slotted masses, stopwatch, scale.',
            'For a loaded spring $T = 2\\pi\\sqrt{m/k}$, so $T^2 = 4\\pi^2 m/k$.',
            'First check the static value with $k = mg/x$ from the extension.',
            'Pull the hanger down slightly and release so the motion stays vertical.',
            'Time 20 oscillations for each load and divide to get $T$.',
            'Use at least five different loads within the elastic limit.',
            'Plot $T^2$ against $m$; the slope equals $4\\pi^2/k$.',
            'The intercept on the mass axis is negative and gives the effective spring mass.',
            'Compare the dynamic $k$ from the graph with the static $k$ from extensions.',
            'Precautions: small amplitude, no sideways swing, wait for steady oscillation.',
            'Error sources: exceeding the elastic limit, air drag, reaction time, a loose clamp.',
        ],
        'bn': [
            'উদ্দেশ্য: উল্লম্ব দোলন থেকে স্প্রিং ধ্রুবক ও কার্যকর ভর নির্ণয়।',
            'যন্ত্রপাতি: স্প্রিং, স্ট্যান্ড, ভারধারক, কাটা ভার, স্টপওয়াচ, স্কেল।',
            'ভারযুক্ত স্প্রিংয়ে $T = 2\\pi\\sqrt{m/k}$, অর্থাৎ $T^2 = 4\\pi^2 m/k$।',
            'প্রথমে প্রসারণ থেকে স্থির মান $k = mg/x$ বের করে রাখুন।',
            'ভারধারককে সামান্য নিচে টেনে ছাড়ুন যেন গতি উল্লম্ব থাকে।',
            'প্রতিটি ভারের জন্য ২০টি দোলনের সময় নিয়ে $T$ বের করুন।',
            'স্থিতিস্থাপক সীমার মধ্যে অন্তত পাঁচটি ভিন্ন ভার নিন।',
            '$T^2$ বনাম $m$ লেখচিত্র আঁকুন; ঢাল $=4\\pi^2/k$।',
            'ভর অক্ষে ঋণাত্মক ছেদক থেকে স্প্রিংয়ের কার্যকর ভর পাওয়া যায়।',
            'লেখচিত্রের গতিজ $k$-এর সঙ্গে স্থিতিক $k$ তুলনা করুন।',
            'সতর্কতা: ছোট বিস্তার, পার্শ্বদোলন নয়, স্থির দোলনের জন্য অপেক্ষা করুন।',
            'ভুলের উৎস: স্থিতিস্থাপক সীমা অতিক্রম, বায়ুর বাধা, প্রতিক্রিয়ার সময়, আলগা ক্ল্যাম্প।',
        ],
    },
    'physics-surface-tension-hsc': {
        'en': [
            'Aim: determine the surface tension of water by capillary rise.',
            'Apparatus: clean capillary tubes, travelling microscope, water beaker, thermometer.',
            'For a wetting liquid $\\gamma = \\dfrac{\\rho g r h}{2\\cos\\theta}$, and $\\theta \\approx 0$ for clean glass.',
            'Use several capillaries of different radii rather than one tube.',
            'Measure the inner radius from the tip with the travelling microscope.',
            'Dip the tube vertically and let the water rise without vibration.',
            'Read the meniscus level inside the tube and the free surface outside.',
            'The rise $h$ is the difference between those two readings.',
            'Note the temperature, because $\\gamma$ falls as the water gets warmer.',
            'Plot $h$ against $1/r$; the graph should be a straight line through the origin.',
            'Precautions: thoroughly clean glass, no grease, no tilting, no parallax on the microscope.',
            'Error sources: contact angle not zero, a dirty or chipped tip, evaporation, temperature drift.',
        ],
        'bn': [
            'উদ্দেশ্য: কৈশিক উত্থান পদ্ধতিতে পানির পৃষ্ঠটান নির্ণয়।',
            'যন্ত্রপাতি: পরিষ্কার কৈশিক নল, ট্রাভেলিং অণুবীক্ষণ, পানির বিকার, তাপমাপক।',
            'ভেজানো তরলে $\\gamma = \\dfrac{\\rho g r h}{2\\cos\\theta}$ এবং পরিষ্কার কাচে $\\theta \\approx 0$।',
            'একটি নলের বদলে বিভিন্ন ব্যাসার্ধের কয়েকটি নল ব্যবহার করুন।',
            'ট্রাভেলিং অণুবীক্ষণ দিয়ে নলের আগার ভেতরের ব্যাসার্ধ মাপুন।',
            'নল খাড়াভাবে ডুবিয়ে কাঁপুনি ছাড়াই পানি উঠতে দিন।',
            'নলের ভেতরের মেনিস্কাস ও বাইরের মুক্ত তলের পাঠ নিন।',
            'উত্থান $h$ এই দুই পাঠের পার্থক্য।',
            'তাপমাত্রা লিখে রাখুন, কারণ গরম পানিতে $\\gamma$ কমে যায়।',
            '$h$ বনাম $1/r$ লেখচিত্র আঁকুন; এটি মূলবিন্দুগামী সরলরেখা হওয়ার কথা।',
            'সতর্কতা: কাচ ভালোভাবে পরিষ্কার, চর্বি নয়, নল হেলানো নয়, অণুবীক্ষণে দৃষ্টিভ্রম নয়।',
            'ভুলের উৎস: স্পর্শকোণ শূন্য না হওয়া, ময়লা বা ভাঙা অগ্রভাগ, বাষ্পীভবন, তাপমাত্রার পরিবর্তন।',
        ],
    },
    'physics-viscosity-stokes-hsc': {
        'en': [
            'Aim: determine the viscosity of a liquid by Stokes’ falling-sphere method.',
            'Apparatus: tall glass jar, liquid, small spheres, micrometer, stopwatch, scale, thermometer.',
            'At terminal speed $\\eta = \\dfrac{2r^2(\\rho_s - \\rho_f)g}{9v_t}$.',
            'Measure the diameter of each sphere and convert it to radius in metres.',
            'Mark two reference lines well below the surface and above the bottom.',
            'Release the sphere centrally and without spin, using a guide tube if needed.',
            'Time the fall between the marks only after terminal speed is reached.',
            'Use spheres of different radii; large spheres may leave the Stokes regime.',
            'Record the liquid temperature — viscosity changes strongly with it.',
            'Plot $v_t$ against $r^2$; the slope gives $\\eta$ from the relation above.',
            'Precautions: no bubbles on the sphere, no wall effects, jar vertical and still.',
            'Error sources: wall and end corrections, turbulence, temperature drift, reaction time.',
        ],
        'bn': [
            'উদ্দেশ্য: স্টোকসের পতনশীল গোলক পদ্ধতিতে তরলের সান্দ্রতা নির্ণয়।',
            'যন্ত্রপাতি: লম্বা কাচের জার, তরল, ছোট গোলক, মাইক্রোমিটার, স্টপওয়াচ, স্কেল, তাপমাপক।',
            'প্রান্তিক বেগে $\\eta = \\dfrac{2r^2(\\rho_s - \\rho_f)g}{9v_t}$।',
            'প্রতিটি গোলকের ব্যাস মেপে মিটারে ব্যাসার্ধে রূপান্তর করুন।',
            'তলের অনেক নিচে এবং তলার অনেক ওপরে দুটি দাগ দিন।',
            'গোলককে মাঝ বরাবর, ঘূর্ণন ছাড়াই ছাড়ুন; প্রয়োজনে গাইড নল ব্যবহার করুন।',
            'প্রান্তিক বেগে পৌঁছানোর পর শুধু দুই দাগের মধ্যবর্তী সময় মাপুন।',
            'বিভিন্ন ব্যাসার্ধের গোলক নিন; খুব বড় গোলক স্টোকসের সীমা ছাড়িয়ে যায়।',
            'তরলের তাপমাত্রা লিখুন — সান্দ্রতা তাপমাত্রায় দ্রুত বদলায়।',
            '$v_t$ বনাম $r^2$ লেখচিত্র আঁকলে ওপরের সম্পর্ক থেকে $\\eta$ পাওয়া যায়।',
            'সতর্কতা: গোলকে বুদবুদ নয়, দেয়ালের প্রভাব নয়, জার খাড়া ও স্থির রাখুন।',
            'ভুলের উৎস: দেয়াল ও প্রান্ত সংশোধন, অশান্ত প্রবাহ, তাপমাত্রার পরিবর্তন, প্রতিক্রিয়ার সময়।',
        ],
    },
    'physics-specific-heat-hsc': {
        'en': [
            'Aim: find the specific heat capacity of a solid by electrical or mixture method.',
            'Apparatus: calorimeter, heater or immersion coil, thermometer, balance, stopwatch, lid.',
            'Energy balance: $Q = mc\\Delta T$, and electrically $Q = VIt$.',
            'Weigh the empty calorimeter, then with water, to get the water mass.',
            'Record the initial temperature and stir until it is uniform.',
            'Pass a steady current and note voltage, current and time.',
            'Record the highest temperature after the heater is switched off.',
            'Correct for heat loss by noting the cooling rate just before switching off.',
            'Use $(m_wc_w + m_cc_c)\\Delta T = VIt$ to solve for the unknown heat capacity.',
            'Precautions: lid on, lagging around the calorimeter, bulb immersed, gentle stirring.',
            'Error sources: radiation loss, evaporation, thermometer lag, uneven temperature.',
            'Viva: the calorimeter’s own heat capacity must be included or the result is low.',
        ],
        'bn': [
            'উদ্দেশ্য: তড়িৎ বা মিশ্রণ পদ্ধতিতে কঠিনের আপেক্ষিক তাপ নির্ণয়।',
            'যন্ত্রপাতি: ক্যালোরিমিটার, হিটার বা নিমজ্জন কুণ্ডলী, তাপমাপক, তুলা, স্টপওয়াচ, ঢাকনা।',
            'শক্তি সমতা: $Q = mc\\Delta T$, তড়িৎ পদ্ধতিতে $Q = VIt$।',
            'খালি ক্যালোরিমিটার, তারপর পানিসহ ভর নিয়ে পানির ভর বের করুন।',
            'শুরুর তাপমাত্রা লিখে সমান হওয়া পর্যন্ত নাড়ুন।',
            'স্থির প্রবাহ চালিয়ে বিভব, প্রবাহ ও সময় লিখুন।',
            'হিটার বন্ধ করার পর সর্বোচ্চ তাপমাত্রা লিখুন।',
            'বন্ধ করার ঠিক আগের শীতলনের হার থেকে তাপক্ষয় সংশোধন করুন।',
            '$(m_wc_w + m_cc_c)\\Delta T = VIt$ থেকে অজানা আপেক্ষিক তাপ বের করুন।',
            'সতর্কতা: ঢাকনা দিন, ক্যালোরিমিটার অন্তরিত রাখুন, বাল্ব নিমজ্জিত রাখুন, আলতো নাড়ুন।',
            'ভুলের উৎস: বিকিরণ ক্ষয়, বাষ্পীভবন, তাপমাপকের জড়তা, অসম তাপমাত্রা।',
            'ভাইভা: ক্যালোরিমিটারের নিজস্ব তাপধারণ ক্ষমতা না ধরলে ফল কম আসে।',
        ],
    },
    'physics-latent-heat-hsc': {
        'en': [
            'Aim: determine the specific latent heat of fusion of ice.',
            'Apparatus: calorimeter, thermometer, balance, dry ice, stirrer, lid, water.',
            'Principle: heat lost by water and calorimeter $=$ heat to melt ice $+$ heat to warm the melt.',
            'Weigh the calorimeter with warm water and record its temperature.',
            'Dry the ice on blotting paper so no extra water enters the calorimeter.',
            'Add small pieces of ice, stirring until each piece has melted.',
            'Stop when the temperature has fallen by about $15^\\circ\\mathrm{C}$ and read the minimum.',
            'Weigh again to find the mass of ice that melted.',
            'Use $m_wc_w(T_1-T_2)+m_cc_c(T_1-T_2)=m_iL+m_ic_w(T_2-0)$.',
            'Apply a radiation correction if the room is much warmer than the mixture.',
            'Precautions: dry ice, small pieces, continuous stirring, a lid between additions.',
            'Error sources: water carried with the ice, evaporation, incomplete melting, heat gain from air.',
        ],
        'bn': [
            'উদ্দেশ্য: বরফের আপেক্ষিক সুপ্ততাপ নির্ণয়।',
            'যন্ত্রপাতি: ক্যালোরিমিটার, তাপমাপক, তুলা, শুকনো বরফ, নাড়ুনি, ঢাকনা, পানি।',
            'নীতি: পানি ও ক্যালোরিমিটারের বর্জিত তাপ $=$ বরফ গলাতে তাপ $+$ গলা পানি গরম করতে তাপ।',
            'উষ্ণ পানিসহ ক্যালোরিমিটারের ভর নিয়ে তাপমাত্রা লিখুন।',
            'বরফ ব্লটিং কাগজে মুছে নিন, যাতে অতিরিক্ত পানি ভেতরে না যায়।',
            'ছোট ছোট টুকরা বরফ দিয়ে নাড়তে থাকুন যতক্ষণ না প্রতিটি গলে যায়।',
            'তাপমাত্রা প্রায় $15^\\circ\\mathrm{C}$ নামলে থামুন এবং সর্বনিম্ন পাঠ লিখুন।',
            'আবার ভর নিয়ে গলা বরফের ভর বের করুন।',
            'সূত্র: $m_wc_w(T_1-T_2)+m_cc_c(T_1-T_2)=m_iL+m_ic_w(T_2-0)$।',
            'কক্ষ গরম হলে বিকিরণ সংশোধন প্রয়োগ করুন।',
            'সতর্কতা: শুকনো বরফ, ছোট টুকরা, ক্রমাগত নাড়া, মাঝে মাঝে ঢাকনা।',
            'ভুলের উৎস: বরফের সঙ্গে আসা পানি, বাষ্পীভবন, অসম্পূর্ণ গলন, বাতাস থেকে তাপগ্রহণ।',
        ],
    },
    'physics-thermal-conductivity-hsc': {
        'en': [
            'Aim: determine the thermal conductivity of a poor conductor (Lee’s disc or slab method).',
            'Apparatus: bad conductor slab, steam chamber, Lee’s disc, two thermometers, balance, scale, stopwatch.',
            'In steady state the heat rate is $Q/t = kA(T_1-T_2)/d$.',
            'Measure the slab thickness $d$ and the disc diameter to get the area $A$.',
            'Pass steam until both thermometer readings stop changing — that is steady state.',
            'Record the steady temperatures $T_1$ and $T_2$ of the two faces.',
            'Remove the slab and heat the lower disc directly, then let it cool with the slab on top.',
            'From the cooling curve find $d\\theta/dt$ at temperature $T_2$.',
            'Combine the heat gained by the disc, $mc\\,d\\theta/dt$, with the conduction rate to get $k$.',
            'Precautions: dry slab, no steam leaks, thermometers in the pockets, still air.',
            'Error sources: lateral heat loss, contact resistance, non-uniform slab, cooling correction.',
            'Viva: the method is for poor conductors; metals need Searle’s bar arrangement instead.',
        ],
        'bn': [
            'উদ্দেশ্য: কুপরিবাহীর তাপ পরিবাহিতা নির্ণয় (লিজ ডিস্ক বা স্ল্যাব পদ্ধতি)।',
            'যন্ত্রপাতি: কুপরিবাহী স্ল্যাব, বাষ্প প্রকোষ্ঠ, লিজ ডিস্ক, দুটি তাপমাপক, তুলা, স্কেল, স্টপওয়াচ।',
            'স্থির অবস্থায় তাপের হার $Q/t = kA(T_1-T_2)/d$।',
            'স্ল্যাবের পুরুত্ব $d$ ও ডিস্কের ব্যাস মেপে ক্ষেত্রফল $A$ বের করুন।',
            'দুই তাপমাপকের পাঠ স্থির না হওয়া পর্যন্ত বাষ্প চালান — এটিই স্থির অবস্থা।',
            'দুই তলের স্থির তাপমাত্রা $T_1$ ও $T_2$ লিখুন।',
            'স্ল্যাব সরিয়ে নিচের ডিস্ক সরাসরি গরম করুন, তারপর স্ল্যাব রেখে ঠান্ডা হতে দিন।',
            'শীতলন রেখা থেকে $T_2$ তাপমাত্রায় $d\\theta/dt$ বের করুন।',
            'ডিস্কের গৃহীত তাপ $mc\\,d\\theta/dt$-কে পরিবহন হারের সঙ্গে মিলিয়ে $k$ নির্ণয় করুন।',
            'সতর্কতা: শুকনো স্ল্যাব, বাষ্প নির্গত নয়, থার্মোমিটার গর্তে বসানো, স্থির বাতাস।',
            'ভুলের উৎস: পার্শ্বীয় তাপক্ষয়, স্পর্শ রোধ, অসম স্ল্যাব, শীতলন সংশোধন।',
            'ভাইভা: এ পদ্ধতি কুপরিবাহীর জন্য; ধাতুর ক্ষেত্রে সিয়ার্লের দণ্ড ব্যবস্থা লাগে।',
        ],
    },
    'physics-speed-sound-resonance-tube-hsc': {
        'en': [
            'Aim: determine the speed of sound in air with a resonance tube.',
            'Apparatus: resonance tube, water reservoir, tuning forks of known frequency, thermometer.',
            'At resonance $v = f\\lambda$, and successive resonances are $\\lambda/2$ apart.',
            'Find the first resonant length $L_1$ for a given fork by lowering the water level.',
            'Find the second resonant length $L_2$ for the same fork.',
            'Use $v = 2f(L_2 - L_1)$ so that the end correction cancels out.',
            'Repeat with at least three tuning forks and take the mean speed.',
            'Record the air temperature; compare with $v \\approx 331 + 0.6t\\ \\mathrm{m/s}$.',
            'Hold the fork above the tube without touching it and strike it on a rubber pad.',
            'Precautions: no bubbles in the tube, fork parallel to the opening, quiet room.',
            'Error sources: judging maximum loudness, end correction, temperature drift, a damped fork.',
            'Viva: the difference $L_2 - L_1$ is preferred because the end correction is unknown.',
        ],
        'bn': [
            'উদ্দেশ্য: অনুনাদ নলে বাতাসে শব্দের বেগ নির্ণয়।',
            'যন্ত্রপাতি: অনুনাদ নল, পানির আধার, জানা কম্পাঙ্কের সুরশলাকা, তাপমাপক।',
            'অনুনাদে $v = f\\lambda$, এবং পরপর দুই অনুনাদের দূরত্ব $\\lambda/2$।',
            'পানির তল নামিয়ে নির্দিষ্ট সুরশলাকার প্রথম অনুনাদ দৈর্ঘ্য $L_1$ বের করুন।',
            'একই সুরশলাকার দ্বিতীয় অনুনাদ দৈর্ঘ্য $L_2$ বের করুন।',
            '$v = 2f(L_2 - L_1)$ ব্যবহার করলে প্রান্ত সংশোধন বাতিল হয়ে যায়।',
            'অন্তত তিনটি সুরশলাকা নিয়ে গড় বেগ বের করুন।',
            'বাতাসের তাপমাত্রা লিখুন; $v \\approx 331 + 0.6t\\ \\mathrm{m/s}$-এর সঙ্গে তুলনা করুন।',
            'সুরশলাকা নলকে স্পর্শ না করে ওপরে ধরুন এবং রাবার প্যাডে আঘাত করুন।',
            'সতর্কতা: নলে বুদবুদ নয়, ছিদ্রমুখের সমান্তরাল শলাকা, নিরিবিলি কক্ষ।',
            'ভুলের উৎস: সর্বোচ্চ শব্দ বিচার, প্রান্ত সংশোধন, তাপমাত্রার পরিবর্তন, ক্ষীণ শলাকা।',
            'ভাইভা: প্রান্ত সংশোধন অজানা বলেই $L_2 - L_1$ পার্থক্য ব্যবহার করা হয়।',
        ],
    },
    'physics-sonometer-hsc': {
        'en': [
            'Aim: verify the laws of a stretched string with a sonometer.',
            'Apparatus: sonometer wire, bridges, hanger, slotted masses, tuning forks, paper rider.',
            'The fundamental frequency is $f = \\dfrac{1}{2L}\\sqrt{T/\\mu}$.',
            'Law of length: at constant tension $fL$ is constant.',
            'Law of tension: at constant length $f/\\sqrt{T}$ is constant.',
            'Law of mass: $f$ is inversely proportional to $\\sqrt{\\mu}$ for the same tension and length.',
            'Set a fixed load, then move the bridges until the paper rider falls off vigorously.',
            'Compare that resonant length with the tuning fork of known frequency.',
            'Repeat for several forks and plot $L$ against $1/f$; the graph is a straight line.',
            'For the tension law keep the length fixed and change the load step by step.',
            'Precautions: wire free of kinks, bridges perpendicular, no overloading, small amplitude.',
            'Error sources: slipping bridges, a damped fork, wire not uniform, parallax on the scale.',
        ],
        'bn': [
            'উদ্দেশ্য: সোনোমিটারে টানটান তারের সূত্রাবলি যাচাই।',
            'যন্ত্রপাতি: সোনোমিটার তার, সেতু, ভারধারক, কাটা ভার, সুরশলাকা, কাগজের রাইডার।',
            'মূল কম্পাঙ্ক $f = \\dfrac{1}{2L}\\sqrt{T/\\mu}$।',
            'দৈর্ঘ্য সূত্র: টান স্থির থাকলে $fL$ ধ্রুব।',
            'টান সূত্র: দৈর্ঘ্য স্থির থাকলে $f/\\sqrt{T}$ ধ্রুব।',
            'ভর সূত্র: একই টান ও দৈর্ঘ্যে $f$ ব্যস্তানুপাতিক $\\sqrt{\\mu}$-এর।',
            'নির্দিষ্ট ভার রেখে সেতু সরান যতক্ষণ না কাগজের রাইডার জোরে ছিটকে পড়ে।',
            'জানা কম্পাঙ্কের সুরশলাকার সঙ্গে সেই অনুনাদ দৈর্ঘ্য তুলনা করুন।',
            'কয়েকটি শলাকা নিয়ে $L$ বনাম $1/f$ আঁকুন; রেখা সরল হবে।',
            'টানের সূত্রে দৈর্ঘ্য স্থির রেখে ধাপে ধাপে ভার বদলান।',
            'সতর্কতা: তারে ভাঁজ নয়, সেতু লম্বভাবে, অতিরিক্ত ভার নয়, ছোট বিস্তার।',
            'ভুলের উৎস: পিছলে যাওয়া সেতু, ক্ষীণ শলাকা, অসম তার, স্কেলে দৃষ্টিভ্রম।',
        ],
    },
    'physics-convex-lens-uv-hsc': {
        'en': [
            'Aim: find the focal length of a convex lens by the u–v method.',
            'Apparatus: optical bench, convex lens in a holder, illuminated object, screen, uprights.',
            'Lens formula $1/f = 1/u + 1/v$, with $u$ and $v$ measured from the optical centre.',
            'Get a rough focal length first by focusing a distant object.',
            'Fix the object pin and place the lens beyond $f$ from it.',
            'Move the screen until the image is sharp, judging by removing parallax.',
            'Record $u$ and $v$ from the lens centre, applying the index correction.',
            'Take at least six readings with $u$ from about $f$ to $2f$ and beyond.',
            'Plot $1/v$ against $1/u$; both intercepts give $1/f$.',
            'Alternatively plot $u$ against $v$ and use the intersection with $u = v = 2f$.',
            'Precautions: lens vertical, tips of object and screen at the same height, dark room.',
            'Error sources: index error of the uprights, blurred judgement of sharpness, thick lens.',
        ],
        'bn': [
            'উদ্দেশ্য: u–v পদ্ধতিতে উত্তল লেন্সের ফোকাস দূরত্ব নির্ণয়।',
            'যন্ত্রপাতি: আলোক বেঞ্চ, ধারকে উত্তল লেন্স, আলোকিত বস্তু, পর্দা, খাড়া দণ্ড।',
            'লেন্স সূত্র $1/f = 1/u + 1/v$, যেখানে $u$ ও $v$ আলোককেন্দ্র থেকে মাপা হয়।',
            'প্রথমে দূরের বস্তু ফোকাস করে আনুমানিক ফোকাস দূরত্ব বের করুন।',
            'বস্তু পিন স্থির করে লেন্সকে তার থেকে $f$-এর বাইরে রাখুন।',
            'দৃষ্টিভ্রম দূর করে পর্দা সরিয়ে স্পষ্ট প্রতিবিম্ব আনুন।',
            'লেন্সের কেন্দ্র থেকে $u$ ও $v$ লিখুন এবং সূচক সংশোধন প্রয়োগ করুন।',
            '$u$ কে $f$ থেকে $2f$ ও তার বাইরে রেখে অন্তত ছয়টি পাঠ নিন।',
            '$1/v$ বনাম $1/u$ আঁকলে দুই অক্ষচ্ছেদই $1/f$ দেয়।',
            'অথবা $u$ বনাম $v$ এঁকে $u = v = 2f$ ছেদবিন্দু ব্যবহার করুন।',
            'সতর্কতা: লেন্স খাড়া রাখুন, বস্তু ও পর্দার অগ্রভাগ একই উচ্চতায়, ঘর অন্ধকার।',
            'ভুলের উৎস: দণ্ডের সূচক ত্রুটি, স্পষ্টতা বিচারে ভুল, মোটা লেন্স।',
        ],
    },
    'physics-prism-refractive-index-hsc': {
        'en': [
            'Aim: determine the refractive index of a prism from its angle and minimum deviation.',
            'Apparatus: spectrometer, prism, sodium lamp, spirit level, reading lens.',
            'Prism angle: $n = \\dfrac{\\sin\\left((A+\\delta_m)/2\\right)}{\\sin(A/2)}$.',
            'Adjust the spectrometer: level the table, focus the telescope on infinity, and set the vertical.',
            'Find the prism angle $A$ from the two reflected images of the slit.',
            'Then turn the table until the deviated image just stops and starts to return.',
            'That turning point is minimum deviation $\\delta_m$; read both verniers.',
            'Repeat three times and take the mean of $A$ and of $\\delta_m$.',
            'Use a monochromatic source, since white light gives a coloured, fuzzy image.',
            'Plot $\\delta$ against the angle of incidence to see the characteristic minimum.',
            'Precautions: no touching the polished faces, tight clamps, no backlash while reading.',
            'Error sources: spectrometer not adjusted, eccentric verniers, stray light, loose prism.',
        ],
        'bn': [
            'উদ্দেশ্য: প্রিজমের কোণ ও ন্যূনতম বিচ্যুতি থেকে প্রতিসরাঙ্ক নির্ণয়।',
            'যন্ত্রপাতি: স্পেকট্রোমিটার, প্রিজম, সোডিয়াম বাতি, স্পিরিট লেভেল, পাঠ লেন্স।',
            'সূত্র: $n = \\dfrac{\\sin\\left((A+\\delta_m)/2\\right)}{\\sin(A/2)}$।',
            'স্পেকট্রোমিটার সমন্বয় করুন: টেবিল সমান্তরাল, দূরবীক্ষণ অসীমে ফোকাস, উল্লম্ব অক্ষ ঠিক।',
            'চিরের দুটি প্রতিফলিত প্রতিবিম্ব থেকে প্রিজম কোণ $A$ বের করুন।',
            'এরপর টেবল ঘোরান যতক্ষণ না বিচ্যুত প্রতিবিম্ব থেমে উল্টো দিকে ফিরতে শুরু করে।',
            'এই বিন্দুই ন্যূনতম বিচ্যুতি $\\delta_m$; দুই ভার্নিয়ারের পাঠ নিন।',
            'তিনবার পুনরাবৃত্তি করে $A$ ও $\\delta_m$-এর গড় নিন।',
            'একরঙা উৎস ব্যবহার করুন, কারণ সাদা আলোয় ঝাপসা রঙিন প্রতিবিম্ব হয়।',
            'আপতন কোণ বনাম $\\delta$ এঁকে বৈশিষ্ট্যসূচক ন্যূনতমটি দেখুন।',
            'সতর্কতা: পালিশ করা তলে হাত নয়, ক্ল্যাম্প শক্ত, পাঠ নেওয়ার সময় ব্যাকল্যাশ নয়।',
            'ভুলের উৎস: সমন্বয়হীন যন্ত্র, কেন্দ্রচ্যুত ভার্নিয়ার, বিক্ষিপ্ত আলো, আলগা প্রিজম।',
        ],
    },
}
