"""Ten to twelve revision points for each school physics practical.

`content/practical-topics.json` used to carry a single one-line note per topic.
These points expand every entry into the short brief a student needs before the
lab: aim, apparatus, the relation used, the steps, what to record, how to
calculate, the graph, precautions, error sources and a viva prompt.

Rules kept across every entry:
* ten to twelve points, one idea each, short enough to scan on a phone;
* relations are written as `$...$` so `MathText` typesets them with KaTeX;
* digits inside a relation stay Latin, Bangla digits stay in the prose;
* Bangla and English points are conceptually parallel, not word-for-word.
"""

POINTS = {
    'physics-ruler-vernier-measurement': {
        'en': [
            'Aim: measure length, diameter and depth correctly with a scale and a vernier.',
            'Apparatus: metre scale, vernier callipers, a wire, a small cylinder, a beaker.',
            'Least count $=$ one main-scale division $\\div$ total vernier divisions.',
            'Close the jaws fully and record the zero error before taking any reading.',
            'Reading $=$ main-scale reading $+$ (vernier division $\\times$ least count) $-$ zero error.',
            'Hold the object gently between the jaws; extra force tilts and springs it.',
            'Measure the same diameter at three places and use the mean value.',
            'Keep the eye exactly above the mark, otherwise parallax shifts the reading.',
            'Tabulate every reading with its unit; do not write values on loose paper.',
            'Error sources: worn jaws, a loose slider, parallax, an uncorrected zero error.',
            'Viva: $n$ vernier divisions equal $(n-1)$ main-scale divisions — that is the whole trick.',
        ],
        'bn': [
            'উদ্দেশ্য: স্কেল ও ভার্নিয়ার দিয়ে দৈর্ঘ্য, ব্যাস ও গভীরতা নির্ভুলভাবে মাপা।',
            'যন্ত্রপাতি: মিটার স্কেল, ভার্নিয়ার ক্যালিপার্স, তার, ছোট সিলিন্ডার, বিকার।',
            'লঘিষ্ঠ গণন $=$ প্রধান স্কেলের এক ঘর $\\div$ ভার্নিয়ারের মোট ঘর।',
            'পাঠ নেওয়ার আগে চোয়াল দুটি পুরো মিলিয়ে শূন্য ত্রুটি লিখে রাখুন।',
            'পাঠ $=$ প্রধান স্কেল পাঠ $+$ (ভার্নিয়ার ঘর $\\times$ লঘিষ্ঠ গণন) $-$ শূন্য ত্রুটি।',
            'বস্তুকে চোয়ালের মধ্যে আলতো করে ধরুন; বেশি চাপে তা বেঁকে যায়।',
            'একই ব্যাস তিন জায়গায় মেপে গড় মান নিন।',
            'চোখ ঠিক দাগের ওপরে রাখুন, না হলে দৃষ্টিভ্রমে পাঠ বদলায়।',
            'প্রতিটি পাঠ এককসহ ছকে লিখুন; ছাড়া কাগজে নয়।',
            'ভুলের উৎস: ক্ষয়প্রাপ্ত চোয়াল, আলগা স্লাইডার, দৃষ্টিভ্রম, শূন্য ত্রুটি না কাটা।',
            'ভাইভা: ভার্নিয়ারের $n$ ঘর প্রধান স্কেলের $(n-1)$ ঘরের সমান — এটাই মূল নীতি।',
        ],
    },
    'physics-density-solid-liquid': {
        'en': [
            'Aim: find the density of an irregular solid and of a liquid.',
            'Apparatus: balance, measuring cylinder, water, thread, the solid and the liquid.',
            'Relation used: $\\rho = m/V$, so mass and volume must be in matching units.',
            'Weigh the dry solid first, before it touches water.',
            'Note the water level, then lower the solid slowly on a thread.',
            'Displaced volume $=$ final level $-$ initial level; read the meniscus at eye level.',
            'For the liquid weigh the empty cylinder, then the cylinder with a known volume.',
            'Convert $\\mathrm{g/cm^3}$ to $\\mathrm{kg/m^3}$ by multiplying by 1000.',
            'Repeat with a second volume and check that density stays the same.',
            'Precautions: no air bubbles on the solid, no splash loss, dry balance pan.',
            'Error sources: meniscus reading, thread volume, balance zero, water on the solid.',
            'Viva: density is a property of the material, so it does not change with sample size.',
        ],
        'bn': [
            'উদ্দেশ্য: একটি অনিয়মিত কঠিন ও একটি তরলের ঘনত্ব নির্ণয়।',
            'যন্ত্রপাতি: তুলা, মাপনী সিলিন্ডার, পানি, সুতা, কঠিন বস্তু ও তরল।',
            'ব্যবহৃত সম্পর্ক: $\\rho = m/V$, তাই ভর ও আয়তনের একক সামঞ্জস্যপূর্ণ রাখুন।',
            'পানিতে ফেলার আগে শুকনো কঠিন বস্তুর ভর নিন।',
            'পানির তল লিখে রাখুন, তারপর সুতা বেঁধে বস্তুটি আস্তে ডোবান।',
            'অপসারিত আয়তন $=$ শেষ তল $-$ শুরুর তল; চোখের সমতলে মেনিস্কাস পড়ুন।',
            'তরলের জন্য খালি সিলিন্ডার, তারপর জানা আয়তনের তরলসহ সিলিন্ডারের ভর নিন।',
            '$\\mathrm{g/cm^3}$ কে $1000$ গুণ করে $\\mathrm{kg/m^3}$-এ নিন।',
            'দ্বিতীয় আয়তনে আবার মেপে দেখুন ঘনত্ব একই থাকে কি না।',
            'সতর্কতা: বস্তুতে বাতাসের বুদবুদ নয়, পানি ছিটানো নয়, তুলার পাত্র শুকনো রাখুন।',
            'ভুলের উৎস: মেনিস্কাস পাঠ, সুতার আয়তন, তুলার শূন্য ত্রুটি, বস্তুতে লেগে থাকা পানি।',
            'ভাইভা: ঘনত্ব পদার্থের নিজস্ব ধর্ম, তাই নমুনার আকারে তা বদলায় না।',
        ],
    },
    'physics-archimedes-principle-lab': {
        'en': [
            'Aim: verify that the loss of apparent weight equals the weight of displaced water.',
            'Apparatus: spring balance, overflow can, measuring cylinder, thread, water, a solid.',
            'Relation used: $F_b = \\rho V g$ acting upwards on the immersed body.',
            'Weigh the solid in air and record it as $W_1$.',
            'Fill the overflow can until water just stops dripping from the spout.',
            'Lower the solid fully into the water while it still hangs from the balance.',
            'Record the new reading $W_2$; the solid must not touch the can walls.',
            'Collect the overflow water in the cylinder and weigh or measure its volume.',
            'Compare $W_1 - W_2$ with the weight of the collected water.',
            'Repeat with the body half immersed and note how the upthrust changes.',
            'Error sources: water left in the spout, splashing, a wet solid, balance zero error.',
            'Viva: the upthrust depends on the displaced volume, not on the depth of immersion.',
        ],
        'bn': [
            'উদ্দেশ্য: আপাত ওজনের হ্রাস যে অপসারিত পানির ওজনের সমান, তা যাচাই।',
            'যন্ত্রপাতি: স্প্রিং তুলা, অফারফ্লো ক্যান, মাপনী সিলিন্ডার, সুতা, পানি, কঠিন বস্তু।',
            'ব্যবহৃত সম্পর্ক: নিমজ্জিত বস্তুর ওপর ঊর্ধ্বমুখী $F_b = \\rho V g$।',
            'বাতাসে বস্তুর ওজন মেপে $W_1$ লিখুন।',
            'অফারফ্লো ক্যানে পানি দিন যতক্ষণ না নল দিয়ে পানি পড়া বন্ধ হয়।',
            'বস্তুটি তুলায় ঝুলিয়ে ধীরে পানিতে পুরো ডোবান।',
            'নতুন পাঠ $W_2$ লিখুন; বস্তু যেন ক্যানের গায়ে না লাগে।',
            'উপচে পড়া পানি সিলিন্ডারে জমিয়ে তার আয়তন বা ওজন নিন।',
            '$W_1 - W_2$-এর সঙ্গে সংগৃহীত পানির ওজনের তুলনা করুন।',
            'বস্তু অর্ধেক ডুবিয়ে আবার দেখুন ঊর্ধ্বমুখী বল কীভাবে বদলায়।',
            'ভুলের উৎস: নলে থেকে যাওয়া পানি, ছিটা, ভেজা বস্তু, তুলার শূন্য ত্রুটি।',
            'ভাইভা: ঊর্ধ্বমুখী বল অপসারিত আয়তনের ওপর নির্ভর করে, কত গভীরে ডুবল তার ওপর নয়।',
        ],
    },
    'physics-simple-pendulum-school': {
        'en': [
            'Aim: study how the period of a simple pendulum depends on its length.',
            'Apparatus: stand, string, small heavy bob, metre scale, stopwatch.',
            'Relation used: $T = 2\\pi\\sqrt{L/g}$, so $T^2$ is proportional to $L$.',
            'Measure the effective length from the point of suspension to the centre of the bob.',
            'Displace the bob by a small angle, about $5^\\circ$, and release without pushing.',
            'Time 20 oscillations and divide by 20; one swing is far too short to time.',
            'Count a full oscillation as there and back, not as one way.',
            'Repeat for lengths such as 50, 60, 70, 80 and 90 cm.',
            'Plot $T^2$ against $L$; the slope equals $4\\pi^2/g$, so $g = 4\\pi^2/\\text{slope}$.',
            'Precautions: rigid support, no spinning bob, no draught, start the stopwatch at the mean position.',
            'Error sources: large amplitude, a stretchy string, reaction time, wrong length measurement.',
            'Viva: the period does not depend on the mass of the bob or on small changes of amplitude.',
        ],
        'bn': [
            'উদ্দেশ্য: সরল দোলকের পর্যায়কাল দৈর্ঘ্যের ওপর কীভাবে নির্ভর করে তা দেখা।',
            'যন্ত্রপাতি: স্ট্যান্ড, সুতা, ছোট ভারী বব, মিটার স্কেল, স্টপওয়াচ।',
            'ব্যবহৃত সম্পর্ক: $T = 2\\pi\\sqrt{L/g}$, অর্থাৎ $T^2$ দৈর্ঘ্যের সমানুপাতিক।',
            'কার্যকর দৈর্ঘ্য মাপুন ঝোলন বিন্দু থেকে ববের কেন্দ্র পর্যন্ত।',
            'ববকে প্রায় $5^\\circ$ কোণে সরিয়ে ধাক্কা ছাড়াই ছেড়ে দিন।',
            '২০টি দোলনের সময় নিয়ে ২০ দিয়ে ভাগ করুন; একটি দোলন মাপার মতো যথেষ্ট নয়।',
            'একটি পূর্ণ দোলন মানে যাওয়া ও ফেরা, শুধু একমুখী গতি নয়।',
            '৫০, ৬০, ৭০, ৮০ ও ৯০ সেমি দৈর্ঘ্যে পরীক্ষাটি পুনরাবৃত্তি করুন।',
            '$T^2$ বনাম $L$ লেখচিত্র আঁকুন; ঢাল $=4\\pi^2/g$, তাই ঢাল দিয়ে $4\\pi^2$ ভাগ করলেই $g$।',
            'সতর্কতা: শক্ত অবলম্বন, বব যেন না ঘোরে, বাতাসের ঝাপটা নয়, ঘড়ি শুরু করুন গড় অবস্থান থেকে।',
            'ভুলের উৎস: বড় বিস্তার, প্রসারণযোগ্য সুতা, প্রতিক্রিয়ার সময়, ভুল দৈর্ঘ্য মাপা।',
            'ভাইভা: ববের ভর বা ছোট বিস্তারের পরিবর্তনে পর্যায়কাল বদলায় না।',
        ],
    },
    'physics-spring-constant-school': {
        'en': [
            'Aim: determine the spring constant from the extension produced by known loads.',
            'Apparatus: spring, stand, mass hanger, slotted masses, metre scale, pointer.',
            'Relation used: $F = kx$ within the elastic limit, so $k = F/x$.',
            'Hang the spring and note the scale reading with the hanger alone.',
            'Add masses in equal steps, for example 50 g each time, up to five loads.',
            'Record the extension after each addition, waiting until the spring stops moving.',
            'Unload step by step and check the readings return to the same values.',
            'Plot load force $F = mg$ on the vertical axis against extension $x$.',
            'The slope of the straight part is $k$ in $\\mathrm{N/m}$; do not use the curved end.',
            'Precautions: never exceed the elastic limit, keep the scale vertical, avoid parallax.',
            'Error sources: a slack initial reading, oscillating spring, worn masses, scale parallax.',
            'Viva: if the graph curves at large loads the spring has passed its elastic limit.',
        ],
        'bn': [
            'উদ্দেশ্য: জানা ভারে সৃষ্ট প্রসারণ থেকে স্প্রিং ধ্রুবক নির্ণয়।',
            'যন্ত্রপাতি: স্প্রিং, স্ট্যান্ড, ভারধারক, কাটা ভার, মিটার স্কেল, নির্দেশক।',
            'ব্যবহৃত সম্পর্ক: স্থিতিস্থাপক সীমার ভেতরে $F = kx$, তাই $k = F/x$।',
            'স্প্রিং ঝুলিয়ে শুধু ভারধারক থাকার স্কেল পাঠ লিখুন।',
            'প্রতিবার যেমন ৫০ g করে সমান ধাপে ভার বাড়ান, সর্বোচ্চ পাঁচটি ভার।',
            'প্রতিটি ভার যোগের পর স্প্রিং স্থির হলে প্রসারণ লিখুন।',
            'ধাপে ধাপে ভার কমিয়ে দেখুন একই পাঠ ফিরে আসে কি না।',
            'উল্লম্ব অক্ষে বল $F = mg$ এবং অনুভূমিক অক্ষে প্রসারণ $x$ নিয়ে লেখচিত্র আঁকুন।',
            'সরলরেখা অংশের ঢালই $k$ ($\\mathrm{N/m}$); বাঁকা অংশ ব্যবহার করবেন না।',
            'সতর্কতা: স্থিতিস্থাপক সীমা অতিক্রম নয়, স্কেল সোজা রাখুন, দৃষ্টিভ্রম এড়ান।',
            'ভুলের উৎস: শুরুর পাঠে আলগা ভাব, দোলনরত স্প্রিং, ক্ষয়প্রাপ্ত ভার, স্কেলের দৃষ্টিভ্রম।',
            'ভাইভা: বেশি ভারে রেখা বেঁকে গেলে বোঝা যায় স্প্রিং স্থিতিস্থাপক সীমা ছাড়িয়েছে।',
        ],
    },
    'physics-lever-inclined-plane-ma': {
        'en': [
            'Aim: find the mechanical advantage of a lever and of an inclined plane.',
            'Apparatus: metre rod and fulcrum, slotted masses, smooth plank, blocks, spring balance.',
            'Mechanical advantage $MA = \\text{load}/\\text{effort}$, and efficiency $= MA/\\text{velocity ratio}$.',
            'For the lever balance the rod on the fulcrum and note the two arms.',
            'Hang the load on one arm and pull or hang the effort on the other until level.',
            'Compare $\\text{load} \\times \\text{load arm}$ with $\\text{effort} \\times \\text{effort arm}$.',
            'For the plane set a fixed height and pull the block up at constant speed.',
            'Read the pulling force with the spring balance held parallel to the plane.',
            'Repeat for three different inclinations and note how the effort changes.',
            'Efficiency is always below 1 because friction consumes part of the effort.',
            'Error sources: balance friction, a spring balance not parallel to the plane, jerky pulling.',
            'Viva: a machine multiplies force, but it never multiplies the work done.',
        ],
        'bn': [
            'উদ্দেশ্য: লিভার ও আনত তলের যান্ত্রিক সুবিধা নির্ণয়।',
            'যন্ত্রপাতি: মিটার দণ্ড ও আলম্ব, কাটা ভার, মসৃণ তক্তা, ব্লক, স্প্রিং তুলা।',
            'যান্ত্রিক সুবিধা $MA = L/E$, যেখানে $L$ ভার ও $E$ প্রযুক্ত বল; দক্ষতা $= MA/VR$।',
            'লিভারের জন্য দণ্ডকে আলম্বের ওপর ভারসাম্য করে দুই বাহু লিখুন।',
            'এক বাহুতে ভার এবং অন্য বাহুতে বল প্রয়োগ করে দণ্ড সমান্তরাল করুন।',
            'ভার $\\times$ ভার বাহু এবং বল $\\times$ বল বাহু তুলনা করুন; দুটি সমান হলে দণ্ড ভারসাম্যে থাকে।',
            'আনত তলের জন্য উচ্চতা স্থির রেখে ব্লককে সমবেগে ওপরে টানুন।',
            'স্প্রিং তুলা তলের সমান্তরাল রেখে টানের বল পড়ুন।',
            'তিনটি ভিন্ন নতিতে পুনরাবৃত্তি করে দেখুন প্রযুক্ত বল কীভাবে বদলায়।',
            'ঘর্ষণ কিছু বল নষ্ট করে বলে দক্ষতা সর্বদা ১-এর কম হয়।',
            'ভুলের উৎস: আলম্বের ঘর্ষণ, তলের সমান্তরাল না রাখা তুলা, ঝাকুনি দিয়ে টানা।',
            'ভাইভা: যন্ত্র বল বাড়ায়, কিন্তু কৃত কাজ কখনো বাড়ায় না।',
        ],
    },
    'physics-friction-coefficient-school': {
        'en': [
            'Aim: measure the coefficient of limiting friction between two surfaces.',
            'Apparatus: wooden block with hook, plank, slotted masses, spring balance, thread.',
            'Relation used: $\\mu = F_{\\text{limiting}}/N$, where $N$ is the normal reaction.',
            'Place the block on the horizontal plank and hook the spring balance to it.',
            'Pull gently and steadily; note the reading at the instant the block just starts.',
            'That maximum reading is the limiting friction, not the reading while sliding.',
            'Add masses on the block to increase $N = mg$ and repeat the pull.',
            'Tabulate normal reaction against limiting friction for at least four loads.',
            'Plot limiting friction against normal reaction; the slope gives $\\mu$.',
            'Alternatively raise one end of the plank until sliding starts: $\\mu = \\tan\\theta$.',
            'Error sources: jerky pulling, a tilted balance, dust on the surfaces, worn spring.',
            'Viva: friction is roughly independent of the apparent area of contact.',
        ],
        'bn': [
            'উদ্দেশ্য: দুটি তলের মধ্যে সীমায়িত ঘর্ষণ গুণাঙ্ক নির্ণয়।',
            'যন্ত্রপাতি: আঁটাসহ কাঠের ব্লক, তক্তা, কাটা ভার, স্প্রিং তুলা, সুতা।',
            'ব্যবহৃত সম্পর্ক: $\\mu = F_{\\text{limiting}}/N$, যেখানে $N$ অভিলম্ব প্রতিক্রিয়া।',
            'ব্লককে অনুভূমিক তক্তায় রেখে তুলার আঁটায় যুক্ত করুন।',
            'আলতো ও সমভাবে টানুন; ব্লক নড়ার ঠিক মুহূর্তের পাঠ লিখুন।',
            'এই সর্বোচ্চ পাঠই সীমায়িত ঘর্ষণ; পিছলে চলার পাঠ নয়।',
            'ব্লকের ওপর ভার রেখে $N = mg$ বাড়ান এবং আবার টানুন।',
            'অন্তত চারটি ভারের জন্য অভিলম্ব বল ও সীমায়িত ঘর্ষণ ছকে লিখুন।',
            'সীমায়িত ঘর্ষণ বনাম অভিলম্ব বল লেখচিত্র আঁকুন; ঢাল থেকে $\\mu$ পাওয়া যায়।',
            'বিকল্পভাবে তক্তার এক প্রান্ত তুলে ধরুন যতক্ষণ না পিছলানো শুরু হয়: $\\mu = \\tan\\theta$।',
            'ভুলের উৎস: ঝাকুনিতে টানা, হেলে থাকা তুলা, তলে ময়লা, পুরনো স্প্রিং।',
            'ভাইভা: স্পর্শতলের আপাত ক্ষেত্রফলের ওপর ঘর্ষণ প্রায় নির্ভরশীল নয়।',
        ],
    },
    'physics-specific-heat-mixture-school': {
        'en': [
            'Aim: find the specific heat capacity of a solid by the method of mixtures.',
            'Apparatus: calorimeter, stirrer, thermometer, water, solid pieces, beaker, heater, balance.',
            'Principle: heat lost by the hot body $=$ heat gained by water and calorimeter.',
            'Weigh the solid, then heat it in boiling water until its temperature is steady.',
            'Weigh the calorimeter with water and record the initial water temperature.',
            'Transfer the hot solid quickly into the calorimeter and cover it.',
            'Stir gently and record the highest steady temperature reached.',
            'Use $m_sc_s(T_s-T_m)=(m_wc_w+m_cc_c)(T_m-T_w)$ to find the unknown $c_s$.',
            'Keep the thermometer bulb in the water, never resting on the solid.',
            'Error sources: heat lost during transfer, evaporation, poor stirring, lagging thermometer.',
            'Precautions: lag the calorimeter, use a lid, and read temperatures at eye level.',
            'Viva: a polished lid and lagging reduce radiation loss, so the result is closer to theory.',
        ],
        'bn': [
            'উদ্দেশ্য: মিশ্রণ পদ্ধতিতে কঠিনের আপেক্ষিক তাপ নির্ণয়।',
            'যন্ত্রপাতি: ক্যালোরিমিটার, নাড়ুনি, তাপমাপক, পানি, কঠিনের টুকরা, বিকার, হিটার, তুলা।',
            'নীতি: গরম বস্তুর বর্জিত তাপ $=$ পানি ও ক্যালোরিমিটারের গৃহীত তাপ।',
            'কঠিনের ভর নিয়ে ফুটন্ত পানিতে রাখুন যতক্ষণ তাপমাত্রা স্থির হয়।',
            'পানিসহ ক্যালোরিমিটারের ভর এবং পানির শুরুর তাপমাত্রা লিখুন।',
            'গরম কঠিনটি দ্রুত ক্যালোরিমিটারে ফেলে ঢাকনা দিন।',
            'আলতো নেড়ে সর্বোচ্চ স্থির তাপমাত্রা লিখুন।',
            '$m_sc_s(T_s-T_m)=(m_wc_w+m_cc_c)(T_m-T_w)$ থেকে অজানা $c_s$ বের করুন।',
            'তাপমাপকের বাল্ব পানিতে রাখুন, কঠিনের গায়ে নয়।',
            'ভুলের উৎস: স্থানান্তরে তাপ হ্রাস, বাষ্পীভবন, দুর্বল নাড়া, তাপমাপকের জড়তা।',
            'সতর্কতা: ক্যালোরিমিটার অন্তরিত রাখুন, ঢাকনা ব্যবহার করুন, চোখের সমতলে তাপমাত্রা পড়ুন।',
            'ভাইভা: চকচকে ঢাকনা ও অন্তরণে বিকিরণ ক্ষয় কমে, তাই ফল তত্ত্বের কাছাকাছি আসে।',
        ],
    },
    'physics-ohms-law-school': {
        'en': [
            'Aim: verify Ohm’s law for a resistor and find its resistance.',
            'Apparatus: cell or battery, rheostat, resistor, ammeter, voltmeter, key, connecting wires.',
            'Relation used: $V = IR$, so a graph of $V$ against $I$ should be a straight line.',
            'Connect the ammeter in series and the voltmeter across the resistor only.',
            'Check the zero of both meters and note their least counts.',
            'Close the key, adjust the rheostat and record one pair of $V$ and $I$.',
            'Take at least five readings by changing the rheostat each time.',
            'Keep the current small and switch off between readings to avoid heating.',
            'Plot $V$ on the vertical axis against $I$; the slope is the resistance $R$.',
            'Alternatively compute $R = V/I$ for each pair and take the mean.',
            'Error sources: heating of the resistor, loose contacts, meter zero error, wrong range.',
            'Viva: a filament lamp does not obey Ohm’s law because its resistance rises with temperature.',
        ],
        'bn': [
            'উদ্দেশ্য: রোধকের ক্ষেত্রে ওহমের সূত্র যাচাই ও তার রোধ নির্ণয়।',
            'যন্ত্রপাতি: সেল বা ব্যাটারি, রিওস্ট্যাট, রোধক, অ্যামিটার, ভোল্টমিটার, চাবি, সংযোগ তার।',
            'ব্যবহৃত সম্পর্ক: $V = IR$, তাই $V$ বনাম $I$ লেখচিত্র সরলরেখা হওয়ার কথা।',
            'অ্যামিটারকে শ্রেণিতে এবং ভোল্টমিটারকে শুধু রোধকের দুই প্রান্তে যুক্ত করুন।',
            'দুটি মিটারের শূন্য পাঠ ও লঘিষ্ঠ গণন লিখে রাখুন।',
            'চাবি বন্ধ করে রিওস্ট্যাট সামলে $V$ ও $I$-এর একটি জোড়া লিখুন।',
            'প্রতিবার রিওস্ট্যাট বদলে অন্তত পাঁচটি পাঠ নিন।',
            'প্রবাহ কম রাখুন ও পাঠের মাঝে চাবি খুলুন, যাতে রোধক গরম না হয়।',
            'উল্লম্ব অক্ষে $V$ ও অনুভূমিক অক্ষে $I$ নিয়ে লেখচিত্র আঁকুন; ঢালই রোধ $R$।',
            'অথবা প্রতি জোড়ার জন্য $R = V/I$ বের করে গড় নিন।',
            'ভুলের উৎস: রোধকের উত্তাপ, আলগা সংযোগ, মিটারের শূন্য ত্রুটি, ভুল রেঞ্জ।',
            'ভাইভা: ফিলামেন্ট বাতি ওহমের সূত্র মানে না, কারণ তাপমাত্রায় তার রোধ বাড়ে।',
        ],
    },
    'physics-series-parallel-resistance-school': {
        'en': [
            'Aim: verify the laws of series and parallel combination of resistors.',
            'Apparatus: two known resistors, battery, key, ammeter, voltmeter, rheostat, wires.',
            'Series law: $R_s = R_1 + R_2$, the same current flows through both.',
            'Parallel law: $R_p^{-1} = R_1^{-1} + R_2^{-1}$, the same potential difference across both.',
            'First measure each resistor alone by the ratio $R = V/I$.',
            'Then connect them in series and measure the combined resistance the same way.',
            'Reconnect them in parallel and measure the combined resistance again.',
            'Compare each measured value with the calculated one and find the percentage error.',
            'In series the voltmeter reads different voltages across the two resistors.',
            'In parallel the ammeter reads different currents in the two branches.',
            'Error sources: heating, contact resistance, meter zero error, resistor tolerance.',
            'Viva: the parallel combination is always smaller than the smallest resistor used.',
        ],
        'bn': [
            'উদ্দেশ্য: রোধের শ্রেণি ও সমান্তরাল সমবায়ের সূত্র যাচাই।',
            'যন্ত্রপাতি: দুটি জানা রোধক, ব্যাটারি, চাবি, অ্যামিটার, ভোল্টমিটার, রিওস্ট্যাট, তার।',
            'শ্রেণি সূত্র: $R_s = R_1 + R_2$; দুটির মধ্য দিয়ে একই প্রবাহ চলে।',
            'সমান্তরাল সূত্র: $R_p^{-1} = R_1^{-1} + R_2^{-1}$; দুটির বিভব পার্থক্য একই।',
            'প্রথমে প্রতিটি রোধক আলাদাভাবে $R = V/I$ অনুপাতে মেপে নিন।',
            'তারপর শ্রেণিতে যুক্ত করে একইভাবে সমবায়ের রোধ মাপুন।',
            'এরপর সমান্তরালে যুক্ত করে আবার সমবায়ের রোধ মাপুন।',
            'মাপা মানের সঙ্গে হিসাব করা মান তুলনা করে শতকরা ভুল বের করুন।',
            'শ্রেণিতে দুই রোধকের দুই পাশে ভোল্টমিটারের পাঠ আলাদা হয়।',
            'সমান্তরালে দুই শাখায় অ্যামিটারের পাঠ আলাদা হয়।',
            'ভুলের উৎস: উত্তাপ, সংযোগ রোধ, মিটারের শূন্য ত্রুটি, রোধকের সহনশীলতা।',
            'ভাইভা: সমান্তরাল সমবায়ের রোধ সর্বদা ব্যবহৃত ক্ষুদ্রতম রোধকের চেয়ে কম।',
        ],
    },
    'physics-glass-slab-refraction-school': {
        'en': [
            'Aim: trace a ray through a glass slab and find the refractive index.',
            'Apparatus: glass slab, drawing board, white paper, pins, protractor, ruler, pencil.',
            'Relation used: $n = \\sin i/\\sin r$ from Snell’s law.',
            'Fix the paper on the board and trace the outline of the slab.',
            'Draw a normal at one face and an incident ray at a chosen angle, say $30^\\circ$.',
            'Fix two pins vertically on the incident ray, about 5 cm apart.',
            'Looking from the other side, fix two more pins so all four appear in one line.',
            'Remove the slab, join the emergent pins and mark the refracted path inside.',
            'Measure the angle of incidence, refraction and emergence with the protractor.',
            'Repeat for $40^\\circ$, $50^\\circ$ and $60^\\circ$ and tabulate $\\sin i$ against $\\sin r$.',
            'The incident and emergent rays are parallel; the ray is only displaced sideways.',
            'Error sources: thick pins, tilted pins, a slab that moved while marking, coarse protractor.',
        ],
        'bn': [
            'উদ্দেশ্য: কাচের স্ল্যাবের মধ্য দিয়ে রশ্মির পথ আঁকুন ও প্রতিসরাঙ্ক নির্ণয় করুন।',
            'যন্ত্রপাতি: কাচের স্ল্যাব, ড্রয়িং বোর্ড, সাদা কাগজ, পিন, চাঁদা, স্কেল, পেন্সিল।',
            'ব্যবহৃত সম্পর্ক: স্নেলের সূত্র অনুযায়ী $n = \\sin i/\\sin r$।',
            'কাগজ বোর্ডে আটকে স্ল্যাবের সীমারেখা এঁকে নিন।',
            'এক তলে অভিলম্ব এবং নির্দিষ্ট কোণে (যেমন $30^\\circ$) আপতিত রশ্মি আঁকুন।',
            'আপতিত রশ্মির ওপর প্রায় ৫ সেমি দূরে দুটি পিন খাড়া করে বসান।',
            'অপর পাশ থেকে দেখে আরও দুটি পিন বসান যেন চারটিই এক সরলরেখায় মনে হয়।',
            'স্ল্যাব সরিয়ে নির্গত পিন দুটি যুক্ত করুন এবং ভেতরের প্রতিসৃত পথ চিহ্নিত করুন।',
            'চাঁদা দিয়ে আপতন, প্রতিসরণ ও নির্গমন কোণ মাপুন।',
            '$40^\\circ$, $50^\\circ$ ও $60^\\circ$-এর জন্য পুনরাবৃত্তি করে $\\sin i$ বনাম $\\sin r$ ছকে লিখুন।',
            'আপতিত ও নির্গত রশ্মি সমান্তরাল; রশ্মি শুধু পাশে সরে যায়।',
            'ভুলের উৎস: মোটা পিন, হেলে থাকা পিন, দাগ দেওয়ার সময় সরে যাওয়া স্ল্যাব, মোটা চাঁদা।',
        ],
    },
    'physics-lens-mirror-image-school': {
        'en': [
            'Aim: locate images formed by a convex lens and a concave mirror.',
            'Apparatus: convex lens, concave mirror, stands, a candle or illuminated object, screen, scale.',
            'Lens relation: $1/f = 1/v - 1/u$ with the sign convention taught in class.',
            'First find the rough focal length by focusing a distant object on the screen.',
            'Place the object beyond $2f$ and move the screen until the image is sharp.',
            'Record object distance $u$, image distance $v$ and whether the image is real or inverted.',
            'Bring the object closer step by step and repeat until it is inside $f$.',
            'Inside $f$ no image forms on the screen — it becomes virtual and magnified.',
            'For the concave mirror the same procedure gives a real inverted image outside $f$.',
            'Plot $1/v$ against $1/u$; the intercepts give $1/f$ for the lens.',
            'Error sources: parallax while judging sharpness, a tilted screen, thick lens assumption.',
            'Viva: a real image can be caught on a screen, a virtual image cannot.',
        ],
        'bn': [
            'উদ্দেশ্য: উত্তল লেন্স ও অবতল দর্পণে গঠিত প্রতিবিম্বের অবস্থান নির্ণয়।',
            'যন্ত্রপাতি: উত্তল লেন্স, অবতল দর্পণ, স্ট্যান্ড, মোমবাতি বা আলোকিত বস্তু, পর্দা, স্কেল।',
            'লেন্সের সম্পর্ক: শ্রেণিতে শেখানো চিহ্ন প্রথা মেনে $1/f = 1/v - 1/u$।',
            'প্রথমে দূরের বস্তু পর্দায় ফোকাস করে আনুমানিক ফোকাস দূরত্ব বের করুন।',
            'বস্তুকে $2f$-এর বাইরে রেখে পর্দা সরিয়ে স্পষ্ট প্রতিবিম্ব আনুন।',
            'বস্তুর দূরত্ব $u$, প্রতিবিম্বের দূরত্ব $v$ এবং প্রতিবিম্ব বাস্তব না উল্টো তা লিখুন।',
            'বস্তুকে ধাপে ধাপে কাছে আনুন এবং $f$-এর ভেতরে না আসা পর্যন্ত পুনরাবৃত্তি করুন।',
            '$f$-এর ভেতরে পর্দায় প্রতিবিম্ব আসে না — তখন তা অবাস্তব ও বিবর্ধিত হয়।',
            'অবতল দর্পণে একই ধাপে $f$-এর বাইরে বাস্তব ও উল্টো প্রতিবিম্ব পাওয়া যায়।',
            '$1/v$ বনাম $1/u$ লেখচিত্র আঁকলে অক্ষচ্ছেদ থেকে লেন্সের $1/f$ পাওয়া যায়।',
            'ভুলের উৎস: স্পষ্টতা বিচারে দৃষ্টিভ্রম, হেলে থাকা পর্দা, মোটা লেন্সের অনুমান।',
            'ভাইভা: বাস্তব প্রতিবিম্ব পর্দায় ফেলা যায়, অবাস্তব প্রতিবিম্ব যায় না।',
        ],
    },
}
