"""Points for the second half of the HSC physics practicals: optics, electricity,
magnetism, electronics and mechanics verification experiments. Merged into the
`POINTS` dictionary of `practical_points_physics_hsc`:
`scripts/add-practical-topic-points.py` imports both modules.
"""

POINTS = {
    'physics-spectrometer-hsc': {
        'en': [
            'Aim: adjust a spectrometer and use it to measure angles accurately.',
            'Apparatus: spectrometer, spirit level, prism or grating, sodium lamp, reading lens.',
            'Adjustment has three stages: the telescope, the collimator and the table.',
            'Focus the telescope on a distant object so it receives parallel rays.',
            'Focus the collimator on the slit until the slit image is sharp, with no parallax.',
            'Level the table with the spirit level and the levelling screws.',
            'Set the telescope vertical and the collimator slit vertical too.',
            'Bring the cross-wire on to the image before every reading, avoiding backlash.',
            'Always read both verniers and take their mean to cancel eccentricity.',
            'Practice reading the vernier scale to the least count before the experiment.',
            'Precautions: do not touch optical surfaces, tighten clamps gently, keep the room dim.',
            'Error sources: unlevelled table, blurred slit, backlash, single-vernier readings.',
        ],
        'bn': [
            'উদ্দেশ্য: স্পেকট্রোমিটার সমন্বয় করে তা দিয়ে নিখুঁত কোণ মাপা।',
            'যন্ত্রপাতি: স্পেকট্রোমিটার, স্পিরিট লেভেল, প্রিজম বা গ্রেটিং, সোডিয়াম বাতি, পাঠ লেন্স।',
            'সমন্বয়ের তিন ধাপ: দূরবীক্ষণ, কোলিমেটর এবং টেবিল।',
            'দূরের বস্তুতে দূরবীক্ষণ ফোকাস করুন যাতে সমান্তরাল রশ্মি পায়।',
            'দৃষ্টিভ্রম ছাড়া চিরের প্রতিবিম্ব স্পষ্ট হওয়া পর্যন্ত কোলিমেটর ফোকাস করুন।',
            'স্পিরিট লেভেল ও সমন্বয় স্ক্রু দিয়ে টেবিল সমতল করুন।',
            'দূরবীক্ষণ এবং চির দুটোই উল্লম্ব রাখুন।',
            'প্রতিটি পাঠের আগে ক্রস-ওয়্যার প্রতিবিম্বের ওপর আনুন এবং ব্যাকল্যাশ এড়ান।',
            'কেন্দ্রচ্যুতি বাতিল করতে সর্বদা দুই ভার্নিয়ারের পাঠের গড় নিন।',
            'পরীক্ষার আগে ভার্নিয়ার স্কেল লঘিষ্ঠ গণন পর্যন্ত পড়ার অনুশীলন করুন।',
            'সতর্কতা: আলোক তলে হাত নয়, ক্ল্যাম্প আস্তে আঁটুন, ঘর আধা-অন্ধকার রাখুন।',
            'ভুলের উৎস: অসমতল টেবিল, ঝাপসা চির, ব্যাকল্যাশ, এক ভার্নিয়ারের পাঠ।',
        ],
    },
    'physics-newtons-rings-hsc': {
        'en': [
            'Aim: determine the wavelength of sodium light with Newton’s rings.',
            'Apparatus: Newton’s ring apparatus, plane glass plate, travelling microscope, sodium lamp.',
            'For a dark ring of order $n$, $D_n^2 = 4n\\lambda R$, so $D_n^2$ is proportional to $n$.',
            'Wedge a thin piece of glass at $45^\\circ$ so the lamp light falls normally on the film.',
            'Focus the microscope on the rings, then move to the centre of the pattern.',
            'Count rings outward without losing track; a miscount changes every result.',
            'Read the cross-wire on the $n$th ring on both sides, then use $D_n = 2 \\times$ radius reading.',
            'Eliminate $R$ by taking $D_{n+p}^2 - D_n^2 = 4p\\lambda R$, which cancels $R$ with a second pair.',
            'Measure for two orders separated by about 10 rings to reduce error.',
            'Use monochromatic light; white light gives coloured rings with no clear order.',
            'Precautions: clean lens and plate, no dust between them, gentle microscope movement, no backlash.',
            'Error sources: dust or dirt in the film, miscounted rings, parallax, a dirty objective.',
        ],
        'bn': [
            'উদ্দেশ্য: নিউটনের বলয় দিয়ে সোডিয়াম আলোর তরঙ্গদৈর্ঘ্য নির্ণয়।',
            'যন্ত্রপাতি: নিউটন বলয় যন্ত্র, সমতল কাচের পাত, ট্রাভেলিং অণুবীক্ষণ, সোডিয়াম বাতি।',
            '$n$-তম অন্ধকার বলয়ে $D_n^2 = 4n\\lambda R$, অর্থাৎ $D_n^2$ সমানুপাতিক $n$-এর।',
            'একটি পাতলা কাচ $45^\\circ$ কোণে রেখে বাতির আলো লম্বভাবে ফেলুন।',
            'অণুবীক্ষণে বলয় ফোকাস করে নকশার কেন্দ্রে আনুন।',
            'বাইরের দিকে বলয় গুনুন, হিসাব হারাবেন না; এক ভুল গণনা সব ফল বদলে দেয়।',
            'উভয় পাশে $n$-তম বলয়ে ক্রস-ওয়্যারের পাঠ নিয়ে $D_n = 2 \\times$ ব্যাসার্ধ-পাঠ ধরুন।',
            '$R$ বাদ দিতে $D_{n+p}^2 - D_n^2 = 4p\\lambda R$ সম্পর্ক ব্যবহার করুন।',
            'প্রায় ১০টি বলয় ব্যবধানে দুটি ক্রম মেপে ত্রুটি কমান।',
            'একরঙা আলো নিন; সাদা আলোয় রঙিন বলয়ে ক্রম নির্ণয় কঠিন।',
            'সতর্কতা: লেন্স ও পাত পরিষ্কার, মাঝে ধুলা নয়, অণুবীক্ষণ আস্তে সরান, ব্যাকল্যাশ নয়।',
            'ভুলের উৎস: স্তরে ধুলা বা ময়লা, ভুল বলয় গণনা, দৃষ্টিভ্রম, ময়লা অভিলক্ষ্য।',
        ],
    },
    'physics-diffraction-grating-hsc': {
        'en': [
            'Aim: determine the wavelength of light using a plane diffraction grating.',
            'Apparatus: spectrometer, diffraction grating, sodium or mercury lamp, reading lens.',
            'The grating equation is $d\\sin\\theta = n\\lambda$, where $d$ is the grating spacing.',
            'If the grating has $N$ lines per inch, then $d = 2.54/N$ cm.',
            'Adjust the spectrometer and set the grating surface normal to the incident beam.',
            'Look through the telescope and note the angular position of the direct image.',
            'Turn the telescope to the first-order image on one side and read both verniers.',
            'Repeat for the same order on the other side; $2\\theta$ is the angle between them.',
            'Measure the second and third orders too and take the mean wavelength.',
            'Do not touch the ruled surface; hold the grating only by its edges.',
            'Precautions: no stray light, tight grating holder, no backlash while turning the telescope.',
            'Error sources: grating not normal to the beam, blurred image, wrong line density, eccentric verniers.',
        ],
        'bn': [
            'উদ্দেশ্য: সমতল অপবর্তন গ্রেটিং দিয়ে আলোর তরঙ্গদৈর্ঘ্য নির্ণয়।',
            'যন্ত্রপাতি: স্পেকট্রোমিটার, অপবর্তন গ্রেটিং, সোডিয়াম বা পারদ বাতি, পাঠ লেন্স।',
            'গ্রেটিং সমীকরণ $d\\sin\\theta = n\\lambda$, যেখানে $d$ গ্রেটিং ব্যবধান।',
            'প্রতি ইঞ্চিতে $N$ রেখা থাকলে $d = 2.54/N$ সেমি।',
            'স্পেকট্রোমিটার সমন্বয় করে গ্রেটিং তল আপতিত রশ্মির লম্ব রাখুন।',
            'দূরবীক্ষণে সরাসরি প্রতিবিম্বের কৌণিক অবস্থান লিখে রাখুন।',
            'এক পাশে প্রথম ক্রমের প্রতিবিম্বে দূরবীক্ষণ ঘুরিয়ে দুই ভার্নিয়ারের পাঠ নিন।',
            'অন্য পাশেও একই ক্রম মাপুন; দুই পাঠের পার্থক্যই $2\\theta$।',
            'দ্বিতীয় ও তৃতীয় ক্রমও মেপে গড় তরঙ্গদৈর্ঘ্য বের করুন।',
            'দাগানো তলে হাত দেবেন না; গ্রেটিং শুধু কিনারা ধরে রাখুন।',
            'সতর্কতা: বিক্ষিপ্ত আলো নয়, গ্রেটিং ধারক শক্ত, দূরবীক্ষণ ঘোরানোর সময় ব্যাকল্যাশ নয়।',
            'ভুলের উৎস: রশ্মির লম্ব না হওয়া, ঝাপসা প্রতিবিম্ব, ভুল রেখাঘনত্ব, কেন্দ্রচ্যুত ভার্নিয়ার।',
        ],
    },
    'physics-meter-bridge-hsc': {
        'en': [
            'Aim: find an unknown resistance with a meter bridge.',
            'Apparatus: meter bridge, resistance box, galvanometer, cell, jockey, key, connecting wires.',
            'At balance $\\dfrac{X}{R} = \\dfrac{l}{100-l}$, where $l$ is the balance length in cm.',
            'Check the polarity and all connections before closing the key.',
            'Start with a resistance in the box that puts the balance near the middle.',
            'Touch the jockey lightly and slide it to find the null point.',
            'A balance near the ends is unreliable — change $R$ and repeat.',
            'Take at least four readings with different known resistances.',
            'Interchange $X$ and $R$ to remove the end-resistance error, then repeat.',
            'Use the mean of the readings rather than a single value of $X$.',
            'Precautions: keep the key closed only while reading, do not drag the jockey, clean terminals.',
            'Error sources: contact resistance, non-uniform wire, heating of the wire, a sensitive galvanometer drifting.',
        ],
        'bn': [
            'উদ্দেশ্য: মিটার ব্রিজে অজানা রোধ নির্ণয়।',
            'যন্ত্রপাতি: মিটার ব্রিজ, রোধ বাক্স, গ্যালভানোমিটার, কোষ, জকি, চাবি, সংযোগ তার।',
            'ভারসাম্যে $\\dfrac{X}{R} = \\dfrac{l}{100-l}$, যেখানে $l$ সেমি-তে ভারসাম্য দৈর্ঘ্য।',
            'চাবি বন্ধ করার আগে মেরুতা ও সব সংযোগ যাচাই করুন।',
            'বাক্সে এমন রোধ নিন যাতে ভারসাম্য বিন্দু মাঝামাঝি আসে।',
            'জকি আলতো ছুঁইয়ে সরিয়ে শূন্য বিন্দু খুঁজুন।',
            'প্রান্তের কাছে ভারসাম্য নির্ভরযোগ্য নয় — $R$ বদলে আবার চেষ্টা করুন।',
            'বিভিন্ন জানা রোধে অন্তত চারটি পাঠ নিন।',
            'প্রান্ত রোধের ত্রুটি কাটাতে $X$ ও $R$ অদলবদল করে পুনরাবৃত্তি করুন।',
            'একটি মানের বদলে পাঠগুলোর গড় থেকে $X$ নিন।',
            'সতর্কতা: পাঠ নেওয়ার সময় ছাড়া চাবি খোলা রাখুন, জকি টানবেন না, টার্মিনাল পরিষ্কার রাখুন।',
            'ভুলের উৎস: স্পর্শ রোধ, অসম তার, তারের উত্তাপ, সংবেদী গ্যালভানোমিটারের বিচ্যুতি।',
        ],
    },
    'physics-potentiometer-hsc': {
        'en': [
            'Aim: compare the emf of two cells with a potentiometer.',
            'Apparatus: potentiometer wire, driver cell, rheostat, two cells, galvanometer, jockey, key.',
            'At balance $\\dfrac{E_1}{E_2} = \\dfrac{l_1}{l_2}$, so no internal-resistance correction is needed.',
            'The driver cell emf must exceed both cell emfs, otherwise there is no balance point.',
            'Connect the positive of the test cell to the high-potential end of the wire.',
            'Check the deflection direction: it must reverse when the jockey moves across the null.',
            'Find the balance length $l_1$ for the first cell, tapping the jockey lightly.',
            'Replace the cell and find $l_2$ for the second cell without touching the rheostat.',
            'Repeat each measurement three times and use the mean lengths.',
            'The method draws no current at balance, which is why it beats a voltmeter.',
            'Precautions: do not change the rheostat between readings, do not drag the jockey, firm contacts.',
            'Error sources: driver emf falling, contact resistance, parallax on the scale, a non-uniform wire.',
        ],
        'bn': [
            'উদ্দেশ্য: পোটেনশিয়োমিটারে দুটি কোষের তড়িচ্চালক বল তুলনা।',
            'যন্ত্রপাতি: পোটেনশিয়োমিটার তার, চালক কোষ, রিওস্ট্যাট, দুটি কোষ, গ্যালভানোমিটার, জকি, চাবি।',
            'ভারসাম্যে $\\dfrac{E_1}{E_2} = \\dfrac{l_1}{l_2}$, তাই অভ্যন্তরীণ রোধ সংশোধন লাগে না।',
            'চালক কোষের emf দুটি কোষের চেয়ে বড় হতে হবে, নইলে ভারসাম্য বিন্দু মিলবে না।',
            'পরীক্ষণ কোষের ধনাত্মক প্রান্ত তারের উচ্চ বিভব প্রান্তে যুক্ত করুন।',
            'বিচ্যুতির দিক যাচাই করুন: শূন্য বিন্দু পার হলে তা উল্টে যাবে।',
            'জকি আলতো ছুঁইয়ে প্রথম কোষের ভারসাম্য দৈর্ঘ্য $l_1$ বের করুন।',
            'রিওস্ট্যাট না ছুঁয়ে দ্বিতীয় কোষ বসিয়ে $l_2$ নির্ণয় করুন।',
            'প্রতিটি মাপ তিনবার করে গড় দৈর্ঘ্য নিন।',
            'ভারসাম্যে কোনো প্রবাহ টানে না বলেই এটি ভোল্টমিটারের চেয়ে ভালো।',
            'সতর্কতা: পাঠের মাঝে রিওস্ট্যাট বদলাবেন না, জকি টানবেন না, সংযোগ শক্ত রাখুন।',
            'ভুলের উৎস: চালক emf কমে যাওয়া, স্পর্শ রোধ, স্কেলে দৃষ্টিভ্রম, অসম তার।',
        ],
    },
    'physics-galvanometer-conversion-hsc': {
        'en': [
            'Aim: find the galvanometer resistance and convert it into an ammeter and a voltmeter.',
            'Apparatus: galvanometer, resistance box, cell, rheostat, key, standard voltmeter and ammeter.',
            'Figure of merit $k$ is the current needed for one division of deflection.',
            'For an ammeter the shunt is $S = \\dfrac{I_gG}{I - I_g}$, connected in parallel.',
            'For a voltmeter the series resistance is $R_s = \\dfrac{V}{I_g} - G$.',
            'Find $G$ by the half-deflection method: note $\\theta$, then halve it with a shunt.',
            'With half deflection the shunt resistance equals $G$, so read it off the box.',
            'Choose the desired range, then compute $S$ or $R_s$ before wiring anything.',
            'Verify against a standard meter and record the percentage difference.',
            'Precautions: protect the galvanometer with a high series resistance while setting up.',
            'Never connect the converted ammeter across a source; it will burn out.',
            'Error sources: battery emf changing during the experiment, contact resistance, parallax on the scale.',
        ],
        'bn': [
            'উদ্দেশ্য: গ্যালভানোমিটারের রোধ নির্ণয় করে অ্যামিটার ও ভোল্টমিটারে রূপান্তর।',
            'যন্ত্রপাতি: গ্যালভানোমিটার, রোধ বাক্স, কোষ, রিওস্ট্যাট, চাবি, আদর্শ ভোল্টমিটার ও অ্যামিটার।',
            'যোগ্যতা গুণাঙ্ক $k$ হলো এক ঘর বিচ্যুতির জন্য প্রয়োজনীয় প্রবাহ।',
            'অ্যামিটারের শান্ট $S = \\dfrac{I_gG}{I - I_g}$, যা সমান্তরালে বসে।',
            'ভোল্টমিটারের সিরিজ রোধ $R_s = \\dfrac{V}{I_g} - G$।',
            'অর্ধ-বিচ্যুতি পদ্ধতিতে $G$ বের করুন: $\\theta$ লিখে শান্ট দিয়ে তা অর্ধেক করুন।',
            'অর্ধেক বিচ্যুতিতে শান্ট রোধ $G$-এর সমান, তাই বাক্সের পাঠই $G$।',
            'কাঙ্ক্ষিত পরিসর ঠিক করে সংযোগের আগেই $S$ বা $R_s$ হিসাব করুন।',
            'আদর্শ মিটারের সঙ্গে মিলিয়ে শতকরা পার্থক্য লিখুন।',
            'সতর্কতা: যন্ত্র সাজানোর সময় গ্যালভানোমিটারের সঙ্গে উচ্চ সিরিজ রোধ রাখুন।',
            'রূপান্তরিত অ্যামিটার কখনো উৎসের দুই প্রান্তে লাগাবেন না; এটি পুড়ে যাবে।',
            'ভুলের উৎস: পরীক্ষার মাঝে ব্যাটারির emf পরিবর্তন, স্পর্শ রোধ, স্কেলে দৃষ্টিভ্রম।',
        ],
    },
    'physics-deflection-magnetometer-hsc': {
        'en': [
            'Aim: compare the magnetic moments of two bar magnets with a deflection magnetometer.',
            'Apparatus: deflection magnetometer in Tan-A position, two bar magnets, metre scale, box compass.',
            'In the Tan-A position $B = B_H\\tan\\theta$, giving $M \\propto d^3\\tan\\theta$.',
            'Level the instrument and set the needle along the magnetic meridian.',
            'Place a magnet on one arm with its axis along the arm, at a measured distance $d$.',
            'Read the deflections at both ends of the needle and take the mean.',
            'Repeat with the magnet reversed — the deflections must agree, or the needle is not free.',
            'Find deflections for several distances and for the second magnet too.',
            'Compare moments from $\\dfrac{M_1}{M_2} = \\dfrac{d_1^3\\tan\\theta_1}{d_2^3\\tan\\theta_2}$.',
            'Plot $\\tan\\theta$ against $1/d^3$; the slope is proportional to the moment.',
            'Precautions: no iron or magnetic objects nearby, arms along the magnetic meridian, gentle handling.',
            'Error sources: nearby steel, an unlevelled box, parallax, a magnet not exactly on the axis.',
        ],
        'bn': [
            'উদ্দেশ্য: বিচ্যুতি চুম্বকমাপকে দুটি দণ্ডচুম্বকের চুম্বক ভ্রামক তুলনা।',
            'যন্ত্রপাতি: Tan-A অবস্থানে বিচ্যুতি চুম্বকমাপক, দুটি দণ্ডচুম্বক, মিটার স্কেল, বাক্স কম্পাস।',
            'Tan-A অবস্থানে $B = B_H\\tan\\theta$, ফলে $M \\propto d^3\\tan\\theta$।',
            'যন্ত্র সমতল করে সুচিকে চৌম্বক দিগংশ বরাবর রাখুন।',
            'এক বাহুতে চুম্বক রাখুন, অক্ষ বাহু বরাবর এবং দূরত্ব $d$ মেপে।',
            'সুচির দুই প্রান্তে বিচ্যুতি পড়ে গড় নিন।',
            'চুম্বক উল্টে আবার মাপুন; বিচ্যুতি মিললে সুচি মুক্তভাবে ঘুরছে।',
            'বিভিন্ন দূরত্বে এবং দ্বিতীয় চুম্বকের জন্যও বিচ্যুতি নিন।',
            '$\\dfrac{M_1}{M_2} = \\dfrac{d_1^3\\tan\\theta_1}{d_2^3\\tan\\theta_2}$ থেকে ভ্রামক তুলনা করুন।',
            '$\\tan\\theta$ বনাম $1/d^3$ আঁকলে ঢাল ভ্রামকের সমানুপাতিক হয়।',
            'সতর্কতা: কাছে লোহা বা চুম্বক নয়, বাহু চৌম্বক দিগংশে, আস্তে নাড়াচাড়া।',
            'ভুলের উৎস: নিকটবর্তী ইস্পাত, অসমতল বাক্স, দৃষ্টিভ্রম, অক্ষের বাইরে চুম্বক।',
        ],
    },
    'physics-diode-transistor-characteristics-hsc': {
        'en': [
            'Aim: plot the forward and reverse characteristics of a diode and a transistor.',
            'Apparatus: diode, transistor, variable DC supply, milliammeter, microammeter, voltmeter, resistors.',
            'Diode: forward current rises sharply after the knee, about $0.7\\ \\mathrm{V}$ for silicon.',
            'In reverse bias only a tiny leakage current flows until breakdown.',
            'Dynamic resistance is $r_d = \\Delta V/\\Delta I$ taken from the steep part of the curve.',
            'Transistor common-emitter: input is $I_B$ versus $V_{BE}$, output is $I_C$ versus $V_{CE}$.',
            'Current gains follow $\\alpha = I_C/I_E$ and $\\beta = I_C/I_B$, with $\\beta = \\alpha/(1-\\alpha)$.',
            'Keep $V_{CE}$ constant while taking the input characteristic and vice versa.',
            'Increase the supply slowly; a diode or transistor is destroyed by excess current.',
            'Record the polarity — a reversed diode gives no forward curve at all.',
            'Precautions: use series limiting resistors, check the meter range before switching on.',
            'Error sources: self-heating of the junction, coarse meter ranges, loose breadboard contacts.',
        ],
        'bn': [
            'উদ্দেশ্য: ডায়োড ও ট্রানজিস্টরের সম্মুখ ও পশ্চাৎ বৈশিষ্ট্য রেখা অঙ্কন।',
            'যন্ত্রপাতি: ডায়োড, ট্রানজিস্টর, পরিবর্তনশীল DC উৎস, মিলিঅ্যামিটার, মাইক্রোঅ্যামিটার, ভোল্টমিটার, রোধক।',
            'ডায়োড: হাঁটুর পরে সম্মুখ প্রবাহ দ্রুত বাড়ে, সিলিকনে প্রায় $0.7\\ \\mathrm{V}$।',
            'পশ্চাৎ বায়াসে ভাঙন পর্যন্ত অতি সামান্য লিকেজ প্রবাহ চলে।',
            'গতিশীল রোধ $r_d = \\Delta V/\\Delta I$, যা রেখার খাড়া অংশ থেকে নেওয়া হয়।',
            'ট্রানজিস্টরের সাধারণ-নির্গমক বর্তনী: প্রবেশ $I_B$ বনাম $V_{BE}$, নির্গম $I_C$ বনাম $V_{CE}$।',
            'প্রবাহ লাভ: $\\alpha = I_C/I_E$ এবং $\\beta = I_C/I_B$, যেখানে $\\beta = \\alpha/(1-\\alpha)$।',
            'প্রবেশ বৈশিষ্ট্য নেওয়ার সময় $V_{CE}$ স্থির রাখুন এবং উল্টোটিও।',
            'উৎস আস্তে বাড়ান; অতিরিক্ত প্রবাহে ডায়োড বা ট্রানজিস্টর নষ্ট হয়।',
            'মেরুতা লিখে রাখুন — উল্টো ডায়োডে সম্মুখ রেখাই আসে না।',
            'সতর্কতা: সিরিজ সীমাকারী রোধ ব্যবহার করুন, চালুর আগে মিটারের পরিসর দেখুন।',
            'ভুলের উৎস: জংশনের নিজস্ব উত্তাপ, মোটা মিটার পরিসর, আলগা ব্রেডবোর্ড সংযোগ।',
        ],
    },
    'physics-logic-gates-hsc': {
        'en': [
            'Aim: verify the truth tables of basic logic gates with an IC or a trainer board.',
            'Apparatus: logic gate IC or trainer, LEDs, connecting wires, $5\\ \\mathrm{V}$ DC supply, switch.',
            'Boolean outputs: $Y_{AND} = AB$, $Y_{OR} = A+B$, $Y_{NOT} = \\bar{A}$.',
            'Also verify $Y_{NAND} = \\overline{AB}$, $Y_{NOR} = \\overline{A+B}$ and $Y_{XOR} = A \\oplus B$.',
            'Identify the pin numbers from the datasheet and connect $V_{CC}$ and ground first.',
            'Apply the four input combinations 00, 01, 10 and 11 with the switches.',
            'Record the LED state for each combination and build the truth table.',
            'A high input is close to $5\\ \\mathrm{V}$ and a low input close to $0\\ \\mathrm{V}$.',
            'Check that NAND and NOR each reproduce the other gates when combined.',
            'Never leave an input pin floating — it picks up noise and gives random output.',
            'Precautions: correct $V_{CC}$ polarity, do not exceed the rated voltage, handle the IC by its edges.',
            'Error sources: floating inputs, a burnt LED, loose wires, static damage to the IC.',
        ],
        'bn': [
            'উদ্দেশ্য: IC বা প্রশিক্ষণ বোর্ডে মৌলিক লজিক গেটের সত্যক সারণি যাচাই।',
            'যন্ত্রপাতি: লজিক গেট IC বা ট্রেইনার, LED, সংযোগ তার, $5\\ \\mathrm{V}$ DC উৎস, সুইচ।',
            'বুলিয়ান নির্গম: $Y_{AND} = AB$, $Y_{OR} = A+B$, $Y_{NOT} = \\bar{A}$।',
            'এছাড়া যাচাই করুন $Y_{NAND} = \\overline{AB}$, $Y_{NOR} = \\overline{A+B}$ এবং $Y_{XOR} = A \\oplus B$।',
            'ডেটাশিট থেকে পিন নম্বর চিনে আগে $V_{CC}$ ও ভূমি সংযোগ করুন।',
            'সুইচ দিয়ে ০০, ০১, ১০ ও ১১ এই চার প্রবেশ সমাবেশ দিন।',
            'প্রতিটি সমাবেশে LED-এর অবস্থা লিখে সত্যক সারণি তৈরি করুন।',
            'উচ্চ প্রবেশ প্রায় $5\\ \\mathrm{V}$ এবং নিম্ন প্রবেশ প্রায় $0\\ \\mathrm{V}$।',
            'NAND ও NOR মিলিয়ে অন্য গেট তৈরি করা যায় কি না যাচাই করুন।',
            'কোনো প্রবেশ পিন ভাসমান রাখবেন না — এতে নয়েজ ঢুকে এলোমেলো নির্গম আসে।',
            'সতর্কতা: $V_{CC}$ মেরুতা ঠিক রাখুন, নির্ধারিত বিভব ছাড়ানো নয়, IC কিনারা ধরে নাড়ান।',
            'ভুলের উৎস: ভাসমান প্রবেশ, পোড়া LED, আলগা তার, স্থির তড়িতে IC নষ্ট হওয়া।',
        ],
    },
    'physics-vector-addition-force-table-hsc': {
        'en': [
            'Aim: verify the parallelogram law of vector addition with a force table.',
            'Apparatus: force table, pulleys, strings, weight hangers, slotted masses, drawing paper, pins.',
            'The resultant is $R = \\sqrt{A^2 + B^2 + 2AB\\cos\\theta}$ with direction $\\tan\\phi = B\\sin\\theta/(A + B\\cos\\theta)$.',
            'Set two pulleys at the chosen angle and hang known masses over them.',
            'Add masses on the third string until the central ring rests exactly at the pin.',
            'The equilibrant equals the resultant in magnitude but points the opposite way.',
            'Record the three forces and their angles measured from a fixed reference line.',
            'Draw the parallelogram to scale on paper and measure the diagonal.',
            'Compare the graphical resultant with the calculated one and note the difference.',
            'Repeat with at least three different angle pairs, including $90^\\circ$.',
            'Precautions: strings free of the table, pulleys turning smoothly, ring exactly centred.',
            'Error sources: pulley friction, string mass, off-scale drawing, unequal tension across a pulley.',
        ],
        'bn': [
            'উদ্দেশ্য: বল টেবিলে ভেক্টর যোগের সামান্তরিক সূত্র যাচাই।',
            'যন্ত্রপাতি: বল টেবিল, পুলি, সুতা, ভারধারক, কাটা ভার, অঙ্কন কাগজ, পিন।',
            'লব্ধি $R = \\sqrt{A^2 + B^2 + 2AB\\cos\\theta}$ এবং দিক $\\tan\\phi = B\\sin\\theta/(A + B\\cos\\theta)$।',
            'নির্ধারিত কোণে দুটি পুলি বসিয়ে জানা ভর ঝুলিয়ে দিন।',
            'তৃতীয় সুতায় ভর যোগ করুন যতক্ষণ না কেন্দ্রের বলয় ঠিক পিনে স্থির হয়।',
            'ভারসাম্যকারী বল লব্ধির সমান কিন্তু বিপরীতমুখী।',
            'স্থির নির্দেশ রেখা থেকে মাপা তিনটি বল ও তাদের কোণ লিখুন।',
            'কাগজে স্কেল ধরে সামান্তরিক এঁকে কর্ণ মাপুন।',
            'লেখচিত্র-লব্ধির সঙ্গে হিসাব-লব্ধি তুলনা করে পার্থক্য লিখুন।',
            '$90^\\circ$-সহ অন্তত তিন জোড়া কোণে পরীক্ষাটি পুনরাবৃত্তি করুন।',
            'সতর্কতা: সুতা টেবিলে ঘষা নয়, পুলি মসৃণভাবে ঘুরবে, বলয় ঠিক কেন্দ্রে।',
            'ভুলের উৎস: পুলির ঘর্ষণ, সুতার ভর, স্কেল-বহির্ভূত অঙ্কন, পুলিতে অসম টান।',
        ],
    },
    'physics-projectile-range-hsc': {
        'en': [
            'Aim: study how the range of a projectile depends on the launch angle.',
            'Apparatus: spring launcher or ramp, steel ball, protractor, metre tape, carbon paper, stand.',
            'For level ground $R = \\dfrac{u^2\\sin 2\\theta}{g}$, which is maximum at $\\theta = 45^\\circ$.',
            'Launch from a fixed height so the initial speed $u$ stays the same every time.',
            'Measure the launch speed separately from the horizontal range at $\\theta = 0$.',
            'Set the launcher at $15^\\circ$ and fire five times, marking each landing point.',
            'Use the mean landing point and measure the range with the tape.',
            'Repeat at $30^\\circ$, $45^\\circ$, $60^\\circ$ and $75^\\circ$ without changing the spring setting.',
            'Plot $R$ against $\\sin 2\\theta$; the graph should be a straight line through the origin.',
            'Compare the measured maximum-range angle with the theoretical $45^\\circ$.',
            'Precautions: same launcher position, level floor, no air currents, mark landings clearly.',
            'Error sources: varying launch speed, air resistance, uneven floor, height of launch not zero.',
        ],
        'bn': [
            'উদ্দেশ্য: নিক্ষিপ্ত বস্তুর পাল্লা নিক্ষেপ কোণের ওপর কীভাবে নির্ভর করে তা দেখা।',
            'যন্ত্রপাতি: স্প্রিং নিক্ষেপক বা র‍্যাম্প, ইস্পাতের বল, প্রোট্র্যাক্টর, টেপ, কার্বন কাগজ, স্ট্যান্ড।',
            'সমতল ভূমিতে $R = \\dfrac{u^2\\sin 2\\theta}{g}$, যা $\\theta = 45^\\circ$-এ সর্বোচ্চ।',
            'নির্দিষ্ট উচ্চতা থেকে নিক্ষেপ করুন যাতে প্রতিবার আদি বেগ $u$ এক থাকে।',
            '$\\theta = 0$-তে অনুভূমিক পাল্লা থেকে নিক্ষেপ বেগ আলাদাভাবে বের করুন।',
            '$15^\\circ$-এ রেখে পাঁচবার নিক্ষেপ করে প্রতিটি পতন বিন্দু চিহ্নিত করুন।',
            'গড় পতন বিন্দু নিয়ে টেপ দিয়ে পাল্লা মাপুন।',
            'স্প্রিং না বদলে $30^\\circ$, $45^\\circ$, $60^\\circ$ ও $75^\\circ$-এ পুনরাবৃত্তি করুন।',
            '$R$ বনাম $\\sin 2\\theta$ আঁকলে মূলবিন্দুগামী সরলরেখা পাওয়া যাবে।',
            'পরিমাপিত সর্বোচ্চ-পাল্লা কোণের সঙ্গে তাত্ত্বিক $45^\\circ$ তুলনা করুন।',
            'সতর্কতা: নিক্ষেপকের অবস্থান একই রাখুন, মেঝে সমতল, বাতাসের ঝাপটা নয়, পতন স্পষ্ট চিহ্নিত করুন।',
            'ভুলের উৎস: নিক্ষেপ বেগের পরিবর্তন, বায়ুর বাধা, অসম মেঝে, নিক্ষেপ উচ্চতা শূন্য না হওয়া।',
        ],
    },
    'physics-mass-spring-shm-hsc': {
        'en': [
            'Aim: show that a mass on a spring executes simple harmonic motion.',
            'Apparatus: spring, stand, mass hanger, slotted masses, stopwatch, metre scale.',
            'The restoring force is $F = -kx$, giving $T = 2\\pi\\sqrt{m/k}$ independent of amplitude.',
            'Displace the hanger a small distance and release it without pushing.',
            'Check that the period stays the same for small and slightly larger amplitudes.',
            'Time 20 oscillations for each load, repeating the timing twice.',
            'Record the extension of the spring at rest for each load to get $k = mg/x$.',
            'Plot $T^2$ against $m$ and confirm a straight line through the origin.',
            'Compare the $k$ from the static extension with the $k$ from the dynamic period.',
            'Sketch the displacement–time graph and identify the amplitude and the period.',
            'Precautions: vertical motion only, small amplitude, no rotation of the hanger.',
            'Error sources: spring mass not negligible, damping, reaction time, exceeding the elastic limit.',
        ],
        'bn': [
            'উদ্দেশ্য: স্প্রিংয়ে ঝোলানো ভর সরল পর্যায় স্পন্দন করে তা দেখানো।',
            'যন্ত্রপাতি: স্প্রিং, স্ট্যান্ড, ভারধারক, কাটা ভার, স্টপওয়াচ, মিটার স্কেল।',
            'প্রত্যায়নী বল $F = -kx$, ফলে $T = 2\\pi\\sqrt{m/k}$ এবং এটি বিস্তার থেকে মুক্ত।',
            'ভারধারককে সামান্য সরিয়ে ধাক্কা ছাড়াই ছেড়ে দিন।',
            'ছোট ও কিছুটা বড় বিস্তারে পর্যায়কাল একই থাকে কি না দেখুন।',
            'প্রতিটি ভারে ২০টি দোলনের সময় নিন এবং মাপটি দুইবার পুনরাবৃত্তি করুন।',
            'প্রতিটি ভারে স্থির প্রসারণ লিখে $k = mg/x$ বের করুন।',
            '$T^2$ বনাম $m$ এঁকে মূলবিন্দুগামী সরলরেখা নিশ্চিত করুন।',
            'স্থিতিক প্রসারণের $k$-এর সঙ্গে গতিজ পর্যায়কালের $k$ তুলনা করুন।',
            'সরণ–সময় লেখচিত্র এঁকে বিস্তার ও পর্যায়কাল চিহ্নিত করুন।',
            'সতর্কতা: শুধু উল্লম্ব গতি, ছোট বিস্তার, ভারধারক যেন না ঘোরে।',
            'ভুলের উৎস: স্প্রিংয়ের নিজস্ব ভর, অবমন্দন, প্রতিক্রিয়ার সময়, স্থিতিস্থাপক সীমা অতিক্রম।',
        ],
    },
    'physics-venturi-bernoulli-hsc': {
        'en': [
            'Aim: verify the continuity equation and Bernoulli’s theorem with a venturi tube.',
            'Apparatus: venturi tube, manometers at several sections, water tank, pump, stopwatch, measuring cylinder.',
            'Continuity gives $A_1v_1 = A_2v_2$, and Bernoulli gives $P + \\frac{1}{2}\\rho v^2 + \\rho gh = $ constant.',
            'Measure the diameters of the wide and narrow sections to get $A_1$ and $A_2$.',
            'Run water at a steady rate and read each manometer once the levels are fixed.',
            'Collect the outflow for a measured time and compute the volume flow rate $Q$.',
            'From $Q$ find the velocities, $v_1 = Q/A_1$ and $v_2 = Q/A_2$.',
            'Check that the manometer height falls at the throat, as Bernoulli predicts.',
            'Compute $P/\\rho g + v^2/2g + h$ at each section and compare the totals.',
            'Repeat at two or three different flow rates for a fair test.',
            'Precautions: no air bubbles in the manometer tubes, steady flow, horizontal tube.',
            'Error sources: turbulence at the throat, viscous losses, air pockets, unsteady pump output.',
        ],
        'bn': [
            'উদ্দেশ্য: ভেন্টুরি নলে অবিচ্ছিন্নতা সমীকরণ ও বার্নুলির উপপাদ্য যাচাই।',
            'যন্ত্রপাতি: ভেন্টুরি নল, বিভিন্ন প্রস্থচ্ছেদের ম্যানোমিটার, পানির ট্যাংক, পাম্প, স্টপওয়াচ, আয়তন মাপক।',
            'অবিচ্ছিন্নতা থেকে $A_1v_1 = A_2v_2$, এবং বার্নুলি থেকে $P + \\frac{1}{2}\\rho v^2 + \\rho gh = $ ধ্রুব।',
            'প্রশস্ত ও সংকীর্ণ অংশের ব্যাস মেপে $A_1$ ও $A_2$ বের করুন।',
            'স্থির হারে পানি চালিয়ে তল স্থির হলে প্রতিটি ম্যানোমিটারের পাঠ নিন।',
            'নির্দিষ্ট সময়ে নির্গম পানি জমিয়ে আয়তন প্রবাহ হার $Q$ হিসাব করুন।',
            '$Q$ থেকে বেগ বের করুন: $v_1 = Q/A_1$ এবং $v_2 = Q/A_2$।',
            'গলায় ম্যানোমিটারের উচ্চতা কমে কি না দেখুন, যেমন বার্নুলি বলে।',
            'প্রতিটি প্রস্থচ্ছেদে $P/\\rho g + v^2/2g + h$ হিসাব করে মোট তুলনা করুন।',
            'নিরপেক্ষ পরীক্ষার জন্য দুই-তিনটি ভিন্ন প্রবাহ হারে পুনরাবৃত্তি করুন।',
            'সতর্কতা: ম্যানোমিটার নলে বাতাস নয়, স্থির প্রবাহ, নল অনুভূমিক।',
            'ভুলের উৎস: গলায় অশান্তি, সান্দ্র ক্ষয়, বাতাসের থলি, অস্থির পাম্প নির্গম।',
        ],
    },
    'physics-wheatstone-bridge-hsc': {
        'en': [
            'Aim: measure an unknown resistance with a Wheatstone bridge circuit.',
            'Apparatus: four known/unknown resistors or boxes, galvanometer, cell, key, connecting wires.',
            'At balance no current flows through the galvanometer and $\\dfrac{P}{Q} = \\dfrac{R}{S}$.',
            'Build the four arms carefully and label $P$, $Q$, $R$ and the unknown $S$.',
            'Close the key briefly and observe the galvanometer deflection direction.',
            'Change the ratio arm until the deflection reverses — the balance lies between.',
            'Reduce the steps until the deflection is as small as the instrument can show.',
            'Use ratio arms of about $1:1$ when $S$ is near $R$ for the best sensitivity.',
            'Interchange $S$ with a known resistance and repeat to cancel end errors.',
            'Record the balanced values and compute $S = RQ/P$ with its unit.',
            'Precautions: firm contacts, short key closures, protect the galvanometer with a high resistance at first.',
            'Error sources: contact and lead resistance, heating of the coils, a drifting galvanometer zero.',
        ],
        'bn': [
            'উদ্দেশ্য: হুইটস্টোন ব্রিজ বর্তনীতে অজানা রোধ পরিমাপ।',
            'যন্ত্রপাতি: চারটি জানা/অজানা রোধক বা বাক্স, গ্যালভানোমিটার, কোষ, চাবি, সংযোগ তার।',
            'ভারসাম্যে গ্যালভানোমিটারে প্রবাহ চলে না এবং $\\dfrac{P}{Q} = \\dfrac{R}{S}$।',
            'চার বাহু সতর্কভাবে সাজিয়ে $P$, $Q$, $R$ ও অজানা $S$ চিহ্নিত করুন।',
            'চাবি সামান্য সময় বন্ধ করে বিচ্যুতির দিক লক্ষ করুন।',
            'বিচ্যুতি উল্টে না যাওয়া পর্যন্ত অনুপাত বাহু বদলান — ভারসাম্য মাঝখানে আছে।',
            'ধাপ ছোট করতে থাকুন যতক্ষণ না বিচ্যুতি যন্ত্রের সীমার কাছাকাছি হয়।',
            '$S$ যদি $R$-এর কাছাকাছি হয়, অনুপাত প্রায় $1:1$ রাখলে সংবেদনশীলতা বাড়ে।',
            '$S$-কে জানা রোধের সঙ্গে অদলবদল করে পুনরাবৃত্তি করুন, প্রান্ত ত্রুটি কাটবে।',
            'ভারসাম্য মান লিখে $S = RQ/P$ এককসহ হিসাব করুন।',
            'সতর্কতা: শক্ত সংযোগ, চাবি অল্প সময় বন্ধ রাখুন, শুরুতে গ্যালভানোমিটারে উচ্চ রোধ রাখুন।',
            'ভুলের উৎস: স্পর্শ ও সংযোগ তারের রোধ, কুণ্ডলীর উত্তাপ, গ্যালভানোমিটারের শূন্য সরে যাওয়া।',
        ],
    },
    'physics-young-double-slit-hsc': {
        'en': [
            'Aim: determine the wavelength of light from Young’s double-slit interference.',
            'Apparatus: laser or filtered source, double slit, screen, metre scale, vernier callipers or micrometer eyepiece.',
            'Fringe spacing follows $\\beta = \\dfrac{\\lambda D}{d}$, hence $\\lambda = \\beta d/D$.',
            'Measure the slit separation $d$ with a travelling microscope or from the datasheet.',
            'Set the screen a large distance $D$ away and measure it with a tape.',
            'Mark the central bright fringe, then count $n$ fringes to one side.',
            'Measure the distance $x$ from the centre to the $n$th bright fringe.',
            'Use $\\beta = x/n$ rather than measuring one fringe, which is too small.',
            'Repeat on the other side of the centre and take the mean spacing.',
            'Plot $x$ against $n$; the slope is $\\beta$, which reduces reading errors.',
            'Precautions: never look directly into a laser, keep the slit clean, dark room, no vibration.',
            'Error sources: fringe counting mistakes, inaccurate $d$, a tilted screen, diffraction envelope effects.',
        ],
        'bn': [
            'উদ্দেশ্য: ইয়াংয়ের দ্বি-চির ব্যতিচার থেকে আলোর তরঙ্গদৈর্ঘ্য নির্ণয়।',
            'যন্ত্রপাতি: লেজার বা ছাঁকা উৎস, দ্বি-চির, পর্দা, মিটার স্কেল, ভার্নিয়ার ক্যালিপার্স বা মাইক্রোমিটার আইপিস।',
            'ডোরার ব্যবধান $\\beta = \\dfrac{\\lambda D}{d}$, তাই $\\lambda = \\beta d/D$।',
            'ট্রাভেলিং অণুবীক্ষণ বা ডেটাশিট থেকে চির ব্যবধান $d$ বের করুন।',
            'পর্দাকে বড় দূরত্ব $D$-তে রেখে টেপ দিয়ে মাপুন।',
            'কেন্দ্রীয় উজ্জ্বল ডোরা চিহ্নিত করে এক পাশে $n$ সংখ্যক ডোরা গুনুন।',
            'কেন্দ্র থেকে $n$-তম উজ্জ্বল ডোরা পর্যন্ত দূরত্ব $x$ মাপুন।',
            'একটি ডোরা মাপার বদলে $\\beta = x/n$ ব্যবহার করুন, কারণ একটি ডোরা খুব ছোট।',
            'কেন্দ্রের অন্য পাশেও মেপে গড় ব্যবধান নিন।',
            '$x$ বনাম $n$ আঁকলে ঢালই $\\beta$, যাতে পাঠের ত্রুটি কমে।',
            'সতর্কতা: লেজারে সরাসরি তাকাবেন না, চির পরিষ্কার রাখুন, ঘর অন্ধকার, কম্পন নয়।',
            'ভুলের উৎস: ডোরা গণনায় ভুল, ভুল $d$, হেলে থাকা পর্দা, অপবর্তন খোলের প্রভাব।',
        ],
    },
}
