'use client';

import { useLocale, useTranslations } from 'next-intl';
import { useState } from 'react';
import type { Element } from '@/lib/constants';
import { Modal } from '@/components/ui/Modal';
import { cn } from '@/lib/utils';

const colors: Record<string, string> = { blue: 'bg-physics-100 text-physics-800 dark:bg-physics-900 dark:text-physics-100', purple: 'bg-violet-100 text-violet-800 dark:bg-violet-950 dark:text-violet-100', orange: 'bg-orange-100 text-orange-800 dark:bg-orange-950 dark:text-orange-100', teal: 'bg-chemistry-100 text-chemistry-800 dark:bg-chemistry-900 dark:text-chemistry-100', green: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-100', slate: 'bg-slate-200 text-slate-800 dark:bg-slate-800 dark:text-slate-100', gold: 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-100', pink: 'bg-pink-100 text-pink-800 dark:bg-pink-950 dark:text-pink-100' };

export function PeriodicTable({ elements }: { elements: Element[] }) {
  const locale = useLocale() as 'bn' | 'en'; const t = useTranslations('constants'); const [selected, setSelected] = useState<Element | null>(null);
  return <><div className="scrollbar-thin overflow-x-auto pb-2"><div className="grid min-w-[720px] grid-cols-18 gap-1.5" style={{ gridTemplateColumns: 'repeat(18, minmax(34px, 1fr))' }}>{elements.map((element) => <button key={element.symbol} type="button" onClick={() => setSelected(element)} className={cn('min-h-[58px] rounded-lg p-1 text-center transition hover:-translate-y-0.5 hover:shadow-md', colors[element.color] ?? colors.blue)} style={{ gridColumn: element.group > 0 ? element.group : 4, gridRow: element.period }} aria-label={`${element.name} (${element.symbol})`}><span className="block text-[10px] font-bold opacity-70">{element.number}</span><span className="block text-lg font-black">{element.symbol}</span><span className="block truncate text-[9px] font-bold">{locale === 'bn' ? element.name_bn : element.name}</span></button>)}</div></div><p className="mt-3 text-xs muted">{locale === 'bn' ? 'মৌলে ক্লিক করলে বিস্তারিত তথ্য দেখুন।' : 'Click an element for a short reference note.'}</p><Modal open={selected !== null} onClose={() => setSelected(null)} title={selected ? `${locale === 'bn' ? selected.name_bn : selected.name} · ${selected.symbol}` : t('details')}><div className="space-y-4"><div className="grid grid-cols-3 gap-2"><div className="rounded-xl bg-[var(--surface-soft)] p-3"><p className="text-xs muted">{t('atomicNumber')}</p><p className="mt-1 text-lg font-black">{selected?.number}</p></div><div className="rounded-xl bg-[var(--surface-soft)] p-3"><p className="text-xs muted">{t('atomicMass')}</p><p className="mt-1 text-lg font-black">{selected?.mass}</p></div><div className="rounded-xl bg-[var(--surface-soft)] p-3"><p className="text-xs muted">{t('category')}</p><p className="mt-1 text-sm font-black">{selected?.category}</p></div></div><p className="text-sm leading-7 muted">{selected?.detail}</p></div></Modal></>;
}
