'use client';

import Link from 'next/link';
import { CheckCircle2, Clock3, Lightbulb, RotateCcw, Trophy, XCircle } from 'lucide-react';
import { useLocale, useTranslations } from 'next-intl';
import { useEffect, useMemo, useState } from 'react';
import type { Quiz } from '@/lib/schemas';
import { useLabStore } from '@/lib/store';
import { Button, LinkButton } from '@/components/ui/Button';
import { Card, CardBody, CardHeader, CardTitle } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { ViewTracker } from './ViewTracker';
import { cn } from '@/lib/utils';

export function QuizRunner({ quiz }: { quiz: Quiz }) {
  const locale = useLocale() as 'bn' | 'en'; const t = useTranslations();
  const [phase, setPhase] = useState<'intro' | 'quiz' | 'result'>('intro'); const [timerMode, setTimerMode] = useState(false); const [timeLeft, setTimeLeft] = useState(60); const [questionIndex, setQuestionIndex] = useState(0); const [activeIndices, setActiveIndices] = useState<number[]>(quiz.questions.map((_, index) => index)); const [selected, setSelected] = useState<number | null>(null); const [answers, setAnswers] = useState<Record<number, number>>({}); const [score, setScore] = useState(0); const [saved, setSaved] = useState(false);
  const addScore = useLabStore((state) => state.addScore);
  const currentIndex = activeIndices[questionIndex]; const question = quiz.questions[currentIndex];
  const options = question ? locale === 'bn' ? question.options_bn ?? question.options : question.options : [];
  useEffect(() => { if (phase !== 'quiz' || !timerMode) return; if (timeLeft <= 0) { setPhase('result'); return; } const timer = window.setInterval(() => setTimeLeft((value) => value - 1), 1000); return () => window.clearInterval(timer); }, [phase, timeLeft, timerMode]);
  useEffect(() => { if (phase === 'result' && !saved) { addScore({ quiz: quiz.slug, score, total: activeIndices.length }); setSaved(true); } }, [activeIndices.length, addScore, phase, quiz.slug, saved, score]);
  const progress = useMemo(() => activeIndices.length ? ((questionIndex + (selected !== null ? 1 : 0)) / activeIndices.length) * 100 : 0, [activeIndices.length, questionIndex, selected]);
  const start = () => { setPhase('quiz'); setQuestionIndex(0); setSelected(null); setAnswers({}); setScore(0); setSaved(false); setTimeLeft(60); };
  const choose = (option: number) => { if (selected !== null || !question) return; setSelected(option); setAnswers((current) => ({ ...current, [currentIndex]: option })); if (option === question.answer) setScore((current) => current + 1); };
  const next = () => { if (questionIndex >= activeIndices.length - 1) setPhase('result'); else { setQuestionIndex((current) => current + 1); setSelected(null); } };
  const retryWrong = () => { const wrong = activeIndices.filter((index) => answers[index] !== quiz.questions[index].answer); if (wrong.length === 0) return; setActiveIndices(wrong); setQuestionIndex(0); setSelected(null); setAnswers({}); setScore(0); setSaved(false); setTimeLeft(60); setPhase('quiz'); };
  if (phase === 'intro') return <div className="mx-auto max-w-2xl"><Card className="overflow-hidden"><div className="bg-physics-50 p-7 dark:bg-physics-900/50 sm:p-10"><Badge tone={quiz.subject === 'physics' ? 'physics' : 'chemistry'}>{quiz.subject === 'physics' ? t('common.physics') : t('common.chemistry')}</Badge><h1 className="mt-4 text-3xl font-black tracking-tight">{locale === 'bn' ? quiz.title_bn : quiz.title_en}</h1><p className="mt-3 leading-7 muted">{locale === 'bn' ? quiz.description_bn : quiz.description_en}</p><div className="mt-6 flex flex-wrap gap-3 text-sm font-bold muted"><span>{quiz.questions.length} {t('quiz.question')}</span><span>·</span><span>{timerMode ? '60 s timer' : 'Self-paced'}</span></div></div><CardBody className="space-y-5 pt-6"><label className="flex items-center justify-between rounded-xl border border-[var(--line)] p-3 text-sm font-bold"><span className="inline-flex items-center gap-2"><Clock3 size={17} />{t('quiz.timer')}</span><input type="checkbox" checked={timerMode} onChange={(event) => setTimerMode(event.target.checked)} className="h-5 w-5 accent-physics-600" /></label><Button className="w-full" onClick={start}>{t('quiz.start')}</Button></CardBody></Card></div>;
  if (phase === 'result') { const wrongCount = activeIndices.filter((index) => answers[index] !== quiz.questions[index].answer).length; return <div className="mx-auto max-w-2xl"><Card className="overflow-hidden text-center"><div className="bg-chemistry-50 p-8 dark:bg-chemistry-900/50"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-chemistry-600 text-white"><Trophy size={30} /></span><p className="mt-5 text-sm font-black uppercase tracking-widest text-chemistry-700 dark:text-chemistry-200">{t('quiz.score')}</p><p className="mt-1 text-6xl font-black text-chemistry-700 dark:text-chemistry-100">{score}<span className="text-2xl">/{activeIndices.length}</span></p><p className="mt-3 text-sm muted">{score === activeIndices.length ? (locale === 'bn' ? 'দারুণ! সবগুলো সঠিক।' : 'Excellent — every answer is correct.') : `${wrongCount} ${locale === 'bn' ? 'টি আবার চেষ্টা করতে পারেন।' : 'to revisit when you are ready.'}`}</p></div><CardBody className="flex flex-wrap justify-center gap-3 pt-6"><Button onClick={start} icon={<RotateCcw size={16} />}>{t('quiz.start')}</Button>{wrongCount > 0 && <Button variant="secondary" onClick={retryWrong}>{t('quiz.retry')}</Button>}<LinkButton href={`/${locale}/quiz`} variant="ghost">{t('quiz.backToQuizzes')}</LinkButton></CardBody></Card></div>; }
  if (!question) return null;
  const correct = selected === question.answer;
  return <div className="mx-auto max-w-3xl"><ViewTracker item={{ slug: quiz.slug, kind: 'quiz', href: `/quiz/${quiz.slug}`, title: locale === 'bn' ? quiz.title_bn : quiz.title_en }} /><div className="mb-5 flex items-center justify-between gap-3"><p className="text-sm font-black">{t('quiz.question')} {questionIndex + 1} <span className="font-normal muted">{t('quiz.of')} {activeIndices.length}</span></p>{timerMode && <span className={cn('inline-flex items-center gap-1 rounded-full px-3 py-1 text-sm font-black', timeLeft <= 10 ? 'bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-200' : 'bg-[var(--surface-soft)] text-[var(--muted)]')}><Clock3 size={15} />{timeLeft}s</span>}</div><div className="mb-5 h-2 overflow-hidden rounded-full bg-[var(--surface-soft)]"><div className="h-full rounded-full bg-physics-500 transition-all" style={{ width: `${Math.max(5, progress)}%` }} /></div><Card><CardHeader><CardTitle className="text-xl leading-8 sm:text-2xl">{locale === 'bn' ? question.q_bn ?? question.q : question.q}</CardTitle></CardHeader><CardBody className="space-y-3">{options.map((option, index) => { const isSelected = selected === index; const isCorrect = index === question.answer; return <button key={option} type="button" onClick={() => choose(index)} disabled={selected !== null} className={cn('flex w-full items-center gap-3 rounded-xl border p-4 text-left text-sm font-bold transition', selected === null ? 'border-[var(--line)] hover:border-physics-400 hover:bg-physics-50 dark:hover:bg-physics-900' : isCorrect ? 'border-chemistry-300 bg-chemistry-50 text-chemistry-900 dark:border-chemistry-600 dark:bg-chemistry-900/60 dark:text-chemistry-100' : isSelected ? 'border-red-300 bg-red-50 text-red-900 dark:border-red-700 dark:bg-red-950/60 dark:text-red-100' : 'border-[var(--line)] opacity-60')}><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-[var(--surface-soft)] text-xs">{String.fromCharCode(65 + index)}</span><span className="flex-1">{option}</span>{selected !== null && isCorrect && <CheckCircle2 size={18} className="text-chemistry-600" />}{selected !== null && isSelected && !isCorrect && <XCircle size={18} className="text-red-600" />}</button>; })}{selected !== null && <div className={cn('rounded-xl border p-4 text-sm leading-6', correct ? 'border-chemistry-200 bg-chemistry-50 dark:border-chemistry-700 dark:bg-chemistry-900/50' : 'border-amber-200 bg-amber-50 dark:border-amber-800 dark:bg-amber-950/40')}><p className="flex items-center gap-2 font-black">{correct ? <CheckCircle2 size={17} /> : <Lightbulb size={17} />}{correct ? t('quiz.correct') : t('quiz.notQuite')}</p><p className="mt-2 muted">{locale === 'bn' ? question.explanation_bn ?? question.explanation : question.explanation}</p></div>}<div className="flex justify-end pt-2"><Button onClick={next} disabled={selected === null}>{questionIndex === activeIndices.length - 1 ? t('quiz.finish') : t('common.next')}</Button></div></CardBody></Card></div>;
}
